### ISSUE TITLE
[Developers] Branch 4.0.*

### ISSUE THREAD

**Issue by stevebauman** [adLDAP2/adLDAP2#1]
Hey everyone, please feel free to commit fixes and make modifications/releases to the 4.0 branch if you'd like.

However, please note that I'm working on the master branch as well as the 5.0 branch and code will be consistently pushed there over the next couple of days until it's complete, so definitely let me know if you'd like to push there and/or offer suggestions.

Thanks!

-- Steve

**Comment by samwilson** [comment]
No worries. :)
