### ISSUE TITLE
search on distinguishedname with contains does not work

### ISSUE THREAD

**Issue by r-springmann** [Adldap2/Adldap2#100]
I try the following:

    $ad->users()->search()->where('distinguishedname', 'contains', 'OU=EDV-OG4')->paginate('10')->getResults();

This does not return any result, but if i try a contains on 'cn' it works fine. I also could search for distinguishedname with '=' but this does not help me if i want to restrict the results on OUs

**Comment by stevebauman** [comment]
You can't perform searches on distinguished names unfortunately. If you're looking to find users inside of an OU, you'll need to search for the OU first, and then perform a new search upon users using the OUs distinguished name as the base DN:

```php
$ou = Adldap::ous()->search()->where('ou', 'contains', 'EDV-OG4')->first();

$users = Adldap::users()->search()->setDn($ou->getDn())->get();
```
