### ISSUE TITLE
Move user OU doesn't works; need rewrite move function

### ISSUE THREAD

**Issue by kichetof** [Adldap2/Adldap2#104]
Hi @stevebauman,

I'm trying to move a user from an OU to an another OU _(group1 to group2)_, without success:

`CN=John Doe,OU=Users,OU=group1,DC=Name,DC=Domain,DC=local`
to
`CN=John Doe,OU=Users,OU=group2,DC=Name,DC=Domain,DC=local`

This is my code:

```php
$newrdn = "CN={$attributes["cn"]}";
$newparent = "OU=Users,OU=$userOU,".BASE_DN;
$log->addInfo("DN actual: {$user->getDn()}; New RDN: {$newrdn}; new parent: {$newparent}");
// log: DN actual: CN=John Doe,OU=Users,OU=group1,DC=Name,DC=Domain,DC=local; New RDN: CN=John Doe; new parent: OU=Users,OU=group2,DC=Name,DC=Domain,DC=local
$user->move($newrdn, $newparent); // <-- return FALSE
```
Normally with this code, everything should work, but not.
I searched with our friend google, and I found this very useful information:
> The modrdn change type cannot move an entry to a completely different subtree. To move an entry to a completely different branch, you must create a new entry in the alternative subtree using the old entry's attributes, and then delete the old entry.
http://stackoverflow.com/q/17035037

### So the "bug" is: we can't move a user from a subtree OU to another subtree OU.

We need to find the best way to "duplicate" user and remove the "original".

_What do you think ?_
Instantiate a new user with all attributes, then save and delete old ?

I hope we'll find the best way to do that :)
Tof

**Comment by kichetof** [comment]
Work in progress _(not tested, only concept)_

```php
public function moveUserToNewParentOu($newDn, $deleteOldUser = false)
{
    $oldUser = $this;

    $attributes = $oldUser->getAttributes();
    $attributes['dn'] = $newDn;

    $this->fill($attributes);

    if ($this->create()) {
        $this->syncRaw();

        if ($deleteOldUser) {
            $oldUser->delete();
        }

        return true;
    } else {
        return false;
    }
}
```

**Comment by stevebauman** [comment]
This could be really tricky to accomplish. Since attributes on the models are set depending on what's selected by the users query, and all attributes on users aren't modifiable, I'm not sure how we could do this to be honest.

I think this may be something the dev needs to implement and not something that's built into Adldap since it could be prone to a lot of potential issues. I'll leave this open though for suggestions and discussion.

**Comment by ChadSikorra** [comment]
Am I missing something...or don't you just have to do? `$user->move($newrdn, $newparent, true);` The third parameter does what you want I think (and should probably be the default for the function?). 

I think part of the confusion also lies in the permissions required to move an object in AD. The account you are bound as needs permission to delete the object from its current OU and it needs permission to create a new user object at the new OU location. AD handles the rest behind the scenes. I know I have successfully used `ldap_rename` to move AD accounts around without any problems.

**Comment by stevebauman** [comment]
@ChadSikorra is right, the third parameter should actually do this. I'll change the default to true for this method.

@kichetof, let me know if this works for you!

**Comment by stevebauman** [comment]
Going to close this for now due to no response. I'll re-open once a response is given.
