### ISSUE TITLE
How to connect with dynamic user

### ISSUE THREAD

**Issue by Xento** [Adldap2/Adldap2#105]
Hello,
I want to have a central config with no default adminuser.
Each user should connect with his permissions.
First I had autoconnect enabled and it worked when I used the authentication method.
But with autoconnect enabled adldap2 will always try to connect without a user first, so I disabled it.
The problem now is, that I can't authenticate anymore.

It is because some settings are only set, when autoconnect is enabled 

        // If we dev wants to connect automatically, we'll construct
        // a new Connection and try to connect using the
        // supplied configuration object.
        if ($autoConnect === true) {
            // Set the beginning protocol options on the connection
            // if they're set in the configuration.
            if ($this->configuration->getUseSSL()) {
                $this->connection->useSSL();
            } elseif ($this->configuration->getUseTLS()) {
                $this->connection->useTLS();
            }

Other settings are set whithin the connect method 

    public function connect()
    {
        // Retrieve the controllers from the configuration
        $controllers = $this->configuration->getDomainControllers();

        // Select a random domain controller
        $controller = $controllers[array_rand($controllers)];

        // Set the controller selected
        $this->configuration->setDomainControllerSelected($controller);

        // Get the LDAP port
        $port = $this->configuration->getPort();

        // Create the LDAP connection
        $this->connection->connect($controller, $port);

        // Set the LDAP options
        $this->connection->setOption(LDAP_OPT_PROTOCOL_VERSION, 3);
        $this->connection->setOption(LDAP_OPT_REFERRALS, $this->configuration->getFollowReferrals());

        // Authenticate to the server
        return $this->authenticate($this->configuration->getAdminUsername(), $this->configuration->getAdminPassword(), true);
    }

I would suggest, that you move those ssl and tls settings to the connect method and give the connect method a username and a password parameter.
If they are specified it should use those credentials to connect instead of the administrator.

**Comment by stevebauman** [comment]
I completely agree with this, will implement this shortly, thanks!

**Comment by stevebauman** [comment]
Added in commit: https://github.com/Adldap2/Adldap2/commit/2d270f92136dd895409ec93d5595f3f88233fbf1
