### ISSUE TITLE
Undefined constant LDAP_MODIFY_BATCH_REPLACE in AbstractModel.php:402 getModifications() method.

### ISSUE THREAD

**Issue by pa102** [Adldap2/Adldap2#107]
Trying to update a user attribute and receiving "ErrorException in AbstractModel.php line 402: Use of undefined constant LDAP_MODIFY_BATCH_REPLACE - assumed 'LDAP_MODIFY_BATCH_REPLACE'"

Stack trace is;

1. in AbstractModel.php line 402
2. at HandleExceptions->handleError('8', 'Use of undefined constant LDAP_MODIFY_BATCH_REPLACE - assumed 'LDAP_MODIFY_BATCH_REPLACE'', '/var/www/html/project/vendor/adldap2/adldap2/src/Models/AbstractModel.php', '402', array('dirty' => array('physicaldeliveryofficename' => array('blah')), 'key' => 'physicaldeliveryofficename', 'value' => array('blah'), 'filtered' => array('blah'))) in AbstractModel.php line 402
3. at AbstractModel->getModifications() in AbstractModel.php line 828
4. at AbstractModel->update() in AbstractModel.php line 815

**Comment by stevebauman** [comment]
Please read the optional requirements for modifying Adldap models.

**Comment by stevebauman** [comment]
Just for clarification though, I will be adding an `$user->updateAttribute()` method as a work around for users without `ldap_modify_batch()`.

**Comment by pa102** [comment]
Thanks for getting back to me on this. Apologies for raising an issue when it was actually down to me not reading the documentation properly.

**Comment by stevebauman** [comment]
No problem at all!
