### ISSUE TITLE
Problem with Fatal error: Interface 'Adldap\Contracts\Adldap' not found

### ISSUE THREAD

**Issue by iOsama** [Adldap2/Adldap2#108]
I have an issue in installation of Adldap2.. 

it gives me this error message: Fatal error: Interface 'Adldap\Contracts\Adldap' not found!!

here's the code: 

include_once(dirname(__ FILE __) . '/Adldap/Adldap.php');
use Adldap\Adldap;

...

try
{
    $ad = new Adldap($config);
} catch(\Adldap\Exceptions\AdldapException $e)
{
    die("Not connected: $e");
}

**Comment by stevebauman** [comment]
You need to include the interface as well if you're not using an autoloader such a composer.
