### ISSUE TITLE
No exception thrown when initial bind fails

### ISSUE THREAD

**Issue by chriseskow** [Adldap2/Adldap2#111]
When you autoconnect with an admin username/password, it's rather difficult to determine whether or not the initial bind succeeded because no exceptions are thrown. It seems the most direct way to check is by calling `$ad->getConnection()->isBound()`, which is a pretty roundabout way of checking if `$ad` is ready to be used.

This seems to be happening because `authenticate()` swallows any exceptions thrown while binding and returns immediately. I'm guessing this is because `authenticate()`'s contract is to return a boolean instead of throwing exceptions... though it *does* throw exceptions when *re*binding...

If we can't make `authenticate()` throw an exception then perhaps we could modify either `connect()` or `__construct()` to throw an exception if `authenticate()` returns false. However that won't get us the root cause (e.g. bad hostname vs invalid credentials, etc.) without storing the details of the exception that was caught in `authenticate()`.

Is there a better way to do error handling that I'm missing?

**Comment by stevebauman** [comment]
You're right, this needs to be changed. Exceptions need to be consistent whenever binding takes place. Going to change this.

**Comment by chriseskow** [comment]
Thanks! The docs should be updated to match:

https://github.com/Adldap2/Adldap2/blob/master/docs/GETTING-STARTED.md

**Comment by stevebauman** [comment]
No problem. Done! https://github.com/Adldap2/Adldap2/commit/9a863e49aa18bb1643d8c229d56520ae6813b7fb

**Comment by chriseskow** [comment]
Hmm, would authenticate() ever return false now? It seems like it would always either return true or throw an exception, in which case the return value doesn't really matter (and that if statement should be removed).

**Comment by stevebauman** [comment]
Yup you're right, still making changes here, apologies.
