### ISSUE TITLE
Support domain controller failover

### ISSUE THREAD

**Issue by chriseskow** [Adldap2/Adldap2#112]
PHP's `ldap_connect()` supports a space-separated list of domain controller hosts, and attempts to connect to each successively if it fails to connect to the first one:

```php
// If corp-dc1.corp.acme.org fails to connect, it will try corp-dc2.corp.acme.org automatically:
$conn = ldap_connect('corp-dc1.corp.acme.org corp-dc2.corp.acme.org');

// Same, except with SSL:
$conn = ldap_connect('ldaps://corp-dc1.corp.acme.org ldaps://corp-dc2.corp.acme.org');
```

Adldap does support specifying multiple DCs in its configuration, however it just pick one at random and doesn't attempt to try the others.

I tried using the space-separated syntax, but that didn't work because Adldap automatically prepends `ldap[s]://` to the hostname:

```php
// Neither of these workarounds work:
'domain_controllers' => ['corp-dc1.corp.acme.org corp-dc2.corp.acme.org']
'domain_controllers' => ['ldap://corp-dc1.corp.acme.org ldap://corp-dc2.corp.acme.org']

// This works but is a hack:
'domain_controllers' => ['corp-dc1.corp.acme.org ldap://corp-dc2.corp.acme.org']
```

Can we either:

1. Change it so that if you specify multiple DCs, it will concatenate them together (with the correct `ldap[s]://` protocol) when passing to `ldap_connect()`. The downside is I'm not sure if there's a way to have `getDomainControllerSelected()` determine which one it ended up choosing, unless there's some way in the PHP LDAP API.
2. Keep the mulitple-DC behavior as-is and just detect space-separated hostnames and prepend the protocol correctly. This may be confusing to the user though because then there'd be two ways of specifying multiple DCs, one with failover support and the other without.
3. Change the connect behavior to catch connection errors and try each DC in turn. Basically, re-implement `ldap_connect()`'s failover behavior in PHP.

Thoughts?

**Comment by stevebauman** [comment]
You're right about this as well, this needs to be implemented. I wasn't aware of this functionality in the `ldap_connect()` method.

I'll keep the array of domain controllers as is, and append each of the controllers into the `ldap_connect()` method with the appropriate protocol prefix. I'll comment back when I have some commits, and let me know what you think, thanks!

**Comment by stevebauman** [comment]
Implemented failover: https://github.com/Adldap2/Adldap2/commit/140063fef5c5ab665d0f92d16e07abb4d438a90c

Unfortunately this means the removal of the configuration method `getDomainControllerSelected()` but the fail-over feature is much more useful than this.

This update along with others will be coming out in a `v5.3.0` due to incompatibilities and new exceptions that are going to be included.

**Comment by chriseskow** [comment]
Thanks! I'll try this out when I get a chance.
