### ISSUE TITLE
Prevent (or at least warn against) anonymous or unauthenticated binds

### ISSUE THREAD

**Issue by chriseskow** [Adldap2/Adldap2#113]
(Sorry for deluge of issues, you'll probably see more in the near future as I convert of our code to use Adldap2! :wink:)

Something that tripped me up is the fact that attempting to authenticate/bind using a empty or null password returns true, even if you specify a valid username. Allowing unauthenticated binds is a "feature" of LDAP, but I think it's important to protect users against this behavior as I don't think many people understand this.

For example:

```php
// Unsurprising behavior
$ad->authenticate('valid.username', 'valid.password'); // true
$ad->authenticate('valid.username', 'wrong.password'); // false
$ad->authenticate('invalid.username', 'anything'); // false

// Surprising behavior
$ad->authenticate('valid.username', ''); // true! (unauthenticated bind)
$ad->authenticate('', ''); // true! (anonymous bind)
$ad->authenticate(' ', ''); // true! (anonymous bind)
```

When Adldap is used to authenticate users based on user-supplied input, the developer must remember to ensure that both the username AND password are non-empty (and trim any leading/trailing whitespace beforehand). I don't think a lot of people will realize that they need to do this.

We could update the documentation to warn against this, but IMO Adldap should be proactive in preventing it. Perhaps reserve a separate API for anonymous or unauthenticated binds, while having the main `authenticate()` method prevent it by default?

**Comment by chriseskow** [comment]
Since "bind" is a core LDAP operation but "authenticate" is a user-level action, perhaps `bindUsingCredentials()` should be made public and allow null username/password (with strong warnings in the docs), and `authenticate()` should prevent it. This would allow most users to continue to use `authenticate` as they would expect (actually authenticating a username+password), while those who actually do need to perform anonymous binds can use `bindUsingCredentials`.

**Comment by stevebauman** [comment]
No need to apologize for the issues, I want Adldap2 to be the best it can be, and I really appreciate all contributions! I completely agree with this, anonymous binding isn't my intention with the `authenticate()` method. Thanks for bringing this up!

I'll make `bindUsingCredentials()` public like you've suggested.

**Comment by stevebauman** [comment]
In the upcoming `v6`, the auth `attemp()` method will now throw an exception on an empty username or password, as well as rebind failure. 

https://github.com/Adldap2/Adldap2/blob/master/src/Auth/Guard.php#L51

`bindUsingCredentials()` is public and throws an exception on failure.

https://github.com/Adldap2/Adldap2/blob/master/src/Auth/Guard.php#L100

Closing this for now since this release will be coming in the next few days.

**Comment by chriseskow** [comment]
Great, thanks!
