### ISSUE TITLE
Error when authenticate

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#114]
Hello @stevebauman !

You change something in authenticate and connect methods ? Since the last update I cannot connect to my LDAP directory. I have this error : 
```
Fatal error: Uncaught exception 'Adldap\Exceptions\Auth\BindException' with message 'Bind to Active Directory failed. Check the login credentials and/or server details. AD said: ' in C:\inetpub\wwwroot\adam\assets\Adldap\Adldap.php:326 Stack trace: #0 
```
My account is correct, I have correct rights for my AD.

Thanks for your reply

**Comment by stevebauman** [comment]
Hi @ciadch, are you using `dev-master`? Please use the latest release and not dev master.

**Comment by ciadch** [comment]
I'm using the master, directly downloaded form github.com. Same behaviour if I user the master branch cloned from my computer.

**Comment by stevebauman** [comment]
Please downloa the latest stable release and not master. The master may contai untested and unreliable code. The latest release will always contain tested code.

**Comment by ciadch** [comment]
Perfect sorry for that, I have to change my habits :-)

**Comment by stevebauman** [comment]
No problem!
