### ISSUE TITLE
Search Exceptions

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2#115]
Hi, I think I have a similar problem to https://github.com/Adldap2/Adldap2/issues/111.

If I search for users with a bad adldap configuration, I see no exceptions. I only see some warnings:
```
PHP warning:  ldap_bind(): Unable to bind to server: Can't contact LDAP server in ...\vendor\adldap2\adldap2\src\Connections\Ldap.php on line 499
PHP warning:  ldap_search(): Search: Can't contact LDAP server in ...\vendor\adldap2\adldap2\src\Connections\Ldap.php on line 420
```
Shouldn't bind exceptions thrown in this case too?

**Comment by strebl** [comment]
More information:
I use the findOrFail method which throws a `Adldap\Exceptions\ModelNotFoundException` Exception in this situation.

**Comment by stevebauman** [comment]
This is already in the works in `dev-master` with the new `BindException`. https://github.com/Adldap2/Adldap2/blob/master/src/Adldap.php#L326

**Comment by stevebauman** [comment]
Going to close this since these exceptions are already in place for `v6`.
