### ISSUE TITLE
useraccountcontrol

### ISSUE THREAD

**Issue by samwilson** [Adldap2/Adldap2#119]
Hi,

I'm a bit confused about using AccountControl... for example, if I want to find out whether an account is disabled, I thought the following might work:

``` php
$user->getUserAccountControl()->accountIsDisabled();
```

But `getUserAccountControl()` returns a string of the actual value of the useraccountcontrol attribute, rather than an `AccountControl` object (and `accountIsDisabled()` isn't boolean like it sort of suggests). Which is fine, I can just do:

``` php
$disabled = ($user->getUserAccountControl() & AccountControl::ACCOUNTDISABLE) == AccountControl::ACCOUNTDISABLE;
```

Is that right?

The [docs](https://github.com/Adldap2/Adldap2/blob/master/docs/models/user/ACCOUNT-CONTROL.md) say to first create a new AccountControl object, give it to the user, save the user, and _then_ ask `$ac` about the user. Something like:

``` php
$ac = new AccountControl();
$user->setUserAccountControl($ac);
$user->save();
$ac->accountIsDisabled();
$isDisabled = $ac->getValue();
```

But I don't think that's right either.

How should I be doing this?! :) Thanks!

**Comment by stevebauman** [comment]
The `AccountControl` object is used for *building* an account control integer easily, but it currently doesn't allow you to set the current integer and determine what options are enabled / disabled. I'll see if I can implement this.

I'll most likely rename the methods to follow what is actually going on with the object, since the methods right now sort of suggest a boolean is returned and you can use it to determine its current state (like you stated above). For example:

    $ac->runLoginScript();

    // Will turn into

    $ac->setRunLoginScript();

**Comment by samwilson** [comment]
Ah, that makes sense; thanks.

So I'm doing it correctly (for now at any rate) with

```php
$disabled = ($user->getUserAccountControl() & AccountControl::ACCOUNTDISABLE) === AccountControl::ACCOUNTDISABLE;
```
I'll keep an eye on things as they develop though :)

Thanks for all your work on this! It's so terrific.

**Comment by espinosa** [comment]
Hi,
I have submitted a pull request  f629605 to add 2 User model methods: isEnabled() & isDisabled().

**Comment by stevebauman** [comment]
You can now construct an `AccountControl` object with a flag and retrieve its values. For example:

```php
$ac = new AccountControl(522);

$values = $ac->getValues();

/**
 * Returns [
 *     0 => 2,
 *     1 => 8,
 *     2 => 512,
 * ]
 */
var_dump($values);
```
