### ISSUE TITLE
ldap_escape is only available in PHP 5.6 or higher.

### ISSUE THREAD

**Issue by ChadSikorra** [Adldap2/Adldap2#12]
I was just browsing through the source a bit and noticed that `ldap_escape` is used here:

https://github.com/Adldap2/Adldap2/blob/master/src/Adldap/Connections/Ldap.php#L572

There is actually a good replacement for this from the person that added this function to PHP:

http://stackoverflow.com/a/8561604/2242593

That way you could maintain PHP 5.3 compatibility.

**Comment by stevebauman** [comment]
Great catch! Had absolutely no idea about this incompatibility. This is my bad. Really appreciate you looking into this.

Will be pushed in shortly here.

**Comment by stevebauman** [comment]
https://github.com/Adldap2/Adldap2/commit/1da5bea01871e667c1a6e1abb9354e8f9959b285

Fixed!
