### ISSUE TITLE
Call to undefined method Adldap\Adldap::auth()

### ISSUE THREAD

**Issue by dozer55** [Adldap2/Adldap2#124]
Getting this message when trying to authenticate user. I have noticed that when I install with Composer the Auth folder is not downloading into Exceptions. Is this a known issue or something localized to me?

**Comment by stevebauman** [comment]
Hi, are you using `dev-master`? If so, please use the last stable version with composer (`5.2.*`).

**Comment by dozer55** [comment]
Thanks for the quick response. Here's the line from my composer.json: "adldap2/adldap2": "5.2.*" under "require"

**Comment by stevebauman** [comment]
Apologies, I've been working on reworking the documentation for `v6`, but the actual method for `5.2` is `$ad->authenticate($username, $password, $bindAsUser = false);`

**Comment by dozer55** [comment]
Aha! Thanks so much!
