### ISSUE TITLE
Authentication with Laravel 5

### ISSUE THREAD

**Issue by franktbc** [Adldap2/Adldap2#129]
New install of Laravel 5.
installed the mod, works, i can actually pull a user.and see details of him.

Now using auth , i changed the required info  and want to auth by samaccountname/username

any idea ?

adldap_auth :

```php
'login_attribute' => 'samaccountname',

'username_attribute' => ['username' => 'samaccountname'],
```

my login blade: 

   <input type="text" name="username" value="{{ old('username') }}">
<input type="password" name="password" id="password">

however using default laravel /auth/login uri it just loops back to the login page, assuming a fail ?

the Authcontroller verification could be a problem ?  from app\Http\Controllers\Auth

```php
 protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:60',
            'email' => 'required|email|max:100unique:users',
            'password' => 'required|confirmed|min:6',
        ]);
    }
```

and app\User.php

```php
class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword, AdldapUserModelTrait; // Insert trait here

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}
```

**Comment by stevebauman** [comment]
To authenticate a user with their username instead of their email, you need to change a couple things.

1. Rename the `email` field inside the default `users` table migration `database/migrations/2014_10_12_000000_create_Users_table.php`

```php
public function up()
{
    Schema::create('users', function (Blueprint $table) {
        $table->increments('id');
        $table->string('name');
        $table->string('username')->unique(); // 'email' to 'username'
        $table->string('password', 60);
        $table->rememberToken();
        $table->timestamps();
    });
}
```
2. Run the migration (`php artisan migrate`)
3. Change the validator inside `app\Http\Controllers\Auth\AuthController` to validate `username` instead of `email`

```php
protected function validator(array $data)
{
    return Validator::make($data, [
        'name' => 'required|max:60',
        'username' => 'required|max:100|unique:users',
        'password' => 'required|confirmed|min:6',
    ]);
}
```

4. Change the fillable attributes on your `app\User.php` model:

```php
protected $fillable = ['name', 'username', 'password'];
```

5. Inside your view, rename the input field from `email` to `username`

`
<input name="username">
`

**Comment by franktbc** [comment]
Ok done that, still same results, no errors

**Comment by stevebauman** [comment]
Did you change your `config/auth.php` file to use `adldap`?

```php
/*
|--------------------------------------------------------------------------
| Default Authentication Driver
|--------------------------------------------------------------------------
|
| This option controls the authentication driver that will be utilized.
| This driver manages the retrieval and authentication of the users
| attempting to get access to protected areas of your application.
|
| Supported: "database", "eloquent"
|
*/

'driver' => 'adldap',
```

Also to answer your question, a local mysql user is created upon authentication, allowing you to attach data as you would a regular user.

**Comment by franktbc** [comment]
// 'driver' => 'database',
    'driver' => 'adldap',

ok anyway to debug ?

**Comment by strebl** [comment]
Did you look into the `$errors` after the redirect?

**Comment by franktbc** [comment]
public function handle($request, Closure $next)
    {
        if ($this->auth->check()) {
           // var_dump($request);exit;
            return redirect('/home');
        } else {
           var_dump($this);exit;
            
        }

        return $next($request);
    }


this is dumping meaning the this-auth-check is false, but no idea where that is

could it session based error ? im actually running this on wamp on windows.

here is the This dump

object(App\Http\Middleware\RedirectIfAuthenticated)[195]
  protected 'auth' => 
    object(Illuminate\Auth\Guard)[200]
      protected 'user' => null
      protected 'lastAttempted' => null
      protected 'viaRemember' => boolean false
      protected 'provider' => 
        object(Adldap\Laravel\AdldapAuthUserProvider)[196]
          protected 'hasher' => 
            object(Illuminate\Hashing\BcryptHasher)[199]
              ...
          protected 'model' => string 'App\User' (length=8)
      protected 'session' => 
        object(Illuminate\Session\Store)[126]
          protected 'id' => string '267adb91a2de4ca920801286214f4c5b84601429' (length=40)
          protected 'name' => string 'laravel_session' (length=15)
          protected 'attributes' => 
            array (size=3)
              ...
          protected 'bags' => 
            array (size=0)
              ...
          protected 'metaBag' => 
            object(Symfony\Component\HttpFoundation\Session\Storage\MetadataBag)[135]
              ...
          protected 'bagData' => 
            array (size=1)
              ...
          protected 'handler' => 
            object(Illuminate\Session\FileSessionHandler)[134]
              ...
          protected 'started' => boolean true
      protected 'cookie' => 
        object(Illuminate\Cookie\CookieJar)[140]
          protected 'path' => string '/' (length=1)
          protected 'domain' => null
          protected 'queued' => 
            array (size=0)
              ...
      protected 'request' => 
        object(Illuminate\Http\Request)[39]
          protected 'json' => null
          protected 'userResolver' => 
            object(Closure)[153]
              ...
          protected 'routeResolver' => 
            object(Closure)[182]
              ...
          public 'attributes' => 
            object(Symfony\Component\HttpFoundation\ParameterBag)[41]
              ...
          public 'request' => 
            object(Symfony\Component\HttpFoundation\ParameterBag)[40]
              ...
          public 'query' => 
            object(Symfony\Component\HttpFoundation\ParameterBag)[47]
              ...
          public 'server' => 
            object(Symfony\Component\HttpFoundation\ServerBag)[44]
              ...
          public 'files' => 
            object(Symfony\Component\HttpFoundation\FileBag)[43]
              ...
          public 'cookies' => 
            object(Symfony\Component\HttpFoundation\ParameterBag)[42]
              ...
          public 'headers' => 
            object(Symfony\Component\HttpFoundation\HeaderBag)[45]
              ...
          protected 'content' => null
          protected 'languages' => null
          protected 'charsets' => null
          protected 'encodings' => null
          protected 'acceptableContentTypes' => null
          protected 'pathInfo' => string '/auth/login' (length=11)
          protected 'requestUri' => string '/auth/login' (length=11)
          protected 'baseUrl' => string '' (length=0)
          protected 'basePath' => null
          protected 'method' => string 'POST' (length=4)
          protected 'format' => null
          protected 'session' => 
            object(Illuminate\Session\Store)[126]
              ...
          protected 'locale' => null
          protected 'defaultLocale' => string 'en' (length=2)
      protected 'events' => 
        object(Illuminate\Events\Dispatcher)[5]
          protected 'container' => 
            object(Illuminate\Foundation\Application)[2]
              ...
          protected 'listeners' => 
            array (size=2)
              ...
          protected 'wildcards' => 
            array (size=0)
              ...
          protected 'sorted' => 
            array (size=39)
              ...
          protected 'firing' => 
            array (size=0)
              ...
          protected 'queueResolver' => 
            object(Closure)[6]
              ...
      protected 'loggedOut' => boolean false
      protected 'tokenRetrievalAttempted' => boolean false

**Comment by franktbc** [comment]
ok after quite a few debugging sessions, i found this in AdldapAuthUserProvider.php

lines :55~


         // Get the input key
         $key = key($attributes);
        // Filter the query by the username attribute
        $query->whereEquals($attributes[$key], $credentials[$key]);
        // this shows as ('samaccountname' , 'frank')
        // Retrieve the first user result
        $user = $query->first();
        $user is null

the base dn , shows as one level over me but recursive = true
      
how can i debug more ? on the AD side ?

**Comment by franktbc** [comment]
this is the $query object content..

http://prntscr.com/92akgm

you see the ad id, etc

**Comment by stevebauman** [comment]
`bound` is false on the connection object. It looks like you may not be properly connected to your ad server? Are you able to retrieve any results from your ad? Try:

```php
$results = \Adldap::search()->all();

dd($results):
```

**Comment by franktbc** [comment]
where should i bind ? in the Authcontroller.php ?
usually in my routes.php test, i do this 


$ad = new \Adldap\Adldap($configldap);    
    $ad->connect();
then this returns my user correctly 
$users = $ad->users()->search()->whereStartsWith('cn', 'frank')->get();

**Comment by stevebauman** [comment]
Closing this due to no updates.
