### ISSUE TITLE
Question: get the user groups

### ISSUE THREAD

**Issue by marcohofmann** [Adldap2/Adldap2#132]
hey steve,
in "adldap" i can use
```
$ad->user()->groups()
```
how can i do this in "adldap2"?
only with
```
$ad->users()->find($username)
```
and the "memberof"-array?

thanks

**Comment by stevebauman** [comment]
Hi @marcohofmann, you can get a users groups like so:

```php
$user = $ad->users()->find($username);

$groups = $user->getGroups(); // or $user->getMemberOf();
```

**Comment by arantxio** [comment]
Did the function change?
I cant call getGroups and getMemberOf

**Comment by stevebauman** [comment]
Hi @arantxio, nothing's changed. There's been no new release in 26 days.

What do you mean you can't call `getGroups()` or `getMemberOf()`?

**Comment by arantxio** [comment]
yes i get this error.
[Tue Jun 28 11:55:53.284629 2016] [:error] [pid 9328] [client 192.168.123.35:54437] PHP Fatal error:  Call to a member function getMemberOf() on a non-object in /var/www/html/qdesk/head.php on line 160
dont know why. same with getGroups

**Comment by stevebauman** [comment]
Looks like your calling the method on a non-existent object. Can you post your code?

**Comment by arantxio** [comment]
i used the code you posted above

$user = $ad->users()->find($username);

$groups = $user->getGroups();

**Comment by stevebauman** [comment]
Are you using OpenLDAP or ActiveDirectory?

**Comment by arantxio** [comment]
We use ActiveDirectory

**Comment by arantxio** [comment]
i found out when i use this code. it returns values but way too much.


$user = $provider->search()->whereEquals('cn', $username)->firstOrFail();

$groups = $user->getGroups();

print_r($groups);

**Comment by arantxio** [comment]
when i use
$user = $provider->search()->whereEquals('cn', $username)->firstOrFail();

$groups = $user->getAttribute('memberof');

print_r($groups);

it returnes the right values.

**Comment by arantxio** [comment]
I am getting the DN of it.
is it possible to filter out the CN from there
