### ISSUE TITLE
groups()->find('groupname') returns unexpected group 

### ISSUE THREAD

**Issue by Surfrdan** [Adldap2/Adldap2#133]
We have an AD with 2 similarly named groups, ONLINE and ONLINEX.

When I perform a $adldap->groups()->find('ONLINE') the returned object is for the ONLINEX group, not the ONLINE group. Is this expected behaviour? I'd have expected a perfect match to be returned over a partial match. Perhaps a string ordering issue?

**Comment by Surfrdan** [comment]
Workaround in case anyone needs one in the meantime. Expensive but gets the job done

    public function getGroup($groupName) {
		$adldap = self::getAd();
		$returnObject = false;
		foreach ($adldap->groups()->all() as $index => $group) {
			if ($group->name[0] == $groupName) {
				$returnObject = $group;
			}	
		}
		return $returnObject;
    }

**Comment by stevebauman** [comment]
Hi @Surfrdan, this is definitely not intended!

Going to investigate, thanks!

**Comment by chriseskow** [comment]
I noticed this issue too, seems it's because `groups()->find()` generates an "anr" (Ambiguous Name Resolution) query which returns all matching results. I've worked around by searching by CN instead.

**Comment by stevebauman** [comment]
Fixed in `5.2.1`, thanks for letting me know about this guys!

**Comment by Surfrdan** [comment]
Thanks, that's working perfectly now
