### ISSUE TITLE
Different suffix for admin vs users account names?

### ISSUE THREAD

**Issue by samwilson** [Adldap2/Adldap2#136]
Is it possible to define a suffix for user accounts, but not use it for the admin account? In `bindUsingCredentials()` it appends the suffix regardless of which type of user it is.

I have a situation where the admin service account is different from the user accounts.

**Comment by stevebauman** [comment]
Unfortunately at the moment this isn't possible, but definitely going to implement this early tomorrow.

**Comment by samwilson** [comment]
Thanks Steve! :)

At the moment I'm doing a wonky workaround that takes into account the fact that our service accounts begin with a hash character! Quite silly.

**Comment by samwilson** [comment]
(You've probably got a better way of fixing this issue, but this might be useful for other reasons.)

Could `\Adldap\Adldap::bindUsingCredentials()` be made protected visibility, rather than private? So I can override it without having to override the other methods that call it?

**Comment by stevebauman** [comment]
No problem! Added administrator account suffix on the master branch (`v6`):
https://github.com/Adldap2/Adldap2/blob/master/src/Auth/Guard.php#L141

Also changed visibility on bind methods: https://github.com/Adldap2/Adldap2/commit/a776087b8d845133c3e5e07af938fa625ed2793b

Please update to `v5.2.4` :)
