### ISSUE TITLE
ldap_modify_batch(): Batch Modify: Server is unwilling to perform

### ISSUE THREAD

**Issue by Surfrdan** [Adldap2/Adldap2#139]
When trying to create new users, I can successfully create users but they are created with a userAccountControl value of 546. i.e. they are disabled. I want them to be 'Normal Users' and am apparently setting a password successfully in the following code (however it's not possible to test as the users are created disabled...). When we get to setting the user as Normal, I receive an error from the AD server, "ldap_modify_batch(): Batch Modify: Server is unwilling to perform"

Here's a code sample:

                        $user = $adldap->users()->newInstance();
                        $user->setRawAttributes($attributes);
                        $user->setPassword($this->getPatronPassword());
                        $result = $user->create();
                        unset($user);
                        $user = $adldap->users()->find($barcode);
                        $ac = new \Adldap\Objects\AccountControl();
                        $ac = $ac->accountIsNormal();
                        $user->setUserAccountControl($ac);
                        $user->save();

I don't know whether the unset and find is required but I was following an old issue #38 which implied it might be required. However simplifying it to the following also fails in the same manner

                        $user = $adldap->users()->newInstance();
                        $user->setRawAttributes($attributes);
                        $user->setPassword($this->getPatronPassword());
                        $ac = new \Adldap\Objects\AccountControl();
                        $ac->accountIsNormal();
                        $user->setUserAccountControl($ac);
                        $result = $user->create();

**Comment by Surfrdan** [comment]
Problem resolved. I'd be under the impression that we were using TLS but switching to SSL resolved the issue.

**Comment by stevebauman** [comment]
Apologies for the long response on this. I'm glad you've resolved the issue!

Please don't hesitate to issue if you encounter any, thanks!
