### ISSUE TITLE
Delete user and change user group

### ISSUE THREAD

**Issue by dididado** [Adldap2/Adldap2#147]
Hello, first of all many thanks to develop this project, you save me a lot of time :)

I'm able to create user and query for it but i also have need to change user group and delete it, do you implemented those two functions?

Thanks.

**Comment by stevebauman** [comment]
You can use the `addGroup($groupDn)` and `removeGroup($groupDn)` methods on the `User` model itself like so:

```php
$user = $ad->users()->find('jdoe');

$groupDn = 'cn=Accounting,ou=Groups,dc=corp,dc=org';

$user->addGroup($groupDn);
$user->removeGroup($groupDn);
```

Or if you have the `Group` model instance, use `addMember($dn)`, and `removeMember($dn)`:

```php
$group = $ad->groups()->find('accounting');

$userDn = 'cn=jdoe,ou=Users,dc=corp,dc=org';

$group->addMember($userDn);
$group->removeMember($userDn);
```

**Comment by dididado** [comment]
Hi steve, i have some problem adding a user to a group, i tryed both before and after $user->save() and i always have this error:

```
PHP Fatal error:  Call to undefined function Adldap\Connections\ldap_modify_batch() in /var/www/html/test/ad/adtest/src/Connections/Ldap.php on line 589
```

this is my code:
```php
$groupDn = 'CN=Group,CN=Users,DC=example,DC=com';

// Add a group to the user
$user->addGroup($groupDn);

if($user->save()) {
    echo "User correctly created\n";
    $user = $adldap->search()->findByDn($attributes['dinstinguishedName']);
    $user->setPassword($attributes['password']);

    var_dump($user);
} else {
    echo "Error\n";
}
```

I have another question, is it possible to enable user after create it? i tried $user->enable() but it doesn't exist this method.

Thanks.

**Comment by stevebauman** [comment]
Please take a look at [optional requirements](https://github.com/Adldap2/Adldap2#optional-requirements).
