### ISSUE TITLE
 Interface 'Adldap\Contracts\Adldap' not found in Adldap on line 13

### ISSUE THREAD

**Issue by hexxamillion** [Adldap2/Adldap2#149]
This is related to #108. The Issue was closed but they did not provide suggestions on code. I am not using composer so I understand that I need to include the interface. Where do I need to include it at? I tried adding to my page underneath the include for adldap. Problem still exists.

    include_once(dirname(__FILE__) . '/include/adLDAP/Adldap.php');
    include_once(dirname(__FILE__) . '/include/adLDAP/Contracts/Adldap.php');

**Comment by stevebauman** [comment]
You need to include the interface before you include Aldap/Adldap.php

**Comment by stevebauman** [comment]
Closing due to no response.

**Comment by star-ley** [comment]
How include the interface?

**Comment by stevebauman** [comment]
`include_once('Adldap/Contracts/Adldap.php');`
