### ISSUE TITLE
Problem with composer

### ISSUE THREAD

**Issue by mathritter** [Adldap2/Adldap2#156]
I am getting this return when I add the package into the composer.json file:

C:\Adldap2-5.2\Adldap2-5.2>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package adldap2/adldap2 No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

I followed the given steps in the api description.

**Comment by stevebauman** [comment]
Sounds like you're not inserting the correct version for composer. Can you send your `require` section of your `composer.json`?

**Comment by mathritter** [comment]
I am kinda new to this composer tool. I read some stuff and how to use it and I followed the given steps . Here is the require section of my composer:
"require": {
        "php": ">=5.4.26",
        "doctrine/collections": "1.3.*",
        "ext-ldap": "*",
	"adldap2/adldap2": "5.2.*"
    }

**Comment by stevebauman** [comment]
Hmmm, can you post your entire `composer.json` if possible?

**Comment by mathritter** [comment]
Yes I can:
{
    "name": "adldap2/adldap2",
    "type": "library",
    "description": "A PHP LDAP Library for Active Directory Manipulation.",
    "keywords": [
        "active directory",
        "directory",
        "ad",
        "ldap",
        "windows",
        "adldap",
        "adldap2"
    ],
    "license": "LGPL-2.1",
    "support": {
        "issues": "https://github.com/Adldap2/Adldap2/issues",
        "source": "https://github.com/Adldap2/Adldap2"
    },
    "authors": [
        {
            "name": "Steve Bauman",
            "email": "steven_bauman@outlook.com",
            "role": "Developer"
        }
    ],
    "require": {
        "php": ">=5.4.26",
        "doctrine/collections": "1.3.*",
        "ext-ldap": "*",
		"adldap2/adldap2": "5.2.*"
    },
    "require-dev": {
        "phpunit/phpunit": "4.6.*",
        "mockery/mockery": "0.9.*"
    },
    "archive": {
        "exclude": ["/examples", "/tests"]
    },
    "autoload": {
        "psr-4": {
            "Adldap\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Adldap\\Tests\\": "tests/"
        }
    }
}

Maybe I am doing something else wrong.

**Comment by stevebauman** [comment]
Oh, you're copying the Adldap `composer.json` file, you need to change the `name` field to your own application name. For example:

```json
"name": "author-name/application-name",
```

You'll receive this error if you have the same name as a package you're trying to install.

**Comment by mathritter** [comment]
Ah, thank you. Now I get how to use this composer. Thank you very much, by the way, changing the name worked, but I will be creating my own composer file.

**Comment by stevebauman** [comment]
No problem! Glad you've solved the issue.
