### ISSUE TITLE
New StyleCI features

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2#159]
Hi @stevebauman 

StyleCI has two new features:
- Automatic PR Sending
- Automatic PR Merging (Only StyleCI's own PRs)

What do you think, should I enable them?

**Comment by stevebauman** [comment]
Hi @strebl, those are awesome new features, definitely enable it, thanks!

**Comment by strebl** [comment]
Okay, now active for booth StyleCI enabled repos: Adldap2/Adldap2 and Adldap2/Adldap2-Laravel

**Comment by stevebauman** [comment]
Ok perfect thanks!
