### ISSUE TITLE
Adldap2 5.* php requirements

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2#16]
While I was writing a Adldap2 feature I noticed that we still support PHP 5.3.

Should we move forward and bump the PHP requirement to 5.4?
I just hate the old array syntax. :smile:

**Comment by stevebauman** [comment]
I definitely agree that it's uglier, and I'd like to move forward, but I'll wait for more opinions on this before I start using the new syntax as well.

**Comment by wunc** [comment]
My 2 cents: It depends on what the intended audience is. Laravel 5, CakePHP 3, Drupal 8, and etc., all require 5.4. Wordpress is the exception as they try to maintain backward compatibility (with their huge user base, sort of like Windows).

Overall, I agree with @strebl on this (I greatly prefer the 5.4 array syntax). It would be nice to be able to use traits, too. As this is a "modern" version of the old package, it seems reasonable to move to 5.4, and if someone needs 5.3 compatibility they can use the old adLDAP package (as they probably already are).

**Comment by stevebauman** [comment]
That's a great point @wunc. They are free to continue using the older package, but the modern version will require 5.4. I'll change this now, thanks for your input guys!
