### ISSUE TITLE
Get All Users

### ISSUE THREAD

**Issue by vhugodev** [Adldap2/Adldap2#163]
Hi,
I've authenticated with admin account but I can't get the list of users. The following code retrieves only a bool value, in this case false. How can I retrieve the users data?

```php
$ad = new \Adldap\Adldap($config);
$ad->connect();
$users = $ad->users()->all();
```

**Comment by stevebauman** [comment]
Try testing an LDAP connection using the config mentioned here:

https://github.com/Adldap2/Adldap2#need-to-test-an-ldap-connection

If you're able to retrieve users from that configuration then it's your configuration your passing to Adldap. If you're not able to retrieve users, then it's an issue with the LDAP extension on your PHP install.

Also, there's no need to call `$ad->connect()`, it auto-connects by default ([Constructor arguments](https://github.com/Adldap2/Adldap2/blob/v5.2/src/Adldap.php#L31)).

**Comment by vhugodev** [comment]
Yeap, your the test works . But does'nt with my own ad. Do I need set some Active Directory configuration?

**Comment by stevebauman** [comment]
> Do I need set some Active Directory configuration?

Yes you do.

Take a look at the [configuration documentation](https://github.com/Adldap2/Adldap2/blob/v5.2/docs/CONFIGURATION.md), and let me know if you encounter any further issues by updating here, thanks :)
