### ISSUE TITLE
PSR-2 coding style

### ISSUE THREAD

**Issue by wunc** [Adldap2/Adldap2#17]
Should we try to stick to the [PSR-2](http://www.php-fig.org/psr/psr-2/) style guideline?

It definitely forces some less-compact syntax for control structures, but for open-source it is useful to have a standard to which contributors adhere. Thoughts?

**Comment by stevebauman** [comment]
Yea we should, I apologize for my 'non-PSR-2' code. I've only recently become aware of their nit-picky code standards like spaces, braces, tabs etc. Once you code a certain style for a period of time, it's hard to remove it, which I'm sure you all know :P.

Once I'm done with changes (which should be very soon), I'll be going through and making it all PSR-2 compatible (unless of course someone wants to make a PR for the changes).

Thanks for letting me know!

**Comment by strebl** [comment]
:+1:
