### ISSUE TITLE
Retrieving users breaks FirePHP debugger

### ISSUE THREAD

**Issue by Sogl** [Adldap2/Adldap2#170]
Hi!

I use FirePHP:
https://addons.mozilla.org/ru/firefox/addon/firephp/

I tried to get one or all users from test (or my own AD server) and got an error:
```
 ["There was a problem writ...ePHP/FirebugConsole/0.1",
SyntaxError: JSON.parse: unexpected character at line 1 column 80 of the JSON data
	
]
```

My code:
```
$users = $ad->users()->all();
fb($users);
```

Firefox 43.0.1
PHP 5.5

**Comment by stevebauman** [comment]
This seems like an issue with Firebug and not Adldap. I'm not sure what exactly you're intending to perform, and I don't know what the `fb()` function does.

**Comment by Sogl** [comment]
`fb()` shows output in Firefox Firebug console. 

Like this:
![firephp](https://cloud.githubusercontent.com/assets/7556290/12816836/0a14650a-cb92-11e5-9be2-bfbe505fa1be.png)

Something breaks it in 80 line if I output all users or just one. 
I'll try to research deeper.

**Comment by stevebauman** [comment]
I'm not sure this has anything to do with Adldap2. This seems like a firebug problem.
