### ISSUE TITLE
How to select some fields for all users 

### ISSUE THREAD

**Issue by Sogl** [Adldap2/Adldap2#171]
Hi!

I want to retrieve all users, but with some fields as described here:
https://github.com/Adldap2/Adldap2/blob/v5.2/docs/classes/USERS.md#find

How to do it?

**Comment by stevebauman** [comment]
Hi @Sogl, you can retrieve all users like so:

```php
$users = $ad->users()->search()->select(['cn', 'mail', 'surname'])->get();
```
