### ISSUE TITLE
cannot config port & tls not work

### ISSUE THREAD

**Issue by gwjwin** [Adldap2/Adldap2#172]
Hi,
The **port** setting in configuration never used, because in connect() function it always using "**ldap://**“ style URL, and the **port** parameter is not used (https://secure.php.net/manual/en/function.ldap-connect.php). This will be a problem when I want to connect to the Global Catalog at port 3268.  ( #173 )

Another problem is I find that the '**use_tls**' setting is no use, The ldap_start_tls() is not used anywhere.

**Comment by gwjwin** [comment]
#173

**Comment by jspringe** [comment]
This commit was merged - should it not be closed?
