### ISSUE TITLE
Admin account requirement interferes with authentication

### ISSUE THREAD

**Issue by therightstuff** [Adldap2/Adldap2#179]
Problem: I don't have access to an admin account, so if I want to authenticate a user I simply connect and then bind using that user's credentials. I don't need to perform a search for the LDAP user attempting to connect, but because this is assumed behaviour by this package I cannot authenticate without supplying the admin credentials.
This has put me in an the unfortunate position of relying on a single account to be able to login as admin when that account could be locked or disabled at any time, which would subsequently prevent any other users from authenticating against the server.

Suggested solution: if the admin credentials in the configuration file are empty or commented out, the binding step should be skipped after connecting and the supplied credentials should be authenticated directly without performing a lookup step first.

**Comment by jspringe** [comment]
When you authenticate have you tried to pass `true` as the last parameter. This is suppose to bind to that users account.

**Comment by isbkch** [comment]
I don't think you are talking about passing ```true``` to the ```attempt()``` method, nor the ```login()``` both in ```laravel\framework\src\Illuminate\Auth\SessionGuard.php```

So where do you suggest passing ```true``` ?

**Comment by stevebauman** [comment]
@isbkch, this is the root Adldap repository so the Laravel session guard isn't relevant to this issue. @jspringe means to try passing true in the last parameter when authenticating to adldap. This is shown in the documentation:

https://github.com/Adldap2/Adldap2/blob/v5.2/docs/GETTING-STARTED.md#authenticating-users

```php
if($ad->authenticate($username, $password, $bindAsUser = true)
{
    // User passed authentication
} else
{
    // Uh oh, looks like the username or password is incorrect
}
```
