### ISSUE TITLE
Custom Exceptions?

### ISSUE THREAD

**Issue by strebl** [Adldap2/Adldap2#18]
Hi guys. I started to implement a password change feature.

You can see my progress @ https://github.com/Adldap2/Adldap2/tree/real_password_change

To help developers I'd like to give them good error handling. There are many possible reasons why a password can't be changed.

How do you guys like to handle errors?

I'd like to return different Exceptions like: 
`PasswordPolicyException` (if the new password does't meet the password policy)
 or `WrongPasswordException` (if the old password is wrong)
With these exceptions it should be easy to return to the user with a understandable error message.

Unfortunately, as I know, there is no way to go deeper into the policy error. I can't find a solution to get a more specific password policy error like: password to short or password history conflict.

After I finished the password change functionality, I'd like to improve the authentication to give better feedback. Now you get "invalid credentials" if a user has to change his password. There I'd like to return a `UserMustChangePasswordException` which you can catch and redirect the user to a password change form or something like that.

Let me know what you think about that.

**Comment by strebl** [comment]
Oh I forgot to say that all these Exceptions would extend AdldapException. Therefore it's easy to implement a simple generic handler.

**Comment by stevebauman** [comment]
I completely agree with this, this would be a great feature!
