### ISSUE TITLE
master/v6 - SSO only over Kerberos

### ISSUE THREAD

**Issue by jspringe** [Adldap2/Adldap2#185]
Are you only accounting for Kerberos (sp?) for SSO? I understand why, but I'm in a Windows to Windows (not by choice) environment and the last time I looked there wasn't a Kerberos solution for a Windows server.

Have you looked at SSPI? With SSPI the authentication is automagically checked by the server (from the browser) and populates $SERVER['REMOTE_USER']. The unfortunate part is the only way I can handle auth with SSPI is to assume the server isn't lying and won't return that var unless it's been verified. Basically you have to assume truth with $SERVER['REMOTE_USER'].

**Comment by stevebauman** [comment]
I'm implementing this now on the Adldap-Laravel repository.

https://github.com/Adldap2/Adldap2-Laravel/blob/v1.4/src/Middleware/WindowsAuthenticate.php

The current implementation of SSO was merely ported from `v4` of Adldap. I didn't previously have access to use SSO at the time being so I was unable to test its usability.

**Comment by jspringe** [comment]
I haven't started using your implementation yet - I will after I finish tackling Laravel's auth/guard techniques (still fairly new to Laravel) and I don't want use it until it's not a mystery to me :).

One thing that you should consider is [here](https://github.com/Adldap2/Adldap2-Laravel/blob/v1.4/src/Middleware/WindowsAuthenticate.php#L52). That's actually a configurable option via `SSPIOmitDomain On`. I currently use it that way because we are only using a single domain.

**Comment by stevebauman** [comment]
> One thing that you should consider is here. That's actually a configurable option via SSPIOmitDomain On. I currently use it that way because we are only using a single domain.

Shoot, had no idea that option was configurable! I'll update that now, thanks :)
