### ISSUE TITLE
Configuration: Ignoring specified port?

### ISSUE THREAD

**Issue by leeralls** [Adldap2/Adldap2#186]
I noticed that in my configuration array, the `setPort` method seems to not be working correctly.
The example below should throw an error, but instead successfully connects:

```php
//ldaps @ port 636 as normal.
$config->setAccountSuffix('@mydomain.local');
$config->setDomainControllers(['ldap.mydomain.dom'] );
$config->setPort(1234); // on purpose
$config->setBaseDn('DC=mydomain,DC=local');
$config->setUseSSL(true);
$config->setUseTLS(false);
$config->setUseSSO(false);

$handle = new \Adldap\Adldap($config);

// should throw an error here
if( $ad->authenticate($username,$password) ) {
    echo 'authenticated';
} else {
    echo 'failed to authenticate';
}
exit;
```

Response: `authenticated`

However, specifying the port in the `setDomainControllers()` method seems to work:

```php
$config->setDomainControllers['ldap.mydomain.com:1234']);
//$config->setPort(1234);
```

Response: `...Cannot contact LDAP server`

Am I doing something wrong here?

**Comment by jspringe** [comment]
Try passing a `$configuration` array instead. Something like:

    $configuration = [
        'base_dn' => 'DC=mydomain,DC=local',
        'domain_controllers' =>['ldap.mydomain.dom'] ,
        'account_suffix' => '@mydomain.local',
        'use_ssl' => true,
    ];

    $adldap = new Adldap($configuration);
