### ISSUE TITLE
Setting Custom AD Attributes while creating user

### ISSUE THREAD

**Issue by sourjya** [Adldap2/Adldap2#187]
Hello,
    How do I pass custom AD attributes when creating new users? 

Thank you.

**Comment by stevebauman** [comment]
Hi @sourjya, you just assign the attribute manually:

```php
// Manually modifying, using their AD attributes
$user->cn = 'Doe, John';
$user->givenName = 'John';
$user->surname = 'Doe';
```

https://github.com/Adldap2/Adldap2/blob/v5.2/docs/models/INDEX.md#modifying-models
