### ISSUE TITLE
ldap auth form in laravel 5.2

### ISSUE THREAD

**Issue by st-claude** [Adldap2/Adldap2#188]
Hi

i'm noob, so this is an issue only for me :)

i know this is a recurrent question, but i started learning laravel a week ago, and after countless hours of watching tutorials and reading documentation, i can't seem to make this auth thing works :)
i read your comment here : Adldap2/Adldap2-Laravel#7 (comment)

and follow the instructions to the letter, but it seems that laravel 5.1 doesn't works exactly as the 5.2, so it's failing somewhere with a cryptic error (for me still)

i was wondering if maybe you could redo this kind of howto from scratch from laravel 5.2 ?

i have to say that i at least succeeded in connecting to my AD server, and dumping user data (i still can't format it properly but at least i see something)

also something else i'm confused in the documentation, this :
$ad = new Adldap($config);

am i supposed to declare in the controller a $config with everything ? if so, what is config/adldap.php for ?

thanks for reading me
regards
Dann

**Comment by stevebauman** [comment]
Hi @st-claude, this issue should be on the [Adldap2-Laravel Repository](https://www.github.com/Adldap2/Adldap2-Laravel), but its okay.

Here's a modified quick guide for laravel 5.2, but I'll create a more thorough walkthrough soon.

 - Created new laravel project using `laravel new adldap-test`
 - Created a new database in phpmyadmin for laravel migrations
 - Renamed `.env.example` to `.env`
 - Ran the command `php artisan key:generate`
 - Entered my DB credentials into `.env` file
 - Ran `php artisan migrate`
 - Added `"adldap2/adldap2-laravel": "1.4.*"` to my `composer.json` file
 - Ran the command `composer update`
 - Inserted providers into `config/app.php`
```php
    \Adldap\Laravel\AdldapServiceProvider::class,
    \Adldap\Laravel\AdldapAuthServiceProvider::class,
```
 - Inserted Facade into `config/app.php` `'Adldap'    => \Adldap\Laravel\Facades\Adldap::class,`
 - Ran the command `php artisan vendor:publish`
 - Changed `bind_user_to_model` to `true` in `config/adldap_auth.php`
 - Changed `config/adldap.php` configuration for my AD server
 - Ran the command `php artisan make:auth`
 - Inserted `Adldap\Laravel\Traits\AdldapUserModelTrait` onto the default `app/User.php` model
 - Switched auth driver in `config/auth.php` to `adldap`:

```php
'guards' => [
        'web' => [
            'driver'   => 'session',
            'provider' => 'adldap',
        ],

        'api' => [
            'driver'   => 'token',
            'provider' => 'users',
    ],
],

'providers' => [
        'adldap' => [
            'driver' => 'adldap',
            'model'  => App\Models\User::class,
        ],

        'users' => [
            'driver' => 'eloquent',
            'model'  => App\Models\User::class,
        ],
],
```

 - Visited `http://localhost/auth/login`, logged in with LDAP credentials, it redirected me to `http://localhost/home` but that doesn't exist so I just visited `http://localhost/` (the welcome page)
 - Edited the `welcome.blade.php` file and pasted `{{ dd(auth()->user()->adldapUser) }}` and ran the welcome page again, and it dumps the Adldap User
 - Refresh a bunch of times, the Adldap user is always dumped, the same instance

**Comment by st-claude** [comment]
Hi @stevebauman 

first, thanks for all your help :)

i will summarize here what i did to make it work, as i found some issues, and it might help other in my case
i managed by trial and error and by looking at the official doc page again.

also sometimes there was no laravel error at all which is quite confusing but trial and error was good in my case

i will copy/paste your post corrected for my case which is :
**i want to authenticate against a username from an active directory server, giving the php artisan make:auth generator.**
_in italic my comments/questions_

- Created new laravel project using `laravel new adldap-test`
- Created a new database in phpmyadmin for laravel migrations 
- (Removed Renamed .env.example to .env)  **no need anymore, generated by laravel new**
- (Removed Ran the command php artisan key:generate)   **same as above**
- Entered my DB credentials into .env file 
- modified database/migrations/2014_10_12_000000_create_users_table.php the line:
`$table->string('email')->unique(); to $table->string('username')->unique();`
- Ran `php artisan migrate`
- Added to the require field of composer.json file :
`"adldap2/adldap2-laravel": "1.4.*"` 
- Ran the command `composer update`
- Inserted providers into config/app.php
```
\Adldap\Laravel\AdldapServiceProvider::class,
\Adldap\Laravel\AdldapAuthServiceProvider::class,
```
_about that, why the backslash before ? that's not on the official doc page. Is it about finding the right path in laravel ? would it work without ?_
- Inserted Facade into config/app.php 
`'Adldap' => \Adldap\Laravel\Facades\Adldap::class, `
- Ran the command `php artisan vendor:publish`
- Changed in config/adldap_auth.php : 
`'bind_user_to_model' => true`
- Changed config/adldap.php configuration for my AD server 
- Ran the command `php artisan make:auth`
- in app/User.php i inserted :
```
<?php
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Adldap\Laravel\Traits\AdldapUserModelTrait;

class User extends Authenticatable {
   use AdldapUserModelTrait;
....
```
- also in app/User.php i changed the variable email to username : 
```
    protected $fillable = [
        'name', 'username', 'password',
    ];

```
- added to app/Http/Controllers/Auth/AuthController.php :

```
class AuthController extends Controller
{
    protected $username = 'username';
...

```
- Switched auth driver in config/auth.php to adldap: 
```
'guards' => [
        'web' => [
            'driver'   => 'session',
            'provider' => 'adldap',
        ],

        'api' => [
            'driver'   => 'token',
            'provider' => 'users',
    ],
],

'providers' => [
           'adldap' => [ 
            'driver' => 'adldap',
            'model'  => App\User::class, 
        ],

        'users' => [
            'driver' => 'eloquent',
            'model'  => App\User::class,
        ],
],
```

- modified login.blade.php to ask for username instead of email
- Visited http://localhost/login, logged in with LDAP credentials, the redirection is kind of messed up but this should be easily fixed
- Edited the home.blade.php file and pasted : 
`{{ dd(auth()->user()->adldapUser) }}`
and ran the home page again, and it dumps the Adldap User 
- Refresh a bunch of times, the Adldap user is always dumped, the same instance 

WORKING ! :)

i created another of laravel instance following "our" guide just to be sure everything was ok, so it should be reusable by anyone.
i think you should post that somewhere in the official doc for newbies like me who try to start learning laravel with a big project in mind (i'm actually trying to create a meeting tool for my company, with actions items, summoning, exchange communication and more features)

thanks again !

**Comment by gman29** [comment]
Hi @st-claude,

Stellar write up! This helped me to get things working.

Joe

**Comment by stevebauman** [comment]
Hi @st-claude, thanks for the write up! I'm really glad you've gotten it working.

I'll be sure to post this in the documentation.

**Comment by omadoyeabraham** [comment]
Hi @st-claude and @stevebauman great step by step howto. I followed it literally and i am able to login and dump the user data from AD, my challenge is that when i try to logout Laravel gives an error (Object of class Adldap\Models\User could not be converted to string). Please help.

**Comment by st-claude** [comment]
Hi @omadoyeabraham 

yes i had the problem too, i don't remember the error though.

the way i solved it, considering it's the same issue here, was to add this route in routes.php : 


```
    Route::get('/logout', function()
    {
        Auth::logout();
        Session::flush();
        return Redirect::to('/login');
    });
```

**Comment by omadoyeabraham** [comment]
Hi @st-claude 
Thanks for the quick reply.
Just tried that now and the error is still there.

**Comment by stevebauman** [comment]
That's strange, I'm not experiencing any of these issues. Are you trying to convert your `App\User` model to JSON?

**Comment by omadoyeabraham** [comment]
No i'm not, all i have done for now is just login. It gives the error when i try logging out.

**Comment by stevebauman** [comment]
Can you post your logout method here?

**Comment by omadoyeabraham** [comment]
<?php

namespace Illuminate\Auth\Events;

class Logout
{
    /**
     * The authenticated user.
     *
     * @var \Illuminate\Contracts\Auth\Authenticatable
     */
    public $user;

    /**
     * Create a new event instance.
     *
     * @param  \Illuminate\Contracts\Auth\Authenticatable  $user
     * @return void
     */
    public function __construct($user)
    {
        $this->user = $user;

    }
}

**Comment by stevebauman** [comment]
The class you've shown is empty, there's no logging out taking place here. Where are you calling `Auth::logout()`?

**Comment by omadoyeabraham** [comment]
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

Route::get('/', function () {
	return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/logout', function () {
	Auth::logout();
	Session::flush();
	return Redirect::to('/login');
});

**Comment by omadoyeabraham** [comment]
Please bear with me, i'm still new to laravel.

**Comment by stevebauman** [comment]
> Please bear with me, i'm still new to laravel.

It's no problem at all, I'm glad to help!

Can you paste the entire stack trace of the exception please?

**Comment by omadoyeabraham** [comment]
ErrorException in helpers.php line 696:
Object of class Adldap\Models\User could not be converted to string
in helpers.php line 696
at HandleExceptions->handleError('4096', 'Object of class Adldap\Models\User could not be converted to string', 'C:\wamp64\www\laravel\adl\vendor\laravel\framework\src\Illuminate\Support\helpers.php', '696', array('search' => '\?', 'replace' => array('BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', '2016-04-14 16:28:25', object(User), '1'), 'subject' => 'update `users` set `remember_token` = BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0, `updated_at` = 2016-04-14 16:28:25, `adldapUser` = ? where `id` = ?', 'value' => object(User)))
at preg_replace('/\?/', 'Object', 'update `users` set `remember_token` = BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0, `updated_at` = 2016-04-14 16:28:25, `adldapUser` = ? where `id` = ?', '1') in helpers.php line 696
at str_replace_array('\?', array('BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', '2016-04-14 16:28:25', object(User), '1'), 'update `users` set `remember_token` = ?, `updated_at` = ?, `adldapUser` = ? where `id` = ?') in QueryException.php line 56
at QueryException->formatMessage('update `users` set `remember_token` = ?, `updated_at` = ?, `adldapUser` = ? where `id` = ?', array('BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', '2016-04-14 16:28:25', object(User), '1'), object(PDOException)) in QueryException.php line 39
at QueryException->__construct('update `users` set `remember_token` = ?, `updated_at` = ?, `adldapUser` = ? where `id` = ?', array('BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', '2016-04-14 16:28:25', object(User), '1'), object(PDOException)) in Connection.php line 675
at Connection->runQueryCallback('update `users` set `remember_token` = ?, `updated_at` = ?, `adldapUser` = ? where `id` = ?', array('BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', '2016-04-14 16:28:25', object(User), '1'), object(Closure)) in Connection.php line 629
at Connection->run('update `users` set `remember_token` = ?, `updated_at` = ?, `adldapUser` = ? where `id` = ?', array('BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', '2016-04-14 16:28:25', object(User), '1'), object(Closure)) in Connection.php line 434
at Connection->affectingStatement('update `users` set `remember_token` = ?, `updated_at` = ?, `adldapUser` = ? where `id` = ?', array('BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', '2016-04-14 16:28:25', object(User), '1')) in Connection.php line 377
at Connection->update('update `users` set `remember_token` = ?, `updated_at` = ?, `adldapUser` = ? where `id` = ?', array('BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', '2016-04-14 16:28:25', object(User), '1')) in Builder.php line 1978
at Builder->update(array('remember_token' => 'BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', 'updated_at' => '2016-04-14 16:28:25', 'adldapUser' => object(User))) in Builder.php line 503
at Builder->update(array('remember_token' => 'BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0', 'updated_at' => '2016-04-14 16:28:25', 'adldapUser' => object(User))) in Model.php line 1555
at Model->performUpdate(object(Builder), array()) in Model.php line 1474
at Model->save() in EloquentUserProvider.php line 78
at EloquentUserProvider->updateRememberToken(object(User), 'BCOUxZI3TSydzVKyXluw83QHJeCud7wsIJwyAcRYYt17re8vjGWJn292eCP0') in SessionGuard.php line 579
at SessionGuard->refreshRememberToken(object(User)) in SessionGuard.php line 538
at SessionGuard->logout()
at call_user_func_array(array(object(SessionGuard), 'logout'), array()) in AuthManager.php line 288
at AuthManager->__call('logout', array()) in Facade.php line 215
at AuthManager->logout() in Facade.php line 215
at Facade::__callStatic('logout', array()) in routes.php line 22
at Auth::logout() in routes.php line 22
at RouteServiceProvider->{closure}()
at call_user_func_array(object(Closure), array()) in Route.php line 158
at Route->runCallable(object(Request)) in Route.php line 137
at Route->run(object(Request)) in Router.php line 724
at Router->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 64
at VerifyCsrfToken->handle(object(Request), object(Closure))
at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 62
at StartSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in Router.php line 726
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 699
at Router->dispatchToRoute(object(Request)) in Router.php line 675
at Router->dispatch(object(Request)) in Kernel.php line 246
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
at Pipeline->then(object(Closure)) in Kernel.php line 132
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
at Kernel->handle(object(Request)) in index.php line 54

**Comment by stevebauman** [comment]
Did you remember to insert the `Adldap\Laravel\Traits\AdldapUserModelTrait` on your `App\User` model outlined here?:

https://github.com/Adldap2/Adldap2-Laravel#binding-the-adldap-user-model-to-the-laravel-user-model

Upon logging out, laravel is trying to save the remember token, and along with it, it's also trying to save the adldap user that's attached to your user model.

**Comment by omadoyeabraham** [comment]
I have done that, but the error still occurs

**Comment by stevebauman** [comment]
No you haven't, I get the exact same error and stack trace when I removed the trait from my User model.

Are you using two different User models for authentication?

**Comment by stevebauman** [comment]
Can you post your configured `App\User` model here (your configured user model located in `config/auth.php`).

**Comment by omadoyeabraham** [comment]
Hi steve,
Sorry for the delayed reply. Here it is

'providers' => [
		'users' => [
			'driver' => 'eloquent',
			'model' => App\User::class,
		],

		'adldap' => [
			'driver' => 'adldap',
			'model' => App\User::class,
		],
with adldap being set as the provider for the web guard

**Comment by stevebauman** [comment]
No problem. Can you post the entire `User` model class?

**Comment by omadoyeabraham** [comment]
<?php

namespace App;
use Adldap\Laravel\Traits\AdldapUserModelTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable {

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name', 'username', 'password',
	];

	//public adldapUser;

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password', 'remember_token',
	];
}

**Comment by stevebauman** [comment]
You've inserted the trait, but you're not using it. You need to insert `use AdldapUserModelTrait` **inside** the `User` class, otherwise it's not applied.

**Comment by omadoyeabraham** [comment]
Thanks steve, its working now. I'm really grateful.

**Comment by st-claude** [comment]
which was written in the guide just above :)

**Comment by omadoyeabraham** [comment]
sadly yes, don't know how i missed it. Thanks for the guide though, it was helpful.

**Comment by stevebauman** [comment]
@omadoyeabraham No problem! Thanks for using Adldap2 :).

@st-claude Thanks again for the complete walkthrough guide, I'm going to put this in the quick-start right now.

**Comment by st-claude** [comment]
@omadoyeabraham happens to the best of us ;)

@stevebauman my pleasure, couldn't have done it without you :)

**Comment by alvinbunk** [comment]
Thank you @st-claude ! I followed your guidelines exactly and it worked for the same scenario. Hopefully @stevebauman you can update the install guide. I appreciate your responding to users comments.

**Comment by stevebauman** [comment]
Hey @alvinbunk, I've updated @st-claude's guide and published it here:

**Comment by alvinbunk** [comment]
Hi there @stevebauman . Thanks for the pointer to the new guide. Some changes needed. I went through it a 2nd time last night:

The line "'Adldap' => Adldap\Laravel\Facades\Adldap::class`," has a "`" in it (after class), can you remove that.

Step 13, "Inside the generated app/Http/Controllers/AuthController.php, you'll need to change the protected $username property if you're logging in users by username";
change to: "Inside the generated app/Http/Controllers/**Auth**/AuthController.php, you'll need to **add **the protected $username property if you're logging in users by username".

Step 15, "<input type="**text**" class="form-control" name="username" value="{{ old('username') }}">"

**Comment by stevebauman** [comment]
Thanks @alvinbunk, the changes have been implemented!

**Comment by alvinbunk** [comment]
Also another question, I'm a newbie to Laravel. How do you force authentication when for example, someone wants to view the "/" directory?

My app/Http/routes.php file has this:

Route::get('/', function () {
    return view('welcome');
});

I want to force to redirect to /auth/login

**Comment by alvinbunk** [comment]
@stevebauman also change step 15 input 'type' to 'text'. The type 'username' is not a valid type...

**Comment by stevebauman** [comment]
No problem, you can use the `auth` middleware and insert the routes you want to protect inside of it:

```php
Route::group(['middleware' => ['auth']], function () {

    Route::get('/', function () {
        return view('welcome');
    });

});
```

You can configure your middleware in your `app/Http/Kernel.php` file, and the middleware itself in `app/Http/Middleware/Authenticate.php`.

**Comment by stevebauman** [comment]
> also change step 15 input 'type' to 'text'. The type 'username' is not a valid type...

Changed, thanks!

**Comment by alvinbunk** [comment]
@stevebauman is there a way to force a logout for an authenticated user? I know in the browser I can delete the session, but I wonder is there a route or way for me to do that? I want to provide a logout link. You can direct me to some other documentation of you know of any. Thanks!

**Comment by stevebauman** [comment]
If you haven't created a logout route, you'll need to create one (this is pointing to the default `app/Http/Auth/AuthController`:

```php
Route::get('auth/logout', [
    'as'     => 'auth.logout',
    'uses' => 'Auth\AuthController@getLogout'
]);
```

In your blade views:

```php
<a href="{{ route('auth.logout') }}">Logout</a>
```

More information here:

https://laravel.com/docs/5.1/authentication

**Comment by st-claude** [comment]
this worked for me : 
https://github.com/Adldap2/Adldap2/issues/188#issuecomment-209905424

it's different from @stevebauman answer though, and i don't know enough if this is good practice ?

**Comment by stevebauman** [comment]
@st-claude That's definitely not bad practice (in my opinion), but I'm not sure why it's needed to flush the session manually after logging out?

This is mine in my application right now:

`routes.php`

```php
$router->group(['middleware' => ['auth']], function (Router $router) {
    $router->get('logout', [
        'as'   => 'logout',
        'uses' => 'AuthController@getLogout',
    ]);
});
```

`app/Http/Controllers/AuthController.php`

```php
/**
 * Log the user out of the application.
 *
 * @return \Illuminate\Http\Response
 */
public function getLogout()
{
    // Log the user out.
    Auth::logout();

    flash()->success('Success!', "You've been logged out!");

    return redirect('/');
}
```

Are you receiving exceptions and / or issues related to Adldap when you don't flush the session?

**Comment by st-claude** [comment]
not at all, it just looked like a good thing to do... i must have read that somewhere...

**Comment by rfahey79** [comment]
Followed steps to the letter, however when I click login button on the login form only error that I receive is password is missing (doesn't seem to care much that the username field is blank). If I provide incorrect credentials I'm just redirected to the login with no errors. When I provide correct credentials I'm just redirected back to the login page and there's no indication that I'm logged in at all (though if I try to DD the user class I get an error that it doesn't exist). 

Suggestions?

**Comment by alvinbunk** [comment]
Hi there @rfahey79 . Use the DEV environment to verify what the problem is. For example if you URL is: http://localhost/, then use: http://localhost/app_dev.php.

Also if you are using a different machine for your browser than the local machine that has Symfony installed, you'll have to edit the "web/app_dev.php" file to include your IP address. Then try to login, then check the log file under var/logs/dev.log. This should help you a lot in troubleshooting.

**Comment by rfahey79** [comment]
I tried what you suggested (i'm running laravel on homestead) and going to my adlap.app:8000/app_dev.php site i get a simple "no input file found". my adlap.app site redirects directly to /public/ so i'm not sure if that makes a difference?

**Comment by alvinbunk** [comment]
Oops, I apologize @rfahey79 . I thought for some reason this was [Symfony](http://symfony.com/) instead of Laravel. Ignore my suggestions. Maybe someone else has some suggestions

**Comment by kordhrufan** [comment]
And what about creating an adminless LDAP verification on a laravel 5.2 project? I can't find a guide in order to configurate my ldap to run witouth admin verification :S

**Comment by stevebauman** [comment]
Hi @kordhrufan, this is more easily said than done. Everyone keeps suggesting this with no implementation plan.

Right now you can use Adldap2 without admin credentials, but you will have to re-authenticate the user on every request to be able to run LDAP operations under their account.

How would you store these user credentials so you can run LDAP commands & queries underneath their account for every request?

Sure you can encrypt their credentials and store them somewhere (session / database / file, etc.), but this is still a security concern, and this is also a framework agnostic package which makes no assumptions of how you store data.

**Comment by kordhrufan** [comment]
I see, let me put the problem I'm having in other perspective.

The client has an LDAP database somewhere, and want his laravel application login using the registered accounts in his LDAP database, besides, he has a local database in postgres that store some of those users in order to gain access to the application.

In other words, he wants to use the LDAP for search purpouses and validate it with the local database, thats why he wants the authentication adminless.

**Comment by stevebauman** [comment]
> In other words, he wants to use the LDAP for search purpouses and validate it with the local database, thats why he wants the authentication adminless.

If only one request is necessary for your application and it's for authentication, you can definitely do this:

```php
$provider = new \Adldap\Connections\Provider();

$config = ['...'];

$provider->setConfiguration($config);

try {
    $provider->connect($username, $password);

    // We're now connected as the above user.

    $user = $provider->search()->where('cn', '=', 'jdoe')->first();
} catch (\Adldap\Auth\BindException $e) {
    // Connection / Authentication failed.
}
```

**Comment by kordhrufan** [comment]
Sorry for the dumb question but... where do I should put that verification?

**Comment by macm7** [comment]
@stevebauman i have same problem as @kordhrufan right now. 
Where should i put exactly this piece of code ?

```
$provider = new \Adldap\Connections\Provider();

$config = ['...'];

$provider->setConfiguration($config);

try {
    $provider->connect($username, $password);

    // We're now connected as the above user.
    // We can now locate their LDAP account.

    $user = $provider->search()->findBy('samaccountname', $username);
} catch (\Adldap\Auth\BindException $e) {
    // Connection / Authentication failed.
}
```

**Comment by stevebauman** [comment]
@kordhrufan @macm7

You would place this in your authentication code, to be able to login users by their LDAP account.

This isn't a concrete implementation and you will definitely need to change this code for your own applications. This simply shows you how to connect & bind to your LDAP server using credentials given by the user.

**Comment by macm7** [comment]
You mean the AuthController? @stevebauman

**Comment by stevebauman** [comment]
Sure, if that's where you authentication logic is. This issue was posted on the root Adldap2 repository which is framework agnostic.

I also have no idea what your trying to accomplish in your application, so I can't tell you what to write or how to implement it.

**Comment by kordhrufan** [comment]
This is the `Controller/auth/AuthController` code

```
<?php

namespace App\Http\Controllers\Auth;

use App\User;
use Validator;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\ThrottlesLogins;
use Illuminate\Foundation\Auth\AuthenticatesAndRegistersUsers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    protected $username = 'username';
    /*
    |--------------------------------------------------------------------------
    | Registration & Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users, as well as the
    | authentication of existing users. By default, this controller uses
    | a simple trait to add these behaviors. Why don't you explore it?
    |
    */

    use AuthenticatesAndRegistersUsers, ThrottlesLogins;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = '/';

    /**
     * Create a new authentication controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware($this->guestMiddleware(), ['except' => 'logout']);
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }
}
```

I am trying to see where I can implement your code 

```
$provider = new \Adldap\Connections\Provider();

$config = ['...'];

$provider->setConfiguration($config);

try {
    $provider->connect($username, $password);

    // We're now connected as the above user.
    // We can now locate their LDAP account.

    $user = $provider->search()->findBy('samaccountname', $username);
} catch (\Adldap\Auth\BindException $e) {
    // Connection / Authentication failed.
}
$provider = new \Adldap\Connections\Provider();

$config = ['...'];

$provider->setConfiguration($config);

try {
    $provider->connect($username, $password);

    // We're now connected as the above user.
    // We can now locate their LDAP account.

    $user = $provider->search()->findBy('samaccountname', $username);
} catch (\Adldap\Auth\BindException $e) {
    // Connection / Authentication failed.
}
```

In other words, I want to use LDAP adminless in order to search the username and validate the user with a local database in a Laravel 5.2

**Comment by stevebauman** [comment]
You'll need to override the `login()` method on your `AuthController`, shown here in the `AuthenticatesAndRegistersUsers` trait:

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L51-L86

I can't offer you a solution that will work in your environment. You'll have to trial and error this to implement it yourself.

**Comment by kordhrufan** [comment]
Ok i'll keep trying until I find a solution, if I succed I'll post it here step-by-step.

**Comment by mvatansever** [comment]
You should implement the codes in a middleware like auth and the middleware must be throw exception if the user or whatever not found.
