### ISSUE TITLE
Recursive inGroup checking not supported?

### ISSUE THREAD

**Issue by barbuslex** [Adldap2/Adldap2#192]
Hi,

I make this code for test if an user is in a group  : 
```php
$user_is_in_group = $ad->users()->find('username')->inGroup('parentgroup');
```

$user_is_in_group variable contains false.

Here the architecture of my groups : 
> user
>    ---> group
>         ---- > parentgroup

I need to test if the user is in parent group. I need to list all groups recursively.

Is it possible to do this with adldap2 library ?

EDIT: 
In v4.0.5 we have the the ability to get groups recursively.

```php 
public function inGroup($group, $recursive = NULL) {
```

In v5.2 not, why ?
```php
public function inGroup($group)
```

Thanks to you

++

**Comment by tof06** [comment]
Because I also need this, I've written a quick patch. 
Not sure this is the best way to do it, but at least, it works.
I can make a PR if you're interested.

Thanks

```
--- vendor/adldap2/adldap2/src/Models/Traits/HasMemberOfTrait.php	(revision )
+++ vendor/adldap2/adldap2/src/Models/Traits/HasMemberOfTrait.php	(revision )
@@ -64,10 +64,16 @@
     /**
      * {@inheritdoc}
      */
-    public function getGroups($fields = [])
+    public function getGroups($fields = [], $recursive=false)
     {
-        return $this->getMemberOf($fields);
+        $groups=$this->getMemberOf($fields);
+        if ($recursive) {
+            foreach ($groups as $group) {
+                $groups=array_merge($groups, $group->getGroups());
-    }
+            }
+        }
+        return $groups;
+    }
 
     /**
      * {@inheritdoc}
@@ -137,9 +143,9 @@
      *
      * @return bool
      */
-    public function inGroup($group)
+    public function inGroup($group, $recursive=false)
     {
-        $groups = $this->getGroups();
+        $groups = $this->getGroups([], $recursive);
 
         if ($group instanceof Group) {
             if (in_array($group, $groups)) {
```

**Comment by barbuslex** [comment]
Thanks to you @tof06 ! Yes can you make a PR please ?

**Comment by stevebauman** [comment]
Added in [v.5.2.13 Release](https://github.com/Adldap2/Adldap2/releases/tag/v5.2.13).

**Comment by barbuslex** [comment]
Thanks so much !

**Comment by ciadch** [comment]
Hello ! 

The recursive function ends with error : 

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) [...]
```
Yes my user is membor of a lot of groups but it should work (it's worked with version 4)

Any suggesion ? 

Thanks a lot

**Comment by stevebauman** [comment]
Might be hitting a recursive infinite loop here, I'll add some validation to prevent this.

**Comment by ciadch** [comment]
Ok thank you.

In my case, I acutally use : 

```php
$this->search()->query('(&(sAMAccountName=MY-ACCOUNT)(memberOf:1.2.840.113556.1.4.1941:=CN-OF-GROUP))')->first();
```

It works perfectly, without any loop.

**Comment by curry684** [comment]
Any chance of adding the `$recursive` love to `getGroupNames` as well?

**Comment by stevebauman** [comment]
Hi @curry684, great suggestion! I'll have that implemented shortly.
