### ISSUE TITLE
search with filter

### ISSUE THREAD

**Issue by xnext40** [Adldap2/Adldap2#196]
Hi all, i creating query on yii 2
`			$server_data = $server->search()
			->where('objectClass', '=', 'user')
			->where('objectCategory', '=', 'person')
			->where('userAccountControl', '!', '514')
			->where('userAccountControl', '!', '66050')
			->select(array('cn', 'samaccountname','displayname','mail','telephoneNumber','mobile','info','dn'))->all();`

yii2 shows exeption:

`Call to undefined method Adldap\Query\Builder::all()`
How can I fix this problem

**Comment by stevebauman** [comment]
USS `->get();`.
