### ISSUE TITLE
Only AD supported?

### ISSUE THREAD

**Issue by quivalen** [Adldap2/Adldap2#198]
While looking for a library to simply use my LDAP directory (which use OpenLDAP) i stumbled on adldap2. I've found that some function strictly limit the use to Microsoft AD: for example the base_dn can only be in the form DC=xxx,DC,yyy while mine is ou=xxx,o=yyy,c=zzz (X,509 format).

I want to ask if this is intended, hence i need to fork the project to work with openLDAP, or if it's possible to insert a new config param (like x509format=true) and implement the function to workaround the problem.

Thank you in advance

**Comment by stevebauman** [comment]
Hi @quivalen, at the moment only Active Directory is supported. You may be able to use some functionality on OpenLDAP, but this isn't documented, nor can I support it.

The reasoning on not supporting OpenLDAP is that I just don't have a server available and the time to dedicate to supporting another LDAP version. I'd be absolutely happy to accept PR's for compatibility though.
