### ISSUE TITLE
Empty Search results

### ISSUE THREAD

**Issue by jmdevince** [Adldap2/Adldap2#199]
Hi,

I'm making a simple query and getting an empty array. I am successfully using it for authentication so I know the base_dn is set correctly. AFAIK all searches by default are recursive (even though the base_dn makes it so it doesn't have to be). 

`[Adldap::search()->where('cn', 'starts_with', 'Joseph')->get()`

If I look on the wire (using TCPdump) and AD result logging, I can see a number of users and properties actually being returned by the AD server. 

Is Adldap2 doing some additional client side filtering I don't know about? I've tried various methods, raw queries, users()->find(), etc and they all fail. I don't get why searching is failing but authentication works. The LDAP server *is* returning results for what I search for, I can see it over the wire but It's not showing me any results when I call ->get(). 

I'm using release 5.2.13

**Comment by jmdevince** [comment]
Turns out this is a problem when converting a result set to a JSON object. For some reason converting the result collection object to an array results in an empty array.

**Comment by stevebauman** [comment]
That's strange, can you show me a demonstration of the bug if possible?

Are you performing:

```php
$users = $ad->users()->all();

$encoded = json_encode($users);
```

**Comment by jmdevince** [comment]
No, using all() in our env would croak my scripts because we have so much data in AD records. 

It was specifically when doing a search 
```
$result = Adldap::search()->where('cn', 'starts_with', 'Joseph')->get()
return json_encode($result);
```

Would yield:
```
{}
```

If I did a var_dump on $result i'd get an object `Doctrine\Common\Collections\ArrayCollection`. If I typecast to `(array)` then I would get results. No typecasting resulted in the yield above.

**Comment by stevebauman** [comment]
Yea you'll need to cast it to an array like you mentioned, or call the `toArray()` method on the resulting collection:

```php
$result = Adldap::search()->where('cn', 'starts_with', 'Joseph')->get();

return json_encode($result->toArray());
```

**Comment by jmdevince** [comment]
I'm surprised it doesn't get typecasted like that automatically. I'm not super familiar with the PHP built in json_encode's internals or how it casts different object types.

**Comment by stevebauman** [comment]
> I'm surprised it doesn't get typecasted like that automatically.

This is the case if the collection object implemented the `JsonSerializable` interface, but unfortunately this isn't the case with doctrine collections.

https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/ArrayCollection.php#L39

These collections are being switched out in `v6` to Laravel collections **which do implement** this interface:

https://github.com/illuminate/support/blob/master/Collection.php#L16
