### ISSUE TITLE
Examples and demo (in /examples)

### ISSUE THREAD

**Issue by samwilson** [Adldap2/Adldap2#2]
I'm working on bringing the examples up to date, and fixing up the demo. My idea is that it should be possible to clone the repo, browse to `adldap2/examples`, stick in a hostname (at the minimum) and get some sort of info about configuration etc. Also log in as a user and see what $info can be found.

Does this sound okay?

Also, such a utility should probably not be included in any production situation, so should I add

```json
"archive": {
    "exclude": ["/examples"]
}
```
to `composer.json`?

**Comment by stevebauman** [comment]
Hey Sam, that sounds great, push away!

Feel free to push the updated examples to the master branch as well as the `composer.json` change if you'd like.


-- Steve

**Comment by samwilson** [comment]
(Oops, I forgot to ref this issue in the commit.)

I've pushed the new demo page to master. See what you think.
