### ISSUE TITLE
Changing a users OU?

### ISSUE THREAD

**Issue by prymribb** [Adldap2/Adldap2#200]
Is it possible to move a user to another OU?

**Comment by stevebauman** [comment]
Have you tried the `move()` method?:

```php
$user = $ad->users()->find('jdoe');

$user->move($rdn, $newParentDn, $deleteOldRdn = false);
```

https://github.com/Adldap2/Adldap2/blob/v5.2/src/Models/AbstractModel.php#L956

**Comment by prymribb** [comment]
That is what I was missing, thanks.

**Comment by stevebauman** [comment]
No problem! Glad I could help. Documentation still needs work unfortunately.
