### ISSUE TITLE
getFirstName

### ISSUE THREAD

**Issue by sn0rcha** [Adldap2/Adldap2#209]
Hey There,

I'm using 5.2.* and after doing:

```
$users = $ad->users()->all();
foreach ($users as $u) {
        echo $u->getFirstName();
        die;
    }
```

I get a null value. I was looking through the User class thought that should work. If I var_dump the $u I can see all the properties, I just can't seem to use all the getting functions, is that normal?

**Comment by stevebauman** [comment]
Hi, your AD schema may differ from the one included in `v5.2`. If you're able to see the properties of the user, retrieve the attribute by accessing it like a property:

```php
$user->firstName;

// Accessing the users CN:
$user->cn;

// Accessing the users DN:
$user->dn;
```
