### ISSUE TITLE
sortBy() sort flags

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#210]
Hello,

It could be really interesting to have the option to modifiy the sorting behaviour of sortBy() method. Especially to bypass uppercase or not in name and having a more "natural" sorting.

Thanks

**Comment by stevebauman** [comment]
Technically this is possible since you're able to override the Processor `processSort()` method:

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Processor.php#L214

What type of API are you looking for?

**Comment by ciadch** [comment]
Ok, with version 6 it's all right for me 

Thanks

**Comment by stevebauman** [comment]
No problem!
