### ISSUE TITLE
Unable to Paginate Users

### ISSUE THREAD

**Issue by sn0rcha** [Adldap2/Adldap2#211]
Hey There,

I'm working with a rather large Active directory, and when I do:

```$users = $ad->users()->all();```

I only get the first 1000.

I've looked at the paginate class and have tried to display all on a single page:

```
$ad->users()->search()->paginate(25)->getResults();
```

But when I do that I get:

```PHP Fatal error:  Call to a member function getResults() on a non-object ```

Anyone have any ideas how to get a full result listing on a single page?

I'm using 5.2.*

Cheers,
Ben

**Comment by stevebauman** [comment]
What type of instance do you receive when you call just `$ad->users()->search()->paginate(25);`?

**Comment by sn0rcha** [comment]
I sorted this out thanks.
