### ISSUE TITLE
attempt return always true

### ISSUE THREAD

**Issue by wranger** [Adldap2/Adldap2#217]
Hi,

the authentification method "attempt" returns always true?

<code>
var_dump($pro_adlogin->auth()->attempt("ThisISaTest", "asdfasdfasdf", true));
</code>

Warning: ldap_bind(): Unable to bind to server: Invalid credentials in /var/www/test/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 269
bool(true)

**Comment by stevebauman** [comment]
Sounds like your administrator credentials are wrong. You shouldn't be receiving an exception for the Auth attempt method.

Also not sure what you mean by always return true?

**Comment by wranger** [comment]
Hi,

yes the credentials are wrong, but the function returns true??

The ldap_bind() didn't throw any exceptions, it returns true or false. http://php.net/manual/en/function.ldap-bind.php and thats the problem. You return false if an exception was fired but there will never be one.


And another problem the ldap_bind() function raises a error in my apache log:

[:error] [pid 3291] [client 127.0.0.1:52590] PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /var/www/test/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 269

Can you add a @before ldap_bind() ?

**Comment by stevebauman** [comment]
That's strange? I've always received an exception when giving invalid credentials to the bind method?

Are you modifying PHP's error reporting level?

For example, this is why this pull was created:

For example: https://github.com/Adldap2/Adldap2/pull/178/files

**Comment by stevebauman** [comment]
I'm literally testing it with my server as we speak and I'm receiving false on invalid credentials.

**Comment by stevebauman** [comment]
Fixed, please update to `v6.0.1`, thanks!

**Comment by wranger** [comment]
works like a charm, thanks for the fast patch :)

**Comment by stevebauman** [comment]
Great to hear! No probrem :)
