### ISSUE TITLE
Select all users memberOf

### ISSUE THREAD

**Issue by duskohu** [Adldap2/Adldap2#219]
Hi,
Is possible select all users memberOf?
`$users = $adldap2->users()->search()->where('memberof', '=', 'myMember')->get();`

**Comment by stevebauman** [comment]
Hi, yes there is. Here you go. 

```php
$ad->users ()->search ()->rawFilter ('(memberof:1.2.840.113556.1.4.1941:=CN=MyGroup,DC=example,DC=com')->get ();
```
