### ISSUE TITLE
Reuse of the Query Builder

### ISSUE THREAD

**Issue by wranger** [Adldap2/Adldap2#220]
Hi,

when I try to reuse the $search Object, I get the same result as before.

Initial 

```
$search = $this->pro_adext->search();
$search->select(["cn","samaccountname","description","givenName","sn"]);
$res =null;
$res2=null;
```

Now the search:

```
$res =$search->where("cn", "contains","czerner")->get();
var_dump($res);
$res2 =$search->where("samaccountname", "contains","31105416")->get();
var_dump($res2);
```

My problem is that $res2 is equal to $res but $res2 should contain 7 entries and not only one. And it will contain 7 entries if I comment the first query out.

Should I always reinitialize the Search Object for every query?

**Comment by stevebauman** [comment]
> Should I always reinitialize the Search Object for ever query?

Yes, this is the point of object oriented searches. You're able to modify the underlying query with methods you call upon the search (whether it be chained or not). You need to call the `newInstance()` method when you want a new search query.

```php
$resultOne = $search->where('cn', '=', 'John Doe')->get();

$newSearch = $search->newInstance();

$resultTwo = $newSearch->where('cn', '=', 'Suzy Doe')->get();
```

**Comment by wranger** [comment]
your are fast, thx :)

**Comment by stevebauman** [comment]
Haha I try to be, thanks!
