### ISSUE TITLE
User create ldap_add error - Howto BUG

### ISSUE THREAD

**Issue by wranger** [Adldap2/Adldap2#221]
Hi,

I used this howto https://github.com/Adldap2/Adldap2/blob/master/docs/distinguished-names.md to create a new user. But a few question arise:

`$dn->addCn($user->getCommonName());`

This return nothing
2.)
When I try to create the DN, this is what I like to get: 

`cn=Test Czerner,ou=Stadtnutzer,ou=User,ou=Company,dc=adext,dc=dir`

and this is what I got

`cn=,ou=Leuphana,ou=Users,ou=Company,dc=dir,dc=adext`

Here is my code. (When I change the order my DN is correct ;))
```
		$user_data =array(
			'cn' => $data["firstname"].' '.$data["lastname"],
			'samaccountname' => $data["uid"]',
			'description' =>$data["matrikel"],
			'mail' => $data["email"],
			'pager' => $data["cardid"],
			'sn' => $data["lastname"],
			'givenName' => $data["firstname"]);
		
		$user = $this->pro_adext->make()->user($user_data);
		
		if($data["password"]==$data["repassword"])
			$user->setPassword($data["password"]);
		
		$user->setCommonName($data["firstname"].' '.$data["lastname"]);
		
		$dn = $user->getDnBuilder();
		$dn->addCn($user->getCommonName());
		$dn->addOu("Stadtnutzer");
		$dn->addOu("Users");
		$dn->addOu('Leuphana');
		$dn->addDc('adext');
		$dn->addDc('dir');
		$user->setDn($dn);
		echo $user->save();
```

```
cn=,ou=Leuphana,ou=Users,ou=Stadtnutzer,dc=dir,dc=adext
Internal Server Error

ldap_add(): Add: Invalid syntax

[lib/base.php:2032] Base->error(500,'ldap_add(): Add: Invalid syntax')
[vendor/adldap2/adldap2/src/Connections/Ldap.php:277] ldap_add(NULL,'cn=,ou=Company,ou=Users,ou=Stadtnutzer,dc=dir,dc=adext',array('cn'=>'Carsten 

```

**Comment by stevebauman** [comment]
1.

> $dn->addCn($user->getCommonName());

> This return nothing

This actually returns the current `DistinguishedName` object:

```php
    /**
     * Adds a CN to the CN array.
     *
     * @param string $cn
     *
     * @return DistinguishedName
     */
    public function addCn($cn)
    {
        $this->commonNames[] = $cn;

        return $this;
    }
```

2. 

I was able to produce your requested output using:

```php
$dn
    ->addCn('Test Czerner')
    ->addOu('Company')
    ->addOu('User')
    ->addOu('Stadtnutzer')
    ->addDc('dir')
    ->addDc('adext');
```

But you're right, this actually feels *backwards*, and it's due to the reverse of array values in the `assembleRdns()` method here:

https://github.com/Adldap2/Adldap2/blob/master/src/Objects/DistinguishedName.php#L252

For some reason during implementation I thought this was desirable. This is definitely going to be changed.

**Comment by stevebauman** [comment]
Fixed: https://github.com/Adldap2/Adldap2/commit/41bfb71f3c1ded18a44a3d1ac49cf86f2097ed94

New release coming shortly. Also the reason you get the ldap_add failure is due to the CN being `null`:

```
// Here
cn=,ou=Company,ou=Users,ou=Stadtnutzer,dc=dir,dc=adext
````
