### ISSUE TITLE
$user->save() error handling

### ISSUE THREAD

**Issue by wranger** [Adldap2/Adldap2#223]
Hi again :),

what is about the error handling when creating a user? On my system it will never return false!

It's true or it will create error entry in my apache log
`
[Fri Apr 08 07:31:46.281347 2016] [:error] [pid 24270] [client 127.0.0.1:47553] ldap_add(): Add: Already exists, referer: http://f3.test/user/ADEXT/create`

I can avoid this error by search for the user first, but there are a lot more errors that can happen!

`$search->findByDn($user->getDn())`

At the old adldap it looked like:

```
        $result = @ldap_add($this->adldap->getLdapConnection(), "CN=" . $add["cn"][0] . ", " . $container . "," . $this->adldap->getBaseDn(), $add);
        if ($result != true) { 
            
	 //   printf("LDAP-Fehlernummer: %s<br>\n", ldap_errno($this->adldap->getLdapConnection()));
	 //   printf("LDAP-Fehler: %s<br>\n", ldap_error($this->adldap->getLdapConnection()));
	    return false;
        }
        
        return true;
```
It would be nice if the function save() / create() return true or false and I can grab the error_message manually for error_logging.

**Comment by wranger** [comment]
Oh man,

I thought I could use findByDn, but the result is the same as ldap_add if no user was found :(.

`
Base->error(500,'ldap_read(): Search: No such object')
[app/controllers/ADEXTUser.php:111] Adldap\Search\Factory->findByDn('cn=asdasd safd,ou=Stadtnutzer,ou=User,ou=Company,dc=adext,dc=dir')
`

**Comment by wranger** [comment]
What a nightmare,

here we go, a simple if to check if a userdoes already exist

`if((sizeof($search->where('samaccountname', '=', $user_data["samaccountname"])->get())==0) || (sizeof($search->where('cn', '=', $user_data["cn"])->get())==0))`

**Comment by stevebauman** [comment]
```php
$result = @ldap_add($this->adldap->getLdapConnection(), "CN=" . $add["cn"][0] . ", " . $container . "," . $this->adldap->getBaseDn(), $add);

if ($result != true) { 
     //   printf("LDAP-Fehlernummer: %s<br>\n", ldap_errno($this->adldap->getLdapConnection()));
     //   printf("LDAP-Fehler: %s<br>\n", ldap_error($this->adldap->getLdapConnection()));
        return false;
}

return true;
```

You're suppressing errors / warnings with the above method (`@`), you're able to do this with Adldap2:

```php
$user = $provider->make()->user();

if(@$user->save()) {
    // User was saved!
} else {
    $error = $provider->getConnection()->getLastError();
}
```

You have the freedom of choosing how to handle errors and warnings. That's the intent.

**Comment by wranger** [comment]
Perfect! Thanks

**Comment by zedfax** [comment]
You can also do it like that : 

`
try {
            $user->save();
        } catch (\Exception $e) {
            dd($e);
        }
`
