### ISSUE TITLE
How to get a group object by search

### ISSUE THREAD

**Issue by wranger** [Adldap2/Adldap2#225]
Hi guys,

I can search for a group by: 

```php
$search = $this->pro_adint->search();
$group = $search->where("cn","grp-alle-studenten")->get();
```
How can I now use the $group->getMembers(); function?

**Comment by stevebauman** [comment]
```php
$group = $search->where("cn","grp-alle-studenten")->first();

$members = $group->getMembers();
```

**Comment by wranger** [comment]
That was too easy :)

2.) Can I add a search filter to the method. It looks if I get back an array with all the user information, I only need the samaccountname?

3.) Is there a paginate mechanism for groups with more than 5000 users? There was a Bug in Ldap1 dealing with this kind of large groups and I fixed it by myself? 

It used the method on a search with more than 5000 members and the result was empty!

MS-AD return max 5000 elements during one request, so we have to split the request into several ...
see https://msdn.microsoft.com/en-us/library/cc223242.aspx
this is very important for the member -attribute of a  group, we need a paging mechanism and change the attribute from " "member" -> "memeber;range=0-1000" and increment it to invinit, the last element is "member;range=akt-val-*"
 the default value ist 1500, and max of 5000 -> this is hardcoded by MS :(

**Comment by stevebauman** [comment]
> 2.) Can I add a search filter to the method. It looks if I get back an array with all the user information, I only need the samaccountname?

Yup absolutely, use the `select($columns = [])` method to only retrieve information that you need. This will speed up your LDAP queries, for example:

```php
$users = $search->users()->select(['samaccountname'])->get();

// Returned models will only contain the `samaccountname` attribute.
```

More Information: https://github.com/Adldap2/Adldap2/blob/master/docs/query-builder.md#selects

> 3.) Is there a paginate mechanism for groups with more than 5000 users? There was a Bug in Ldap1 dealing with this kind of large groups and I fixed it by myself?

This is also built into Adldap2, use the `paginate()` method instead of the `get()` method when running large queries:

```php
// This would return only 1000 LDAP entries.
$records = $search->get();

// This would return **all** LDAP entries (1000 per page).
$records = $search->paginate(1000);
```

More Information: https://github.com/Adldap2/Adldap2/blob/master/docs/query-builder.md#paginating

**Comment by wranger** [comment]
Hi again, sorry maybe I'm to stupid for this? :(

2.) Yes, at first I search for the group. Thats the first query and I can setup a filter for this query. But when I got the Object and I call the getMembers() function on that, the object will return a whole Dataset for every Member. How can I set a filter on the getMember() function. 

Maybe there are 1000 user in this Group. There is the first query to get the Group and 1000 queries for getting the user Information with all the data. Can you please provide an example for working with groups.
gettingMembers / adding Members /deleting Members / isGroupMember

3.) I think we are not talking about the same thing, you talk about users. I talk about a Group and getting all the [member] attribute.

Example:  Your AD only returns 1000 member for each query, but your Group has 3000 Members the result was not the [member] attribute it is [member;range=0-1000] after that was returned you have to query for the next members [member;range=1000-2000]  and so on until you get the last element [member;range=2000-*].

For you info: Our largest groups has 12.000 members. Thats why I like to speed up my code. ;)
