### ISSUE TITLE
[6.0] Problem with illuminate

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#226]
Hi @stevebauman,

I try to upgrade ma Adldap with the last version. Now I have a fatal error with class illuminate : 

```
Fatal error: Uncaught Error: Class 'Illuminate\Support\Collection' not found in ...\Adldap\Query\Processor.php:186 Stack trace: #0 
```

Could you give me more information about this class ?

Thank you for your time and your help

**Comment by stevebauman** [comment]
Hi @ciadch, are you using composer? Adldap now return a new `Illuminate\Support\Collection` instance when returning search results (as mentioned here):

https://github.com/Adldap2/Adldap2/blob/master/docs/upgrading.md#search-results

If not, you'll need to require this class manually like you have for the previous doctrine collections:

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Collection.php

**Keep in mind**, installations without using composer aren't supported, and I've heavily recommend jumping on the bandwagon as soon as possible.

**Comment by ciadch** [comment]
Thank you for your help ! Yes I have to jump in :-) I'll do that asap !

**Comment by stevebauman** [comment]
No problem at! :)

**Comment by ciadch** [comment]
Ok i try with composer and now I have this error
```
Fatal error: Uncaught Error: Call to undefined function Illuminate\Support\data_get()
````

I'm sorry but i'm not an expert with this framework :-(

Any idea ? 

Thanks for your help
