### ISSUE TITLE
catching ConnectionException

### ISSUE THREAD

**Issue by veron-33** [Adldap2/Adldap2#227]
Hi.

In https://github.com/Adldap2/Adldap2/blob/master/docs/quick-start.md written:

```php
try {
    $ad->connect('default');
   . . .
} catch (\Adldap\Exceptions\Auth\BindException $e) {
    // There was an issue binding to the server.
} catch (\Adldap\Exceptions\ConnectionException $e) {
    // There was an issue connecting to the server.
}
```

but we can catch ConnectionException only `if the syntactic check fails` while executing ldap_connect (see http://php.net/manual/en/function.ldap-connect.php#refsect1-function.ldap-connect-returnvalues)

If I try to connect to the unreachable DC, now i catch BindException.

Also, can you add in every exception the ldap_errno, please? Something like this (in bind method):

```php
throw new BindException($message, $this->connection->errNo());
```

ps: sorry for my bad english

**Comment by stevebauman** [comment]
> but we can catch ConnectionException only if the syntactic check fails while executing ldap_connect
> (see http://php.net/manual/en/function.ldap-connect.php#refsect1-function.ldap-connect-returnvalues)

That's correct, I'll definitely update the docs to reflect this, instead of implying that there's a connection issue.

> Also, can you add in every exception the ldap_errno, please? Something like this (in bind method):

Yes definitely, good suggestion! I'll start implementing this now.

**Comment by stevebauman** [comment]
Added: https://github.com/Adldap2/Adldap2/commit/0ad234eb25341e485daa7d67ea8b5c758419a1c2

The bind exception is the only relevant class to be given the LDAP error number. But if I missed something. let me know, thanks!

**Comment by veron-33** [comment]
Thanks for adding ldap_errors to exception.

PS: if necessary, it is possible to catch ConnectionException by checking LDAP error number only. If server is unreachable, ldap_errno return "-1"
