### ISSUE TITLE
Filter data like ORMs do

### ISSUE THREAD

**Issue by nsossonko** [Adldap2/Adldap2#23]
Would be nice to filter data being passed to ldap_bind and ldap_search. Probably just calling ldap_escape with the correct flag would work (for 5.6+).

**Comment by nsossonko** [comment]
Ok, so I'm coming from adLDAP (the original), never realized that was shutdown and forked to here for active development. I think this is done already? Or must the callers call escape on the input themselves?

**Comment by stevebauman** [comment]
Hi, data is already escaped when placed inside any filter function. I've also added manual escaping to mirror the PHP 5.6 functionality [Connections/Ldap.php#L729](https://github.com/Adldap2/Adldap2/blob/master/src/Connections/Ldap.php#L729). This means that any PHP version (5.4 or greater) will have the same escaped output.

You can see it in action here in the [Query builder](https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L236).

This is also mentioned in the [search documentation](https://github.com/Adldap2/Adldap2/blob/master/docs/SEARCH-FUNCTIONS.md#where).

**Comment by stevebauman** [comment]
I'll also mention, filter fields and operators **are not escaped**, only the values. This is intended though, as it would be extremely rare to offer a user access to choose their own fields and operators when running LDAP query.

**Comment by nsossonko** [comment]
What about the credentials provided (eg to change a password, or authenticate a user), are they escaped too?

**Comment by stevebauman** [comment]
No, usernames and passwords are not escaped. This should be done by the dev since escaping usernames and passwords could cause issues. 

The `ldap_escape()` function is **only** for use in LDAP queries, not binding and other operations.

**Comment by nsossonko** [comment]
Not according to the docs here:
http://php.net/manual/en/function.ldap-escape.php

**Comment by stevebauman** [comment]
According to the docs, they are:

PHP Docs:
> ldap_escape — Escape a string for use in an LDAP **filter** or **DN**

My quote:
> only for use in LDAP queries (such as **filters** and **DN's**)

**Comment by nsossonko** [comment]
Why should it not be used in bind? There's no mention of this restriction
in the docs...

**Comment by stevebauman** [comment]
It's not that it `just` shouldn't be used in a bind, `ldap_escape()` converts characters to hex codes, for example:

    $password = 'testing=+<>"";:#()\x00';

    $escapedPassword = ldap_escape($password);

    echo $escapedPassword; // Returns \74\65\73\74\69\6e\67\3d\2b\3c\3e\22\22\3b\3a\23\28\29\5c\78\30\30

So this valid user password, just became invalid due to it being escaped, and this would result in a binding error.. The same goes for a username.

**Comment by stevebauman** [comment]
You're right about escaping the username, I'll be implementing this shortly here, but we still cannot escape passwords.

**Comment by nsossonko** [comment]
Ah, ok. I fully understand. Anyhow, aren't the passwords encoded before
being bound and/or changed?

**Comment by stevebauman** [comment]
I believe it depends on your connection to your server. If your using a non SSL/TLS connection, passwords are sent in plain text to your server, however you won't be able to change passwords without using an SSL or TLS connection, only authenticate.

Looking into the regular bind method in PHP source code, to my knowledge it doesn't look like any encoding or anything is done to the passwords before being sent to the server. [Link](https://github.com/php/php-src/blob/b8ba3203e59ffe063ceb24c0ab916208ef0e88c0/ext/ldap/ldap.c#L438)

**Comment by nsossonko** [comment]
I was looking at this: Link
<https://github.com/Adldap2/Adldap2/blob/master/src/Classes/AdldapUsers.php#L395>
in Adldap2 code. It's just encoding it to unicode, but I think that should
mitigate any attack vectors, no?

**Comment by stevebauman** [comment]
@strebl Implemented the new `changePassword()` method, he'd be the best to ask about this one. In my environment, no SSL connection exists for my AD server, so I use COM to change passwords.

**Comment by strebl** [comment]
Hmm, I don't fully understand the question, sorry.
Escaping the password string would change the password you're sending to the server.
Maybe that would work if you escape it every time, but the you can't change how for example windows sends the password to the server.
I don't see the problem of an escaped password string.
On filters, as @stevebauman said, totally fine. There you could change the whole filter, similar to SQL injections I think.

**Comment by nsossonko** [comment]
An unescaped password (if sent plainly to the server) would allow for ldap
injections, I assumed. Is that incorrect? My question was, since the
changePassword function encodes the password in unicode, does that
essentially mitigate the entire issue?

**Comment by strebl** [comment]
Hmm, I think that's not correct. There is nothing to parse for the server. You send a REPLACE or whatever request for a attribute with a value to the server.
That's not like a filter where you just send a string which the server will parse and execute.

**Comment by nsossonko** [comment]
Ok, I guess that makes sense. There was always concern in SQL of ending
statements prematurely with injection techniques...maybe that doesn't exist
with LDAP.

**Comment by stevebauman** [comment]
I agree with @strebl, to my knowledge, it doesn't matter what a password contains, it cannot escape and LDAP modification and allow for injections. This is because [Windows allows all UTF-16 characters](http://serverfault.com/questions/59686/invalid-characters-for-an-nt-password) to be used inside a password. If this was possible, it would be a massive security hole in AD, and any directory service for that matter.

**Comment by strebl** [comment]
@nsossonko That should only be a problem on values the server will parse, like filters.

@stevebauman Yeah, would be nonsense to encourage users to use special characters if they would be escaped :smile:

**Comment by stevebauman** [comment]
What we can do though, is hash the password before sending it to AD, prefixing it with the hash used. 

For example:

    $password = 'password';

    $hashed = '{MD5}'.md5($password);

    echo $hashed = '{MD5}5f4dcc3b5aa765d61d8327deb882cf99';

[Link](http://blog.michael.kuron-germany.de/2012/07/hashing-and-verifying-ldap-passwords-in-php/)

**Comment by strebl** [comment]
Wouldn't do that. It forces a secure connection anyway.
There are systems needing the password in plain text.
For example a directory sync service which syncs objects between multiple directories.
To sync the user password they'll listen to password changes.

**Comment by stevebauman** [comment]
Ah ok, good to know! :smile:

**Comment by strebl** [comment]
It seems the directory itself decides how to store the password. I think forcing a method, specially MD5 isn't that great too.

Another problem I see there: Let's say a user changes his password on a computer, the directory stores that as SHA1. How would you bind that user to the directory if you force MD5 on our side. 

For extracting users from the directory, totally fine I think.

I think that's one of the reasons the AD forces SSL.
