### ISSUE TITLE
$user->isDisabled() returns wrong result in version 6

### ISSUE THREAD

**Issue by szaqal83** [Adldap2/Adldap2#230]
Checking if account is disabled by $user->isDisabled() method returns FALSE though account is actually disabled. I've found an old [pull request](https://github.com/Adldap2/Adldap2/commit/f62960544f1072d2c571f7247ad88a99efbf1534) where isDisabled() looked like this:
```
return ($this->getUserAccountControl() & AccountControl::ACCOUNTDISABLE) === AccountControl::ACCOUNTDISABLE;
```
changing current:
```
return $this->getUserAccountControl() === AccountControl::ACCOUNTDISABLE;
```
to this one from pull request fixed it. $user attribute useraccountcontrol shows:
```
['useraccountcontrol'] =>
array(
[0] =>
546
) 
```

**Comment by stevebauman** [comment]
Thanks! Fixed is new release (`v6.0.5`).
