### ISSUE TITLE
[6.0] Remove CN, problem with accents ?

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#234]
How can I remove a CN which contains accent ? 

For exemple, I need to get remove a CN for a user, so my code is 
```php 
    $current_dn = $this->provider->search()->users()->find($user);
    $dn = $current_dn->getDnBuilder();
    $cn = $current_dn->getCommonName();
    // Remove current CN
    $dn->removeCn($cn);
    return $dn
```
The result is : 

```
cn=Test Pr\5cC3\5cA9nom,ou=....
```

But if my firstname is without accent, it works perfetly !

Thanks

**Comment by stevebauman** [comment]
Strange, going to investigate, thanks!

**Comment by stevebauman** [comment]
Seems like this is linked to #239. Fix is incoming.

**Comment by ciadch** [comment]
Thanks !
