### ISSUE TITLE
Model, getSamaccountname()

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#235]
It could be really usefull to have a function to get/set directly the samaccountname.

Thanks

**Comment by ciadch** [comment]
I saw that I can use 
```php
__get() and __set()
```
It's ok for me like that !

**Comment by stevebauman** [comment]
Yup you're able to set all attributes manually lIke so:

```php
$user->samaccountname = "johndoe";
$user->cn = "Doe, John";
```

**Comment by ciadch** [comment]
Ok perfect, And to get them directly ? If I use
```php
$user->samaccountname; 
```
I have an array and not the direct value

**Comment by stevebauman** [comment]
Yup you can retrieve all attributes of an Adldap model like that.

You will receive an array for almost every attribute since this is how they are actually returned from LDAP itself.

To get around this, access the first key of the array or use the `getAttribute ()` method:

```php
$username = $user->samaccountname[0];
$username = $user->getAttribute ('samaccountname', 0);
```

**Comment by ciadch** [comment]
Ok i'll use it like that ! 

Thank you so much !

**Comment by stevebauman** [comment]
No problem :)
