### ISSUE TITLE
Get authenticated user

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#236]
Hi !

Is there a function to get the authenticated user ? 

Thanks

**Comment by wranger** [comment]
What do you mean by authenticated user?

You can pass username + password to AD and check if the credentials are correct:

https://github.com/Adldap2/Adldap2/blob/master/docs/authenticating.md

**Comment by veron-33** [comment]
Agree with @wranger's question.

And if you want get binding username you can get it by calling
`getAdminUsername()` of  your `Adldap\Connections\Configuration` object. After you can get model of user using username and `search()` factory.

**Comment by ciadch** [comment]
Ok thanks, my question is a bit confused sorry. I think what I want is simply not possible :-) ! I will investigate...

Thanks guys

**Comment by stevebauman** [comment]
Are you using the laravel package? If you are then yes it's possible. Otherwise no unfortunately.
