### ISSUE TITLE
Howto:  Changing connection admin

### ISSUE THREAD

**Issue by wranger** [Adldap2/Adldap2#237]
Hi,

can I change the

```php
    'admin_username'        => 'admin',
    'admin_password'        => 'password',
```

of the connection after the config was set to the provider?

Administrator Username & Password (required)

When connecting to your AD server, an administrator username and password is required to be able to query and run operations on your server(s). You can use any user account that has these permissions.

--------------

After a user logs in, I need to change the initial admin to the, who currently logged in. 

------------
At first I thought the attempt() method does it, but it doesn't?

**Comment by stevebauman** [comment]
You'll want to use the [Bind As User](https://github.com/Adldap2/Adldap2/blob/master/docs/authenticating.md#binding-as-authenticated-users) boolean in the third paramter of the `attemp()` method.

**Comment by wranger** [comment]
Sorry that dosen't work Thats my code:

Bob is admin and opens the connection.
Alice use bobs connection for authentification
```php
if($this->pro_adint->auth()->attempt("alice", "Password", true))
```
But when I run a query() or a save(), the credentials from bob are passed to the connection (tcpdump).

**Comment by wranger** [comment]
```php
$ad = new \Adldap\Adldap();
$pro_adint = new \Adldap\Connections\Provider($config_adint);
$ad->addProvider("adint",$pro_adint);
```
befor and after calling the attempt() method i run a var_dump on $pro_adint and both connecting parameter are identical:
```pp

    ["adminUsername":"Adldap\Connections\Configuration":private]=>
    string(10) "bob
    ["adminPassword":"Adldap\Connections\Configuration":private]=>

```

**Comment by stevebauman** [comment]
This is because the beginning connect method of your provider by default uses your administrator credentials and binds to your server first as administrator, then the attempt method will bind as the user you've specified. For example:

```php
$config ['...'];

$provider = new Provider($config);

$provider->connect(); // This will bind to your server as your configured administrator in configuration.

$provider->auth()->attempt('jdoe', 'password', true); // This will bind to your server as 'jdoe'.
```

> befor and after calling the attempt() method i run a var_dump on $pro_adint and both connecting parameter are identical:

Also, yes you're dumping the AD object, which contains your configuration, which contains your administrator credentials.

**Comment by stevebauman** [comment]
My results in WireShark using `auth()->attempt('jdoe', 'password', true);`

```php
[LDAP] bindRequest(1) "admin" simple
[LDAP] bindResponse(1) success
[LDAP] bindRequest(2) "jdoe" sumple
[LDAP] bindResponse(2) success
[LDAP] searchRequest ...
```

My results in WireShark using `auth()->attempt('jdoe', 'password');` (No third parameter).

```php
[LDAP] bindRequest(1) "admin" simple
[LDAP] bindResponse(1) success
[LDAP] bindRequest(2) "jdoe" sumple
[LDAP] bindResponse(2) success
[LDAP] bindRequest(3) "admin" simple
[LDAP] bindResponse(3) success
[LDAP] searchRequest ...
```

**Comment by wranger** [comment]
Sorry, please stop any investigation. I think, after the attempt the object was overwritte by the default object.

**Comment by wranger** [comment]
I'm so sorry, I'm new to complete OOP in php? The attempt was set during login, but calling a new page creates new objects, I just needed to recall the attempt every time and not just during the login ;).

**Comment by stevebauman** [comment]
No problem at all! Glad you'd resolved it :)
