### ISSUE TITLE
No objectCategory in OpenLdap 

### ISSUE THREAD

**Issue by codbox** [Adldap2/Adldap2#238]
openLdap does not seem to have objectCategory. 

when searching  for users, we are adding objectCategory also. 

i am getting a query like this; 

```
"(&(objectclass=inetorgperson)(groupOfNames=person))"
```

Code:

```
    public function users()
    {
        return $this->query
            ->where([
                $this->schema->objectClass()    => $this->schema->objectClassPerson(),
                $this->schema->objectCategory() => $this->schema->objectCategoryPerson(),
            ]);
    }

```

**Comment by stevebauman** [comment]
Hi @codbox,

Unfortunately OpenLDAP isn't directly supported. I don't have access to an OpenLDAP server nor the resources / time to implement one for testing at the moment.

In `v6` there's now a Schema object that you can modify to work with OpenLDAP's differences if you're willing to try it out.

https://github.com/Adldap2/Adldap2/blob/master/docs/schema.md

**Comment by wranger** [comment]
Hi @stevebauman,

I could install a openldap server based on debian8  for you, if you like. You can choose between a Vmware or VirtualBox image, or I can give you access to a online server for a small amount of time, 4 weeks or so.
