### ISSUE TITLE
[6.0] Wrong encoded DNs

### ISSUE THREAD

**Issue by veron-33** [Adldap2/Adldap2#239]
Hi!

There is one problem with non-latin characters in DNs. Its encoded to ASCII in the ldap_explode_dn() function and search factory doesn't return objects, that`s really exist.

Can you make some correction in your explodeDn() method like in this:
```php
public static function explodeDn($dn, $removeAttributePrefixes = true)
    {
        $result = ldap_explode_dn($dn, ($removeAttributePrefixes ? 1 : 0));
        foreach($result as $key=>$value){
            $result[$key]=preg_replace("/\\\([0-9A-Fa-f]{2})/e", "''.chr(hexdec('\\1')).''", $value);
        }
        return($result);
    }
```
Please, look at this comment:
http://php.net/manual/en/function.ldap-explode-dn.php#34724

**Comment by stevebauman** [comment]
Fixed in commit https://github.com/Adldap2/Adldap2/commit/462e377c59b3d5b08a40b655e43451fc3b28cef4
