### ISSUE TITLE
Feedback on search API

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2#24]
Hey Guys, I'm just looking for some feedback on the search API before it's finalized. I had some ideas but if the current one in place is fine, then that's what I'll go with.

What I'm not sure on:

**String Operators**

    $ad->search()->where('cn', 'contains', 'John');

Should operators be converted into their own function? For example:

    $ad->search()->where('cn')->contains('John');

Using a `where()` method would return a where filter object, which allows you to transform it based on the operator. Thoughts?

**Comment by strebl** [comment]
Hmm...
```
$ad->search()->where('cn', 'contains', 'John');
```
That looks more familiar to me and would allow something like this in the future:
```
$ad->search()->whereCnContains('John');
$ad->search()->whereCnIs('John');
$ad->search()->whereCnIs('John')->orWhereCnIs('Jane');
```
If that is something you may wish to implement in the future.

**Comment by stevebauman** [comment]
Ended up going with a hybrid of your solution:

    $ad->search()->whereContains($field, $value);
    $ad->search()->whereStartsWith($field, $value);
    $ad->search()->whereEndsWith($field, $value);

Thanks!

**Comment by strebl** [comment]
👍🏼
