### ISSUE TITLE
Interface 'Adldap\AdldapInterface' not found

### ISSUE THREAD

**Issue by CHERTS** [Adldap2/Adldap2#240]
I use the version v6.0.7
I created an simple index.php file:

> <?php
> require_once 'src/Adldap.php';
> ?>

and I at once an error has occurred:

> 2016/04/26 17:58:01 [error] 1118#1118: *72395 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Interface 'Adldap\AdldapInterface' not found in /var/www/src/Adldap.php

How to work with the library?

**Comment by wranger** [comment]
Hi,

I use composer to get all the required php files:

http://robertan.com/home/2016/02/02/use-php-composer-in-existing-project/

**Comment by stevebauman** [comment]
Hi @CHERTS, @wranger is correct, I'd **really** recommend implementing composer. I don't support non-composer based installations (due to dependency and auto-loading issues).

Though to answer your question anyway, the correct path for the interface is:

```php
Adldap\Contracts\AdldapInterface
```
