### ISSUE TITLE
Tag an alpha or beta release?

### ISSUE THREAD

**Issue by wunc** [Adldap2/Adldap2#25]
I know Adldap2 isn't ready yet, but is it close enough to perhaps tag a v5.0.0-alpha.1 or v5.0.0-beta.1?

Core functionality (auth & search) seems to be there, and it would be nice to be able to reference a version that I could begin to use in other projects.

Thanks again for all your work.

**Comment by stevebauman** [comment]
Hey Wun, sorry for the long response on this. I completely agree with you. I'll tag an alpha release right now.

**Comment by wunc** [comment]
Awesome, thanks!
