### ISSUE TITLE
inGroup always False

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#251]
Hi,
I want add a user to a group, but checking before if the user is yet in that group.

This is my code:
`$user = $provider->search()->findBy('samaccountname', 'test');`
`$group = $provider->search()->groups()->findBy('cn', 'test-group');`

The result of `$user->inGroup($group);` is FALSE.
But, `$user->getGroups();` return an array with 1 item, wich is the group searched before.

Thanks!

**Comment by stevebauman** [comment]
Experiencing this locally, fixing now, thanks!

As a workaround for at the moment, you can pass the common name of the group into the `inGroup('Group Name')` method and it will return true.

**Comment by stevebauman** [comment]
Please update to `v6.0.10`, thanks!

**Comment by Albvadi** [comment]
That quickly!
I´ll wait for the update in packagist for update with composer.

Thnaks so much!
