### ISSUE TITLE
Inconsistent getAttribute??

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#258]
Hi,
sometimes getAttribute() return an array and others return a string, but I don´t know what ever...

Example:
`$user = $provider->search()->findBy('samaccountname', 'tester');`

`echo "GivenName: " . $user->getAttribute('givenname');` <= gives error because it return a Array, so, the correct sintax is `echo "GivenName: " . $user->getAttribute('givenname', 0);`

Now, I set the attribute with `$user->setAttribute('givenname', 'test');`
`$user->getAttribute('givenname', 0)` <= is NULL, because now, it return a String, so, the correct sintax is `$user->getAttribute('givenname')`

I don´t know if I´m doing anything wrong...
Thanks!

**Comment by stevebauman** [comment]
Hi @Albvadi,

While this is intended, I agree it causes confusion.

Since all LDAP attributes are located inside arrays, I think this should be labelled as a bug rather than what I thought may be a good feature / API.

Fixing now, thanks!

**Comment by Albvadi** [comment]
Hi, 
tested this issue and #259 and all work perfect.

Only want to thank you your amazing and fast support.
It´s not easy to find a developer who perform support like you. I appreciate it a lot!

Thanks!!! :smiley:

**Comment by Albvadi** [comment]
New problem at creating user with this change...

```PHP
$user = $provider->make()->user([
    'cn' => 'New User',
]);

if ($user->save()) {
    echo 'SAVED';
} else {
    echo 'ERROR';
}
```

**OUTPUT**
**Warning:** ldap_add() expects parameter 2 to be string, array given in **\vendor\adldap2\adldap2\src\Connections\Ldap.php** on line **259**
ERROR

**Comment by stevebauman** [comment]
> Only want to thank you your amazing and fast support.
It´s not easy to find a developer who perform support like you. I appreciate it a lot!

Thanks for the kind words! Appreciate it :)

I use Adldap2 in my production environments so it's crucial that I update it continually to make sure it's free from any issues.

Also, bug is directly related to the commit above:

https://github.com/Adldap2/Adldap2/commit/1b74cae60230669bcac17457347f99d1a30ed35b

It completely slipped my mind that the models distinguished name isn't located inside an array, which is giving the error. Fix will be out shortly, thanks!
