### ISSUE TITLE
Opposite to getDirty()??

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#259]
Hi,
I know there are a protected array with the original attributes.

If I set an attribute, I get the modified attributes with getDirty()... but, There are any option to get the original attribute before the change... any like getOriginal or getOriginalAttribute()??

Thanks!

**Comment by stevebauman** [comment]
Hi @Albvadi,

Strangely no this isn't available, I'm going to implement this now, thanks!
