### ISSUE TITLE
$ad->user()->all() is empty

### ISSUE THREAD

**Issue by elite123** [Adldap2/Adldap2#26]
I have successfully managed to connect and authenticate however when I call

    $ad->user()->all()

I get an empty array, likewise I get empty result on 

    $ad->user()->find($username);

Could this be a setting I need to change in AD?

**Comment by stevebauman** [comment]
If you try performing a standard search, do you receive any results?

Try:

    $results = $ad->search()->where('cn', '=', 'John Doe')->get();

**Comment by elite123** [comment]
Thanks for the suggestion, unfortunatley I still get an empty array

**Comment by stevebauman** [comment]
Must be a configuration issue, have you set your `base_dn`?

**Comment by elite123** [comment]
Yep:

    [
	'user_id_key' => 'samaccountname',
        'account_suffix' => '@domain.local',
        'person_filter' => array('category' => 'objectCategory', 'person' => 'person'),
        'base_dn' => 'DC=domain,DC=local',
        'domain_controllers' => array('adserver.domain.local'),
        'admin_username' => 'xxxx',
        'admin_password' => 'xxxx',
        'real_primarygroup' => true,
        'use_ssl' => false,
        'use_tls' => false,
        'recursive_groups' => true,
       'ad_port' => '389',
        'sso' => false,
    ];

Where domain is my domain and adserver is my ad server hostname

**Comment by wunc** [comment]
Double-check that objectCategory=person is the correct filter to narrow down your query to a person. You can use a tool like Apache Directory Studio and search for (cn=John Doe) or something like that, then inspect the attributes of the results. In my case, the correct person filter is actually objectClass=person, and I have to change it in the config array.

**Comment by stevebauman** [comment]
Yea you might need to fiddle with the configuration a bit and test your server connection with an external tool like @wunc mentioned. AD is pretty picky sometimes unfortunately.

**Comment by elite123** [comment]
Thanks guys - I have the following in ADS (am I right that these are what I should be looking at?):

    objectClass = organizationalPerson (structual)
    objectClass = person (structural)
    objectClass = top (abstract)
    objectClass = user (structural)
    objectCategory = CN=Person,CN=Schema,CN=Configuration,DC=DOMAIN,DC=local

So I assume as @wunc suggested I should be using:

    'person_filter' => array('category' => 'objectClass', 'person' => 'person'),

Sorry, my AD knowledge is somewhat limited...

**Comment by strebl** [comment]
Maybe a stupid question... What did you change on your configuration before you posted it here?
Are the values correct? account_suffix, base_dn etc.

**Comment by elite123** [comment]
This is my current config (only change is the admin username and password:

    [
	'user_id_key' => 'samaccountname',
        'account_suffix' => '@aba.local',
        'person_filter' => array('category' => 'objectClass', 'person' => 'person'),
        'base_dn' => 'DC=aba,DC=local',
        'domain_controllers' => array('optimus.aba.local'),
        'admin_username' => 'xxxxxx',
        'admin_password' => 'xxxxxx',
        'real_primarygroup' => true,
        'use_ssl' => false,
        'use_tls' => false,
        'recursive_groups' => true,
        'ad_port' => '389',
        'sso' => false,
];

**Comment by strebl** [comment]
As @wunc mentioned, try to connect with [Apache Studio](https://directory.apache.org/studio/download/download-windows.html) first.

Connection Settings Example:
![image](https://cloud.githubusercontent.com/assets/6151204/8748773/0e0774f2-2c9d-11e5-94f0-e1d053cf39a8.png)
![image](https://cloud.githubusercontent.com/assets/6151204/8748788/1c3114e8-2c9d-11e5-94be-20d3a117642a.png)

**Comment by elite123** [comment]
Yes, connection and auth are fine I get the following back (as above)from ADS:

    objectClass = organizationalPerson (structual)
    objectClass = person (structural)
    objectClass = top (abstract)
    objectClass = user (structural)
    objectCategory = CN=Person,CN=Schema,CN=Configuration,DC=aba,DC=local

I then use - 

    'person_filter' => array('category' => 'objectClass', 'person' => 'person'),

 in my config but get an empty array - is this correct based on the results from ADS?

**Comment by wunc** [comment]
So, now that you know you can connect, use ADS to verify that you can also search. The search results should also help you troubleshoot and give you an idea of what your AD user attributes look like. We're just suggesting this to try to eliminate that as source of your error and to help you formulate the proper search filter to use to find users.

In ADS, do `LDAP` > `New Search...` and fill in the search base (`dc=aba,dc=local`) and filter. For a filter, you could try something like `(& (objectClass=person) (cn=John Doe))`

**Comment by elite123** [comment]
Thanks for the pointers - I get the following returned:

![image](https://cloud.githubusercontent.com/assets/304047/8772031/20056004-2ec0-11e5-89bd-8568a3a69bd0.png)

**Comment by stevebauman** [comment]
Not seeing anything unusual. Try retrieving everything from AD, and see if anything is returned:

    $results = $ad->search()->all();

    var_dump($results);

**Comment by elite123** [comment]
Ok, so I am now getting:

    ErrorException in Entry.php line 52:
    Undefined offset: 2

if I wrap line 52 in an if I get output

    if(isset($attributes[$key][$i]))
    {
        $data[] = $attributes[$key][$i];
    }

So I then tried the following

    $results = $ad->user()->find('Joe Bloggs'); // returns false
    $results = $ad->user()->all(); // returns empty array

**Comment by stevebauman** [comment]
Try using the latest beta and see if you still encounter this issue.

**Comment by stevebauman** [comment]
Closing this as no update has been given on the issue.

**Comment by samwilson** [comment]
I was having exactly this issue, and it turned out to be just that I had the admin username/password wrong! :( oops. In one app, we had to do this, because we weren't allowed anon binding:

```php
$adldap->getConfiguration()->setAdminUsername($username);
$adldap->getConfiguration()->setAdminPassword($password);
```
