### ISSUE TITLE
Question about OpenLDAP support

### ISSUE THREAD

**Issue by fillup** [Adldap2/Adldap2#261]
I started integrating with this library yesterday and so far it is working nicely for searching. I'm using it with OpenLDAP and today I just noticed on the README:

> An Active Directory Server (no OpenLDAP support at this time)

Since the search is working for me I'm curious what features of this library do not work with OpenLDAP? Or is it just that you're not using it in that use case so you haven't tested it?

**Comment by stevebauman** [comment]
Hi @fillup,

> Or is it just that you're not using it in that use case so you haven't tested it?

This is exactly the reason. I just don't have access to an OpenLDAP server, so it's impossible for me to test with it and hope that it functions correctly. Though I'd definitely love to fully support OpenLDAP.

**Comment by fillup** [comment]
That makes sense, thanks. Looking through your tests I see it primarily uses mocks for the response. Do you have any dummy data for running actual integration tests? I could run them for you and report back if you'd like. I'll keep using this library with OpenLDAP for now until I have problems since it is working so far for me. 

Another quick question though. I'm trying to get access to an "[operational attribute](http://www.zytrax.com/books/ldap/ch3/#operational)" on a record, specifically pwdChangedTime. Does AD have that kind of feature too and if so how do you get access to those attributes?

**Comment by stevebauman** [comment]
> Do you have any dummy data for running actual integration tests?

I don't have a repository of dummy data, but this is absolutely something I should add for testing. I'll work on updating the tests in the coming days and get back to you.

> Another quick question though. I'm trying to get access to an "operational attribute" on a record, specifically pwdChangedTime. Does AD have that kind of feature too and if so how do you get access to those attributes?

There's a `pwdlastset` attribute in AD that's retrieved from the `Adldap\Models\User` here:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/User.php#L556

But you can retrieve any attribute that's returned from LDAP on a model like so:

```php
$user = $provider->search()->users()->where('cn', '=', 'John Doe')->first();

$user->pwdChangedTime;

$user->getAttribute('pwdChangedTime');
```

**Comment by miken32** [comment]
I think that line in the readme should be changed to "experimental" support, as it mostly worked for us as well. After changing the schema being used, I only had to make a small change to the Adldap\Schemas\OpenDLAP object to change another `person` to `inetOrgPerson`, and now it is working just fine.

**Comment by stevebauman** [comment]
Hi @miken32, I'm really glad that works for you with OpenLDAP!

Due to your suggestion, I've made the change in the readme: https://github.com/Adldap2/Adldap2/commit/6757e1ee0a16f7c1744b98cc3d867206aa0e64ff.

**Comment by fillup** [comment]
Thanks, I also wanted to report that access to the operational attributes works just like any other attributes. I was confused initially but realized it was because the attribute I wanted wasn't even set, so of course it wasn't returned.
