### ISSUE TITLE
BC Break :  $user->save() after v6.0.13

### ISSUE THREAD

**Issue by wallish** [Adldap2/Adldap2#264]
Hey,

I found a BC break from v6.0.13 to v6.0.15.

I put 6.0.* in my composer.json, and I got a surprise in v6.0.15, the insert is not working, so I downgrade step by step and everything is working in v6.0.13 (and below)

This is my array (I didnt put my dn for the example) :
```php
array(19) {
  ["sn"]=&gt;
  string(5) "Bar"
  ["givenname"]=&gt;
  string(5) "Foo"
  ["cn"]=&gt;
  string(11) "Foo.Bar"
  ["displayName"]=&gt;
  string(11) "Foo Bar"
  ["userPrincipalName"]=&gt;
  string(23) "Foo.Bar@test.fr"
  ["description"]=&gt;
  string(19) "PLANNER STRATEGIQUE"
  ["company"]=&gt;
  string(8) "TEST"
  ["telephoneNumber"]=&gt;
  string(11) "+33 1 22 22"
  ["streetAddress"]=&gt;
  string(36) "7, Des petits poney
75011 Paris"
  ["countryCode"]=&gt;
  string(3) "250"
  ["postalCode"]=&gt;
  string(5) "75011"
  ["c"]=&gt;
  string(2) "FR"
  ["st"]=&gt;
  string(6) "France"
  ["l"]=&gt;
  string(5) "Paris"
  ["accountExpires"]=&gt;
  string(19) "9223372036854775807"
  ["title"]=&gt;
  string(19) "PLANNER STRATEGIQUE"
  ["mail"]=&gt;
  string(23) "Foo.Bar@test.fr"
  ["samaccountname"]=&gt;
  string(11) "Foo.Bar"
  ["name"]=&gt;
  string(11) "Foo.Bar"
}
```
My function : 
```php
public function insert($data)
{
	try {
        $user = $this->_provider->make()->user($data);
		$dn = new \Adldap\Objects\DistinguishedName($data['dn']);
		$dn->addCn($data['cn']);
		$user->setDn($dn);

		//die(var_dump($data)); <= the dump you have above
		if ($user->save()) {
			echo "ok";
		} else {
			echo "fail";
		}
	} catch (Exception $e) {
	    echo $e->getMessage();
            die();
	}
}
```

- Version 6.0.12 : **success**
- Version 6.0.13 : **success**
- Version 6.0.14 : **Fail** => ``PHP Warning:  ldap_add() expects parameter 2 to be string, array given in .../vendor/adldap2/adldap2/src/Connections/Ldap.php on line 259``
- Version 6.0.15 : **Fail** = > ``PHP Warning:  ldap_add(): Add: No such attribute in .../vendor/adldap2/adldap2/src/Connections/Ldap.php on line 267``

Let me know, if you need more information.

**Comment by stevebauman** [comment]
Hi @wallish, looking into it now thanks!

**Comment by stevebauman** [comment]
Hey @wallish, I've found the issue.

You mentioned:

> This is my array (I didnt put my dn for the example) :

I'm assuming you were inserting the dn into your `$data` array under the `dn` key?

For example:

```php
$data = [
    'dn' => 'dc=corp,dc=acme,dc=org',
    ...
];
``

The correct key is:

```php
$data = [
    'distinguishedname' => 'dc=corp,dc=acme,dc=org',
    ...
];
```

**Comment by stevebauman** [comment]
Fixed: https://github.com/Adldap2/Adldap2/commit/bb9eca61caa29b14010819f65521952bacf7f649.

**Comment by wallish** [comment]
Thx 👍
