### ISSUE TITLE
Errors searching in OpenLDAP

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#265]
Hi!,
actually I´m using others libraries to query OpenLDAP, so viewing #261, I want try...
Also, I´m beginning a Laravel App, so, using this too, help me a lot of much!!

I set the config, but I have errors simply searching, so I think I´m missing anything...

Maybe someone can point me to the right way...

Config (With LDAPAdmin works well):
![sin-titulo-2](https://cloud.githubusercontent.com/assets/6285255/15502838/a2c85002-21b6-11e6-8589-dda71edc7cc3.png)

The simple code:
```$user = $provider->search()->findBy('uid', 'testuser');```

In web browser, the error is:
**Warning: ldap_search(): Search: No such object in \vendor\adldap2\adldap2\src\Connections\Ldap.php** on **line 219**

**Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in \vendor\adldap2\adldap2\src\Connections\Ldap.php** on **line 113**

In console with LDAP Debug:
```log
ldap_search_ext
put_filter: "(uid=\74\65\73\74\75\73\65\72)"
put_filter: simple
put_simple_filter: "uid=\74\65\73\74\75\73\65\72"
ldap_build_search_req ATTRS:t
                             ▒U\^U▒
ldap_send_initial_request
ldap_send_server_request
ldap_result ld 0353A628 msgid 2
wait4msg ld 0353A628 msgid 2 (infinite timeout)
wait4msg continue ld 0353A628 msgid 2 all 1
** ld 0353A628 Connections:
* host: openldap.***.***  port: 389  (default)
  refcnt: 2  status: Connected
  last used: Tue May 24 13:59:09 2016


** ld 0353A628 Outstanding Requests:
 * msgid 2,  origid 2, status InProgress
   outstanding referrals 0, parent count 0
  ld 0353A628 request count 1 (abandoned 0)
** ld 0353A628 Response Queue:
   Empty
  ld 0353A628 response count 0
ldap_chkResponseList ld 0353A628 msgid 2 all 1
ldap_chkResponseList returns ld 0353A628 NULL
ldap_int_select
read1msg: ld 0353A628 msgid 2 all 1
read1msg: ld 0353A628 msgid 2 message type search-result
read1msg: ld 0353A628 0 new referrals
read1msg:  mark request completed, ld 0353A628 msgid 2
request done: ld 0353A628 msgid 2
res_errno: 32, res_error: <>, res_matched: <>
ldap_free_request (origid 2, msgid 2)
ldap_parse_result
ldap_err2string

Warning: ldap_search(): Search: No such object in \vendor\adldap2\adldap2\src\Connections\Ldap.php on line 219

Warning: ldap_get_entries() expects parameter 2 to be resource, boolean given in \vendor\adldap2\adldap2\src\Connections\Ldap.php on line 113
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed
```

Thanks for any help!!

**Comment by Albvadi** [comment]
Ok, I think I found the problem...

My LDAP server is an old SUN ONE Server and the very first baseDN is "**o=**intranet..." instead of "**ou=**intranet...". The following dn are ou=, but the very first it´s o=.

And, when the constructor set basedn, first search exploding ou, dc and cn, but not o, so my basedn property it´s always empty.

@stevebauman, have you any idea to bypass this problem? Any workaround or something?? :disappointed_relieved: 

Thanks!

**Comment by stevebauman** [comment]
Added https://github.com/Adldap2/Adldap2/commit/4b3d60e0ef950f5d99dfe25d5c40376470495404

**Comment by Albvadi** [comment]
I have no words to thank you for your support implementing features only for my needs..
I am expectant for the new release to test it in my two projects, normal and laravel-based...

Thanks so so much!! :smiley:
