### ISSUE TITLE
Unable to find users

### ISSUE THREAD

**Issue by gdiazderadaa** [Adldap2/Adldap2#271]
Hi there,
I'm struggling retrieving the users from the LDAP. It's quite weird because doing a general search do yield results, among which I can see users info. Any clue what's going on?

This is the statement I used to see the info:
`Yii::$app->ldap->search()->all()`
However the following one returns empy:
`Yii::$app->ldap->users()->all();`

Thanks in advance!

**Comment by stevebauman** [comment]
Hi @gdiazderadaa,

Are you using OpenLDAP?

**Comment by gdiazderadaa** [comment]
Hi!
Yes, I'm using a local instance of LDAP.

**Comment by stevebauman** [comment]
Just to absolutely clarify, you're using OpenLDAP and **not** Active Directory?

**Comment by gdiazderadaa** [comment]
That's right

**Comment by gdiazderadaa** [comment]
Hi @stevebauman , you got any change to look into the issue? As a workaround I´m trying to use the array `original` of every element returned by `Yii::$app->ldap->search()->all()`, but though I can see it has indexes like 'uid', 'userpassword' etc I cannot access them

**Comment by stevebauman** [comment]
Hi @gdiazderadaa, apologies for the long response.

You should be able to loop through each user and retrieve the properties you need, for example:

```php
$users = Yii::$app->ldap->search()->all();

foreach ($users as $user) {
    echo $user->uid[0];
    
    // Or

    echo $user->getAttribute('uid', 0);
}
```
