### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Mylo-92** [Adldap2/Adldap2#272]
Good Day,

Firstly, thank you for the package :). I am planning on implementing it on a laravel based project housed in Windows Server 2012 R2 but prior to that I am trying to install the **adldap2/adldap2** package. But I seem to be running into this issue:

![screen shot 2016-06-02 at 2 36 17 am](https://cloud.githubusercontent.com/assets/7414783/15730223/04a1ae26-286b-11e6-8c39-8f9057695c33.png)

Is Laravel 5.1* LTS not supported? Or am I missing something else?

Regards,

**Comment by Albvadi** [comment]
Hi,
the package to implement in Laravel is [https://github.com/Adldap2/Adldap2-Laravel](Adldap2-Laravel) and you need add in composer.json ```"adldap2/adldap2-laravel": "2.0.*",``` instead of ```"adldap2/adldap2": "6.0.*"```

**Comment by Mylo-92** [comment]
Hi, thank for your response. Both ```"composer require adldap2/adldap2-laravel"``` and ```"composer require adldap2/adldap2"``` result in that error.

**Comment by Albvadi** [comment]
You don´t need the two commands, only the first. adldap2-laravel has a dependency of adldap2, so, it´s automatically download..

I have a clean installation of Laravel, i run ```compose require adldap2/adldap2-laravel``` and the result is:

```composer
Using version ^2.0 for adldap2/adldap2-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing adldap2/adldap2 (v6.0.17)
    Downloading: 100%

  - Installing adldap2/adldap2-laravel (v2.0.10)
    Downloading: 100%

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
```

**Comment by Albvadi** [comment]
You don´t need the two commands, only the first. adldap2-laravel has a dependency of adldap2, so, it´s automatically download..

I have a clean installation of Laravel, i run ```compose require adldap2/adldap2-laravel``` and the result is:

```composer
Using version ^2.0 for adldap2/adldap2-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing adldap2/adldap2 (v6.0.17)
    Downloading: 100%

  - Installing adldap2/adldap2-laravel (v2.0.10)
    Downloading: 100%

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
```

**Comment by Mylo-92** [comment]
I understand that,perhaps I worded it wrongly in the aim of conveying that I tried both. I'm assuming that is from a fresh install of Laravel v5.2.*?. Tried with a fresh install as well,I think it just doesn't work with v5.1.*

**Comment by Albvadi** [comment]
Ok, It´s a problem with versions... (I think)
Maybe @stevebauman have a correct or better solution....

- ```adldap2/adldap2-laravel``` requires ```adldap2/adldap2``` which in turn requires ```illuminate/support: ~5.2```

- ```laravel/laravel 5.1.*``` requires ```laravel/framework``` which ships with ```illuminate/support: ~5.1```, so the dependencies are not satisfying

Summarizing, you need use the 1.* branch of ```adldap2/adldap2-laravel```.
Use ```composer require adldap2/adldap2-laravel 1.*```

I tested in a fresh version of 5.1.36 LTS of Laravel and install correctly. Only tested the installation of the package,

**Comment by stevebauman** [comment]
Just fixed, thanks for the report! Please try updating again.

@Albvadi was correct about the versioning issue. It should now allow laravel versions >=5.0.
