### ISSUE TITLE
Doing another search after paginated search causes 'Critical extension is unavailable' Error

### ISSUE THREAD

**Issue by bakanyaka** [Adldap2/Adldap2#274]
Hello. While trying to do two consecutive searches where first search is paginated, I've encountered following error:
ldap_search(): Search: Critical extension is unavailable

Simplified version of my code:

       $provider = \Adldap::getDefaultProvider();
        $search = $provider->search()->users();
        $paginator = $search->paginate(5);//Force pagination for test purposes
        $paginator->getResults();//This works fine and returns results;
        $newsearch = $provider->search()->whereEquals('name', 'Some User Name')->get(); //This Causes Error

Is this a bug or am I doing something wrong?

PS: I'm using Laravel Adldap Facade here and Active Directory. Adldap2 version is 6.0. In version 5.2 I had almost same code and it worked fine.

**Comment by stevebauman** [comment]
Strange, I'm getting the same thing locally.

Going to investigate, thanks!

**Comment by stevebauman** [comment]
As a workaround for the time being, you can actually run the query **first**, then run the paginated query.

**Comment by bakanyaka** [comment]
Thanks for quick reply. Unfortunately I can't swap queries in my real world app because second query actually uses data returned from first query. (I'm doing another search based on secretary user's attribute to find secretaries). And I use pagination not for actual pagination but so I can get all results without 'Sizelimit exceeded' error.
So I hope you find what's causing the error, thanks.

**Comment by stevebauman** [comment]
Fixed, here's what was going on:

While resetting the control paged result by passing in `0` (zero) is supposed to work, it actually still prevents any further queries being ran during the same request.

We actually need to set it to a large number to run **any** further queries it seems. For example:

```php
ldap_control_paged_result($connection, 100, true, $cookie);

// Run the search
...

// What is supposed to work (reset)
ldap_control_paged_result($connection, 0, false, $cookie);

// What actually works
ldap_control_paged_result($connection, 1000, false, $cookie);
```

https://github.com/Adldap2/Adldap2/blob/6676bb0e975c5a2c439be163e374061ebcd19cf7/src/Query/Builder.php#L309
