### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'users'

### ISSUE THREAD

**Issue by kelvinrolex** [Adldap2/Adldap2#275]
Please anytime i want to get the group of a user with the following code

```php
if (Auth::attempt(['username' => $username, 'password' => $password)])) {
        return $users = Adldap::users()->all();
        $user = Auth::user();

        var_dump($user); // Returns instance of App\User;

        var_dump($user->adldapUser); // Returns instance of Adldap\Models\User;

        // Retrieving the authenticated LDAP users groups
        $groups = $user->adldapUser->getGroups();
        var_dump($groups);

    }
```

I get this error message 

call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'users'.

Please help.

**Comment by stevebauman** [comment]
You're calling non-existent methods.

The correct usage it:

```php
$users = Adldap::search()->users()->get();
```

Please refer to the following documentation:

https://github.com/Adldap2/Adldap2/blob/master/docs/query-builder.md#scopes

**Comment by kelvinrolex** [comment]
Sorry, i have made the corrections but i get this error message

ldap_search(): Partial search results returned: Sizelimit exceeded...

in Ldap.php line 219
at HandleExceptions->handleError('2', 'ldap_search(): Partial search results returned: Sizelimit exceeded', '/home/vagrant/Code/exeat.api/vendor/adldap2/adldap2/src/Connections/Ldap.php', '219', array('dn' => 'dc=elizadeuniversity,dc=edu,dc=ng', 'filter' => '(&(objectclass=\70\65\72\73\6f\6e)(objectcategory=\70\65\72\73\6f\6e))', 'fields' => array()))
at ldap_search(resource, 'dc=elizadeuniversity,dc=edu,dc=ng', '(&(objectclass=\70\65\72\73\6f\6e)(objectcategory=\70\65\72\73\6f\6e))', array()) in Ldap.php line 219
at Ldap->search('dc=elizadeuniversity,dc=edu,dc=ng', '(&(objectclass=\70\65\72\73\6f\6e)(objectcategory=\70\65\72\73\6f\6e))', array()) in Builder.php line 259


What is the issue here?

**Comment by stevebauman** [comment]
> ldap_search(): Partial search results returned: Sizelimit exceeded...

How many users do you have in your AD? It sounds like it's hitting a return limit.

Try paginating the results:

```php
$users = Adldap::search()->users()->paginate(10);
```

**Comment by kelvinrolex** [comment]
Ok thank, but pls is there any method of getting the Logged in User Group...or the real_primary_group?

**Comment by stevebauman** [comment]
Do you have the option `bind_user_to_model` enabled in your `config/adldap_auth.php` file?

Then you can retrieve the logged in users groups like so:

```php
$groups = Auth::user()->adldapUser->getGroups();
```

**Comment by kelvinrolex** [comment]
When I used this method 
$groups = Auth::user()->adldapUser->getGroups(); it was showing me all the users in the active directory not the logged in user.

**Comment by stevebauman** [comment]
> $groups = Auth::user()->adldapUser->getGroups(); it was showing me all the users in the active directory not the logged in user.

Are you sure? When the `getGroups()` method is called, it retrieves the distinguished names attached to the Adldap `User` instance, and the runs a `findByDn()` query on each distinguished name to retrieve the groups.

If you're still using the code you've shown above, you're returning all users before any other queries:

```php
// Your code
if (Auth::attempt(['username' => $username, 'password' => $password)])) {
    // You're returning all users here.
    return $users = Adldap::users()->all();
    $user = Auth::user();
    
    var_dump($user); // Returns instance of App\User;
    
    var_dump($user->adldapUser); // Returns instance of Adldap\Models\User;
    
    // Retrieving the authenticated LDAP users groups
    $groups = $user->adldapUser->getGroups();
    var_dump($groups);
}
```

**Comment by kelvinrolex** [comment]
Ok, thanks, but I will try it again and if it still returns all user I will let you know...

**Comment by kelvinrolex** [comment]
Good day stevebauman, I have been able to do it, but it doesn't show any group when I var_dump the $groups. bellow is my code

if (Auth::attempt(['username' => 'username', 'password' => 'password')])) {
        $user = Auth::user();

        //var_dump($user); // Returns instance of App\User;

        //var_dump($user->adldapUser); // Returns instance of Adldap\Models\User;

        // Retrieving the authenticated LDAP users groups
        $groups = $user->adldapUser->getGroups();

        var_dump($groups);
    }


RESULT:

/home/vagrant/Code/exeat.api/app/Http/routes.php:30:
object(Illuminate\Support\Collection)[213]
  protected 'items' => 
    array (size=1)
      0 => 
        object(Adldap\Models\Group)[205]
          public 'exists' => boolean true
          public 'dateFormat' => string 'Y-m-d H:i:s' (length=11)
          protected 'query' => 
            object(Adldap\Query\Builder)[209]
              ...
          protected 'schema' => 
            object(Adldap\Schemas\ActiveDirectory)[197]
              ...
          protected 'attributes' => 
            array (size=35)
              ...
          protected 'original' => 
            array (size=35)
              ...
          protected 'modifications' => 
            array (size=0)
              ...
          protected 'timestampFormat' => string 'YmdHis.0Z' (length=9)

**Comment by stevebauman** [comment]
By the looks of your result you posted, it's giving you one group result?

```php
object(Adldap\Models\Group)[205]
```

**Comment by kelvinrolex** [comment]
oh ok thanks

**Comment by kelvinrolex** [comment]
Thanks, I just found out that when i use return $groups instead of var_dump($groups), it works very well. Thanks once more...

**Comment by stevebauman** [comment]
No problem at all! If you have any further issues please let me know :).
