### ISSUE TITLE
Undefined Offset - Entry.php

### ISSUE THREAD

**Issue by KerchumA222** [Adldap2/Adldap2#28]
`for ($i = 0; $i <= $attributes[$key]['count']; $i++) {`
Should be:
`for ($i = 0; $i < $attributes[$key]['count']; $i++) {`

**Comment by stevebauman** [comment]
Yup, this is fixed in the current master:

https://github.com/Adldap2/Adldap2/blob/master/src/Objects/Ldap/Entry.php

Going to be releasing a `alpha.2` tonight.
