### ISSUE TITLE
getPrimaryGroup() does not work

### ISSUE THREAD

**Issue by theliass** [Adldap2/Adldap2#284]
Hi!
I need to get the Primary Group of a user, but it returns false everytime.
I did a bit of debugging and I found out a possible cause in method getPrimaryGroup() in User.php.

Primary Group SID is generated from user SID, but in a wrong way!

Example:
__User SID__: S-1-5-21-1234567890-123456789-1234567890-20222
__Prim. Grp SID__ (generated from user sid): S-1-5-21-1234567890-123456789-1234567890-2513
__Real Primary Group ID__: 513

I tried to modify class method like this:

```php
public function getPrimaryGroup()
{
    $sid = $this->getSid();

    $groupSid = explode("-", $sid);
    $groupSid[7] = $this->getPrimaryGroupId();
    $groupSid = implode("-", $groupSid);

    return $this->query->findBySid($groupSid);
}
```

After the modify, the Primary Group SID is now generated correctly, but it returns false anyway.
With LDAP browser using filter (objectSid=S-1-5-21-1234567890-123456789-1234567890-513) I get the group.

Am I doing something wrong?

Configurations:
```php
$config->setDomainControllers('10.20.30.40');
$config->setBaseDn('DC=contoso,DC=local');
$config->setAdminUsername('admin');
$config->setAdminPassword('password');
$config->setAccountSuffix('@contoso.local');
$config->setAdminAccountSuffix('@contoso.local');
$config->setFollowReferrals(true);
$config->setUseSSL(true);
```

**Comment by stevebauman** [comment]
Hi @theliass, no you're not doing anything wrong.

I've just fixed this https://github.com/Adldap2/Adldap2/commit/ddbd2249f3a5fbfd59e134c59c6fdbbe6d3191ad, thanks for the report!

Can you update using `dev-master` in your `composer.json` configuration and let me know if you still experience the same issue?

**Comment by theliass** [comment]
It works!

Thank you very much!

**Comment by stevebauman** [comment]
Great! No problem at all :)

New release will be out shortly. Thanks!
