### ISSUE TITLE
Attribute name problem in setAttribute

### ISSUE THREAD

**Issue by theliass** [Adldap2/Adldap2#287]
Hi!
I found out a minor bug, but that can waste a lot of time.

Using this code (kept as simple as possible):

```php
$record = $this->_provider->search()->findByOrFail('samaccountname', $username);
$record->setAttribute("givenName", "Kate");
$record->save();
```

I kept getting **PHP Warning:  ldap_modify_batch(): Batch Modify: Type or value exists** and user was not saved.

After some time of trial and error I found out that the problem was the uppercase 'N' in 'givenName' attribute name. When I put it all lowercase everything started working correctly.

A possible easy solution can be the normalization of the attribute name is setAttribute method.

Thanks for the awesome work!
Keep it up! :+1:

**Comment by stevebauman** [comment]
Hi @theliass, thanks for the report!

Just fixed, appreciate you using Adldap2 :).
