### ISSUE TITLE
GitHub Packagist Hook

### ISSUE THREAD

**Issue by trinet-at** [Adldap2/Adldap2#29]
When I wanted to submit a PR, I forked the repo and realized that the cloned master branch differs from "dev-master" from Packagist (via Composer).

Could you ensure that your GitHub Packagist hook is working correctly?

Thanks!

**Comment by stevebauman** [comment]
Hmm I just checked and didn't see any issues, though I force updated it.

Ill reapply the packagist service in the settings. Ill close this for now but definitely comment back if there's still an issue, thanks!
