### ISSUE TITLE
Remove pwdLastSet from Contact creation

### ISSUE THREAD

**Issue by biwerr** [Adldap2/Adldap2#291]
Contact Class has no pwdLastSet attribute, please remove

**AdldapContact.php**
```
// ldapSchema function returns wrong array with pwdLastSet 
$add = $this->adldap->ldapSchema($attributes);
```

**Comment by biwerr** [comment]
sorry, issue is from old version

**Comment by stevebauman** [comment]
No problem! If you experience any issues with 6.*, don't hesitate to contact me :).
