### ISSUE TITLE
I cannot retrieve my groups

### ISSUE THREAD

**Issue by dudz94** [Adldap2/Adldap2#296]
Hi,

First, thanks a lot for this tools.
I’m using it since 1 week and I can find almost everything I want with.

I have a question about it. I’m using it with php without framework and I would like to retrieve all groups of my AD in one array:
I tried to use:
$search = $provider->search();
$results = $search->groups()->get();

but the result is too verbose and I can’t retrieve only the groups names.

Could you help me to resolve this issue ?

**Comment by stevebauman** [comment]
Hi @dudz94,

When you perform a query with `->get()`, you'll receive a `Illuminate\Support\Collection` object.

Collections are glorified arrays that add lots of extra, useful functionality. Here are the collection methods you can use:

https://laravel.com/docs/5.2/collections#available-methods

This is how you would retrieve all of your groups names:

```php
$results = $search->groups()->get();

$names = [];

foreach($results as $groups) {
    $names[] = $groups->getCommonName();
}
```
