### ISSUE TITLE
Multi-value field order isn't preserved

### ISSUE THREAD

**Issue by biwerr** [Adldap2/Adldap2#298]
If you have multivalue fields like `otherTelephone` the `originalIsNumericallyEquivalent` function doesnt work properly.

Im writing the following values to our AD
```
array (
  0 => '+49 6503 917338',
  1 => '+49 000000',
)
```
If i query the object the recieved values look like this

```
array (
  0 => '+49 000000',
  1 => '+49 6503 917338',
)
```

Maybe we should reverse multivalue fields when model is filled by query.

**Comment by biwerr** [comment]
according to ms [documentation](https://technet.microsoft.com/en-us/library/ee156515.aspx) , multivalued fields have no specific ordering. We should use array_diff for multivalued fields.

**Comment by stevebauman** [comment]
Hi @biwerr, that's correct, unfortunately we can't preserve the order of multi-valued attributes.

Why should we use array_diff? For what would we use the method on? Retrieving and setting attributes?

Can you provide an example?

**Comment by biwerr** [comment]
This method is used in `AbstractModel::update()`. In my case for example a user could change the order of his  phone numbers in an edit form. The model `update()` method will try to update the array fields because the `getDirty()` method marks the array as dirty. 

The ldap update will end in an error because the value already exists. 
```
ErrorException in Ldap.php line 299:
ldap_modify_batch(): Batch Modify: Type or value exists
```

**Comment by stevebauman** [comment]
Can you require `dev-master` and try the most recent commit please?

https://github.com/Adldap2/Adldap2/commit/479cc5c0385a0fd968ab0c6f9c1a3bbf35af294a

**Comment by biwerr** [comment]
My error is fixed with this commit. Issue can be closed. Thanks.

**Comment by jrohde** [comment]
Hi all, 

Just playing around with Adldap2 (great stuff!), but encountered a problem regarding this 'fix'.
I'm afraid this solution is not complete. 

From the array_diff manual: _"Returns an array containing all the entries from array1 that are not present in any of the other arrays."_

E.g

```
$cur = [1,2,3];
$new = [1];
var_dump(array_diff($cur, $new));
// output: [2,3]
```

No problem here; it's marked 'dirty' and life goes on.
But let's check the following situation:

```
$cur = [1];
$new = [1,2,3];
var_dump(array_diff($cur, $new));
//output: []
```

Nothing dirty anymore!!

I think a simple solution to satisfy all is to use just a simple === comparisson. E.g.:
```
protected function originalIsNumericallyEquivalent($key)
{
        $current = $this->attributes[$key];

        $original = $this->original[$key];

        echo "<br>";
        var_dump($current == $original);
        echo "<br><hr>";

        return  is_numeric($current) &&
                is_numeric($original) &&
                strcmp((string) $current, (string) $original) === 0 ||
                $current === $original;
}
```
Or (better?) just leave the whole array check out of this function, because it's not really a 'numeric' equivalent check in the first place i guess. So in the getDirty() function do something like:

```
public function getDirty()
{
        $dirty = [];

        foreach ($this->attributes as $key => $value) {
            if (!array_key_exists($key, $this->original)) {
                $dirty[$key] = $value;
           } elseif ($value !== $this->original[$key]
                && (is_array($value) || !$this->originalIsNumericallyEquivalent($key))) {
                    $dirty[$key] = $value;
            }
        }
        return $dirty;
}
```

Cheers

**Comment by stevebauman** [comment]
Hi @jrohde, I think this slipped past me in my email, this was recently brought up in issue #466.

I've modified the method and have created tests for the dirty method as well.

A new release will be out shortly with this fix, thanks again!
