### ISSUE TITLE
Just check user authentication without admin account

### ISSUE THREAD

**Issue by Phisherman** [Adldap2/Adldap2#307]
Is it possible to check if an user can authenticate without the need of an admin account? If I use the user credentials as admin account and the credentials are incorrect it throws an binding exception. With this approach I can't distinguish between an server binding error and an authentication error.

**Comment by stevebauman** [comment]
Hi @Phisherman,

Apologies for the long response.

You can check by calling the `auth()->attempt()` method on your Provider instance **and pass in true into the last parameter:**

```php
if ($provider->auth()->attempt($username, $password, $bindAsUser = true)) {
    // Passed!
}
```

Setting the `$bindAsUser` parameter to true, bypassed re-binding as your configured administrator.

**Comment by Phisherman** [comment]
Thanks!
