### ISSUE TITLE
Add groups before save user?

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#308]
Hi,
It´s possible work with groups before save the user??

I´m importing users from LDAP and my idea is:
* Read the user from LDAP
* Create user Model for AD
* Fill all attributes
* Add groups
* Save all user data in one step.

But, before save user, I dump the user and no data group related... `$user->getGroupNames();` it´s null.
For the conversion between role and group, I have and array and the code is:
```php
foreach ($user->nsroledn as $role) {
	foreach ($_arrRoleEq as $eqRolLDAP => $eqGrupoDA) {
		if (stripos($role, $eqRolLDAP) != false){
			$group = $this->provider->search()->groups()->findBy('cn', $eqGrupoDA);
			$this->getNewUser()->addGroup($group);
		}
	}
}
```
Is it mandatory save the user before add groups?

Thanks!

**Comment by stevebauman** [comment]
Hi @Albvadi, the user needs to exist in LDAP before you can attach any groups to it. This is because you're actually adding the user to the group, and not vice versa, so the user your adding to the group needs to contain a valid and existing distinguished name.

Otherwise you'll receive an exception:

```php
ldap_modify_batch(): Batch Modify: Server is unwilling to perform
```

**Comment by Albvadi** [comment]
Well, I have to change my script... because the form of working of AD...

Thanks as always for your answers :)

**Comment by stevebauman** [comment]
No problem! Definitely create another issue if you have any further questions, thanks :)
