### ISSUE TITLE
Resync issue with groups after save user

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#311]
Hi again...
More questions about groups and sync. Related with #308 
Is it mandatory refresh the search after addGroup to User and save it??.

For example:
```php
$group = $provider->search()->groups()->find('TEST-GROUP');
$user = $provider->make()->user();
$user->setDn('CN=TEST USER,OU=Labs,DC=company,DC=net');
$user->setAttribute('samaccountname', 'test.user');

// At this point: $user->countAttributes() = 3

if ($user->save()) {
    // At this point: $user->countAttributes() = 51
    // It refresh all attr from DA after create and now, exists = true. All correct

    $user->addGroup($group);
    $user->save();

    // At this point: $user->countAttributes() = 51 yet
} 

$user->getGroups(); // <-- It´s NULL!!

$user = $provider->search()->users()->findBy('samaccountname', 'test.user');

// At this point: $user->countAttributes() = 53

$user->getGroups(); // <-- It´s the Adldap\Models\Group (TEST-GROUP)
```

**Comment by Albvadi** [comment]
Well, reviewing all the Users methods, I saw in save() if user don´t exists, you call `syncRaw()` and if the user exists, you call `syncOriginal` to get the same attributes.

So, for my question, I think I simply can change `$user = $provider->search()->users()->findBy('samaccountname', 'test.user');` for `$user->syncRaw();`

I understand how it works and makes sense, because if I use search->select(), and update a user, it´s normal get the same original attributes and not all of the server... But, in this case, the normal will be get all attributes, because the first sync get all...

Sooo, I don´t know really if it´s really a issue and in this case, if it´s difficult to control...

**Comment by stevebauman** [comment]
Hi @Albvadi,

> Well, reviewing all the Users methods, I saw in save() if user don´t exists, you call syncRaw() and if the user exists, you call syncOriginal to get the same attributes.

The users attributes are sync'ed on `create()` or `update()`:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Model.php#L683

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Model.php#L637

When a record is updated or created, it's re-queried and the returned models attributes are set on your current model instance.

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Model.php#L270

The thing is, I think it's possible that the changes aren't **immediately** made on your LDAP server. They may take a couple milliseconds, and if you're looking for a change that was just made, it may not appear during the same PHP request (which may only be a couple micro/milliseconds long).

At least this is how I've experienced this. When I make a change to an entry, the changes are only visible **on the next PHP request**. I'm going to see if this is a bug though.

Thanks for the report!

**Comment by stevebauman** [comment]
If you call `syncRaw()` manually in the same request when adding a user to a group, do you receive the group when you call `$user->getGroups()`?

**Comment by Albvadi** [comment]
Yep.

I tested it after my last comment, changing the search for the syncRaw(),
and with this change, I get the groups correctly.

Until monday I can't view the code, and I did a lot of tests, but I'm
almost 100% sure...

**Comment by stevebauman** [comment]
Ok, I made a change https://github.com/Adldap2/Adldap2/commit/5af6ff918f8d03a614c451df2d0710203ac19871, please try `dev-master` and let me know if it works, thanks!

**Comment by Albvadi** [comment]
Hi,
I tried dev-master and work as expected, I get the groups immediately after addGroup to the user..

But, I tested what I said in the penultimate comment. If I use select(), It´s ignored after add group.
Example:
```php
$cols = ['cn', 'samaccountname', 'mail'];
$group = $provider->search()->groups()->find('TEST-GROUP');

$user = $provider->search()->users()->select($cols)->findBy('samaccountname', 'test.user');

//At this point, $user only has 6 attrs,

$user->addGroup($group);

//At this point, $user has the full list of attr, 53, and select() it´s ignored
```
For me, it´s not a problem, because a full query with all the attributes in my system it´s almost inmediately. But, maybe, this can cause problems for other people...

It´s very difficult find a good way to solve this, so perhaps, the best solution is to leave it as is. I can call syncRaw() for my neededs and it´s not affected to other people..

It´s your decision.

Thanks so much!

**Comment by stevebauman** [comment]
> But, I tested what I said in the penultimate comment. If I use select(), It´s ignored after add group.

Shoot, you're right. Like you said, it may be best to leave this in so developers can control how much they query. / when and call `syncRaw()` when needed manually.

This could cause other issues as well, since modifying a model and then calling `addGroup()` would re-sync every original attribute clearing the models modification.

I'm going to revert this commit, but this is definitely something I'm going to keep an eye on.

Thanks again! :)

https://github.com/Adldap2/Adldap2/commit/19c7846c6bab1339b6bb262bbbf30eb92b4cf014
