### ISSUE TITLE
Issues moving users

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#314]
Hi again,
Sorry for be so annoying, but I have troubles with my script...

Now, it´s the turn of move a user.
When I move a user, the process it´s Ok, but the user itsn´t sync from the server.

Example:
```php
$user = $provider->search()->users()->findBy('samaccountname', 'test.user');
$group = $provider->search()->groups()->find('Test-Group');

$oldDn = $user->dn; // cn=Test User, OU=group1,OU=area1,DC=foo,DC=bar

$rDn = $user->getDnBuilder()->assembleCns();
$newParentDn = 'OU=group2,OU=area2,DC=foo,DC=bar';

$user->move($rdn, $newParentDn); // return true. The user was moved correctly.

$user->dn; // return OLD dn

$user->addGroup($group) or $user->syncRaw() // return ERRORS

// WORKAROUND
$user = $provider->search()->users()->findBy('samaccountname', 'test.user');
$user->dn; // return NEW dn
```
I think `addGroup()` and `syncRaw()` fails because do a search with the actual DN in the user model, and the actual DN is the old DN, that not exists yet...

**Comment by stevebauman** [comment]
Hi @Albvadi, no problem. I really appreciate any and all feedback on issues and concerns.

On this line here:

```php
$user->addGroup($group) or $user->syncRaw() // return ERRORS
````

What errors are returned on both methods?

**Comment by stevebauman** [comment]
I see what you're saying.

The `syncRaw()` method won't actually re-sync the correct models attributes because it tries to re-locate the model by it's distinguished name, which is incorrect after a successful move. Since no model will be found, the new distinguished name isn't applied.

Going to see what I can do!

**Comment by stevebauman** [comment]
Hi @Albvadi, this is fixed in the latest commit. A new update will be out shortly.

Thanks for the report!
