### ISSUE TITLE
Exchange Mailbox

### ISSUE THREAD

**Issue by X3nz** [Adldap2/Adldap2#315]
Hello, was wondering if there are plans to implement exchange mailbox creation?

**Comment by stevebauman** [comment]
Hi @X3nz,

Right now there's no `make()` method for creating an exchange mailbox, but I have just implemented a way of creating a new LDAP record easily: https://github.com/Adldap2/Adldap2/commit/f6e1362f131ce6a1fb46eb1a17c19791c84db14c

```php
$entry = $provider->make()->entry($attributes);

$entry->save();
```

I've personally never created an exchange mailbox through LDAP for user accounts. I'd be glad to accept PR's on this though.
