### ISSUE TITLE
Add recursive option to getGroupNames()

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2#316]
Referenced by @curry684 in #192, add `$recursive` option to the `getGroupNames()` method.

**Comment by curry684** [comment]
Cheers, thanks for the swift response and the great library, happily using it in our newest project  😄  if I wasn't so busy on the project I'd add a PR myself hehe.

**Comment by stevebauman** [comment]
@curry684 No problem! Glad you enjoy using it :).
