### ISSUE TITLE
Add getAccountName() on User model

### ISSUE THREAD

**Issue by NullIsNot0** [Adldap2/Adldap2#318]
It would be nice to have function on User model to get LDAP's "sAMAccountName" value:

```php
public function getAccountName()
{
    return $this->getAttribute($this->schema->accountName(), 0);
}
```
And set function accordingly.

Using v6.

**Comment by stevebauman** [comment]
Hi @NullIsNot0,

This method already exists on the `Entry` model, which the `User` model extends from:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Entry.php#L52

**Comment by NullIsNot0** [comment]
I did not notice that it already exists. Thank you for pointing to Entry model!
