### ISSUE TITLE
Create user from another

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#319]
Hi,
I'm back again to request a little help...

In my LDAP system, move users it´s disabled, so, when a user change the DN, it´s mandatory create a user in the new tree and delete the old dn. So in my script to sync users from AD to LDAP, when detect a change in dn in AD, the script must delete the user and re-create in the new dn.

I saw in #315 you had implemented a method to create a new entry with and array of attributes, but, in my idea, don´t works well.
Example:
```php
$oldUser = $provider->search()->users()->findBy('uid', 'test.user');
$oldDn = $oldUser->getDistinguishedName();

$newDn = 'uid=test.user,ou=company,dc=foo,dc=bar';
$newUser = $provider->make()->entry($oldUser->getAttributes());
$newUser->setDn($newDn);
```
The user it´s created, but the attributes don´t fill correctly. I tried with `getAttributes()` and `getOriginal()` but same result. 

My idea it´s setup the user with this method, save the new user, and delete the old.

Any help??
Thanks!

**Comment by stevebauman** [comment]
Hi @Albvadi, what do you mean by `the attributes don´t fill correctly`? Can you post an example?

**Comment by Albvadi** [comment]
Hi,
sorry for don´t explain well... I don´t post the last example correctly.

In the last example, works well. The new user have the attributes correct.
The problem it´s if the old user has select in the query.

Example:
```php
$select = array('businesscategory', 'cn', 'l', 'mail', 'uid', 'userpassword');

$oldUser = $provider->search()->users()->select($select)->findBy('uid', 'test.user');
$newUser = $provider->make()->entry($oldUser->getAttributes());

d($oldUser->getAttributes());
d($newUser->getAttributes());
```
The results are:
![atributos](https://cloud.githubusercontent.com/assets/6285255/18003522/5d602e00-6b8e-11e6-968b-6db53a237ece.png)

Besides, in the `$newUser`, original array and function `getOriginal()` it´s empty.

Thanks!

**Comment by stevebauman** [comment]
> The problem it´s if the old user has select in the query.

If you're only selecting certain attributes on a query, you'll only get those attributes calling the `getAttributes()` method on the returned model instances.

> Besides, in the $newUser, original array and function getOriginal() it´s empty.

This is intended, for the new user, since it doesn't exist yet, it contains no original attributes. Original attributes are set when the attribute actually exists in LDAP.

**Comment by Albvadi** [comment]
I see different output in the attr from new user and old user... It's
correct anyway?
If I don't use select, the two output with kint are exact same.

I'm on holidays and can't get the code to try, so if you think all it's
correct, simply close the issue...

Thanks!

**Comment by stevebauman** [comment]
> I see different output in the attr from new user and old user... It's
correct anyway?

I'm not sure what you mean? It looks as though you're receiving the same attributes from the old and new user in your attached image.

Also, no problem, I'll leave this open for whenever you have time to test this on your end (it works fine on my end).

**Comment by Albvadi** [comment]
Hi,
with the different output, I mean that in the new attributes, Kint not detect arrays sames and the old user (with the purple cell in objectclass for example) and that made me think the new user was created different than old user.

But I tried `->getAttribute('mail', 0)` or `->getCommonName()` in both users and all works well.
So, sorry for losing your time, You can close this issue.

Thanks so much!

**Comment by stevebauman** [comment]
No problem @Albvadi, thanks!
