### ISSUE TITLE
Configuration method problems

### ISSUE THREAD

**Issue by KerchumA222** [Adldap2/Adldap2#32]
setSSL and setTLS accept boolean values but cannot both be set to false explicity.

This may not seem like something that normally happens since false is the default value but in my case I am retrieving user configured values with my own defaults. setSSL(false) and setTLS(false) should always set them to false.

**Comment by stevebauman** [comment]
Fixed this in: https://github.com/Adldap2/Adldap2/commit/965b50619b208d179abfd3ded798058e15142025
