### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by mvatansever** [Adldap2/Adldap2#323]
Hi,

I want to reset user's password. I do this with two function:

I use setPassword() function of Model\User class for this operation. After this function want to use save() function of User object to save changes. I think may be exist a function for reset password to save object and will catch the PasswordPolicyException. Because this function not catch any exception.

I choose different way to reset password I think changePassword() function maybe more secure than setPassword(). Next, I use changePassword() function of Model\User class for this operation. But 2 way exists for use to this function. First way if you are change password with old password. This way is not for me because **If I want to reset password than I don't know what is old password!** For this reason I choose another way. It's set true to last parameter -replaceNotRemove- . So this way didn't think for reset password operation than not catch **PasswordPolicyException**. When update() function throw exception than it's not catch. **This means update() function does not return false** and code breaking at this line. So does not handle error exceptions.

I look at test of Model\User class but I don't see to use changePassword() with last parameter. When I create a test function for changePassword() function to use with last parameter. Here is my test function:

    public function test_change_password_policy_replace_not_remove()
    {
        $connection = $this->newConnectionMock();

        $connection->shouldReceive('isUsingSSL')->once()->andReturn(false);
        $connection->shouldReceive('isUsingTLS')->once()->andReturn(false);

        $user = new User([], $this->newBuilder($connection));

        $this->setExpectedException('Adldap\Exceptions\PasswordPolicyException');

        $user->changePassword("", "", true);
    }

And this test is failure!

**For now I use changePassword() function between try-catch block and catch \Exception at my project to handle this error. But it's not true way.**

I think many different way to resolve this problem. If you are accept this error?

**Comment by stevebauman** [comment]
Hi @mvatansever, apologies for the long response.

I'm having difficulty understanding your issue. I'm assuming English isn't your first language, and that's okay.

It sounds like you're trying to change an existing users password without needing to know their password but you receive an exception? I'm not sure.

Please clarify and I can help you further.

**Comment by mvatansever** [comment]
Yes exactly! This is my problem. 
Exists functions don't do it.

**Comment by stevebauman** [comment]
What exception do you receive when you call the `setPassword()` method? Are you also using SSL / TLS to connect to your server?

**Comment by mvatansever** [comment]
`setPassword()` function not handle any exception without SSL/TLS connection. But my problem is password policy and this exception does not handle by the function. 

For this reason I choose `changePassword()` function to use. This function execute `update()` function when the process throw an exception without try-catch block so after this line does not execute. Want to catch and handle this exception where used `changePassword()` function. Like this:

	try {
	    return $user->changePassword("", $this->password, true);
	} catch (\Exception $ex) {

		$ldapConnection = $ldapUser->getQuery()->getConnection();
        $errorCode = $ldapConnection->getExtendedErrorCode();
        if ($errorCode == '0000052D') {
            throw new PasswordPolicyException();
        }
    }

May be develop `changePassword()` function or adding a `resetPassword()` function.

**Plus**:
A new scenario want to add for changePassword() which I send to first post.

**Comment by mvatansever** [comment]
Hello again,

I research dozens of times why didn't catch specific exceptions from my project. I found this is not a bug of Adldap2 package at last. I used the package from my Laravel project without your "Adldap2 for Laravel" package. Though, I didn't tested your Laravel package how to work with this function. So Laravel automatically catch any exceptions and does not continue codes execution from this section (Adldap\Models\User line 846):

        // Update the user.
        $result = $this->update();

You may see from this [link](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php) how to use Laravel framework's set handler function. Laravel maybe doing this right way so it's catch all of exception if it does not cover with try-catch blocks.

It seems bug of PHP Ldap extension. Because `ldap_modify_batch()` function does not throw any exception only return true/false value. 

I hope you understood me with my bad english :) 

Lastly, this issue must be "close".

Thanks.
