### ISSUE TITLE
Add sort and array_unique on getGroupNames function

### ISSUE THREAD

**Issue by barbuslex** [Adldap2/Adldap2#325]
Hi,

It would be userfull to add sort and unique value on getGroupNames function because when i use recursive parameter i have many duplicate groups in the result array.

Exemple : (in Laravel)
```
$user = Auth::user();
$groups = $user->adldapUser->getGroupNames(true);
sort($groups);
var_dump(array_unique($groups));
```

If sort and array_unique function are integrated in getGroupNames function this would refer a cleaner result and would prevent us from making unwanted tricks.

I hope that this enhancement will be retained.

Thanks in advance

++

**Comment by stevebauman** [comment]
Added, thanks for the suggestion!
