### ISSUE TITLE
DistinguishedName Object is not converted to string on ldap_search

### ISSUE THREAD

**Issue by biwerr** [Adldap2/Adldap2#327]
If i use a DN Object to set the Query BaseDN, the implicit conversion to string is not working. The Query returns `ldap_search(): Search: No such object`

**Fails:**
`$object = $adConnection->search()->contacts()->setDn($dn)->get();`

**Works:**
`$object = $adConnection->search()->contacts()->setDn($dn->__toString())->get();`

Maybe we should convert the DistinguishedName Object excplcit in the query builder when performing a query

**Comment by stevebauman** [comment]
Hi @biwerr, thanks strange.

The `setDn()` method already does this:

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L262

Are you on an older version by chance?

I'll run through some tests and see if I experience the same issue.

**Comment by biwerr** [comment]
Fixed in 6.1. I'm using 6.0.* with adldap for laravel
