### ISSUE TITLE
No results from Query builder limited to users

### ISSUE THREAD

**Issue by geodeveloper** [Adldap2/Adldap2#329]
Hi,
I was testing with a server that the users didn't have an objectCategory field and I didn't get any results until I removed from where method the `objectCategory`. Line `156` on `vendor/adldap2/adldap2/src/Search/Factory.php`:

![image](http://i.imgur.com/SvA1FGV.png)

```
    public function users()
    {
        return $this->where([
            $this->schema->objectClass()    => $this->schema->objectClassPerson(),
          //  $this->schema->objectCategory() => $this->schema->objectCategoryPerson(),
        ]);
    }
```
Is there a way to override this ?

Thank you.

**Comment by stevebauman** [comment]
Hi @geodeveloper,

You can override this by creating your own custom `Schema` object that either inherits or extends an already existing schema:

Please have a look at the docs:

https://github.com/Adldap2/Adldap2/blob/master/docs/schema.md

You could also create your own provider, extend the existing provider, and override the `search()` method and return your own `SearchFactory` instance which overrides the `users()` method.

**Comment by geodeveloper** [comment]
Thanks for your reply! Ok, then I will need extend the existing provider.
