### ISSUE TITLE
Adldap2 and Laravel 4.2

### ISSUE THREAD

**Issue by rpwang** [Adldap2/Adldap2#331]
Hi,

Is there a version of adldap2 that works with Laravel 4.2? I saw that adldap 4.04 is not maintained anymore.

Cheers,
Rui

**Comment by stevebauman** [comment]
Hi @rpwang,

Unfortunately there is no Adldap2-Laravel version that is compatible with Laravel 4.2.

Though you are free to utilize the newest version of the root Adldap2 repository with any version of Laravel.
