### ISSUE TITLE
getGroupNames() results in an error

### ISSUE THREAD

**Issue by tcharlye** [Adldap2/Adldap2#334]
The following error occurs on `$user->getGroupNames()` when User has Entry (not Group instance) at `memberof` attribute:

```
Argument 1 passed to Adldap\Models\User::Adldap\Models\Traits\{closure}() must be an instance of Adldap\Models\Group, instance of Adldap\Models\Entry given (/Users/charles/Sites/jumper/vendor/adldap2/adldap2/src/Models/Traits/HasMemberOfTrait.php:103)
```

`memberof` content:

```
cn=jumper,cn=groups,cn=accounts,dc=mydomain,dc=com,dc=br
ipaUniqueID=523ed3ga-5a3d-22c4-e46a-g8f95a62e735,cn=hbac,dc=mydomain,dc=com,dc=br
cn=wiki,cn=groups,cn=accounts,dc=mydomain,dc=com,dc=br
```

Using workaround:

``` php
    /**
     * @param \Illuminate\Support\Collection $collection
     * @return array
     */
    public function getGroupNamesFromMemberOf(\Illuminate\Support\Collection $collection)
    {
        $groups = [];

        foreach ($collection as $item) {
            if ($item instanceof \Adldap\Models\Group) {
                $groups[] = $item->getCommonName();
            }
        }

        return $groups;
    }
```

**Comment by stevebauman** [comment]
Actually, can you confirm a couple things?

Are you using Active Directory or another provider?

Because all memberof attributes should be Group instances when searched. Or can the memberof attribute contain non-group resources?

**Comment by tcharlye** [comment]
@alanwillms can answer us that

**Comment by martimarkov** [comment]
#350 Should fix this exact issue, I was having it today. With me it was OpenLDAP server.

**Comment by tcharlye** [comment]
Actually I'm using FreeIPA server.

This memberof item is a group for ssh access (HBAC), which is not being recognized as a Group instance:

```
ipaUniqueID=523ed3ga-5a3d-22c4-e46a-g8f95a62e735,cn=hbac,dc=mydomain,dc=com,dc=br
```

**Comment by stevebauman** [comment]
@tcharlye, do you know the `objectclass` of this group?

**Comment by tcharlye** [comment]
@stevebauman 

```
[objectclass] => Array
    (
        [0] => ipaassociation
        [1] => ipahbacrule
    )
```

**Comment by martimarkov** [comment]
@stevebauman I think that part needs to be rewritten to support more than one different type for groups. FreeIPA defines 3 different `objectclass` values for group:

```POSIX group is a group with object class posixGroup
external group is a group with object class ipaExternalGroup
non-POSIX group is a group which is not posix nor external: it doesn't have posixGroup nor ipaExternalGroup object class.
```

I think its fair if we support posixGroup and ipaExternalGroup

http://www.freeipa.org/page/V3/Filtering_groups_by_type

**Comment by martimarkov** [comment]
@tcharlye I think that object is ACL rather than a group?

**Comment by tcharlye** [comment]
Don't know. I'll check

**Comment by martimarkov** [comment]
@tcharlye was it an ACL or group?

**Comment by tcharlye** [comment]
@martimarkov ACL

**Comment by stevebauman** [comment]
Since this object was an ACL and not a Group, I'll assume there isn't an issue here?

I'll close this for now, but please comment back if you're still encountering any problems.
