### ISSUE TITLE
Exchange 2003 Support in v6.1.*

### ISSUE THREAD

**Issue by Hy3n4** [Adldap2/Adldap2#336]
Hi,

I am testing your library from yesterday and I stumbled on some pages in earlier version that described support of exchange 2003 accounts and its operations.

I that support implemented in v6 of Adldap2? Currently I am using v6.1.9 installed from composer.

I tried to follow documentation from what i found [link](https://github.com/Adldap2/Adldap2/blob/master/docs/query-builder.md#scopes), but there is no function **$provider->search()->exchangeServers()** 

Am I missing something?

EDIT:

Well, right now I am successfully creating, editing and deleting Exchange 2003 Mailboxes (2003? Yes, just don't ask.).

Still there is a lot of question but i feel that all of them could be answered at once.

Could I search for AD object in Configuration namespace? What I'm trying to achieve is to get all Exchange Servers, Storage Groups and Mailbox Databases from AD. But i am stuck and don't know if that is even possible?

BTW: thank you for your amazing work.

Thanks
Patrik

**Comment by stevebauman** [comment]
Hi @Hy3n4,

Thanks for pointing that out in the docs! Direct exchange support was removed but you can still easily query for exchange servers:

```php
$mailboxes = $provider->search()->where('objectcategory', '=' ,'ms-exch-exchange-server')->get();
```

Then, you can query for mailbox information by setting the search DN to the mailboxes DN:

```php
$mailbox = $provider->search()->where('objectcategory', '=' ,'ms-exch-exchange-server')->first();

$storageDatabases = $provider->search()->setDn($mailbox->getDn())->where('objectcategory', '=' , 'msexchprivatemdb')->get();

$storageGroups= $provider->search()->setDn($mailbox->getDn())->where('objectcategory', '=' , 'msExchStorageGroup')->get();
```

**Comment by Hy3n4** [comment]
Hi Steve,

That would be awesome, but I tried that already. It seems like search() alone does not have method where(). I am forced to specify user(), computer(), etc.

I have provider configured like this:

$config = [
        'account_suffix'        => '@' . $_SESSION['suffix'],
        'domain_controllers'    => [$_SESSION['ldap_server']],
        'base_dn'               => $_SESSION['base_dn'],
        'admin_username'        => $_SESSION['user_name'],
        'admin_password'        => $_SESSION['user_password'],
        'use_ssl'               => true,
        'use_tls'               => false
    ];
$ad = new \Adldap\Adldap();
$provider = new \Adldap\Connections\Provider($config);
$ad->addProvider('default', $provider);

Did I do something wrong in provider setup?

Thanks for support

**Comment by stevebauman** [comment]
>That would be awesome, but I tried that already. It seems like search() alone does not have method where(). I am forced to specify user(), computer(), etc.

Any methods called upon the search factory are automatically called upon a new query:

https://github.com/Adldap2/Adldap2/blob/master/src/Search/Factory.php#L270

So you can dynamically call all methods on the search so it's entirely chainable:

```php
$provider->search()->whereHas('mail')->whereEquals('cn', 'John Doe')->get();
```

**Comment by Hy3n4** [comment]
So I have must have something misconfigured, because if I try to search for object category it result in an empty array. My base DN is set at root domain DC=lab01,DC=expg,DC=net. So if I'm right it should search in Configuration scope and it should give me desired results. Right?

**Comment by stevebauman** [comment]
Yes you might need to set the dn of the exchange server search to your configuration naming context DN:

```php
$context = $provider->search()->getConfigurationNamingContext();

$mailboxes = $provider->search()->setDn($context)->where('objectcategory', '=', 'ms-exch-exchange-server')->get();
```
