### ISSUE TITLE
Help understanding config parameters for authentication

### ISSUE THREAD

**Issue by utugs** [Adldap2/Adldap2#337]
After some trial and error, I can both bind and authenticate to our LDAP server using an admin username/password and and and end user's username/passwrod. However, my understating of how the `admin_account_suffix` and `account_suffix` configuration parameters work does not seem to be accurate or, perhaps, our LDAP server's connection strings don't match up with Adldap2's default configuration options.

Here's the current configuration that allows for a successful bind and authentication:

```php
$ad = new \Adldap\Adldap();

$config = [
  'domain_controllers'    => ['domain.controller.edu'],
  'base_dn'               => 'dc=entdir,dc=xxxxx,dc=edu',

  'admin_username'        => 'uid=ADMIN_USERNAME,ou=services,dc=entdir,dc=xxxxx,dc=edu',
  'admin_password'        => 'ADMIN_PASSWORD',

  'account_prefix'        => 'uid=',
  // 'account_suffix'        => 'ou=people,dc=entdir,dc=xxxxx,dc=edu',
  // 'admin_account_suffix'  => 'ou=services,dc=entdir,dc=xxxxx,dc=edu',

  'use_ssl'               => true,
  'port'                  => 636

];

$provider = new \Adldap\Connections\Provider($config);

$ad->addProvider('default', $provider);

try {
    $ad->connect('default');
} catch (\Adldap\Exceptions\Auth\BindException $e) {
    die ("Can't bind to LDAP server.");
}

$username = 'USERNAME,ou=people,dc=entdir,dc=utexas,dc=edu';
$password = 'PASSWORD';

try {
    if ($provider->auth()->attempt($username, $password)) {
        echo "Login successful";
    } else {
        echo "Credentials rejected.";
    }
} catch (\Adldap\Exceptions\Auth\UsernameRequiredException $e) {
    print_r($e);
} catch (\Adldap\Exceptions\Auth\PasswordRequiredException $e) {
    print_r($e);
}
```

You can see that the commented out `admin_account_suffix` and `account_suffix` reflect what is in use in the `admin_username` and the `$username`, respectively. My expectation would be that I could remove these strings from `admin_username` and `$username` and then uncomment the `admin_account_suffix` and `account_suffix`.

However, if I simply start by uncommenting the `account_suffix` config parameter and remove `,ou=people,dc=entdir,dc=utexas,dc=edu` from the `$username` string, the bind fails. I would not have expected `account_suffix` to impact the `admin_username` since there's the admin-specific `admin_account_suffix` config parameter.

Given the the above configuration provides for a successful bind and authentication, is there any way to move `,ou=people,dc=entdir,dc=utexas,dc=edu` from the `$username` string into a config parameter?

Many thanks!

**Comment by utugs** [comment]
Well, the Devil is in the details. That resolved the connection. Cheers.

**Comment by stevebauman** [comment]
Great to hear! If you encounter any further issues, please don't hesitate to create another, thanks!
