### ISSUE TITLE
getManager method failed after updating to 6.1.10

### ISSUE THREAD

**Issue by jagDanJu** [Adldap2/Adldap2#338]
Hey Guys,

after updating from version 6.1.9 to 6.1.10, i get the following error:

`ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'getManager' in ..\vendor\adldap2\adldap2\src\Adldap.php:108`

Is there any solution?

Greetings Daniel

**Comment by ArabAgile** [comment]
+1

**Comment by xBytez** [comment]
+1

**Comment by jagDanJu** [comment]
For my understanding, it should be still have this method..

**Comment by xBytez** [comment]
If you use Adldap2-Laravel and you get this error. you need to change Line 272 on https://github.com/Adldap2/Adldap2-Laravel/blob/f4a183369076a184e4135599ad3391c5c74d470f/src/Traits/ImportsUsers.php#L272 to the current version on Git. I assume composer hasn't updated for adldap2-laravel. Doing that fixed this issue for me.

**Comment by stevebauman** [comment]
Apologies, huge oversight on my part everyone.

Sorry guys, completely my fault.

I tagged the master branch with 6.1.10 instead of the 6.1 branch. Please re-pull update using composer update.

**Comment by jagDanJu** [comment]
Ahh fine!
re-pull and everything works.

Thanks man.

**Comment by stevebauman** [comment]
No problem! Apologies for the inconvenience :).
