### ISSUE TITLE
set and then get doesn't return expected data

### ISSUE THREAD

**Issue by sshearn** [Adldap2/Adldap2#34]
When I call setFirstName in the User model and then I call getFirstName later, it returns null because the get method passes a subkey of 0 to the getAttribute method, but the set method doesn't create it as an array with a subkey. Is this expected behavior ?

**Comment by stevebauman** [comment]
Nope it's not. Just fixed! Going to go through all attributes.

**Comment by sshearn** [comment]
It still doesn't work properly, the getFirstName methods for the user model have a subkey of 0 and the set method doesn't set it that way.

**Comment by stevebauman** [comment]
Yes it does.

https://github.com/Adldap2/Adldap2/blob/master/src/Models/User.php#L89

**Comment by sshearn** [comment]
I apologize, I thought I had rerun composer update, apparently I didn't. Good fix.

**Comment by stevebauman** [comment]
No problem! Yea you might need to specify `"adldap2/adldap2": "v5.0.0-beta.2"` in your `composer.json` to get it updated.
