### ISSUE TITLE
User changePassword function throws always ErrorException

### ISSUE THREAD

**Issue by rafa7oliveira** [Adldap2/Adldap2#340]
When there is any error (eg. wrong old password) throws always ErrorException.
I suggest this change to solve the problem

Original code:

```php
public function changePassword($oldPassword, $newPassword, $replaceNotRemove = false)
{
[...]
// Update the user.
$result = $this->update();
```

To:
```php
public function changePassword($oldPassword, $newPassword, $replaceNotRemove = false)
{
[...]
// Update the user.
try {
   $result = $this->update();
} catch (\ErrorException $ex) {
   $result = false;
}
```
I am using Laravel with PHP 7 and AD 2008 R2.

**Comment by stevebauman** [comment]
The purpose of the exceptions is to notify the user why the change failed, so we throw different exceptions:

https://github.com/Adldap2/Adldap2/blob/v6.1/src/Models/User.php#L858-L868

Why don't you catch the exception yourself?

```php
try {
    $user->changePassword('...');
} catch (Exception $e) {
    return $e->getMessage();   
}
```

**Comment by rafa7oliveira** [comment]
Thanks for the feedback.

Catch the exception in this way does not work for me, because I wanted to send a message back to the reason for failure of the user in the operation. But as is always returned ErrorException with code "0" and message "ldap_modify_batch (): Modify Batch: Constraint violation" would have to have access to "connection" to filter by extended error as in [https://github.com/Adldap2/Adldap2/blob/v6.1/src/Models/User.php#L848-L870](url)

My code:
```php
try {
    if ($user->adldapUser()->changePassword($oldPassword, $newPassword)) {
        Auth::logout();
        flash()->success(trans('passwords.messages.update.success'))->important();
        return redirect('login');
    }
    flash()->error(trans('passwords.messages.update.error'))->important();

} catch (PasswordPolicyException $ex) {

    flash()->error(trans('passwords.messages.update.policy'))->important();

} catch (WrongPasswordException $ex) {

    flash()->error(trans('passwords.messages.update.wrong'))->important();

} catch(Exception $ex) {

   flash()->error(trans('passwords.messages.update.error'))->important();

}
```
But always catches the ErrorException, even when sending the wrong old password.
