### ISSUE TITLE
Cannot update common name

### ISSUE THREAD

**Issue by gitRpm** [Adldap2/Adldap2#341]
Hello,

I cannot update the common name. I can update any of these other properties, but when the display name is changed I get an error.

    private function setEditableProperties(User $user, \Adldap\Models\User $adUser)
    {
        $adUser->setFirstName($user->getFirstName());
        $adUser->setLastName($user->getLastName());
        $adUser->setAttribute('samaccountname', $user->getUsername());
        $adUser->setTitle($user->getJobTitle());
        $adUser->setCommonName($user->getDisplayName());
        $adUser->setEmail($user->getEmail());
    }

Exception:

    ErrorException in Ldap.php line 293:
    ldap_modify_batch(): Batch Modify: Operation not allowed on RDN

    1. in Ldap.php line 293

    2. at HandleExceptions->handleError('2', 'ldap_modify_batch(): Batch Modify: Operation not allowed
    on RDN', '\adldap2\adldap2\src\Connections\Ldap.php', '293', array('dn' => 'CN=Test
    Persons,OU=Domain Users,DC=corp,DC=domain,DC=com', 'values' => array(array('attrib' => 'cn',
    'modtype' => '3', 'values' => array('Test Personsss')))))

    3. at ldap_modify_batch(resource, 'CN=Test Persons,OU=Domain
    Users,DC=corp,DC=domain,DC=com', array(array('attrib' => 'cn', 'modtype' => '3', 'values' =>
    array('Test Personsss')))) in Ldap.php line 293

    4. at Ldap->modifyBatch('CN=Test Persons,OU=Domain Users,DC=corp,DC=domain,DC=com',
    array(array('attrib' => 'cn', 'modtype' => '3', 'values' => array('Test Personsss')))) in Model.php line
    673

**Comment by gitRpm** [comment]
I ended up using `$adUser->rename('cn=' . $user->getDisplayName())` but I'm not sure why I can't directly set the cn.

**Comment by stevebauman** [comment]
If you're editing an existing user, the CN must be processed through a 'rename' like you've discovered.

This is because the users full DN (distinguished name) relies on the CN (common name) (ex `cn=John Doe,dc=corp,dc=acme,dc=org`), to make up it's RDN (relative distinguished name).

Unfortunately this is just how active directory works (unsure for other LDAP providers).

**Comment by stevebauman** [comment]
Just keep in mind, that a rename method will actually resync your users attributes after the operation has taken place, so be sure to perform this before or after saving:

```php
private function setEditableProperties(User $user, \Adldap\Models\User $adUser)
{
    $adUser->rename('cn=' . $user->getDisplayName());

    $adUser->setFirstName($user->getFirstName());
    $adUser->setLastName($user->getLastName());
    $adUser->setAttribute('samaccountname', $user->getUsername());
    $adUser->setTitle($user->getJobTitle());
    $adUser->setCommonName($user->getDisplayName());
    $adUser->setEmail($user->getEmail());
}
```

**Comment by gitRpm** [comment]
That's cool, thanks for the response! You may want to update your documentation though.



Updating 
 If you are sure the model does exist already inside your AD, you can use the update() method: 
 `$user = $provider->search()->whereEquals('cn', 'John Doe')->firstOrFail();`

    $user->cn = 'Suzy Doe';

    if ($user->update()) {
        // User was updated.
    } else {
         // There was an issue updating this user.
    }

**Comment by stevebauman** [comment]
Ah great didn't catch that. Thanks for pointing that out!
