### ISSUE TITLE
SSL Question for setting password

### ISSUE THREAD

**Issue by gitRpm** [Adldap2/Adldap2#343]
The exception message when trying to set a password says that ssl or tsl needs to be configured on Web server. SSL is configured on the web server, but not the AD server. Does it need to be configured on the AD server as well?

In my adldap config file I have:

    'use_ssl' => true,
    'use_tls' => false,

I even tried putting `ldaps://` in front of the domain host ip, but nothing is working.

Thanks!

**Comment by stevebauman** [comment]
Hi @gitRpm,

Yes unfortunately. If your AD server does not have SSL configured, it will reject the request and you'll receive an exception.
