### ISSUE TITLE
understandable Empty Search 

### ISSUE THREAD

**Issue by donfal71** [Adldap2/Adldap2#346]
Hi,

First, I want to thanks you for your tremendous work about this Adldap2 library.

I want to use this in order to allow my wordpress app to update users password. In order to test, my AD admin has create an OU=test and inside 2 users, admin_test (read/write access) and user_test (read only).

I am authenticated through an SSL Connection, it works, but It is impossible to search and get any results (I tried several methods according your doc), moreover, I read several posts related to this issue, none of them gave me a solution. I'm starting to think that I miss something and my AD knowledge is close to zero...

The following code returns : 

```
object(Illuminate\Support\Collection)#176 (1) {
  ["items":protected]=> array(0) { }
}
```

if I add ->get(), then I get **NULL**

Here my code : 
```

        $options = [
            "domain_controllers"    => ['clouddc01'],
            "account_suffix"        => "@mycompany.com"
            "base_dn"               => "ou=test,dc=mycompany,dc=fr",
            "admin_username" => "admin_test",
            "admin_password" => "******",
            "use_ssl"        => true
        ];

        $ad = new Adldap();

        // Create a new connection provider.
        $provider = new \Adldap\Connections\Provider($options);

        // Add the provider to Adldap.
        $ad->addProvider('default', $provider);

        try {
            // Connect using the providers alias name.
            $ad->connect('default');

            // Perform a query.
            $result = $ad->search()->all();

            var_dump($results);

        } catch (\Adldap\Exceptions\Auth\BindException $e) {

        }
```

I can search with this account using softerra LDAP Administrator, It works.

I really don't know how to make it works.

Many thanks for you help.

**Comment by stevebauman** [comment]
Hi @donfal71, thanks for your kind words!

Can you try setting your `base_dn` to: `dc=mycompany,dc=fr` and see if you're returned any results?

**Comment by donfal71** [comment]
HI @stevebauman ,

Thanks for your quick reply. 

I already tried it, I just did it again but the result is the same : 

```
object(Illuminate\Support\Collection)#176 (1) {
  ["items":protected]=> array(0) { }
}

```

To be clear, the user I use is not actually not an AD Administrator, but It has read/write access through all AD.

Thanks again.

**Comment by stevebauman** [comment]
Can you try retrieving the root DSE and see if anything is returned?

```php
var_dump($ad->search()->getRootDse());
```

**Comment by donfal71** [comment]
Yep, It returns me an huge object, find it in the next file :

[getrootdse.txt](https://github.com/Adldap2/Adldap2/files/594972/getrootdse.txt)

**Comment by stevebauman** [comment]
Okay, your `base_dn` seems to be incorrect, can you try setting it to:

```php
DC=cloud,DC=company,DC=fr
```

And then try retrieving results using `search()->all()`?

**Comment by donfal71** [comment]
Yeah, It works.

I was pretty sure I tried this way this morning...Damn It.

Anyway, many thanks, now let's play with LDAP :)

**Comment by stevebauman** [comment]
Perfect! No problem :).

Definitely let me know if you encounter any further issues.
