### ISSUE TITLE
LDAP Authentication issue in Laravel 5.2

### ISSUE THREAD

**Issue by senthilkumar123** [Adldap2/Adldap2#347]
We are using two login type with tab based - standard (email) and LDAP (scienceid as username).

Initially they have configured Standard login in Laravel5.2 and it is working fine. Now we have added ldap type login and configured below steps

Below are the steps and issue:

1.	Opened  `composer.json` file and inserted in the `require: {}` array:  - `"adldap2/adldap2-laravel": "2.1.*"`
2.	Run the `composer update` command in the root directory of your project to pull in Adldap2 and its dependencies
3.	Inserted the following service providers in your `config/app.php` file (in the `providers` array):
a.	 Adldap\Laravel\AdldapServiceProvider::class,
b.	Adldap\Laravel\AdldapAuthServiceProvider::class,
4.	  run `php artisan vendor:publish` in root project directory to publish Adldap2's configuration files (`config` folder, `adldap.php` and `adldap_auth.php`)
5.	Opened  config/auth.php configuration file and change the following:
'providers' => [
    'users' => [
        'driver' => 'adldap', // Changed from 'eloquent'
        'model' => App\User::class,
    ],
],
6.	Modify the `config/adldap.php` file for your AD server configuration.
7.	 Run the command `php artisan make:auth` to scaffold authentication controllers and routes.
8.	 Inside the generated `app/Http/Controllers/Auth/AuthController.php`, 
9.	class AuthController extends Controller
    {
        protected $username = 'username';
    ```
10.	Now insert a new auth driver inside your `config/auth.php` file:

    ```php
    
	'providers' => [
        'users' => [
            'driver' => 'adldap', // Was 'eloquent'.
          
	  'model'  => App\User::class,
        ],
    ],
    ```
11.	Inside your `resources/views/auth/login.blade.php` file, 

	if you're requiring the user logging in by username, you'll
    need to modify the HTML input to `username` instead of `email`. 

I followed the instructions in this URL  https://github.com/Adldap2/Adldap2-Laravel (Laravel 5.2 & Up) 

We are receiving below error: Please any one help me

**angular.min.js:118TypeError: Cannot read property 'credentialString' of null
    at Object.list (lookupEndpoints.js:19)
    at loadLookup (lookup.js:20)
    at Object.<anonymous> (lookup.js:94)
    at Object.invoke (angular.min.js:41)
    at Object.$get (angular.min.js:39)
    at Object.invoke (angular.min.js:41)
    at angular.min.js:43
    at d (angular.min.js:40)
    at e (angular.min.js:41)
    at Object.invoke (angular.min.js:41)**

**Comment by stevebauman** [comment]
Hi @senthilkumar123,

This sounds like an angular issue, I'm not sure where this error is coming from.

I won't be able to assist you since I've never used angular.

**Comment by senthilkumar123** [comment]
Thanks for your reply. I will try to fix this issue and ask you if I have any problem in Laravel for assistance.

**Comment by senthilkumar123** [comment]
Hi  @stevebauman
I have fixed the angularJS issue and I used below code in loginaction controller page. I didn't return any data. I am struggling in creating custom module for LDAP setting in Laravel.  I would like know if I missed any or do you need any other information?

**Auth::attempt($credentials);**
