### ISSUE TITLE
attribute jpegPhoto missing

### ISSUE THREAD

**Issue by wallish** [Adldap2/Adldap2#349]
The attributre `jpegPhoto` is missing.

With this attribute i can put picture like 200 x 200 pixels in order to have a better quality photo than thumbnailPhoto.

The recommended size photo for thumbnailPhoto is 96 x 96 pixels, i respect this format for the apps who are using this field and expect to get 96 x 96 pixels photo.

So what about the add `jpegPhoto` in the shema inside this pretty lib

**Comment by wallish** [comment]
I can make a PR if you want

**Comment by stevebauman** [comment]
That'd be great!

**Comment by wallish** [comment]
you were faster than me, thx ;)
