### ISSUE TITLE
adldap user() method undefined

### ISSUE THREAD

**Issue by zerojargon** [Adldap2/Adldap2#35]
Hey,

Having a rather strange error.

    $adLDAP->user()->all()

Is returning 

    Call to undefined method Adldap\Adldap::user()

I have confirmed that the connection is working, and I can do other things such as

    $adLDAP->authenticate();

**Comment by stevebauman** [comment]
Sorry, documentation still need to be updated (will be doing that today) You need to call `$ad->users()`.
