### ISSUE TITLE
Add User Schema attributes

### ISSUE THREAD

**Issue by tecnical** [Adldap2/Adldap2#351]
Hi Steve,

Can you add in the user schema the attributes departmentnumber, roomnumber and employeenumber?

Best regards sincerely.

**Comment by stevebauman** [comment]
Hi @tecnical, just added.

These will be available in the `v7.0` release due to the schema changes.

**Comment by tecnical** [comment]
Tnks man,

You're doing a awesome job!!

**Comment by stevebauman** [comment]
Thanks so much for the kind words! :).

**Comment by forevermatt** [comment]
Hi @stevebauman. I just hit this employeeNumber issue, as well. Do you have a timeline for when you expect to release `v7.0`? Thanks for all your great work on this library.

**Comment by forevermatt** [comment]
Sorry to have bothered you, I just realized I can use `...->getAttribute('employeenumber', 0)` in the meantime. Thanks again!

**Comment by stevebauman** [comment]
No problem @forevermatt!

You can also use `$model->getFirstAttribute('employeenumber');`

It returns `null` if the attribute is empty / doesn't exist.
