### ISSUE TITLE
Recursive group getMembers()

### ISSUE THREAD

**Issue by barbuslex** [Adldap2/Adldap2#352]
Hi,

Is it possible to retreive all users in group recursively (without displaying subgroups) ?
I have try this (in laravel but its same with just adldap library) : 
```
$Groups = Adldap::search()->groups()->where('managedBy', '=', $Group->getDn())->sortBy('samaccountname')->get();
var_dump($Groups->getMembers());
```

I have subgroup displayed but not users.

Can you help me ?

Thanks

**Comment by stevebauman** [comment]
Hi @barbuslex, you'll actually need to query for users with the specific group:

https://github.com/Adldap2/Adldap2/blob/master/docs/troubleshooting.md#retrieving-all-records-inside-a-group

```php
$filter = '(memberof:1.2.840.113556.1.4.1941:=CN=MyGroup,DC=example,DC=com)';

$users = $provider->search()->users()->rawFilter($filter)->get();
```

**Comment by barbuslex** [comment]
Ok thanks ;) I didn't see it in documentation.

**Comment by stevebauman** [comment]
No problem :)
