### ISSUE TITLE
findByGuid() function implementation ?

### ISSUE THREAD

**Issue by barbuslex** [Adldap2/Adldap2#354]
Hi,

Following to issue #320 

Is it possible to implement the findByGuid() function for users and groups ?

Because, i need an id for identify entries and pass it to url's parameter.

Thanks

**Comment by stevebauman** [comment]
Hi @barbuslex,

There isn't a built in method for this, but this is how you can perform this right now:

```php
$guid = Utilities::stringGuidToHex('0be6c40a-f712-4d4b-bdc7-2f9eaaef62c6');

$model = Adldap::search()->rawFilter("(objectguid={$guid})")->first();
```

**Comment by stevebauman** [comment]
Just added in `dev-master`, the method will be available in `7.0` due to the addition of the `whereRaw()` method.

**Comment by barbuslex** [comment]
Thanks so much ! 
I am already in `dev-master` for NoDatabaseSynchronisation ^^ 
I will just type `composer update` ;)

**Comment by stevebauman** [comment]
No problem! Ok great :)
