### ISSUE TITLE
Can't set user password - A bunch of errors

### ISSUE THREAD

**Issue by Crapmo** [Adldap2/Adldap2#355]
Code I'm trying to execute:
```
    $search = $provider->search();
    $ad->connect('default');
    $user = $ad->search()->find('test2013');
    $user->setPassword('Password')->save();
```

PHP result:

```Notice: Use of undefined constant LDAP_MODIFY_BATCH_REPLACE - assumed 'LDAP_MODIFY_BATCH_REPLACE' in /*snip*/process/vendor/adldap2/adldap2/src/Models/User.php on line 783```
```Notice: Use of undefined constant LDAP_MODIFY_BATCH_REMOVE_ALL - assumed 'LDAP_MODIFY_BATCH_REMOVE_ALL' in /*snip*/process/vendor/adldap2/adldap2/src/Objects/BatchModification.php on line 198```
```Notice: Use of undefined constant LDAP_MODIFY_BATCH_REMOVE - assumed 'LDAP_MODIFY_BATCH_REMOVE' in /*snip*/process/vendor/adldap2/adldap2/src/Objects/BatchModification.php on line 202```
```Notice: Use of undefined constant LDAP_MODIFY_BATCH_ADD - assumed 'LDAP_MODIFY_BATCH_ADD' in /*snip*/process/vendor/adldap2/adldap2/src/Objects/BatchModification.php on line 204```
```Notice: Use of undefined constant LDAP_MODIFY_BATCH_REPLACE - assumed 'LDAP_MODIFY_BATCH_REPLACE' in /*snip*/process/vendor/adldap2/adldap2/src/Objects/BatchModification.php on line 206```
```Fatal error: Call to undefined function Adldap\Connections\ldap_modify_batch() in /*snip*/process/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 293```

Searching is working fine and echos results normally, however setting/resetting user password's seems to not work as it should.

I'm sorry if this is a quick and easy fix, I haven't done much with PHP nor ADLDAP, so I'm quite unaware of all exceptions and errors.

Thanks!

**Comment by stevebauman** [comment]
Hi @Crapmo, what version of PHP are you using?

**Comment by Crapmo** [comment]
PHP 5.5.9-1ubuntu4.20 (cli)

**Comment by Crapmo** [comment]
Nevermind, got a new error on PHP 7

```
Fatal error: Uncaught Error: Call to undefined function Adldap\ldap_explode_dn() in /var/www/html/process/vendor/adldap2/adldap2/src/Utilities.php:20 Stack trace: #0 /var/www/html/process/vendor/adldap2/adldap2/src/Objects/DistinguishedName.php(252): Adldap\Utilities::explodeDn('ou=soana,DC=sol...', false) #1 /var/www/html/process/vendor/adldap2/adldap2/src/Objects/DistinguishedName.php(74): Adldap\Objects\DistinguishedName->setBase('ou=soana,DC=sol...') #2 /var/www/html/process/vendor/adldap2/adldap2/src/Connections/Configuration.php(124): Adldap\Objects\DistinguishedName->__construct('ou=soana,DC=sol...') #3 /var/www/html/process/vendor/adldap2/adldap2/src/Connections/Configuration.php(436): Adldap\Connections\Configuration->setBaseDn('ou=soana,DC=sol...') #4 /var/www/html/process/vendor/adldap2/adldap2/src/Connections/Configuration.php(112): Adldap\Connections\Configuration->fill(Array) #5 /var/www/html/process/vendor/adldap2/adldap2/src/Connections/Provider.php(123): Adldap\Connections\Configuration->__construct(Array in /var/www/html/process/vendor/adldap2/adldap2/src/Utilities.php on line 20

**Comment by stevebauman** [comment]
`ldap_explode_dn()` is a common method available in PHP 4, 5 & 7. Are you sure you have the LDAP extension enabled properly?

http://php.net/manual/en/function.ldap-explode-dn.php

**Comment by Crapmo** [comment]
I had to reinstall LDAP, didn't get to test it yet though. I'll reply once I have new results.

**Comment by Crapmo** [comment]
Managed to fix it, well that was dumb. Thanks for the help! Closing this.

**Comment by stevebauman** [comment]
No problem!
