### ISSUE TITLE
User must change password at next logon

### ISSUE THREAD

**Issue by tecnical** [Adldap2/Adldap2#357]
Hi Steve,

Can I set this option with adldap2? I looked at the code, but I could not find it.

thank you again

**Comment by stevebauman** [comment]
Hi @tecnical,

You'll need to set the users `pwdLastSet` attribute to `0`. See:

https://msdn.microsoft.com/en-us/library/aa746510(v=vs.85).aspx

In Adldap2:

```php
$user = $provider->search()->find('jdoe');

$user->setAttribute('pwdlastset', 0);

$user->save();
```

**Comment by tecnical** [comment]
Hi Steve,,

Thanks, but o cannot make it work just with a zero (0).

$user->setAttribute('pwdlastset', 0);

Using

$user->setAttribute('pwdlastset', '0000');

worked like a charm.

Thank you! And Merry Christmas!

**Comment by stevebauman** [comment]
Perfect, glad you've resolved it! Thanks for the information. I'll definitely put this in the docs.

You have a Merry Christmas as well :).

**Comment by laharshah** [comment]
When we are finding user using find() method it actually returns the first matched user. 

When we want to update any attribute/password we really need the unique user for whom we want to make that update. 

So it is always better to use where() clause or findBy() method instead of find()

For example:
```
$user = $provider->search()->->where('samaccountname', '=', $username)
                                ->select([
                                    'cn',
                                    'memberof',
                                    'samaccountname',
                                    'mail',
                                    'telephoneNumber',
                                    'pwdlastset',
                                    'accountexpires',
                                    'useraccountcontrol'
                                     ])
                                ->first();
```
