### ISSUE TITLE
reset pass in AD

### ISSUE THREAD

**Issue by aliemam** [Adldap2/Adldap2#358]
Hi, is there way to reset pass in AD with this library?
i use Adldap2-laravel with adldap-auth driver. i managed to login with adldap but for reseting password its after i retrieved email from ldap and used sendResetLink() to send reset link. in getUser func in PasswordBroker.php laravel tries to get user with retrieveByCredentials in AdldapAuthUserProvider.php but it requires username and password which are not in credentials (it shouldn't be cuz i try to reset the password). 

are there any solution or extended module for that. or i did sth wrong i dont know.

**Comment by stevebauman** [comment]
Hi @aliemam,

Resetting AD passwords isn't built into the auth driver currently. You'll have to do this manually through Adldap:

```php
$user = Adldap::search()->users()->find('jdoe'):

if ($user->changePassword($oldPassword, $newPassword)) {

    // Password has been changed!

}
```

However you'll need to be connected to your AD server via SSL or TLS if you want to change passwords.

**Comment by aliemam** [comment]
Hi @stevebauman 
tanx for reply. just one thing that i did not get, typically when you want to reset pass by link, after done some security matter you change pass in db directly, i mean you just overwrite it. but in this case, do you have to know the old pass cuz as far as i know you can not retreive passwords from ad. 
i know this is an ad question bust i saw productions can reset ad pass so i wonder if it is possible with adldap2.

**Comment by stevebauman** [comment]
Have you tried:

```php
// The `setPassword()` method sets the `unicodepwd` attribute in AD.
$user->setPassword('newpassword');

$user->save();
```
