### ISSUE TITLE
$ad->user()->inGroup() method missing?

### ISSUE THREAD

**Issue by JeremyHargis** [Adldap2/Adldap2#36]
Hello.

We were using an older version of adldap in a few of our projects and we used to use the inGroup() method to check group membership. For example:

```php
$ad->user()->inGroup($username, $groupname);
```
I now get an error when I try to use this method: "Call to undefined method Adldap\Adldap::user()." I tried searching the API docs for this method to see if it has simply been moved to a different class but I couldn't find it. Has the functionality of this older method been moved to a new location?

Thanks.

**Comment by stevebauman** [comment]
The `user()` method has been renamed to `users()`, also I've just re-added this in the `User` model now:

https://github.com/Adldap2/Adldap2/commit/1a040b028c82fb63c16741a2d9e9501f74a93c73#diff-61d36f782b569eb739564391b9ddb5f2R70

Though if you'd like to perform the check yourself, you can use:

    $groupName = 'Group Name';

    $user = $ad->users()->find('jdoe');

    foreach($user->getMemberOf() as $group)
    {
        if($groupName == $group->getName()) return true;
    }

**Comment by stevebauman** [comment]
If you're using `adldap2/adldap2: dev-master`, then you can just use `$user->inGroup('group name')`

**Comment by JeremyHargis** [comment]
@stevebauman Thank you very much for your prompt response. It seems like that is working, but I have one additional question now. I wasn't using the find() method before. Now that I will be using it, is there a way I can make this method match the samAccountName exactly? I am finding that it finds other accounts if they share an initial portion of the sanAccountName. Thanks again.

**Comment by stevebauman** [comment]
No problem, you can actually use:
    
    $username = 'jdoe';    

    $user = $ad->users()->search()->whereEquals('samAccountName', $username)->first();

    if($user)
    {
        // User was found!
    }

**Comment by JeremyHargis** [comment]
Fantastic! That works like a charm. I really like that syntax.

Thanks for your help!

**Comment by stevebauman** [comment]
That's great to hear! I've been working hard at it and I hope it's enjoyable to use.

If you have any more issues don't hesitate to let me know, thanks!
