### ISSUE TITLE
Can't contact LDAP server over ssl

### ISSUE THREAD

**Issue by aliemam** [Adldap2/Adldap2#362]
Hi everyone. i have problem with connecting to AD on windows server. Does anyone have experience, creating CA on windows server, setting up server ldap CA tanx to this article:
http://social.technet.microsoft.com/wiki/contents/articles/2980.ldap-over-ssl-ldaps-certificate.aspx

BUT...
whats next??

**Comment by wranger** [comment]
Hi,

I used this old Howto for my Server2012 : 

https://github.com/adldap/adLDAP/wiki/LDAP-over-SSL

Maybe it might help you?!

**Comment by aliemam** [comment]
@wranger tanx man its realy help :)
