### ISSUE TITLE
Password policy exceptions not catched for changePassword() method

### ISSUE THREAD

**Issue by meons** [Adldap2/Adldap2#365]
The following code does not catch any exception when I set a password that doesn't match my password policy.
```php
try {
	$user->changePassword($passwordActual, $passwordNew);
} catch (UserPasswordPolicyException $e) {
	return $this->render('default/show.html.twig', array(
		'msg' => $e->getMessage(),
	));
} catch (AdldapException $e) {
	return $this->render('default/show.html.twig', array(
		'msg' => $e->getMessage(),
	));
}
```
Instead of catched exception I get the following error.
<code>[2017-01-18 12:43:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: ldap_modify_batch(): Batch Modify: Constraint violation" at /var/www/html/ldap-frontend/vendor/adldap2/adldap2/src/Connections/Ldap.php line 302 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: ldap_modify_batch(): Batch Modify: Constraint violation at /var/www/html/ldap-frontend/vendor/adldap2/adldap2/src/Connections/Ldap.php:302)"} []</code>

I checked in [User.php](https://github.com/Adldap2/Adldap2/blob/d647613cffa391f3e608162e67ce9c7d64198265/src/Models/User.php) and throw code looks okay into changePassword() method.

Any idea ?

**Comment by meons** [comment]
Of course I could catch it with a standard `Exception`, but anyway there is something wrong with actual code.

**Comment by stevebauman** [comment]
Hi @meons,

A `Constraint violation` usually means you're hitting a password policy on your AD server.

This could mean the new password isn't complex enough / doesn't contain enough characters / has already been used previously (password history requirement) / etc.

Are you sure the new password you're setting it to passes the password policies on your AD server?

**Comment by meons** [comment]
Hi @stevebauman 

Nope my password does not pass pwd policies on my AD. That's exactly the point that I have explained: I expected that UserPasswordPolicyException raises an exception when password policy does not match. But in fact it doesn't raise any exception. For me it should raise an exception because if you have to deal with that by yourself, UserPasswordPolicyException class is actually useless.

I hope it's more clear now =)

**Comment by stevebauman** [comment]
Thanks @meons, you're absolutely right. Fixing this now, thanks!

**Comment by meons** [comment]
Of course but this week I'm pretty busy. I will test your change next week.
So for testing I have to temporarily replace `"adldap2/adldap2": "7.0.*"` by `"adldap2/adldap2": "dev-master"` in my composer.json and then run a `composer install` rigth?

**Comment by stevebauman** [comment]
Yup that's correct. Thanks!

**Comment by sulzer** [comment]
Hi @stevebauman 

I have the same issue as @meons , just gave it a try using the master branch but no joy.  I get a constraint violation in any case, even when I specify correct passwords that match the password policy:

`
$user =  $adldap->search()->users()->find($username);
try {
	$user->changePassword($oldpassword, $newpassword);
	exit();
}
	
catch (UserPasswordPolicyException $e) {
	echo "Password policy error: " . $e;
	exit();
}
catch (AdldapException $e) {
	echo "LDAP error: " . $e;
	exit();
}
`

This is the case with a Win 2012 R2 AD server.

Resetting the password as follows works:

`
$user = $adldap->search()->find($username);
$user->setPassword($pwnew);
		
if ($user->update()) {
	echo "pw changed.";
}
`
Thanks!

**Comment by mvatansever** [comment]
[Here](https://github.com/Adldap2/Adldap2/issues/323) I was wanting to explain this issue :)
Thanks for resolvers of this issue.

**Comment by chriseskow** [comment]
@stevebauman We're trying to upgrade our code from v5.2 to v7 and are running into an issue with password changing and resets, which is related to this issue.

I believe the change in 0f3d795 is incorrect - in fact, I think the code was working better *before* that commit.

When the `ldap_modify_batch()` call is made with bad parameters (e.g. wrong current password, or new password doesn't meet complexity standards), it emits a PHP Warning and returns false. In version 5.2, the warning was suppressed via the `@` operator and the false return value was checked and the appropriate exception was thrown (`WrongPasswordException` or `PasswordPolicyException`).

In version 7, the error suppressing seems to have been done away with. @meons seems to be using the Symfony Debug component which converts PHP Warnings to exceptions. That's why he was getting the `ContextErrorException`.

Now, after the change in 0f3d795, `changePassword()` has a try/catch which incorrectly assumes that `$this->update()` will throw an exception - but unless you have a error handler set which converts PHP Warnings to exceptions, it will not throw an exception.

I think that 0f3d795 should be reverted so that `changePassword()` checks the return value of `$this->update()`, like it did before. If error suppression could be added back to the `Adldap\Connections\Ldap` class that would be great as well. If not, then I guess we can work around that by suppressing errors in the client code: `@$user->changePassword(...);`

**Comment by stevebauman** [comment]
Hi @chriseskow, you're right, this is still an issue.

I'll fix this for both scenarios. I'll mute the warnings and exceptions when calling `update()`, and if it fails it will be converted into an exception by default, satisfying both use cases.

**Comment by stevebauman** [comment]
@chriseskow Can you try `dev-master` and give it shot?

https://github.com/Adldap2/Adldap2/commit/f90cef22986a8f34db7d4df16f06ef1471e9713d

**Comment by chriseskow** [comment]
@stevebauman Thanks for the fast turn-around, we'll test it out!

**Comment by chriseskow** [comment]
@stevebauman Based on our testing `dev-master` seems to be muting the warnings and throwing the exceptions as expected.

**Comment by stevebauman** [comment]
Thanks @chriseskow! And no problem. I use Adldap2 in full production, so bug fixes are a huge priority to me.

Working on adding some more tests and then I'll have a new release out tonight.

**Comment by rafa7oliveira** [comment]
I reported this bug 5 months ago:
"User changePassword function throws always ErrorException #340"... but I was ignored!

**Comment by stevebauman** [comment]
Hi @rafa7oliveira, I'm sorry you feel that way. I assure you I wasn't ignoring you. There'd be no reason for me to do that. There was just no detailed change suggestion made on the issue like @chriseskow proposed (muting warnings and throwing an exception on failure).

**Comment by laharshah** [comment]
Using find method I ran into the problem where I get the wrong user as find returns the first match user. 

$user =  $adldap->search()->users()->find($username);

Finds the first matched user, which can lead into changing the password for wrong user in some cases. 

samaccountname is unique username here:

Make sure you find the unique user using where clause. For example: 

$adldap->search()->where->('samaccountname', '=', $username)->select(['cn',
                                    'memberof',
                                    'samaccountname',
                                    'mail',
                                    'telephoneNumber',
                                    'pwdlastset',
                                    'accountexpires',
                                    'useraccountcontrol'])->first()
