### ISSUE TITLE
users method

### ISSUE THREAD

**Issue by gaalgergely** [Adldap2/Adldap2#369]
- Adldap2 Version: 6.1.10
- PHP Version: 7.1.1

### Description:
vendor/adldap2/adldap2/src/Search/Factory.php
line 156 public function users(){}

Returns with empty array, always.
If I comment out line 160, then it works.
Should it be an OR condition instead of AND?
### Steps To Reproduce:
I use the Laravel package:
```
$users = Adldap::search()->users()->get();
dd($users);
```

**Comment by stevebauman** [comment]
Hi @gaalgergely,

> If I comment out line 160, then it works.

Line 160 in the `Search\Factory`?

Also, does using`Adldap::search()->all();` return any records?

**Comment by gaalgergely** [comment]
`$this->schema->objectCategory() => $this->schema->objectCategoryPerson()` -> Line 160 yes
Also, does using `Adldap::search()->all();` return any records? Yes

**Comment by gaalgergely** [comment]
Collection {#456 ▼
  #items: array:6 [▼
    0 => Entry {#448 ▶}
    1 => Entry {#449 ▶}
    2 => Entry {#450 ▶}
    3 => Entry {#451 ▶}
    4 => User {#452 ▼
      +exists: true
      +dateFormat: "Y-m-d H:i:s"
      #dn: "cn=kp@kp.hu,ou=users,dc=ldap,dc=server"
      #query: Builder {#439 ▶}
      #schema: ActiveDirectory {#441}
      #attributes: array:19 [▶]
      #original: array:19 [▶]
      #modifications: []
      #timestampFormat: "YmdHis.0Z"
    }
    5 => Entry {#453 ▶}
  ]
}
I have 2 users in the LDAP DB. One of them has the person object class, but that is optional. The default object class is inetOrgPerson for "persons". Also I can not see how they can be objectCategoryPerson. And I think they can not be objectPerson and objectCategoryPerson in the same time. What do you think?

**Comment by stevebauman** [comment]
Are you using OpenLDAP?

**Comment by gaalgergely** [comment]
Yes.

**Comment by stevebauman** [comment]
When adding a provider, you'll need to switch out the LDAP schema. By default it uses an AD schema:

https://github.com/Adldap2/Adldap2/blob/v6.1/src/Connections/Provider.php#L49

https://github.com/Adldap2/Adldap2/blob/v6.1/src/Schemas/OpenLDAP.php

```php
$schema = new \Adldap\Schemas\OpenLDAP();

$provider = new \Adldap\Connections\Provider($config, null, $schema);

$ad->addProvider('default', $provider);
```

**Comment by gaalgergely** [comment]
I edited:
config/auth.php
`'providers' => [
        'users' => [
            'driver' => 'adldap',
            'model' => App\User::class,
        ],`
And started to debug down the issue.
I found that the Factory class user method returns empty.

**Comment by stevebauman** [comment]
Actually, forgot you're using Adldap2-Laravel. You'll need to edit the schema here:

https://github.com/Adldap2/Adldap2-Laravel/blob/v2.1/src/Config/config.php#L50-L63

**Comment by gaalgergely** [comment]
Thanks! :)

**Comment by stevebauman** [comment]
No problem! :)

If you encounter any other issues please don't hesitate to create another issue.
