### ISSUE TITLE
getGroups() returns empty Collection

### ISSUE THREAD

**Issue by scotepi** [Adldap2/Adldap2#371]
- Adldap2 Version: 7.0
- PHP Version: 5.6.29
- LDAP Version: ActiveDirectory, Windows Server 2016, 2016 Function Level

### Description:
I am trying to authenticate a user and then check their groups to create a simple ACL system in PHP.

Running _$user->getGroups();_ returns an empty collection.

### Steps To Reproduce:
```
<?php
$config = [
  'account_suffix'          => '', # Require the @ part of usernames
  'domain_controllers'      => ['dcsv01'],
  'base_dn'                 => 'DC=ad,DC=example,DC=com',
];

$ad->addProvider($config);
$provider = $ad->connect();

$username = 'user@domain.com';
$password = '***';

if ($provider->auth()->attempt($username, $password, $bindAsUser=true)) {
    echo "Logged in as $username";

    $user = $provider->search()->users()->find(explode('@', $username)[0]);
    $groups = $user->getGroups();
    
    var_dump($user, $groups);
} else {
    die('Bad Auth');
}
```

**$user** looks fine, _object(Adldap\Models\User)[9]_ but I notice there is only _primarygroupid_ nothing about other groups.

**$groups** on the other hand is empty
```
object(Illuminate\Support\Collection)[13]
  protected 'items' => 
    array (size=0)
      empty
```

**Comment by stevebauman** [comment]
Hi @scotepi,

Can you dump the users attributes (using `$user->getAttributes()`) and verify that they have a `memberof` key with the distinguished names of groups that the user is apart of?

**Comment by scotepi** [comment]
There is no `memberof` there is a `distinguishedname` though _CN=Scott,CN=Users,DC=ad,DC=example,DC=com_

**Comment by stevebauman** [comment]
That would be the issue.

Are you specifying a port at all in your config? Also, this user you're binding with may not have permissions to view all of a users properties.

**Comment by scotepi** [comment]
Using the default port. Still trying to get SSL/TSL working but that's a whole nother issue. I would hope that a user could at least read their own information.

I think I see the issue, though. I added a user to another, nondefault group, and now it is showing up.

Expected behavior was to see the groups 'User' and 'Domain User' like in adLDAP 4, however, adLDAP2 appears to suppress them and only shows me 'New Group'.

**Comment by stevebauman** [comment]
> Expected behavior was to see the groups 'User' and 'Domain User' like in adLDAP 4, however, adLDAP2 appears to suppress them and only shows me 'New Group'.

What do you mean suppresses them?

Adldap2 just leverages what is returned by your server in the users `memberof` attribute.

If the groups DN isn't contained in that array, it doesn't exist.

**Comment by scotepi** [comment]
It still just returns the `New Group`, no `Domain Users` which I verified the user was a member of in _Active Directory Users and Computer_

**Comment by stevebauman** [comment]
Oh hang on, this is because it's a different attribute in AD. You need to call:

```php
$user->getPrimaryGroup(); // Returns 'Domain Users' group.
```

**Comment by scotepi** [comment]
There we go. It just seems odd that that that wouldn't be included in getGroups() because the primary group is still a group the user is a member of.

**Comment by stevebauman** [comment]
You're right, this should be included.

Will be fixed shortly, thanks!

**Comment by stevebauman** [comment]
New release will be out with the change momentarily.
