### ISSUE TITLE
Warning: ldap_add(): Add: Naming violation in \src\Connections\Ldap.php on line 271

### ISSUE THREAD

**Issue by yuriang85** [Adldap2/Adldap2#372]
- Adldap2 Version: Adldap2
- PHP Version: 5.6.25

### Description:
I'm trying to create an Organizational Unit, but I get as an error: Warning: ldap_add (): Add: Naming violation.
Before of course I checked the connection, the same is exítosa and I can search in active directory, I can create users and assign new attributes to them, but not so organizational units.

### Steps To Reproduce:

With this I get the error:

```php
$container = $provider->make()->container([
    'cn' => 'VPNUsers',
]);

$container->save();
```

With this I get the error:

```php
$cn = "Test";

$new_ou = $provider->make()->ou();

$new_ou->setCommonName($cn);

if ($new_ou->save()) {
    echo "OU was saved.";
} else {
    echo " There was an issue saving this OU.";
}
```

**Comment by stevebauman** [comment]
Are you using Active Directory or OpenLDAP?

**Comment by yuriang85** [comment]
I am using Active Directory windows server 2008 r2

**Comment by yuriang85** [comment]
please help me.

**Comment by stevebauman** [comment]
@yuriang85 You need to set the `dn` of your new OU:

```php
$ou = $provider->make()->ou();

$ou->setDn('ou=My Ou,dc=test,dc=local,dc=com');

if ($ou->save()) {

    // Saved!

}
```

**Comment by yuriang85** [comment]
Thank you very much, problem solved.

**Comment by stevebauman** [comment]
No problem :). If you encounter any further issues please let me know!
