### ISSUE TITLE
how to get Groups within a OU

### ISSUE THREAD

**Issue by arantxio** [Adldap2/Adldap2#374]
- Adldap2 Version: 7.0
- LDAP Type: Active Directory
- PHP Version: 7

### Description:
I am trying to get groups within a OU but I can't directly find this within the documentation.

Can you help?

**Comment by stevebauman** [comment]
Hi @arantxio,

Here you go:

```php
$groups = $provider->search()->groups()->in('ou=My Ou,dc=corp,dc=acme,dc=org')->get();
```
