### ISSUE TITLE
Create contact

### ISSUE THREAD

**Issue by dico** [Adldap2/Adldap2#375]
- Adldap2 Version: 7.0
- LDAP Type: Active Directory
- PHP Version: 7

Is there any doc or info about how to create contact with Adldap2?

I see the doc under the "The Contact Model" it's written "...and contains no specific methods / attributes that are limited to it". But does this mean it's not added any methods for contacts yet?

**Comment by stevebauman** [comment]
Hi @dico,

Model creation is documented here:

https://github.com/Adldap2/Adldap2/blob/master/docs/models/model.md#available-make-methods

```php
$contact = $provider->make()->contact($attributes);
```
