### ISSUE TITLE
Query Builder : Grouped contitions 

### ISSUE THREAD

**Issue by soft2u** [Adldap2/Adldap2#376]
- Adldap2 Version: #.#
- LDAP Type: 
- PHP Version: #.#

### Description:
Is there any doc or info about how to create a query like this?

`( |(&(attrBar=value)(attrFoo=value2)) (&(bla=bla2)(bla3=bla1)) )`

Thank you

**Comment by stevebauman** [comment]
Hi @soft2u,

Right now this isn't possible in the query builder, you'll have to use the `rawFilter()` method.

I've pondered the idea of having separate grouped conditions built into the query builder, but I personally haven't seen the need for it.

If you can push a PR that supports the current query builder API and incorporates the ability of grouping conditions, then I'd definitely merge it.

**Comment by soft2u** [comment]
Hello! Thank you for your quick clarification. I know that is not need-it for normal usage. 
Anyway, I have managed with a small customization, "quick and dirty": 
- create raw subqueries and append-it to the builder with **whereRaw** or **orWhereRaw** method - for this I have added a new operator **query** which use only the value argument.

code customization
new method in Query\Grammar.php
```
    /**
     * Returns a the query string.
     *
     * Produces: value
     *
     * @param string $field
     * @param string $value
     *
     * @return string
     */
    public function compileQuery($field, $value)
    {
        return $value;
    }
```
new property in Query\Operator.php

```
 /**
     * The custom query operator.
     *
     * @var string
     */
    public static $query = 'query';
```

Demo usage :
```
$q1 =  $ad_provider->search()
                    ->where('attrBar', '=', 'value')
                    ->where('attrFoo', '=', 'value2')
                    ->getQuery();

$q2 =  $ad_provider->search()
                    ->where('bla', '=', 'bla2')
                    ->where('bla3', '=', 'bla1')
                    ->getQuery();

$q3=  $ad_provider->search()
                    ->orWhereRaw('', 'query', $q1)
                    ->orWhereRaw('', 'query', $q2)
                    ->getUnescapedQuery();
                 
echo $q3;
```

**Comment by stevebauman** [comment]
Cool! Thanks for sharing your implementation :)

I agree with you that this should be implemented for Adldap2 to have a *fully featured* query builder, since it's limited in its current state.

What are your thoughts on using closures?:

```php
$q = $provider->search()->orFilter(function ($query) {
    $query->where('cn', '=', 'John Doe');
})->getUnescapedQuery();

echo $q; // Returns: '(|(cn=John Doe))
```

**Comment by stevebauman** [comment]
Added grouped conditions. Will be released in a patch soon.

This will be the API (using your example above):

```php
$query = $provider->search()->orFilter(function ($query) {
    $query->andFilter(function ($query) {
        $query->where([
            'attrBar' => 'value',
            'attrFoo' => 'value',
        ]);
    })->andFilter(function ($query) {
        $query->where([
            'bla1' => 'bla',
            'bla2' => 'bla',
        ]);
    });
})->getUnescapedQuery();

echo $query; // Returns '(|(&(attrBar=value)(attrFoo=value))(&(bla1=bla)(bla2=bla)))'
```

**Comment by soft2u** [comment]
Cool :) Nice work! Thank you!

**Comment by soft2u** [comment]
Cool! Nice work!
Thank you!
