### ISSUE TITLE
var_dump return NULL when find with username

### ISSUE THREAD

**Issue by thinhnd8752** [Adldap2/Adldap2#378]
- Adldap2 Version: #.#
- LDAP Type: 
- PHP Version: #.#

### Description:
Please looking at my code.

```php
$ad = new \Adldap\Adldap();

// Add a connection provider to Adldap.
$ad->addProvider($config);
    
$provider = $ad->connect();

if ($provider->auth()->attempt($username, $password)) {
        print("Login Success!");
           
        $user = $provider->search()->users()->find($username);
        
        var_dump($user->cn);
} else {
    print("Username/Password not Correct");
}
```

When I login with right username/password it print Login Success! but var_dump return null.
My username i use has administrator privilege too.
I'm not sure because my code or it is an issue.
Thanks all.

**Comment by stevebauman** [comment]
Hi @thinhnd8752,

Usually no results will be returned when your `base_dn` that you've set in your `$config` array is incorrect.

Can you paste your configuration with sensitive details omitted?

**Comment by thinhnd8752** [comment]
Hi stevebauman, this is my $config
$config = [
  // Your account suffix, for example: jdoe@corp.acme.org
  'account_suffix'        => '@digi-texx.local',

  // You can use the host name or the IP address of your controllers.
  'domain_controllers'    => ['10.x.x.x'],

  // Your base DN.
  'base_dn'               => 'dc=Company,dc=domain,dc=local',

  // The account to use for querying / modifying users. This
  // does not need to be an actual admin account.
  'admin_username'        => 'Administrator',
  'admin_password'        => 'myadministrator',
];

Block : 
if ($provider->auth()->attempt($username, $password)) {
        print("Login Success!");
           
        $user = $provider->search()->users()->find($username);
        
        var_dump($user->cn);
}
It print Login Success! so I think it can get my $username and $password from base_dn.

**Comment by stevebauman** [comment]
> It print Login Success! so I think it can get my $username and $password from base_dn.

Not sure what you mean. It sounds like you're authenticating properly, but your `base_dn` is still incorrect which will return no results when searching your directory.

Judging by your `account_suffix`, your `base_dn` is probably `dc=digi-texx,dc=local`, but this still may not be the case.

Try using the `base_dn` I've given above, and if you still receive no search results you'll need to go into your LDAP server and determine it manually.

**Comment by thinhnd8752** [comment]
Thanks stevebauman,
I changed base_dn and everything work fine.

**Comment by stevebauman** [comment]
@thinhnd8752 great! I'm glad you've resolved the issue.

Thanks for following up :).
