### ISSUE TITLE
Admin_auth not required

### ISSUE THREAD

**Issue by thedangler** [Adldap2/Adldap2#379]
- Adldap2 Version: 5.2.17
- LDAP Type: Active Directory 
- PHP Version: 5.6

### Description:
Our connection doesn't require admin_authentication only user, however it seems to always try to use admin_user and password when they are null and autoConnect is set to false.
Is it possible not to use the admin user and password?

**Comment by stevebauman** [comment]
Can you post your usage?

By default if your connection isn't bound and you try to perform dynamic calls on your connection, it will automatically try and call `connect()` on your provider. This will try to utilize your admin username and password:

    /**
     * {@inheritdoc}
     */
    public function __call($method, $parameters)
    {
        $provider = $this->getDefaultProvider();

        if (!$provider->getConnection()->isBound()) {
            // We'll make sure we have a bound connection before
            // allowing dynamic calls on the provider.
            $provider->connect();
        }
        return call_user_func_array([$provider, $method], $parameters);
    }

**Comment by thedangler** [comment]
I was using it with yii2 and I didn't see how updated your version was. Im now trying to use yours without the yii2 wrapper. Ill try again with version 7.

Sorry for this.
I'm currently trying to connect to the ldap server which is starting to turn out to be a pain in the a.
because I received the information from people that are doing ldap with .NET and aren't having issues lol.

Ill get back to you if I have any issues.

Thank you for the reply,

**Comment by stevebauman** [comment]
No problem! It looks like a generic connection error to your LDAP server.

I'll close this for now, but if you encounter the same issue and you're sure your configuration is correct, then I'll re-open.

**Comment by thedangler** [comment]
Hey I got the connection string working but can't seem to figure how to do a search then auth or just auth first.
the confusing part is in your docs where it says todo connect('default')? but the connect takes username and password. then I get invalid DN syntax error.
I have working code with php functions but would like to use your lib because its clean.

here is what I have that works using php methods.

`$ldapconfig['host'] = 'ldap://auth.domain.ca:389';
        $ldapconfig['port'] = '389';
        $ldapconfig['basedn'] = 'ou=people,o=domain.ca,dc=its';
        $PHP_AUTH_USER = "username";
        $PHP_AUTH_PW = "pass";
        $ds = ldap_connect($ldapconfig['host'],$ldapconfig['port']);
        ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3);
        ldap_set_option($ds, LDAP_OPT_REFERRALS, 0);
        $r = ldap_search( $ds, $ldapconfig['basedn'], '(uid=username)', [], 0, 1, 10);
        if($r){
            $result = @ldap_get_entries( $ds, $r);
            if ($result[0]) {
                if (@ldap_bind( $ds, $result[0]['dn'], $PHP_AUTH_PW) ) {
                    return $result[0];
                }
            }
        } else {
            $error = ldap_error($ds);
            echo $error;
        }`

how can I get this to work with you're code.
if I don can straight up auth without searching that would be cool.

**Comment by thedangler** [comment]
I got it working like so:
 $val = $ad->authenticate('uid=username,ou=people,o=domain.ca,dc=its',$pass,true);
