### ISSUE TITLE
unable to create a new user (Fatal error: Models/User.php on line 418)

### ISSUE THREAD

**Issue by kichetof** [Adldap2/Adldap2#38]
Hi guy!
We encounter a bug when we want to create a new user.
Everything works very well for authentificate (many thanks for this really helpfully class!).

This is our code:

```php
// ... action before
try {
        $option = array('account_suffix'        => ACCOUNT_SUFFIX,
                        'base_dn'               => BASE_DN,
                        'domain_controllers'    => unserialize(DOMAIN_CONTROLLERS),
                        'admin_username'        => ADMIN_USERNAME,
                        'admin_password'        => ADMIN_PASSWORD,
                        'use_ssl'               => true,
                       );

        $adldap = new adLDAP($option);

        $user = $adldap->users()->newInstance();
        $user->setCommonName($attributes['firstname'] . " " . mb_strtoupper($attributes['surname']));
        $user->setFirstName($attributes['firstname']);
        $user->setLastName($attributes['surname']);
        $user->setTitle($attributes['title']);
        $user->setDepartment($attributes['department']);
        $user->setTelephoneNumber($attributes['ipphone']);
        $user->setCompany($attributes['company']);
        $user->setEmail($attributes['email']);
        $user->setPassword($attributes['password']);
        $user->disable();

        $dn = $user->getDnBuilder();
        $dn->addCn($user->getCommonName());
        $dn->addOu('Users');
        $dn->addDc('local');
        $dn->addDc('ad');
        $dn->addDc('domain');

        $user->setDn($dn);

        if($user->save()){
            echo "Ok";
        }else{
            echo "ERROR";
        }
    }
    catch (adLDAPException $e) {
        echo $e;
        exit();
    }
// ... action after
```

When we `$user->setPassword`, a FATAL ERROR occurs:

<b>Fatal error</b>:  Call to a member function isUsingSSL() on null in <b>/dev-web/AD/vendor/adldap2/adldap2/src/Models/User.php</b> on line <b>418</b>

The function `isUsingSSL()` seem to occurs this error but we don't know why because we set `'use_ssl' => true` or `'use_ssl' => 1` on the ldap config and not null ?!

Our `$option` works well to bind a user, so after many hours of research, we ask you to help us to find a way to solve this problem!

Hope you guy can help us and enjoy your great class!!! :)
Tof

_Server info:
Debian 8
PHP 5.6.9-0+deb8u1
Apache/2.4.10_

_Another info:
An application that doesn't use this class is able to modify the password using SSL on the same server_

**Comment by stevebauman** [comment]
That's a bug, just fixed. Try using `adldap2\adldap2: dev-master` and let me know if you encounter any issues, then I'll release a `5.0.2`.

**Comment by kichetof** [comment]
Wow ! Too fast!
I'll try tomorrow (some bug with SSH and composer) and I'll let you know!
Big thanks !!

**Comment by stevebauman** [comment]
Ok no problem!

**Comment by kichetof** [comment]
Hi guy !

Error on line 418 solved ! :) Thanks!
But now, impossible to add a new user.
We test 2 method (old with $attribute = array() and new one with $user object)

```
var_dump($attribute);
array(18) {
  ["userprincipalname"]=>
  string(27) "testcf12@AD.DOMAIN.local"
  ["givenname"]=>
  string(10) "test1"
  ["sn"]=>
  string(10) "TEST2"
  ["cn"]=>
  string(21) "Test1 TEST2"
  ["displayname"]=>
  string(21) "Test1 TEST2"
  ["mail"]=>
  string(30) "Test1.Test2@domain.co"
  ["dinstinguishedName"]=>
  string(80) "CN=Test1 TEST2,OU=Users,DC=AD,DC=DOMAIN,dc=local"
  ["department"]=>
  string(9) "TEST"
  ["physicaldeliveryofficename"]=>
  string(3) " ; "
  ["telephoneNumber"]=>
  string(1) " "
  ["ipphone"]=>
  string(1) " "
  ["initials"]=>
  string(2) "TT"
  ["title"]=>
  string(1) " "
  ["company"]=>
  string(1) " "
  ["streetaddress"]=>
  string(1) " "
  ["postalcode"]=>
  string(1) " "
  ["l"]=>
  string(1) " "
  ["c"]=>
  string(2) "CH"
}
$result = $adldap->users()->create($attributes);
// var_dump($result) return FALSE
```

And the new method on the first post (`var_dump($user->save()) return false`). But with the new method, we can't find the way to specify the `samaccountname` and the `userprincipalname`. We perform some search on the class but nothing to set these attributes.
Do you have some recommandation ?

**Comment by stevebauman** [comment]
Right now the methods `$user->enable() / $user->disable()` try to save the user after setting the `enable / disable` attribute, so create a user first, then call that method (though I just fixed this) in `dev-master`. Also the same goes for the `setPassword()` method. Try creating the user first, then call the `setPassword()` method and let me know if that works!

**Comment by kichetof** [comment]
Okay it's more understandable now :)
Unfortunately, our group policy require a password when we create a new user. There is a possibility to add it when we create from the class like the first version ?

**Comment by stevebauman** [comment]
Of course, all attributes are modifiable without their "setters", just modify the attribute directly:

    $user->cn = 'John Doe';
    $user->samAccountName = 'jdoe';
    $user->password = '12345';
    $user->dn = 'cn=John Doe,ou=Users,dc=corp,dc=acme,dc=org';
    $user->save();

Let me know if it works for you!

**Comment by kichetof** [comment]
Oh yeah so good!

But when I save --> error and I can't find anything on the logs.
Maybe an encoding problem ? Or maybe we have a problem with our new server and our certificate. We'll migrate them soon on production.

**Comment by stevebauman** [comment]
Try displaying errors using the `showErrors()` method on the Adldap connection:

    $adldap->getConnection->showErrors();

    $user = $adldap->users()->newInstance();
    
    // Create the user

**Comment by kichetof** [comment]
Yeah!!

`Warning</b>:  ldap_add(): Add: No such attribute in <b>/dev-web/AD/vendor/adldap2/adldap2/src/Connections/Ldap.php</b> on line <b>487</b>`

```
$adldap = new \Adldap\Adldap($config);
$adldap->getConnection()->showErrors();

$user = $adldap->users()->newInstance();

$user->cn = $attributes["displayname"];
$user->samAccountName = $attributes['samaccountname'];
$user->userprincipalname = $attributes['userprincipalname'];
$user->password = $attributes['password'];
$user->sn = $attributes['sn'];
$user->givenname = $attributes['givenname'];
$user->dn = $attributes['dinstinguishedName'];


if($user->save()){
   echo "ok";
}else{
   echo "bug";
}
```

**Comment by stevebauman** [comment]
Ok sounds good, but I believe it's because of the `$user->dn` attribute. This is fixed in the latest release coming up in a minute here.

**Comment by kichetof** [comment]
Fixes applied and same error `Warning:  ldap_add(): Add: No such attribute in <b>/dev-web/AD/vendor/adldap2/adldap2/src/Connections/Ldap.php</b> on line <b>487</b>`

I'll play with attributes to try to solve it!

**Comment by kichetof** [comment]
My colleague comes to examine the code and find a bug.

On `namespace Adldap\Connections;` function `public function add($dn, array $entry)` the `$dn` var is NULL.

We think that the problem comes from the AbstractModel.php on `public function create()`

This is a var_dump: _(as you can see that there have not dn defined)_

```
NULL // var_dump($dn) on Connections/Ldap.php line 483 function add
array(6) { //var_dump($entry) on Connections/Ldap.php line 484 function add
  ["objectclass"]=>
  array(4) {
    [0]=>
    string(3) "top"
    [1]=>
    string(6) "person"
    [2]=>
    string(20) "organizationalperson"
    [3]=>
    string(4) "user"
  }
  ["cn"]=>
  string(22) "Test1112233 TEST112233"
  ["samAccountName"]=>
  string(10) "testcf1308"
  ["userprincipalname"]=>
  string(27) "testcf1308@AD.DOMAIN.local"
  ["sn"]=>
  string(10) "TEST112233"
  ["givenname"]=>
  string(11) "test1112233"
}
````

**Comment by stevebauman** [comment]
No this isn't a bug, the DN string is just passed into the 'connection->add($dn, $attributes)` method separately. If you include the DN attribute in the attribute array, ldap throws a 'No such attribute' error.

**Comment by kichetof** [comment]
Strange!
By setting $dn in function add, we can create a user.
We continue to look up why it doesn't work! :)

**Comment by kichetof** [comment]
That works!!! :)

$user->dn // <-- doesn't work
$user->setDn() // <-- WORKS !!!!

**Comment by stevebauman** [comment]
Hmmm that's strange, going to investigate, I'm glad you've solved the issue!

I'm going to leave this issue open and I'll update when I've fixed the issue.

Thanks!

**Comment by stevebauman** [comment]
Are you able to show the snippet of code where you were setting the `$user->dn` attribute if possible?

**Comment by kichetof** [comment]
:) yeah big thanks to you!

we encountered a bug when we want to change password.
This is my worked code until `$user->setPassword`:

```
$user->cn = $attributes["displayname"];
        $user->samAccountName = $attributes['samaccountname'];
        $user->userprincipalname = $attributes['userprincipalname'];
        $user->sn = $attributes['sn'];
        $user->givenname = $attributes['givenname'];
        $user->setDn($attributes['dinstinguishedName']);

        if($user->save()){
            echo "ok";
        }else{
            echo "error";
        }

        $user = $adldap->search()->findByDn($attributes['dinstinguishedName']);
        $user->setPassword($attributes['password']);
```

And error:

```
<b>Warning</b>:  ldap_modify_batch(): Batch Modify: Server is unwilling to perform in <b>/dev-web/AD/vendor/adldap2/adldap2/src/Connections/Ldap.php</b> on line <b>559</b>


<b>Fatal error</b>:  Uncaught exception 'Adldap\Exceptions\AdldapException' with message 'Error 53: Server is unwilling to perform. Your password might not match the password policy.' in /dev-web/AD/vendor/adldap2/adldap2/src/Models/User.php:441
Stack trace:
#0 /dev-web/AD/includes/addUser.ajax.php(266): Adldap\Models\User->setPassword('spU9Hdp4')
#1 {main}
  thrown in <b>/dev-web/AD/vendor/adldap2/adldap2/src/Models/User.php</b> on line <b>441</b>
```

**Comment by stevebauman** [comment]
Hmmm... I'm not too sure to be honest. Can you try using:

    $ad->users()->changePassword('', $attributes['password']);

Let me know what happens, thanks!

**Comment by kichetof** [comment]
Unable to perform changePassword:

```
<b>Warning</b>:  ldap_modify_batch(): Batch Modify: Server is unwilling to perform in <b>/dev-web/AD/vendor/adldap2/adldap2/src/Connections/Ldap.php</b> on line <b>556</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'Adldap\Exceptions\AdldapException' with message 'Error: 00002077: SvcErr: DSID-03190E49, problem 5003 (WILL_NOT_PERFORM), data 0
' in /dev-web/AD/vendor/adldap2/adldap2/src/Models/User.php:497
Stack trace:
#0 /dev-web/AD/includes/addUser.ajax.php(275): Adldap\Models\User-&gt;changePassword('', '2vBVJzWE')
#1 {main}
  thrown in <b>/dev-web/AD/vendor/adldap2/adldap2/src/Models/User.php</b> on line <b>497</b><br />
```

My code:

```
        $user = $adldap->users()->newInstance();

        $user->cn = $attributes["displayname"];
        $user->samAccountName = $attributes['samaccountname'];
        $user->userprincipalname = $attributes['userprincipalname'];
        $user->sn = $attributes['sn'];
        $user->givenname = $attributes['givenname'];
        $user->setDn($attributes['dinstinguishedName']); // $attributes["dinstinguishedName"]        = "CN={$attributes["cn"]},OU=Users,".BASE_DN;

        if($user->save()){
            echo "ok";
        }else{
            echo "error";
        }

        $user = $adldap->search()->findByDn($attributes['dinstinguishedName']);
        $user->changePassword('', $attributes['password']);
```

**Comment by stevebauman** [comment]
Hmmm I'm not too sure to be honest. There's a possibility it could be your server, or Adldap. Due to my environment I can't play with changing passwords on my AD (don't have an SSL / TLS connection). However, @strebl would you have any suggestions for @kichetof? Are you able to change passwords with Adldap2 successfully?

**Comment by ianacid** [comment]
Hi Steve ! 
I'm the colleague of @kichetof, we're working on that project together.
First, big thanks for your help ! and you've done a wonderful job.
This morning ... in switzerland ... ;-), I 've implemented one of my personal function inside the @kichetof 's code. This function (used for another app) change the password in our AD over a PHP web page. It worked after the creation of the user by your class. So I don't think that our server is in cause.
Many thx !!!

**Comment by kichetof** [comment]
YEAH ! That works!

I'll edit this post to paste a cleaned snippet :)

**Comment by stevebauman** [comment]
@ianacid Ok so it's not you're server then, no problem.

@kichetof Awesome! So disabling the user first and setting the password solved this issue?

**Comment by stevebauman** [comment]
@kichetof Also for your comment:

> $user->cn = $attributes["displayname"]; doesn't affect CN field on AD ?!

The common name needs to be changed on the distinguished name as well as the entry itself I believe.

**Comment by kichetof** [comment]
Updated a little bit

```php
try {

        $config = new \Adldap\Connections\Configuration();

        $config->setAccountSuffix(ACCOUNT_SUFFIX);
        $config->setDomainControllers(unserialize(DOMAIN_CONTROLLERS));
        $config->setBaseDn(BASE_DN);
        $config->setAdminUsername(ADMIN_USERNAME);
        $config->setAdminPassword(ADMIN_PASSWORD);
        $config->setFollowReferrals(false);
        $config->setUseSSL(true);

        $adldap = new \Adldap\Adldap($config);
        $adldap->getConnection()->showErrors();

        $user = $adldap->users()->newInstance();

        $user->setDn($attributes['dinstinguishedName']);
        $user->setName($attributes['sn']);
        //$user->setCommonName($attributes["displayname"]); // BUG
        $user->setAccountName($attributes['samaccountname']);
        $user->setFirstName($attributes['givenname']);
        $user->setLastName($attributes['sn']);
        $user->setTitle($attributes['title']);
        $user->setDepartment($attributes['department']);
        $user->setTelephoneNumber($attributes['ipphone']);
        $user->setCompany($attributes['company']);
        $user->setEmail($attributes['mail']);

        $user->initials = $attributes['initials'];
        $user->physicaldeliveryofficename = $attributes['physicaldeliveryofficename'];
        $user->streetaddress = $attributes['streetaddress'];
        $user->postalcode = $attributes['postalcode'];
        $user->l = $attributes['l'];
        $user->c = $attributes['c'];
        $user->displayname = $attributes['displayname']; // works for display name instead of common name
        //$user->change_password = 1;

        if($user->save()){
            echo "OK";
            $user = $adldap->search()->findByDn($attributes['dinstinguishedName']);
            $user->setPassword($attributes['password']);
            $user->disable();
            var_dump($user);
        }else{
            echo "ERROR";
        }

    }
    catch (adLDAPException $e) {
        echo $e;
        exit();
    }
```

And every fields on AD have my values!!! That's awesome!! Thank a lot for all your great support!!!

Improved code:

Add the possiblity to set:

- User need to change password on first login
- Expiration date of the account
- Possibility to add a manager (DN required for this field; possibility to send a CN or a samaccountname)

One more time, THANK YOU! :)

**Comment by stevebauman** [comment]
That's great! Really glad to hear everything's resolved. No problem at all.

I'll add the remaining user attributes to the User model for easy setting / getting (`initials, physicaldeliveryofficename, streetaddress, postalcode, l, c, & display name`).

Also, to make the user change their password upon login, you need to use the `$user->setAccountControl($ac)` method. [More about this here.](https://github.com/Adldap2/Adldap2/blob/master/docs/models/user/ACCOUNT-CONTROL.md)

I'll also add the manager attribute as well.

**Comment by kichetof** [comment]
I'll read the doc to change the password :)

I'll be very happy to view all these modification when I'll be back from my holiday!!

Many thanks for all!

**Comment by stevebauman** [comment]
Sounds good! And no problem at all, thanks for all the information and for helping me improve Adldap2!
