### ISSUE TITLE
Adldap2 authentication always returns true - Yii2

### ISSUE THREAD

**Issue by WebDragonStudios** [Adldap2/Adldap2#381]
- Adldap2 Version: v7.0.*
- LDAP Type:  Active Directory
- PHP Version: 7.1.1

### Description:
I'm running into an issue when I try to authenticate users on my ldap server. I can successfully make a connection and and retrieve user data, but when trying to authenticate if a user's username and password are correct or not, it always returns true, even if the creds are wrong. Below is my code snippet (with the config array not showing of course):

### Steps To Reproduce:
    $ad->addProvider($config);

    try {
        // If a successful connection is made to your server, the provider will be returned.
        $provider = $ad->connect();

        //User below does return the correct information from the ldap server
        $user = $provider->search()->users()->find('quillin');

       try{
          $provider->auth()->attempt("wrongUsername","wrongPassword");
          die("WIN");
        }catch( Exception $e ){
          die("Exception " . $e);
        }

     }catch (\Adldap\Auth\BindException $e) {

       die( "There was an issue binding / connecting to the server. <br />" . $e);

    }

###Description Continued

No matter what I put in for the username and password fields, it always returns true and hits the die("WIN");

**Comment by stevebauman** [comment]
Hi @WebDragonStudios,

You'll actually use an `if` statement, not a `try / catch`.

The bind exception is only thrown on first bind / re-bind failures using your `admin` credentials in the configuration array you've supplied.

```php
try {
    // If a successful connection is made to your server, the provider will be returned.
    $provider = $ad->connect();

    //User below does return the correct information from the ldap server
    $user = $provider->search()->users()->find('quillin');

   try {
      if ($provider->auth()->attempt("wrongUsername","wrongPassword")) {
        // The users credentials are correct.
      }

      // The users credentials are incorrect.
      die("WIN");
    } catch( Exception $e ) {
      // Failed connecting to your server.

      die("Exception " . $e);
    }

 } catch (\Adldap\Auth\BindException $e) {

   die( "There was an issue binding / connecting to the server. <br />" . $e);

}
```

**Comment by WebDragonStudios** [comment]
Thank you for the heads up. I tried using the if statement. The following
code now always returns false no matter if the user and pass and right or
wrong:

*            if ($provider->auth()->attempt($user, $pass, $bindAsUser =
true)) {*
*                die("WIN .User: " . $user . " Pass: " . $pass);*
*            }else{*
*                die("lose. User: " . $user . " Pass: " . $pass);*
*            }*

I'm still able to get a response before this code by doing:
*            $user = $provider->search()->users()->find('quillin');*
*            die(print_r($user));*

**Comment by stevebauman** [comment]
Can you post your configuration array? This is usually due to the `account_prefix` / `account_suffix` option.

**Comment by WebDragonStudios** [comment]
Thank you again for replying :) I actually just figured it out. It looks
like $username was actually looking for userprincipalname from the ldap
server. I was able to look the user up by that, validate with the password
and was able to authenticate. Thanks again for your help.

**Comment by stevebauman** [comment]
@WebDragonStudios Great! Glad you've resolved your issue :).
