### ISSUE TITLE
Find password expiration Date or Delay

### ISSUE THREAD

**Issue by DisasteR** [Adldap2/Adldap2#385]
- Adldap2 Version: 7.0.9
- LDAP Type: Active Directory
- PHP Version: 5.6

### Description:

Hi,

It is possible to find password expiration date or delay ?
getMaxPasswordAge return always NULL.

```
$user = $provider->search()->find('login');
$user->getMaxPasswordAge();
```

Best Regards,

**Comment by stevebauman** [comment]
Hi @DisasteR,

You'll actually retrieve the `maxPwdAge` attribute from your root domain record using:

```php
$baseDn = 'dc=corp,dc=acme,dc=org';

$entry = $provider->search()->findByDn($baseDn);

$age = $entry->getMaxPasswordAge();

$days = abs($age) / 10000000 / 60 / 60 / 24;

// The amount of days until passwords expire.
echo $days;
```
