### ISSUE TITLE
Adldap2 - Multipe domains, same forest

### ISSUE THREAD

**Issue by aabuasad** [Adldap2/Adldap2#386]
- Adldap2 Version: dev-master
- LDAP Type: Active Directory
- PHP Version: 7.1.1
- Laravel version: 5.4

### Description:
Hello and thanks for this amazing package, and the up to the point walk through, i have managed to get logins working with LDAP, but my issue is that i have users from 2 domains that would use my website, and both domains are under the same forest. on the login form users are requested to provide their email and password. 

I have created two connections under adldap.php, named them alpha and beta, now under adldap_auth, how can i have it check on both connections? or better have it check connection alpha if the email ends with alpha.com, and beta if the email ends with beta.com?

**Comment by stevebauman** [comment]
Hi @aabuasad, can you move this to the [Adldap2-Laravel](https://github.com/Adldap2/Adldap2-Laravel) repository please?

Thanks!
