### ISSUE TITLE
Find user by username just returns the first found

### ISSUE THREAD

**Issue by samwilson** [Adldap2/Adldap2#39]
I know this was discussed a bit in #6, but I thought I'd bring it up again because it's causing me a headache today :)

On the face of things, the following should result in getting the details of the user who's logging in:

```php
if ($adldap->authenticate($username, $password)) {
    $ldapUser = $adldap->users()->find($username);
}
```

but because find() uses ANR, this actually results in an LDAP query [something like](http://social.technet.microsoft.com/wiki/contents/articles/22653.active-directory-ambiguous-name-resolution.aspx#How_ANR_Works):

    (|(displayName=smith*)(givenName=smith*)(legacyExchangeDN=smith)
    (physicalDeliveryOfficeName=smith*)(proxyAddresses=smith*)(Name=smith*)
    (sAMAccountName=smith*)(sn=smith*))

Note the trailing wildcard on `sAMAccountName`! :(

So the PHP above can acually result in `$ldapUser` referring to a different user to that which has been authenticated.

I know it's pretty easy to get around this by doing the double-equals [work around thing](http://social.technet.microsoft.com/wiki/contents/articles/22653.active-directory-ambiguous-name-resolution.aspx#Details):

```php
    $ldapUser = $adldap->users()->find('='.$username);
```

but it just seems that the first method is more intuitive and likely to be used by people unfamiliar with Adldap.

Am I missing something obvious?

**Comment by stevebauman** [comment]
Agreed, probably isn't a good idea to rely on ANR for a find method. Fixed!

**Comment by stevebauman** [comment]
Shoot, I remember why I used ANR inside the search `find()` method. This is due to not knowing what type of object we're querying for, since a computer or group won't have the `sAMAccountName` attribute. I'll change the find method for the users class only.

**Comment by samwilson** [comment]
Thanks for fixing this so quickly! :) You're great.

>  This is due to not knowing what type of object we're querying for

Don't forget you can always prepend an ANR search value with `=` to make it do exact matches (still might fail us in this situation, but nice to know for the times when looking for a computer name etc.).
