### ISSUE TITLE
limitation_filter ignored after update to Laravel 5.4 and Adldap2 3.0.4

### ISSUE THREAD

**Issue by gd-jroberts** [Adldap2/Adldap2#390]
- Adldap2 Version: 3.0.4
- LDAP Type: ActiveDirectory
- PHP Version: 7.0.12

### Description:
`php artisan adldap:import` correctly applies limitation_filter in version 2.1.3. I upgraded Laravel from 5.3 to 5.4, and adldap2-laravel from 2.1.3 to 3.0.4 and the limitation_filter no longer was applied. I reverted only adladap2-laravel to 2.1.3 and the limitation_filter works again.

#### adldap2 3.0.4
vagrant@homestead:~/Code/gdcentral$ php artisan adldap:import
Found 361 user(s).

#### adldap2 2.1.3
vagrant@homestead:~/Code/gdcentral$ php artisan adldap:import
Found 25 user(s).

### Steps To Reproduce:
Using Laravel 5.4 and Adldap2 3.0.4, run `php artisan adldap:import` with both a base_dn and a limitation_filter.

I'm using the following:
'limitation_filter' => env('ADLDAP_LIMITATION_FILTER', '(|(samaccountname=xxxx)(&(!(samaccountname=xxxx))(objectCategory=person)(department=*)(samaccountname=*)(title=*)))'),

**Comment by stevebauman** [comment]
Hi @gd-jroberts,

This is mentioned in the upgrade guide:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/upgrading.md#limitation-filter

You must utilize scopes instead of the `limitation_filter` option.

**Comment by gd-jroberts** [comment]
I've gotten 3.0.4 to bind and log me in. `php adldap:import` will return several hundred AD users, however, when I apply the following scope it always returns zero AD users. I've tried to follow the example. Can you please give any additional advice?

My basedn is ADLDAP_BASEDN='ou=GlynnDevins,dc=GlynnDevins,dc=com'

```
<?php
namespace App\Scopes;

use Adldap\Query\Builder;
use Adldap\Laravel\Scopes\ScopeInterface;

class GdTechnicalScope implements ScopeInterface
{
    /**
    * Apply the scope to a given LDAP query builder.
    *
    * @param Builder $query
    *
    * @return void
    */
    public function apply(Builder $query)
    {
        // The distinguished name of our LDAP group.
        $gd = 'ou=Users,ou=Technical,ou=Departments,ou=GlynnDevins,dc=GlynnDevins,dc=com';

        $query->columns = [
            'cn',
            'mail',
            'samaccountname',
            'title',
            'department',
            'msexchshadowtelephonenumber',
            'telephonenumber',
            'mobile',
            'thumbnailphoto',
            'userprincipalname'
        ];

       $query->whereMemberOf($gd);
    }
}
```

**Comment by stevebauman** [comment]
Hi @gd-jroberts, I'll definitely help you get this sorted.

You're utilizing the `whereMemberof()` query builder method which checks the users `memberof` attribute. However, you're not including this attribute when your setting the query columns:

```php
$query->columns = [
    'cn',
    'mail',
    'samaccountname',
    'title',
    'department',
    'msexchshadowtelephonenumber',
    'telephonenumber',
    'mobile',
    'thumbnailphoto',
    'userprincipalname'
];
```

Should be:

```php
$query->columns = [
    'cn',
    'mail',
    'samaccountname',
    'title',
    'department',
    'msexchshadowtelephonenumber',
    'telephonenumber',
    'mobile',
    'thumbnailphoto',
    'userprincipalname',
    'memberof', // Added 'memberof' here.
];
```

Are you able to make the  above modification and see if this resolves your issue?

**Comment by gd-jroberts** [comment]
Thanks for the quick response. I've tried running the command both with 'memberof' added and with the columns removed from the scope (I was limiting columns for speed), both returned  

```Found 0 user(s).```

**Comment by gd-jroberts** [comment]
Not sure if it is pertinent, but when I execute this I get the 178 users I expect:

```
php artisan adldap:import --filter '(&(!(samaccountname=conference))(!(samaccountname=db*))(!(samaccountname=*admin))(objectCategory=person)(department=*)(samaccountname=*)(title=*)))'
```

**Comment by stevebauman** [comment]
Oh hang on, this is actually an organizational unit, not a group.

You'll need to use the `in()` method:

```php
$query->in($gd);
```

**Comment by gd-jroberts** [comment]
That did it. Thanks so much!

**Comment by stevebauman** [comment]
Awesome, no problem at all! :)
