### ISSUE TITLE
Catch errors ( password expired )

### ISSUE THREAD

**Issue by arantxio** [Adldap2/Adldap2#391]
- Adldap2 Version: Latest
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:
How can I catch all kind of errors.
So I can map the error codes.

Because one of the users tried to login with a expired password, but he only gets a message wrong credentials because I don't catch the different error codes.

These are the only things I am catching now:

} catch (\Adldap\Exceptions\Auth\UsernameRequiredException $e) {
} catch (\Adldap\Exceptions\Auth\PasswordRequiredException $e) {
}

### Steps To Reproduce:
Try to login with a account that has been expired

**Comment by stevebauman** [comment]
Hi @arantxio,

You should be able to get the last error from LDAP using:

```php
$provider->getConnection()->getExtendedError();

// As well as:

$provider->getConnection()->getExtendedErrorCode();
```

Then you can check the code and see what type of error it is. This is done in the User model already:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/User.php#L987-L1005

**Comment by stevebauman** [comment]
According to this PHP pull-request, there are some useful error codes detailed there:

https://bugs.php.net/bug.php?id=47222

> 525 - user not found
52e - invalid credentials
530 - not permitted to logon at this time
531 - not permitted to logon from this computer
532 - password expired
533 - account disabled
701 - account expired
773 - user must reset password
775 - account locked

**Comment by arantxio** [comment]
So i've just tested it.

$provider->getConnection()->getExtendedError(); works for me.

$provider->getConnection()->getExtendedErrorCode(); brings a big error code example: 80090308.

The first one returns this:

80090308: LdapErr: DSID-0C0903D9, comment: AcceptSecurityContext error, data 532, v2580.

Now I can't do anything with a full string. so I preg match it like this:

$errorcode = $provider->getConnection()->getExtendedError();
if (isset($errorcode)) {
	if (preg_match_all('/\bdata\b\s(\d+)/', $errorcode, $matches, PREG_SET_ORDER, 0)) {
		$errorcode = $matches[0][1];
	}
}

now $errorcode brings out the right error.

now the full string only brings out 532 which means my password has expired.

Thanks very much for your reply!

**Comment by stevebauman** [comment]
Thanks for following up @arantxio!

Glad I was able to help :) Let me know if you encounter any further problems or issues!
