### ISSUE TITLE
LDAP query result is always converted to an object of objects

### ISSUE THREAD

**Issue by victorleal** [Adldap2/Adldap2#394]
- Adldap2 Version: 7.0.12
- LDAP Type: Both
- PHP Version: 7.0.15

### Description:
I don't know yet if this is a Adldap or Laravel issue. I'm using the following code to do some search on OpenLDAP and Active Directory (this search will depend on some decisions, so we enabled the search on both directories).

```
    $query = 'John';

    try {
        $search = $provider->search()
            ->whereStartsWith('departmentNumber', '0.0.0')
            ->whereContains('cn', $query);

        $users = $search
            ->select([ 'cn', 'departmentNumber' ])
            ->get()
            ->toArray();

    } catch (\Adldap\Auth\BindException $e) {
        die("Can't connect / bind to the LDAP server! Error: $e->getMessage()");
    }

    return response()->json([
        'users' => $users
    ]);
```

When I have just some few results (4, for example) the Chrome console shows me an array of objects, as expected. But, when we go high (45 results, for example) I got an **object of objects**.

Is this the expected behavior? Should I write a JS code able to handle both types of responses?

### Steps To Reproduce:
Run the code above being called by an AJAX request (I'm using it through Select2 component).

**Comment by stevebauman** [comment]
Hi @victorleal,

The response should be the same no matter the result size.

Are you able to screenshot what you're seeing in your Chrome console for both cases?

**Comment by victorleal** [comment]
Sure, here it is!

![array_object](https://cloud.githubusercontent.com/assets/2012559/25385300/ff143b00-2999-11e7-8919-517eb25e8ddb.png)

**Comment by stevebauman** [comment]
Hmmm.. I don't get this issue? 

```json
{"users":{"260":{"objectclass":["top","person","organizationalPerson","user"],"0":"objectclass","
```

```json
{"users":{"6":{"objectclass":["top","person","organizationalPerson","user"],"0":"objectclass","
```

No matter the size of the result set, I'm always returned the same json format.

Does this type of issue occur with both ActiveDirectory and OpenLDAP?

**Comment by victorleal** [comment]
Yes, with both. It really is a strange behavior.

But you're getting a object of objects. Shouldn't it be an array?

**Comment by stevebauman** [comment]
I'm getting a JSON result set, it's the same with 9 results as it is with over 300:

![9 results](https://cloud.githubusercontent.com/assets/6421846/25501600/54ecff08-2b61-11e7-9182-229a50228036.PNG)
![over 300 results](https://cloud.githubusercontent.com/assets/6421846/25501602/58cd7ba2-2b61-11e7-8e6a-70332581644e.PNG)

**Comment by victorleal** [comment]
Nice!

I think this is maybe a Laravel problem. Can you tell me which version of Laravel you're running?

**Comment by stevebauman** [comment]
I'm testing through Laravel 5.3.30, you?

**Comment by victorleal** [comment]
5.4.16 :thinking: 

Maybe a Laravel problem, then? I think I should open an issue there, but maybe they will say that is a problem of the library.

**Comment by stevebauman** [comment]
Let me test in Laravel 5.4 and then we can debug further.

**Comment by stevebauman** [comment]
I get this on Laravel 5.4 as well... but not on 5.3... Going to see if this is intended somehow.

**Comment by victorleal** [comment]
@stevebauman Can you give an example of your code? I would like to see how you're doing your query to AD and how you build the response ( `return response()->json(['result' => $result])` )

**Comment by stevebauman** [comment]
```php
Route::get('/users', function () {
    return response()->json([
        'users' => Adldap::search()->users()->limit(10)->select(['cn'])->get()
    ]);
});
```

Then in google chrome console I type:

```bash
axios.get('/users');
```

**Comment by victorleal** [comment]
@stevebauman a workaround was to create a JSON object with the number of entries to allow the JS code to parse it:

``` PHP
$users = Adldap::search()->users()->limit(10)->select(['cn'])->get();

Route::get('/users', function () {
    return response()->json([
        'users' => $users,
        'numberOfUsers' => count($users)
    ]);
});
```

Then, in Javascript we can parse the data (doesn't matter if is an object or an array):

``` Javascript
for (var i = 0, len = data.numberOfUsers; i < len; i++) {
    // do whatever you want here      
    // accessing object: data.users[i]
    // accessing array: data.users[i]
}
```

**Comment by joeythai** [comment]
Is it possible to do an application using LDAP for begginers or could you help me, I'm starting with laravel and I need to do a login screen with LDAP

**Comment by victorleal** [comment]
@joeythai What do you really need? If you're looking for using LDAP with Laravel, you can use this excellent library. Just look on the main page (https://github.com/Adldap2/Adldap2) and see the instructions to use it. It's easy.

If you still need some help, I think the best way to do it is going to StackOverflow and making a question there. Here we just open issues related with the library.
