### ISSUE TITLE
getGroups won't return correct commonName

### ISSUE THREAD

**Issue by KarimGeiger** [Adldap2/Adldap2#395]
- Adldap2 Version: 7.0.12
- LDAP Type: AD
- PHP Version: 7.1.3

### Description:
Hi, since the update from version 7.0.11 to version 7.0.12 the following code snippet returns just empty strings instead of the common name, which it did before. This is pretty critical to us, so we're currently stuck with version 7.0.11.

The change introducing the bug was: https://github.com/Adldap2/Adldap2/commit/2ec082b453ba5b4931ebf703de228786f452628a

### Steps To Reproduce:
```php
foreach ($user->getGroups() as $group) {
    echo $group->getCommonName() . "\n";
}
```

Expected output:
```
bamboo-users
bamboo-admin
jira-users
jira-developers
Domain Users
```

Actual output:
```




Domain Users
```

Note that it prints the new line, so the groups do exist, `getCommonName()` just returns an empty string.

I'm not sure if this helps you to debug the problem entirely. If you need any additional information, feel free to ask.

**Comment by stevebauman** [comment]
Going to check into this now, thanks for the report @KarimGeiger!

**Comment by stevebauman** [comment]
Confirmed bug, you can get around this right now by inserting `cn` in the fields array:

```php
foreach ($user->getGroups(['cn']) as $group) {
    echo $group->getCommonName() . "\n";
}
```

**Comment by stevebauman** [comment]
Hi @KarimGeiger, please update to `v7.0.13`. This has been fixed.

This was an oversight on my part, apologies for the inconvenience.

**Comment by KarimGeiger** [comment]
Hi @stevebauman, thank you for the quick fix! Will test the changes tomorrow.
