### ISSUE TITLE
How to access a user's mobile phone?

### ISSUE THREAD

**Issue by keithslater** [Adldap2/Adldap2#399]
- Adldap2 Version: 7.0.14
- LDAP Type: Active Directory
- PHP Version: 5.6

### Description:

Is there a way to access the user's mobile phone number? On the same lines, how can I just access the raw result when doing a search?

**Comment by stevebauman** [comment]
Hi @keithslater,

I believe the attribute is `mobile` that you'd be looking to retrieve from each user model:

```php
$user = $provider->search()->users()->first();

$phone = $user->getFirstAttribute('mobile');

var_dump($phone);
```

To answer your other question, you can retrieve raw search results from your LDAP query by calling the `raw()` method:

```php
$users = $provider->search()->users()->raw()->get();

var_dump($users); // Returns raw LDAP result array
```

Or, you can dump the users attributes to see what their phone is contained in by calling the `getAttributes()` method on each user model:

```php
$user = $provider->search()->users()->first();

var_dump($user->getAttributes());
```

**Comment by keithslater** [comment]
That worked, thanks for clearing that up for me.

**Comment by stevebauman** [comment]
No problem! :)
