### ISSUE TITLE
Commit History: Unrecognized User

### ISSUE THREAD

**Issue by strebl** [adLDAP2/adLDAP2#4]
Wow, really nice work so far! Hope I'll have some free time soon to help you!

While I was reading thought the commits I saw a minor issue. 
If I visit the commit history I can't click on your name @stevebauman. Did you add your `@outlook` email address to your GitHub account?

Keep up your good work!
Regards

**Comment by stevebauman** [comment]
Thanks! And good catch! Just fixed, you were right, my outlook email was different than profile email. Changed, should be all set now.


-- Steve
