### ISSUE TITLE
sortBy not working with paginate

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#40]
I use your fantastic Adldap library since a lot of year and I'm really a fan ! Thanks for your great job ! Now I update my code with this new version. I find a strange behaviour with paginate. It seems that sortyBy dosen't work when I use paginate after. Have you an workaround for that or could you apply a fix for this method ? In my test, I will sort my result by DN.

Thanks for your help

**Comment by stevebauman** [comment]
I'll take a look at this shortly, thanks for creating an issue for this

**Comment by ciadch** [comment]
Hi angain,

It seems that Paginator continues not sorting elements correctly. In each array of page, it's ok but what clould be really interesting is to have a sort in the entire array of results. With that, when you navigate in your differents pages, you keep the sort

Thanks
