### ISSUE TITLE
GUID syncing and authentication 

### ISSUE THREAD

**Issue by cbloss** [Adldap2/Adldap2#400]
- Adldap2 Version: 7.0.15
- LDAP Type: Active
- PHP Version: 7.1

### Description:
This is more like a two part question: 

1.) Like some other people have said, emails and samaccountname's change (ie. people getting married), but the guid stays the same for the life of the account. I'd like to sync the guid when a user gets created. I know there's a way to create an event listener with Eloquent, but I wasn't sure if there is a way to do it via the sync_attributes in the adldap_auth. I am able to retrieve it by doing...

`'sync_attributes' => [

        'first_name'  => 'givenname',
        'last_name'   => 'sn',
        'email'       => 'mail',
        'guid'        => 'objectguid'

    ],`

But the objectguid is the encrypted string and not the hex. 

2.) Is there a way to have like a fallback attribute? So if the email isn't found, it would fallback and try to find the user by GUID and then re-sync the email. For example, if sallyj@domain.com was already in the system and then her email gets updated to sallys@domain.com, it would update her sallyj@ account because the GUID was in there. Does that make any sense?? I was wondering if that's what the select_attributes in the adldap_auth is for.

Thanks!

**Comment by cbloss** [comment]
I think I'm going to go with the event listener for the objectguid. 

I'm still not exactly sure how make the package update a User instead of creating one if the guid is in the database. Any clue?

**Comment by stevebauman** [comment]
Hi @cbloss, unfortunately this isn't built into the auth driver. If username / email changes, this will create a new account in your local database.

This is difficult to do, since when a username changes, we can't ask active directory what the users previous username was. We would essentially have to login users via GUID for this functionality, or force all users of this package to add a GUID column to their database and find out if a local database record exists with their GUID.

This might be something I add in the future, but will certainly cause more confusion and installation issues with people not aware of how it works.

Though, you can easily write your own auth driver with this functionality and simply use the `Adldap` facade to access your LDAP directory and create and sync user records yourself.

Here's a quick pseudo login script with this type of functionality:

```php
public function login(Request $request)
{
    $ldap = Adldap::search()->users()->whereMail($request->email)->first();

    if ($ldap) {
        // User located.
        $user = User::firstOrNew(['objectguid' => $ldap->getConvertedGuid()]);

        // Sync user attributes.
        $user->name = $ldap->getCommonName();
        $user->email = $ldap->getEmail();

        $user->save();

        Auth::login($user);

        // Logged in!
        return redirect('/');
    }
    // User not found, return validation error.
}
```

**Comment by stevebauman** [comment]
Also, for your first question on syncing GUID's, you'll need to use an attribute handler and set the users local `objectguid` attribute using the method `$ldapUser->getConvertedGuid()`:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/syncing.md#attribute-handlers

```php
namespace App\Handlers;

use App\User as EloquentUser;
use Adldap\Models\User as LdapUser;

class LdapAttributeHandler
{
    /**
     * Synchronizes ldap attributes to the specified model.
     *
     * @param LdapUser     $ldapUser
     * @param EloquentUser $eloquentUser
     *
     * @return void
     */
    public function handle(LdapUser $ldapUser, EloquentUser $eloquentUser)
    {
        $eloquentUser->name = $ldapUser->getCommonName();
        $eloquentUser->objectguid = $ldapUser->getConvertedGuid(); // Here
    }
}
```

**Comment by cbloss** [comment]
Thank you for your help on this! I was reading about the Attribute Handler right about the time you responded. How I missed this in the documentation is beyond me. So thank you for that!

With regards to the overriding login, this saved me BIG time. Thank you for that pseudo code. I was able to get in and change it. I wasn't even sure where to begin and I thought the package was using different way to authenticate. I was wrong and happy to be so. :) Thank you so much!!!

**Comment by stevebauman** [comment]
No problem at all! I'm glad I can help :), if you encounter anything else just create another issue.

**Comment by SandeepAgrahari** [comment]
Hi @stevebauman, I wanna log in system with objectguid only. means the user has to enter only objectguid. it will be authenticated and successfully logged in.
Please help me to achieve this

**Comment by stevebauman** [comment]
Hi @SandeepAgrahari,

You will have to customize several things in your application to do this, such as:

- The `users` database migration (remove the `email` column)
- The `login.blade.php` file (rename the `email` input field to `objectguid`)
- The `LoginController.php` (modify the `credentials` method to return an array containing the `objectguid` key and the value of the `objectguid` submitted in the request)
- The user resolver callback in LdapRecord-Laravel's `DatabaseUserProvider`:

```php
// app/Providers/AuthServiceProvider.php

// ...
use LdapRecord\Models\ActiveDirectory\User;

class AuthServiceProvider extends ServiceProvider
{
    // ...

    public function boot()
    {
        $this->registerPolicies();

        Auth::getProvider()->resolveUsersUsing(function ($credentials) {
            return User::findByGuid($credentials['objectguid']);
        });
    }
}
```

This should definitely get you started, but you may need further modifications. 👍

**Comment by SandeepAgrahari** [comment]
Hi,

Please help mentor sync ldap user password with local database.

**Comment by stevebauman** [comment]
Hi @SandeepAgrahari, you've asked the same question on multiple issues. I've given you examples on how to implement what you asked for. You will have to do the rest.
