### ISSUE TITLE
Attributes not in schema

### ISSUE THREAD

**Issue by dododedodonl** [Adldap2/Adldap2#403]
- Adldap2 Version: 7.0.15
- LDAP Type: OpenLdap
- PHP Version: 7.0

### Description:
In the query builder, some attributes are hardcoded. The wanted behaviour would be to get them from the schema, so these functions work with openldap as well.

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L940
https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L950
https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L962

**Comment by stevebauman** [comment]
Thanks @dododedodonl, do you know these attributes on OpenLDAP that I can utilize on the Schema object?

**Comment by dododedodonl** [comment]
The disabled attribute is `pwdAccountLockedTime` but the Password Policy Overlay has to installed for this attribute to be available. If the attribute is present, the account is locked.
 The memberOf attribute is just `memberOf`.

**Comment by stevebauman** [comment]
Hi @dododedodonl,

Can you specify these attributes again if possible? The master branch builder has been changed since and I'm not sure which attributes need to reside in the schema for OpenLDAP support.

Thanks!
