### ISSUE TITLE
Auth not working because of object id conversion

### ISSUE THREAD

**Issue by dododedodonl** [Adldap2/Adldap2#404]
- Adldap2 Version: 7.0.15
- LDAP Type: OpenLdap (with laravel)
- PHP Version: 7.0

### Description:
The authentication does not work out of the box with openldap. This is because openldap does not by default have an objectSid that has to be converted from binary to string. This is done by default in [the Model.php file](https://github.com/Adldap2/Adldap2/blob/master/src/Models/Model.php#L672). Making this conversion optional via the schema would be preferred.

**Comment by stevebauman** [comment]
Thanks for the report @dododedodonl! I'll have this fixed.

**Comment by stevebauman** [comment]
Fixed: 

- https://github.com/Adldap2/Adldap2/commit/de401055abf1d4311f087ac1bae2ed0048fcdb75
- https://github.com/Adldap2/Adldap2/commit/d89f105f0335fd77b48f467449aa559c4e9169af
