### ISSUE TITLE
Search and not starts with

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#41]
Hi again,

It could be really interesting to have the possibility to add a * (means everything after) in where clause.Or maybe to have a method to call like whereNotStartsWith

For exemple : 
I need to exclude all user who start with "test" so I will use where('samaccountname', '!', 'test*') if it's possible. Now it dosen't work :-( 

Maybe you have a workaround for that ? 

Thanks

**Comment by stevebauman** [comment]
You're right, I completely forgot about this scenario? I'll implement this shortly.
