### ISSUE TITLE
Missing config/adldap.php

### ISSUE THREAD

**Issue by andrecastillo** [Adldap2/Adldap2#411]
- Adldap2 Version: #.#
- LDAP Type: 
- PHP Version: #.#

### Description:
After running through the installation steps, I go into my config/adldap_auth.php file, and the comments say that I need to specify my connection sin the config/adldap.php config file. But that file doesn't exist. I've searched for references to the constants that are in there like 'ADLDAP_CONNECTION' and don't find them in any place where I can set all the necessary connection settings.

**Comment by stevebauman** [comment]
How did you publish the configuration files?

If you used the command option `--provider` and specified the `Adldap\Laravel\AdldapAuthServiceProvider` you will only receive the `config/adldap_auth.php` file.

You must also run this for the main service provider: `Adldap\Laravel\AdldapServiceProvider`.

If you ran just `php artisan vendor:publish` and don't receive the `config/adldap.php` file, then you haven't added the `AdldapServiceProvider` to your `config/app.php` file.

**Comment by andrecastillo** [comment]
I figured out the problem. My apologies. I let my IDE tab fill some stuff. So when i was adding the service provider in my config/app.php, I filled it with "AdldapAuthServiceProvider" instead of "AdldapServiceProvider". I added the correct one and now it's there.

**Comment by stevebauman** [comment]
Great, thanks for following up @andrecastillo! Appreciate it.
