### ISSUE TITLE
How to enable a computer?

### ISSUE THREAD

**Issue by wranger** [Adldap2/Adldap2#412]
- Adldap2 Version: 7.0.15
- LDAP Type: AD 2012
- PHP Version: 5.6.30

### Description:
How could I enable a computer object?

When I add a computer to our AD it is disabled by default (UserAccountControl = 546) - When the object is enabled (manually) this value will change to 544.

Is there a method for a computer object like for a user object

I tried:

```php
$pc = $this->pro_adint->make()->computer($attr);
$pc->setUserAccountControl(544); <- error

$pc->setComputerAccountControl(544) <- not implemented
```
---------------
Anyway, what is about `$object->setAccountControl(value);`?

**Comment by stevebauman** [comment]
Hi @wranger, this actually slipped my mind that the `userAccountControl` attribute is available on computer accounts as well... I'll need to implement this in a trait, thanks!

However, as a workaround, what you can do now is:

```php
$pc = $this->pro_adint->make()->computer($attr);

$ac = new \Adldap\Objects\AccountControl();

$ac->accountIsDisabled()
    ->accountIsForWorkstation();

$pc->userAccountControl = (int) $ac;

$pc->save();
```

Can you give the above code a shot and see if it works for you?

In the domain I'm working with, disabled computer accounts actually contain the value `4098`. This is because it contains the rules `ACCOUNTDISABLE` & `WORKSTATION_TRUST_ACCOUNT`.

You can see the values here:

https://support.microsoft.com/en-us/help/305144/how-to-use-the-useraccountcontrol-flags-to-manipulate-user-account-properties

**Comment by wranger** [comment]
Ok, I don't know why the value of 546 was set by default ? Most workstations have set a value of Workstation/server: 0x1000 (4096)

------------------

That dosen't work for me, I don't know if I need php 7 for real type casting.

echo (int) $ac; returns 1 and I get a "Base->error(500,'ldap_add(): Add: Server is unwilling to perform')"

------------

Bu it works if I set it manually to 4096:

$pc->userAccountControl = 4096;

--------------

Does anybody know if I have to set the $ in the samaccountname of a computer object?

**Comment by stevebauman** [comment]
> Ok, I don't know why the value of 546 was set by default ? Most workstations have set a value of Workstation/server: 0x1000 (4096)

Yea that's strange. It could be something in your AD setting this as the default.

---

> That dosen't work for me, I don't know if I need php 7 for real type casting.
> echo (int) $ac; returns 1 and I get a "Base->error(500,'ldap_add(): Add: Server is unwilling to perform')"

Yup sorry about that, was a typo (fixed above). You can use `getValue()` or `__toString()` or `__toInt()` to get the value of the account control object.

---

> Bu it works if I set it manually to 4096:
>
> $pc->userAccountControl = 4096;

That's great that it works for you, I'll be patching this in and will leave this issue open until it's been implemented.

---

> Does anybody know if I have to set the $ in the samaccountname of a computer object?

I'm actually not sure about this. I would try both ways and see what the outcome is in AD. I've actually never created computer objects manually through LDAP.

**Comment by wranger** [comment]
> Does anybody know if I have to set the $ in the samaccountname of a computer object?
> 
> I'm actually not sure about this. I would try both ways and see what the outcome is in AD. I've actually never created computer objects manually through LDAP.

"It is the sAMAccountName values of the computer objects that must be unique in the domain. When you create a computer object in ADUC, the first 15 characters of the Common Name (the value of the cn attribute) becomes the NetBIOS name, and this name plus a trailing "$" character becomes the sAMAccountName. The Common Name need only be unique in the OU.

However, AD actually enforces a maximum length for the sAMAccountName attribute of 20 (because computer objects have class user). You can modify the sAMAccountName attribute and assign a value up to 20 characters (although I would retain the trailing "$"). You can use ADSI Edit, the Attribute Editor in Windows Server 2008 ADUC, a script, or a command line utility to do this. I have done this myself as a test, assigning a value that is 20 characters long. However, I have not investigated all of the consequences."

https://social.technet.microsoft.com/Forums/de-DE/f2afb2ce-74fb-4434-932b-6b71c3654a98/ad-computer-names-over-15-characters?forum=winserverDS
