### ISSUE TITLE
Group ?

### ISSUE THREAD

**Issue by Fcases** [Adldap2/Adldap2#414]
- Adldap2 Version: *
- LDAP Type: Active directory
- PHP Version: *

### Description:
Can we filter access if user x belongs to group B ?

### Steps To Reproduce:
NA

**Comment by stevebauman** [comment]
Hi @Fcases, I'm not sure what you're referring to.

Is this a question about Adldap2-Laravel?

If so, you'll need to utilize scopes or rules:

**Scopes**:
https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/scopes.md

**Rules**:
https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/rules.md
