### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by joeythai** [Adldap2/Adldap2#415]
- Adldap2 Version: #.#
- LDAP Type: 
- PHP Version: #.#

### Description:
My code ins't running, appear a message that says "Invalid Credentials", what I'm doing worng ? I don't how to fix thats problem. 

### Steps To Reproduce:

class UserController.php

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Adldap;

class UserController extends Controller
{
    //
    /**
    * @var Adldap
    */
    protected $adldap;

    /**
    * Constructor.
    *
    * @param AdlInterface $adldap
    */


    /**
    * Displays the all LDAP users.
    *
    * @return \Illuminate\View\View
    */

    public function index(){
         

        $ad = new \Adldap\Adldap();

        $config = [

            'account_suffix' => '@example.com',
            'domain_controllers' => ['ldap.forumsys.com','ldap.forumsys.com'],
            'base_dn' => 'cn=read-only-admin,dc=example,dc=com,dc=example,dc=com',
            'admin_username' => 'cn=read-only-admin,dc=example,dc=com',
            'admin_password' => 'password',
        ];

        $ad->addProvider($config);

        try{
            $provider = $ad->connect();

            $results = $provider->search()->where('ou', '=', 'riemann')->get();
            $user = $provider->search()->find('gauss');

            $user = $provider->make()->user(['ou' => 'riemann',
                                             'title' => 'Accountant',
                                            'description' => 'User Accountant',
                ]);

            $user->cn = 'read-only-admin';

            if($user->save()){

            }

        }catch(\Adldap\Auth\BindException $e){
            return 'Erro '. $e->getMessage();
        }

    }


}
```

**Comment by stevebauman** [comment]
Hi @joeythai,

Your config appears to be incorrect. It seems you're using OpenLDAP (correct me if I'm wrong)?

It should be:

```php
$config = [
            'domain_controllers' => ['ldap.forumsys.com'],
            'base_dn' => 'dc=example,dc=com,dc=example,dc=com',
            'admin_username' => 'cn=read-only-admin,dc=example,dc=com',
            'admin_password' => 'password',
];
```

**Comment by stevebauman** [comment]
Accidentally closed issue, apologies.

**Comment by joeythai** [comment]
No problem steve, actually, I did the download of the library adldap2 from your tutorial and I'm trying to do the connection according to your tutorial, after I removed some lines of the my code to became  it like yours, appeard a different issues:
 
at HandleExceptions->handleError(2, 'ldap_add(): Add: Invalid syntax', '/srv/www/ramais_phorte/vendor/adldap2/adldap2/src/Connections/Ldap.php', 270, array('dn' => 'cn=read-only-admin,dc=example,dc=com,dc=example,dc=com', 'entry' => array('ou' => array('riemann'), 'title' => array('Accountant'), 'description' => array('User Accountant'), 'objectclass' => array('top', 'person', 'organizationalperson', 'user'), 'cn' => array('read-only-admin'))))

sorry about my bad english!!

**Comment by zmiKaminski** [comment]
@joeythai long shot.. add `'auto_connect' => true` to your `$config` array.

**Comment by stevebauman** [comment]
Hi @joeythai, there is multiple issues with the account you're trying to add.

The account requires a valid distinguished name, this is invalid `cn=read-only-admin,dc=example,dc=com,dc=example,dc=com`.

Also, you've added an `ou` to this account as well, but this requires a valid distinguished name for the OU you would like to store the account it: `'ou' => array('riemann')`.

Since this is an old issue, if you still encounter this after fixing the invalid attributes, please create another issue and I can assist you there, thanks!
