### ISSUE TITLE
How to change dn (move group)

### ISSUE THREAD

**Issue by nohnaimer** [Adldap2/Adldap2#416]
- Adldap2 Version: dev-master
- LDAP Type: Active Directory
- PHP Version: 7.1.6

### Description:
How to change destination name?

### Steps To Reproduce:
For create group I use:

        $group = Yii::$app->ad->make()->group();

        $group->setAccountName($name);

        $dn = $group->getDnBuilder();
        $dn->addCn($group->getAccountName());
        $dn->addOu($server)
            ->addOu($region)
            ->addOu('Files Shares')
            ->addOu('Groups')
            ->addOu('Accounts');
        $group->setDn($dn);

        if ($group->save()) {
            return $group->getConvertedGuid();
        }

        return false;

Everything works well as it should. But if I want to move the group on the server, that is, change dn I need both old and new data:

        $group = Yii::$app->ad->search()->groups()->findByGuidOrFail($guid);
        $dn = $group->getDnBuilder();
        $dn->removeCn('old_CN');
        $dn->removeOu('old_Ou');
        $dn->removeOu('old_Ou');
        $dn->addCn('new_Cn')
               ->addOu('new_Ou')
              ->addOu('new_Ou');

        $group->setDn($dn);

        return $group->save() ? true : false;

Can this operation be done somehow more beautifully?
Thank you!

**Comment by stevebauman** [comment]
Thanks @Kdecherf, you are right, using the `move()` or `rename()` method is definitely the more fluent and easy way of performing this.

Closing, but if you need more assistance just let me know :).
