### ISSUE TITLE
Using TLS doesn't supply the correct protocol

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Adldap2/Adldap2#419]
- Adldap2 Version: 7.0.*
- LDAP Type: AD
- PHP Version: N/A

### Description:

~Using `use_tls => true,` means `Ldap::getProtocol()` returns `ldap://` instead of the required `ldaps://`.~

~Seeing as TLS is an extension on SSL, it doesn't make any sense to allow both to be enabled at the same time?~

### Steps To Reproduce:

```php
...
	'use_tls' => true,

	'port' => 636,
...
```

### Code change required to fix:

~Apart from the code change required to make both options mutually exclusive, I'd do two things:~
1. ~Change the default port when secure and not supplied to 636 (https://msdn.microsoft.com/en-gb/library/cc223502.aspx)~
2. ~Pull this check of SSL or TLS out into a method of `Ldap::isSecureConnection()` like the following:~
```php
	public function isSecureConnection()
	{
		return $this->isUsingSSL() || $this->isUsingTLS();
	}
```

~And then I'd change the two references to this:~
```php
	public function canChangePasswords()
	{
		return $this->isSecureConnection();
	}
```
and
```php
	public function getProtocol()
	{
		return $this->isSecureConnection() ? $this::PROTOCOL_SSL : $this::PROTOCOL;
	}
```

### Workaround

~Enable both `use_tls` and `use_ssl` at the same time.~

### Suggestion

There is no documentation on enabling TLS, I had to dig around the config code to find out how to enable this.

**Comment by ElvenSpellmaker** [comment]
I think I understand now after some reading, but the issue stands in a different part.

While I see why they are separate parameters (c.f. ldaps vs start_tls), the `isSecureConnection` doesn't cater for secure TLS connections.

**Comment by stevebauman** [comment]
Hi @ElvenSpellmaker, apologies for the very long response for this issue.

> There is no documentation on enabling TLS, I had to dig around the config code to find out how to enable this.

This has always been located in the configuration documentation as early as v5.0:

https://github.com/Adldap2/Adldap2/blob/v5.2/docs/CONFIGURATION.md#ssl--tls-optional

https://github.com/Adldap2/Adldap2/blob/v6.0/docs/configuration.md#ssl--tls-optional

I'd be surprised if you missed it while looking, as it's even in the documentation when creating a new configuration instance.

> I believe the "correct" method is to use tls over the old port and start_tls, something which isn't obvious, using ldaps is the older deprecated method.

That is correct, but it's still secure and still in use. I try avoid bias with different environments in my documentation, but I can definitely suggest the usage of TLS over SSL.

I'll update my docs to include this, thanks!
