### ISSUE TITLE
variable name correction

### ISSUE THREAD

**Issue by erickneverson** [Adldap2/Adldap2#420]
- Adldap2 Version: 7.0.*
- LDAP Type: Active Directory
- PHP Version: 7.0.18-0ubuntu0.16.04.1

### Description:
In section 'Checking if the Model is apart of a Group', variable name $office should be $group.

### Steps To Reproduce:
check has-member-of.md

Tried creating a PR but not allowed :)

**Comment by stevebauman** [comment]
Thanks! :)
