### ISSUE TITLE
Paginator doesn't work

### ISSUE THREAD

**Issue by aleksandrychev** [Adldap2/Adldap2#421]
- Adldap2 Version: 7.0.*
- LDAP Type: 
- PHP Version: 5.6

### Description:
Paginator returns all results. http://storage7.static.itmages.com/i/17/0719/h_1500475240_4682000_87f94fecad.png

### Steps To Reproduce:
Make search and apply paginate.
```
$provider->search()->rawFilter('(objectClass=person)')->paginate(1,2)
```

**Comment by aleksandrychev** [comment]
I've noted that using getIterator() instead of getResults() solve the issue.

**Comment by stevebauman** [comment]
Hi @aleksandrychev, please see my response here: https://github.com/Adldap2/Adldap2-Laravel/issues/333
