### ISSUE TITLE
Problem with DN Builder after update

### ISSUE THREAD

**Issue by wranger** [Adldap2/Adldap2#422]
- Adldap2 Version: 7.0.x
- LDAP Type:AD
- PHP Version: 7.6.x

### Description:
During an Update from 7.0.x to 7.0.y some changes in the DN-Builder happend:

Befor the Update I had to add the CN to the DN after the update it is not nessary any more:

$dn->addOu($name);
$dn->addOu("Mitarbeiter");
$dn->addOu("User");
$dn->addOu('COMPANY');
$dn->addDc('adint');
$dn->addDc('dir');

That results in a failure, cause the DN was added twice:

object(Adldap\Objects\DistinguishedName)#40 (7) { ["schema":protected]=> object(Adldap\Schemas\ActiveDirectory)#14 (0) { } ["commonNames":protected]=> array(0) { } ["userIds":protected]=> array(0) { } ["organizationUnits":protected]=> array(4) { [0]=> string(1) "T" [1]=> string(11) "Mitarbeiter" [2]=> string(4) "User" [3]=> string(8) "COMPANY" } ["domainComponents":protected]=> array(4) { [0]=> string(5) "**adint" [1]=> string(3) "dir" [2]=> string(5) "adint" [3]=> string(3) "dir"** } ["organizationNames":protected]=> array(0) { } ["types":protected]=> array(5) { [0]=> string(1) "o" [1]=> string(2) "dc" [2]=> string(2) "ou" [3]=> string(3) "uid" [4]=> string(2) "cn" } }

**Comment by stevebauman** [comment]
Hi @wranger,

I'm not sure what might have changed. Nothing has changed with the DN builder for a few releases.

Can you check to see which version you're running? Release `v7.0.7` was the only time a change occurred recently:

https://github.com/Adldap2/Adldap2/releases/tag/v7.0.7

**Comment by wranger** [comment]
Yes, it was a old version 7.0.4 or 7.0.3 my before last Composer update was from January 31.

Thats the way I create a new group:

$group = $this->pro_adint->make()->group($g_data);
	
$dn = $group->getDnBuilder();
			
$dn->addCn($data["name"]);
$dn->addOu("Security-Gruppen");
$dn->addOu("Groups");
$dn->addOu('Company');
//$dn->addDc('adint');
//$dn->addDc('dir');
			
$group->setDn($dn);

**Comment by stevebauman** [comment]
Ok, no problem. Simply replace `getDnBuilder()` with `getNewDnBuilder()`.

This was completely my mistake. I under estimated this as a breaking change and thought of it as a convenience. Sorry!

Unfortunately I can't revert this change as some users may rely on the current functionality of how it works now.

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Model.php#L594-L618

If you experience any further issues please create a new issue.

Thanks for bringing this to my attention @wranger.
