### ISSUE TITLE
Schema is null

### ISSUE THREAD

**Issue by munverzagt** [Adldap2/Adldap2#423]
- Adldap2 Version: 3.0.5
- LDAP Type: Active Directory
- Laravel Version 5.3
- PHP Version: 7.1.7

### Description:
Get the error: Call to a member function memberOf() on null in HasMemberOf.php line 84

### Steps To Reproduce:
Hi Steve,
i am new to Laravel and also to Adldap. After one week of trying i have a SSO and the user gets saved into a SQL Server database. Now i wanna work with AD-Groups. My user table has a field 'group'.
I want a Middleware class that should differ between the groups of a user to authorize only allowed pages.
GroupPermissions.php
```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Contracts\Auth\Guard;
use Adldap\Laravel\Traits\UsesAdldap;

class GroupPermissions
{
  use UsesAdldap;
  protected $auth;
  public function __construct(Guard $auth){
    $this->auth = $auth;
  }
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next, $group)
    {

      if ($this->auth->user()->inGroup($group)) {
        return $next($request);
      }
      return redirect('/');
    }
}
```
In my web.php
```
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
  Route::group(['middleware' => 'group.perm:it'], function(){
    Route::get('/admin', 'AdminController@index');
    Route::get('/customer/{id}', 'CustomerController@index');
  });
  Route::group(['middleware' => 'group.perm:costumerservice'], function(){
    Route::get('/customer/{id}', 'CustomerController@index');
  });
});

```
The Middleware auth refers to a copy of the WindowsAuthenticate.php.
In the class User.php i use HasMemberOf trait.
Can you please tell what i forget to use?
I'm not sure if this is the right way.
Thank you for your time investigation.

**Comment by stevebauman** [comment]
Hi @munverzagt,

You'll need to remove the `UsesAdldap` trait from your middleware and instead enable the feature [binding users to their model](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth/binding.md).

All you need to do is insert this trait onto your `App\User` model: `Adldap\Laravel\Traits\HasLdapUser`, and then you can perform this like so:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Contracts\Auth\Guard;

class GroupPermissions
{
  protected $auth;

  public function __construct(Guard $auth){
    $this->auth = $auth;
  }

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next, $group)
    {

      if ($this->auth->user()->ldap->inGroup($group)) {
        return $next($request);
      }
      return redirect('/');
    }
}
```

You also mention you receive the error:

> Call to a member function memberOf() on null in HasMemberOf.php line 84

When do you receive this?

**Comment by munverzagt** [comment]
I recive this error if i go to laravel.app/home.
The web.php in my first post is an example how it should used if all runs. Now i have only the route to /home that must go through the middleware.

```
Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::group(['middleware' => 'auth'], function() {
    Route::group(['middleware' => 'group.perm:it'], function(){
      Route::get('/home', 'HomeController@index');
    });
});
```
I have made the changes you say and now become the error:
`Call to undefined method Illuminate\Database\Query\Builder::ldap().`

**Comment by stevebauman** [comment]
> I have made the changes you say and now become the error:
Call to undefined method Illuminate\Database\Query\Builder::ldap().

Did you add the trait I specified to your User model?

**Comment by munverzagt** [comment]
Yes of course:
```
<?php
namespace App;

use Adldap\Laravel\Traits\HasLdapUser;
use Adldap\Models\Traits\HasMemberOf;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasMemberOf;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'password',
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    /**
    * Neues Standardformat für Zeitstempel. Standard gibt Millisekunden zurück, womit der SQL-Server nichts anfangen kann.
    * @return String
    */
    public function getDateFormat(){
      return 'Y-d-m H:i:s';
    }
}

```

**Comment by stevebauman** [comment]
This is incorrect, please re-read my message:

> All you need to do is insert this trait onto your App\User model: Adldap\Laravel\Traits\HasLdapUser, and then you can perform this like so:

Insert the trait **Adldap\Laravel\Traits\HasLdapUser** onto your **User** model, **not** the `HasMemberOf` trait.

**Comment by munverzagt** [comment]
Now i have this but same error:

```
<?php
namespace App;

use Adldap\Laravel\Traits\HasLdapUser;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasLdapUser;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
    * Neues Standardformat für Zeitstempel. Standard gibt Millisekunden zurück, womit der SQL-Server nichts anfangen kann.
    * @return String
    */
    public function getDateFormat(){
      return 'Y-d-m H:i:s';
    }
}
```
Didn't i need the HasMemberOf Trait to work with groups?

**Comment by munverzagt** [comment]
Solved it. I have this line in my GroupPermission.php
`if ($this->auth->user()->ldap()->inGroup($group))`
But the brackets after ldap are wrong.
Thank you very much Steve.

**Comment by stevebauman** [comment]
No problem! Glad you've resolved it, thanks for following up :).
