### ISSUE TITLE
Missing attributes HomeDirectory & Home-Drive

### ISSUE THREAD

**Issue by aleex1848** [Adldap2/Adldap2#424]
- Adldap2 Version: latest
- LDAP Type: Active Directory or OpenLDAP?
- PHP Version: 7.0

Hi,
i'm using the Adldap2-laravel package and really appreciate your work.
Now i'm only missing these attributes:
https://msdn.microsoft.com/en-us/library/ms676191(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/ms676190(v=vs.85).aspx

You would make me smile implementing these :)

Thanks!

**Comment by stevebauman** [comment]
Hi @aleex1848, thanks, I'll have these implemented soon :).

At the time being you can still access and modify these attributes:

```php
$user = $provider->search()->users()->find('jdoe');

echo $user->getFirstAttribute('homedrive');
echo $user->getFirstAttribute('homedirectory');
```

**Comment by aleex1848** [comment]
$user->setFirstAttribute('homedrive',$value); 
is what i need. Thank you!

**Comment by sborrill** [comment]
Can you add setters for homeDrive and homeDirectory attributes too?

**Comment by stevebauman** [comment]
Hi @sborrill, these have already been added:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/User.php#L490-L512

**Comment by sborrill** [comment]
Those are getters, not setters.

**Comment by stevebauman** [comment]
@sborrill Woops! You're right, should have read your comment more clearly.

Implementing now, thanks :)
