### ISSUE TITLE
User Groups within an OU

### ISSUE THREAD

**Issue by cbloss** [Adldap2/Adldap2#426]
This will probably be a quick question. Is there an easy way to find a user's groups that are within an OU? I know how to find all groups for a user and how to find all groups within an OU, but not a user's groups that are within an OU. I found several forms that were asking something similar, but not quite the same and it's bugging me. 

THANKS! :) 

- LDAP Type: AD
- PHP Version: 7.1

**Comment by stevebauman** [comment]
Hi @cbloss,

You'll have to filter the groups manually by checking if the DN contains the OU's DN.

Here's an example:

```php
$user = $provider->search()->users()->find('jdoe');

$groups = $user->getGroups()->filter(function ($group)) {
    $accounting = 'ou=Accounting,dc=corp,dc=acme,dc=org';

    return str_contains($group->getDn(), $accounting);
});
```
