### ISSUE TITLE
Finding the base DN by binding as a user?

### ISSUE THREAD

**Issue by francislavoie** [Adldap2/Adldap2#429]
- Adldap2 Version: 7.0.15
- LDAP Type: Active Directory
- PHP Version: 7.0

I'm trying to figure out if this is possible. I need to set up dynamic configuration of LDAP, because my users can specify the connection details. In some cases, they will know their username and password, but not their base DN. Is there a way to bind with the username and password and get the DN of that authenticated user, without configuring a base DN?

I can bind just fine with `$ad->auth()->attempt($username, $password, true);` but then trying something like `$results = $ad->search()->findBy('samaccountname', $username);` afterwards gives me `NULL`.

Essentially I'd like to be able to find and suggest the base DN to the user after they authenticate, making the assumption that all the users are in the same base DN.

Is this even possible? This might just be a hopeless endeavor :disappointed:

**Comment by francislavoie** [comment]
I figured out a solution.

I can query for the RootDSE and grab the base DN from there.

Example:
```
            // Query for the RootDSE (server properties) and grab the baseDN
            $rootDSE = $ad->search()->getRootDSE();
            $base_dn = $rootDSE->getRootDomainNamingContext();

            // Set the base DN in the config based on the results
            $config['base_dn'] = $base_dn;
            $ad->getProvider('default')->setConfiguration($config);

            // Search to find the current user
            $results = $ad->search()->findBy('samaccountname', $username);
```

**Comment by stevebauman** [comment]
Great solution @francislavoie, thanks for sharing!
