### ISSUE TITLE
JSON encode fails 

### ISSUE THREAD

**Issue by francislavoie** [Adldap2/Adldap2#430]
- Adldap2 Version: 7.0.15
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:
JSON encoding a user model doesn't always succeed - some properties are not properly UTF8 encoded. As a workaround I recursively utf8_encode the `$model->getAttributes()` array with the below:

```
    /**
     * Encode array to utf8 recursively
     * @param $dat
     * @return array|string
     */
    private function array_utf8_encode($dat)
    {
        if (is_string($dat))
            return utf8_encode($dat);
        if (!is_array($dat))
            return $dat;
        $ret = array();
        foreach ($dat as $i => $d)
            $ret[$i] = self::array_utf8_encode($d);
        return $ret;
    }
```

Edit: Specifically, it seems like the `logonHours` property that's malformed in my case.

**Comment by stevebauman** [comment]
Thanks @francislavoie, will have fix out shortly!

**Comment by francislavoie** [comment]
@stevebauman Maybe consider using the converted GUID/SIDs when serializing?

**Comment by stevebauman** [comment]
Good idea, will do :)

**Comment by francislavoie** [comment]
This seems like a breaking change, should probably be in 8.0, right?

**Comment by stevebauman** [comment]
Yup that's correct. Just added the conversions:

https://github.com/Adldap2/Adldap2/commit/f43d4dc504b06013b549144f28f1b9d791610b38

Need to finish up upgrade documentation and make some smaller changes before release.
