### ISSUE TITLE
How to get all Users from AD

### ISSUE THREAD

**Issue by SirTom76** [Adldap2/Adldap2#431]
- Adldap2 Version: 7.0.15
- LDAP Type: openLDAP
- PHP Version: 5.6

### Description:
I use adldap2 for a web-application-login. Now I would like to create an admin backend and try to get all users:

$ad = new \Adldap\Adldap();
$ad->addProvider($config);

for the login:
$provider = **$ad->connect();
$provider->auth()->attempt($user, $pw, true);

Try to get all users:
$users = $ad->search()->users()->get();
print_r($users); 

The result:
Illuminate\Support\Collection Object ( [items:protected] => Array ( ) ) 

What ist wrong???
Thanks for your help!
Tom

**Comment by stevebauman** [comment]
Hi @SirTom76, you'll need to switch the Shema from ActiveDirectory to OpenLDAP.  This is why you're not seeing any user's. Here's a doc to show you how to implement the OpenLDAP schema:

https://github.com/Adldap2/Adldap2/blob/master/docs/schema.md

**Comment by SirTom76** [comment]
Thanks a lot! Now it works perfect!

**Comment by M3ndes** [comment]
had the same error, and the link is broken. Any solutions at the offical documentation?

**Comment by M3ndes** [comment]
> Hi @SirTom76, you'll need to switch the Shema from ActiveDirectory to OpenLDAP. This is why you're not seeing any user's. Here's a doc to show you how to implement the OpenLDAP schema:
> 
> https://github.com/Adldap2/Adldap2/blob/master/docs/schema.md

had the same error, and the link is broken. Any solutions at the offical documentation?

**Comment by stevebauman** [comment]
Hi @M3ndes, it's here:

https://adldap2.github.io/Adldap2/#/setup?id=using-other-ldap-servers-openldap-freeipa-etc

Is it hard to locate these things in the official docs? Asking honestly so I can change the layout depending on users opinions.

Thanks!

**Comment by stevebauman** [comment]
Example for anyone looking at this issue in the future in case doc links break:

```php
$ad = new Adldap\Adldap();

$config = [
    '...',
    'schema' => Adldap\Schemas\OpenLDAP::class
];

$ad->addProvider($config);
```

**Comment by M3ndes** [comment]
> Hi @M3ndes, it's here:
> 
> https://adldap2.github.io/Adldap2/#/setup?id=using-other-ldap-servers-openldap-freeipa-etc
> 
> Is it hard to locate these things in the official docs? Asking honestly so I can change the layout depending on users opinions.
> 
> Thanks!

it isnt hard, i was looking for schemas, my bad.

**Comment by M3ndes** [comment]
it isnt hard, i was looking for schemas, my bad.

> Hi @M3ndes, it's here:
> 
> https://adldap2.github.io/Adldap2/#/setup?id=using-other-ldap-servers-openldap-freeipa-etc
> 
> Is it hard to locate these things in the official docs? Asking honestly so I can change the layout depending on users opinions.
> 
> Thanks!

it isnt hard, i was looking for schemas, my bad. Already added the code line into the $config array, but still gettin a empty aray when i try print_r($results);  Any idea to what it could be?

**Comment by stevebauman** [comment]
Okay great, wanted to make sure.

For your other issue, have you checked your  `base_dn` in your config array to make sure it's correct? Having an incorrect base DN will result in nothing being returned from your LDAP server.

**Comment by M3ndes** [comment]
> Okay great, wanted to make sure.
> 
> For your other issue, have you checked your `base_dn` in your config array to make sure it's correct? Having an incorrect base DN will result in nothing being returned from your LDAP server.

it works! Thanks for your help mate!

**Comment by stevebauman** [comment]
Awesome! No problem at all! Glad you’re up and running.
