### ISSUE TITLE
Rename cn and also samaccountname

### ISSUE THREAD

**Issue by wallish** [Adldap2/Adldap2#435]
- Adldap2 Version: 7.0.15
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:

I have a question about rename function : 
https://github.com/Adldap2/Adldap2/blob/f8e855681e8544ef23e98fec6f6a397e98323c3b/src/Connections/ConnectionInterface.php#L352

This function will rename only the cn, but i feel samaccountname is related with the cn.

Souldnt we rename in the same time cn and samaccountname ?

**Comment by stevebauman** [comment]
Hi @wallish,

I don't think we should rename the `samacccountname` with the `cn`. I think this should be changed manually so the developer knows it's being updated.

I agree with your reasoning that most of the time you'd like both changed at the same time, but there's scenarios where you may want to _only_ change the `cn` and renaming is the only way to perform this.

**Comment by wallish** [comment]
I understand, thank you for your answer :)

**Comment by stevebauman** [comment]
No problem, thanks for the suggestion! :)
