### ISSUE TITLE
Set lockoutTime attribute ?

### ISSUE THREAD

**Issue by barbuslex** [Adldap2/Adldap2#436]
- Adldap2 Version: ALL
- LDAP Type: Active Directory
- PHP Version: 7.0

Hi,

How can i set lockoutTime attribute to 0 for unlock locked users ?
Is it possible with adldap2 ?

Thanks in advance ?

++

**Comment by stevebauman** [comment]
Hi @barbuslex, modifying the `lockoutTime` attribute isn't possible with LDAP. It's set by the system.

Please see: http://ldapwiki.com/wiki/Lockouttime

Also, a value of zero indicates that the account **is not** locked out.

Otherwise it will return a timestamp as to when the lockout ends.
