### ISSUE TITLE
getConvertedSid not returning correct data

### ISSUE THREAD

**Issue by cryogenx** [Adldap2/Adldap2#437]
- Adldap2 Version: 7.0.15
- LDAP Type: Active Directory
- PHP Version:  5.6.28
### Description:
when using the getConvertedSid() method it is retrieving "S-1-5-21--237028803--1898362650-536798400-1202" for a specific user, however, when pulling the same information directly from AD I get "S-1-5-21-4057938493-2396604646-536798400-1202"

**Comment by stevebauman** [comment]
This is a bug I've been experiencing, however my knowledge to converting binary SIDs to strings is very limited.

Any suggestions?

**Comment by stevebauman** [comment]
This has been resolved in the master branch.

A `v8.0` will be released shortly with this fix.
