### ISSUE TITLE
How to get all Dns from the group

### ISSUE THREAD

**Issue by nohnaimer** [Adldap2/Adldap2#438]
Hello,
At once I will tell, all works as well as it is conceived!

The problem is this: when adding 10 or more users to a group (in a loop), the process takes 4-5 seconds - it's a lot!

Whether prompt it is possible to implement $ group->addMember**s**($users)?
$users - array or something similar.

Thank you in advance, forgive me for the terrible English!

**Comment by nohnaimer** [comment]
Maybe something like this:

```
   /**
     * Adds users to the current group.
     * @param array $dns
     * @return bool
     */
    public function addMembers(array $dns)
    {
        $this->addModification(new BatchModification(
            $this->schema->member(),
            LDAP_MODIFY_BATCH_ADD,
            $dns
        ));

        return $this->save();
    }
```

**Comment by nohnaimer** [comment]
And one more question:
How to get all Dns from the group?
foreach ($group->members as $member) { - Invalid argument supplied for foreach()

```
foreach ($group->getMembers() as $member) {
            $data[] = $member->getDn();
        }
```
Almost beautiful...

**Comment by stevebauman** [comment]
Hi @nohnaimer,

I'm adding the `addMembers()` method now, thanks for the suggestion!

> foreach ($group->members as $member) { - Invalid argument supplied for foreach()

What is being returned by the `getMembers()` method on your group?

**Comment by stevebauman** [comment]
Hi @nohnaimer,

If you're still having issues, please create another and I can assist you futher since your original issue is resolved: https://github.com/Adldap2/Adldap2/commit/4a88c1cf8696e8e3a4e03f0f29eb0bef15cbf008

**Comment by nohnaimer** [comment]
Now there are no problems anymore. I use Yii2 framework and I redefined the schematics and some models from AdLdap2:
<img width="212" alt="2017-10-01 16 35 49" src="https://user-images.githubusercontent.com/8865830/31055010-9d3aa536-a6c6-11e7-9c87-73cee6ca4a56.png">
For the batch add/delete, I use two methods:
```
/**
     * Adds entries to the current entry.
     *
     * @param array $entries
     * @return bool
     */
    public function addEntries($entries)
    {
        $this->addModification(new BatchModification(
            $this->schema->member(),
            LDAP_MODIFY_BATCH_ADD,
            $entries
        ));

        return $this->save();
    }

    /**
     * Delete entries from current entry.
     *
     * @param array $entries
     * @return bool
     */
    public function removeEntries($entries)
    {
        $this->addModification(new BatchModification(
            $this->schema->member(),
            LDAP_MODIFY_BATCH_REMOVE,
            $entries
        ));

        return $this->save();
    }
```
To get the data, I use the attributes of the object:
Group:
```
/**
     * @return array
     */
    public function getDns()
    {
        return $this->getAttribute($this->schema->member());
    }
```
User:
```
/**
     * @return array
     */
    public function getDns()
    {
        return $this->getAttribute($this->schema->memberOf());
    }
```
And for snacks: the method inGroup() is terrible! It only works for one object and then slowly. Where better to do diff dns on group and user!
