### ISSUE TITLE
Batch Modify: Server is unwilling to perform in

### ISSUE THREAD

**Issue by nohnaimer** [Adldap2/Adldap2#439]
- Adldap2 Version:
v7.0.15
- LDAP Type:
Active Directory
- PHP Version:
7.1.8 macOS Sierra
### Description:
When I try to delete records from an object I get an error Batch Modify: Server is unwilling to perform.
Method for delete:
```
/**
     * Delete entries from current entry.
     *
     * @param array $entries
     * @param string $attribute
     * @return bool
     */
    public function removeEntries($entries, $attribute)
    {
        $this->addModification(new BatchModification(
            $attribute,
            LDAP_MODIFY_BATCH_REMOVE,
            $entries
        ));

        return $this->save();
    }
```
At the same time, the addition works as it should:
```
/**
     * Adds entries to the current entry.
     *
     * @param array $entries
     * @param string $attribute
     * @return bool
     */
    public function addEntries($entries, $attribute)
    {
        $this->addModification(new BatchModification(
            $attribute,
            LDAP_MODIFY_BATCH_ADD,
            $entries
        ));

        return $this->save();
    }
```
### Steps To Reproduce:
I use TLS. Try SSL - same error.
Try:
TLS_CIPHER_SUITE ALL:!VERS-TLS1.2
TLS_CIPHER_SUITE NORMAL:!VERS-TLS1.2
on ldap.conf - same error.
Try putenv in my code (I use Yii2 Framework) - same error.

Any ideas?

**Comment by stevebauman** [comment]
Hi @nohnaimer,

You need to use a domain administrator account or an account that has the privileges to delete other AD accounts.

Try using another account with these permissions and see if it works.

This is most likely the issue.

If it doesn't work, I'll re open the issue.

**Comment by nohnaimer** [comment]
Hi @stevebauman,

I try with Domain Administrator account and have same error. Full error trace:

```
yii\base\ErrorException: ldap_modify_batch(): Batch Modify: Server is unwilling to perform in /Users/and1/phpStormProjects/www/ems/vendor/adldap2/adldap2/src/Connections/Ldap.php:302
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'ldap_modify_bat...', '/Users/and1/php...', 302, Array)
#1 /Users/and1/phpStormProjects/www/ems/vendor/adldap2/adldap2/src/Connections/Ldap.php(302): ldap_modify_batch(Resource id #157, 'CN=\xD0\x90\xD1\x81\xD1\x82\xD0\xB0\xD0\xBF\xD0\xB5...', Array)
#2 /Users/and1/phpStormProjects/www/ems/vendor/adldap2/adldap2/src/Models/Model.php(737): Adldap\Connections\Ldap->modifyBatch('CN=\xD0\x90\xD1\x81\xD1\x82\xD0\xB0\xD0\xBF\xD0\xB5...', Array)
#3 /Users/and1/phpStormProjects/www/ems/vendor/adldap2/adldap2/src/Models/Model.php(719): Adldap\Models\Model->update(Array)
#4 /Users/and1/phpStormProjects/www/ems/common/components/Adldap/Models/Entry.php(48): Adldap\Models\Model->save()
#5 /Users/and1/phpStormProjects/www/ems/common/components/ActiveDirectory.php(261): Adldap\Models\Entry->removeEntries(Array, 'memberof')
#6 /Users/and1/phpStormProjects/www/ems/frontend/models/ShareAccessBaseModel.php(270): common\components\ActiveDirectory->removeEntries('ef1a1e07-ee7f-4...', 'users', Array)
#7 /Users/and1/phpStormProjects/www/ems/frontend/controllers/ShareAccessController.php(197): frontend\models\ShareAccessBaseModel->delete()
#8 [internal function]: frontend\controllers\ShareAccessController->actionDelete('278', '54', '2')
#9 /Users/and1/phpStormProjects/www/ems/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/and1/phpStormProjects/www/ems/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/and1/phpStormProjects/www/ems/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('delete', Array)
#12 /Users/and1/phpStormProjects/www/ems/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('share-access/de...', Array)
#13 /Users/and1/phpStormProjects/www/ems/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 /Users/and1/phpStormProjects/www/ems/frontend/web/index.php(18): yii\base\Application->run()
#15 {main} 
```

**Comment by stevebauman** [comment]
What attributes are you trying to delete on the object?

**Comment by nohnaimer** [comment]
On User Object attribute memberof I try delete dns of groups to which the user enters.
That is, the command looks like this:

```
       $this->addModification(new BatchModification(
            'memberof',
            LDAP_MODIFY_BATCH_REMOVE,
            [
               dn1,
               dn2,
               dn3
            ],
        ));

        return $this->save();
```

**Comment by stevebauman** [comment]
You can't modify the `memberof` attribute directly, you actually need to modify the group and remove the entries from the groups `member` attribute manually.

See: https://stackoverflow.com/questions/39345990/how-to-add-attribute-member-memberof-in-ldap-active-directoryad-using-zf2

This is why the methods for removing models from groups actually call the `removeMember()` method on the `Group` model itself:

The `User` model:

https://github.com/Adldap2/Adldap2/blob/fee84a4d42b2e61d27128f0b6141fd094747e130/src/Models/Concerns/HasMemberOf.php#L36-L58

The `Group` model:

https://github.com/Adldap2/Adldap2/blob/fee84a4d42b2e61d27128f0b6141fd094747e130/src/Models/Group.php#L97-L123

**Comment by stevebauman** [comment]
I need to update the docs to reflect these issues as it would definitely help future users out with troubleshooting these problems, however time is short at the moment :(.

**Comment by nohnaimer** [comment]
Thank for links. I also found a description https://stackoverflow.com/questions/11360339/active-directory-member-and-memberof-properties-relationship

I will rewrite the method of deleting access.
Thanks again!
