### ISSUE TITLE
List all users in group?

### ISSUE THREAD

**Issue by benyanke** [Adldap2/Adldap2#443]
I am having trouble listing all the group members on my AD server. 

I have tried all the queries I could find in the documentation, and still I am getting blank datasets returned. 

How does one list all the members of an AD group by the groups's DN?

**Comment by stevebauman** [comment]
Hi @benyanke,

Can you show your current code? You should be able to perform this like so:

```php
$group = $provider->search()->groups()->find('Accounting');

$members = $group->getMembers();

foreach($members as $member) {
    echo $member->getDn();
}
```

**Comment by benyanke** [comment]
That worked, thank you!

**Comment by stevebauman** [comment]
Perfect, no problem! :)
