### ISSUE TITLE
Binding as the authenticated user

### ISSUE THREAD

**Issue by ikwijaya** [Adldap2/Adldap2#446]
- Adldap2 Version: 8.0
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:
I use auth()->attempt(user,passwd,true) for binding ldap and no error return. this is my code : 

```php
public static function auth($username,$password)
{
        $ad = new Adldap();
        $ad->addProvider(Config::get('LDAP_CONFIG'));
        try{
        	$provider = $ad->connect();
        	if ($provider->auth()->attempt($username,$password,true)) {
                $search = $provider->search()->where('samaccountname','=',$username)->get();
                $group = $search[0]['memberof'];
                $attributes = ["samaccountname","useraccountcontrol","memberof"];   
                $entries = [];
                for($i=0;$i<count($search);$i++){
                    for($a=0;$a<count($attributes);$a++){
                        $entries[$attributes[$a]] = $search[$i][$attributes[$a]];
                    }
                }
                $output = self::check_group($group,$entries);
            } else {
                $output = Response::fails('No Authorized.',403);
            }
            return $output;
        } catch(\Adldap\Auth\BindException $e){
            Response::fails($e,403);
        }catch (\Adldap\Auth\UsernameRequiredException $e) {
            Response::fails('Username is required.',403);
        } catch (\Adldap\Auth\PasswordRequiredException $e) {
            Response::fails('Password is required.',403);
        }
 }
```

then i want to update attribute to server, and always return  **Insufficient access**
<br />
<b>Warning</b>:  ldap_mod_replace(): Modify: Insufficient access in <b>/home/wksadm/APPS/adldap/vendor/adldap2/adldap2/src/Connections/Ldap.php</b> on line <b>318</b><br />
false

this is my code : 

```php
public static function update_attribute($search,$samaccountname,$attr,$attr_val){
		$ad = new Adldap();
        $ad->addProvider(Config::get('LDAP_CONFIG'));
        $search = strtolower($search);
        try{
            $provider = $ad->connect();
            if($search == 'users'){
            	$for = $provider->search()->users();
            }elseif ($search == 'groups') {
            	$for = $provider->search()->groups();
            }elseif($search == 'computers'){
            	$for = $provider->search()->computers();
            }elseif($search == 'printers'){
            	$for = $provider->search()->printers();
            }elseif($search == 'ous'){
            	$for = $provider->search()->ous();
            }elseif($search == 'containers'){
            	$for = $provider->search()->containers();
            }elseif($search == 'contacts'){
            	$for = $provider->search()->contacts();
            }else {
            	return Response::fails('Search not found.',403);
            }
            $output = $for->whereEquals('samaccountname',$samaccountname)->firstOrFail();
	        $execute = $output->updateAttribute($attr,$attr_val);
	        $output->save();
            return $execute;
        } catch(\Adldap\Auth\BindException $e){
            Response::fails($e,403);
        } catch(\Adldap\Models\ModelNotFoundException $ex){
        	Response::fails($ex,403);
        }
}
```

I not understand how to use authentication so  **run all LDAP operations under this user**, can you give me some example for login then some search or update attribute can be done, with php static function.

thanks for advance
ikwijaya

**Comment by stevebauman** [comment]
> then i want to update attribute to server, and always return Insufficient access

This means that the user you're authenticating with **does not** have permission to update the attribute you're trying to modify.

This user will need permissions in your Active Directory to be able to modify user attributes.

Also, your code here is incorrect usage:

```php
$execute = $output->updateAttribute($attr,$attr_val);

$output->save();
```

The `updateAttribute()` method updates one attribute and returns the response:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Model.php#L829-L849

If you're wanting to use the `save()` method you need to use the `setAttribute($attribute, $value)` method.

I also noticed you're using version `v7.0`, are you able to upgrade to `v8.0` and try this again?

**Comment by ikwijaya** [comment]
thanks for quick respon.

i change my method update_attribute like you guide. than i still not understand about binding as the authenticated user.

my logic like this.
1. I define username and password standar let say (just_standard) (just show record on AD) with member of scope Domain Users on AD, so all of operation just allow change attribute for this username (just_standard). And not allowed for other users.
2. Then i login for operation change from just_standar user to other user let say (scope_admin) with member of scope is 
- Administrator(builtin),
- Domain Admins, 
- Domain Users, and
- Enterprise Admins
I want all of operation run under scope_admin. But actually i cannot change attribute with it. Am i wrong? with method auth or my scope member on AD?

thanks in advance.
ikwijaya

**Comment by stevebauman** [comment]
Hi @ikwijaya,

I'm not sure I'm understanding what you're mentioning.

> Warning: ldap_mod_replace(): Modify: Insufficient access in /home/wksadm/APPS/adldap/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 318

This exception isn't lying to you, the account you're using to modify attributes **does not** have permission to do so.

This could be due to requiring an SSL / TLS connection. Are you trying to change user passwords?

**Comment by ikwijaya** [comment]
Hi @stevebauman 

if I change the configuration with scope_admin, any operation runs fine.

actually what I ask is how do we know that the next operation is done by another user login? so I can know that the permissions on the server are not correct.

because at this time if i want to do ldap operation after login done then i have to store username and password in session, and it will be very dangerous. Maybe you have another solution,

thank you in advance
ikwijaya

**Comment by stevebauman** [comment]
> actually what I ask is how do we know that the next operation is done by another user login? so I can know that the permissions on the server are not correct.

You can simply change your configuration to bind as an administrator account on your domain and try modifying your account again to see if it's a permission based issue.

> because at this time if i want to do ldap operation after login done then i have to store username and password in session, and it will be very dangerous. Maybe you have another solution,

Unfortunately I don't. PHP (like HTTP) is completely stateless. This is why I have the configuration options to use an account so you can always connect to your LDAP server. Otherwise you will need to store the users username and password somewhere to be able to bind to your LDAP server as this user.

If you just need LDAP authentication, you can do so without an account configured. However, if you need a persistent LDAP connection throughout your application, you will **need** to configure a user account to authenticate with - or store the users credentials (which you've pointed out, is definitely dangerous).
