### ISSUE TITLE
Contact class doesn't have getEmail() method

### ISSUE THREAD

**Issue by pdifeo** [Adldap2/Adldap2#447]
- Adldap2 Version: #.#
- LDAP Type: 
- PHP Version: #.#

### Description:
Contact class doesn't have getEmail() method

**Comment by stevebauman** [comment]
Hi @pdifeo, thanks for bringing this up. I'll be fixing this shortly. There are several attribute getters / setters missing from the contact class.

**Comment by stevebauman** [comment]
Sorry for the wait on this fix, looking to extract these user methods into a trait that the contact class will use as well.
