### ISSUE TITLE
"Option 0 does not exist" when creating instance

### ISSUE THREAD

**Issue by rnrstar** [Adldap2/Adldap2#448]
- Adldap2 Version: 2 (not sure where to look but I used composer to pull the latest I presume).
- LDAP Type: Active Directory
- PHP Version: 7.0.22

### Description:
I'm trying to bind to find a user and when I use the following:

```php
require 'vendor/autoload.php';

// Create the configuration array.
$config = [    // Mandatory Configuration Options
    'domain_controllers'    => ['fs-00-03'],
    'base_dn'               => 'DC=internal,DC=cashfactoryusa,DC=com',
    'admin_username'        => 'administrator',
    'admin_password'        => 'admin password',
    
    // Optional Configuration Options
    'account_prefix'        => '',
    'account_suffix'        => '',
    'admin_account_prefix'  => '',
    'admin_account_suffix'  => '',
    'port'                  => 389,
    'follow_referrals'      => false,
    'use_ssl'               => false,
    'use_tls'               => false,
    'timeout'               => 5,
    
    // Custom LDAP Options
    'custom_options'        => [
        // See: http://php.net/ldap_set_option
        LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_HARD
    ]
];

// Construct new Adldap instance.
$ad = new \Adldap\Adldap($config);
```

I get:
[Mon Oct 09 15:31:52.670108 2017] [:error] [pid 8420] [client 10.0.1.216:54593] PHP Fatal error:  Uncaught Adldap\\Configuration\\ConfigurationException: Option 0 does not exist. in /var/www/html/vendor/adldap2/adldap2/src/Configuration/DomainConfiguration.php:116\nStack trace:\n#0 /var/www/html/vendor/adldap2/adldap2/src/Configuration/DomainConfiguration.php(146): Adldap\\Configuration\\DomainConfiguration->get(0)\n#1 /var/www/html/vendor/adldap2/adldap2/src/Configuration/DomainConfiguration.php(94): Adldap\\Configuration\\DomainConfiguration->validate(0, 'fs-00-03')\n#2 /var/www/html/vendor/adldap2/adldap2/src/Configuration/DomainConfiguration.php(77): Adldap\\Configuration\\DomainConfiguration->set(0, 'fs-00-03')\n#3 /var/www/html/vendor/adldap2/adldap2/src/Connections/Provider.php(74): Adldap\\Configuration\\DomainConfiguration->__construct(Array)\n#4 /var/www/html/vendor/adldap2/adldap2/src/Connections/Provider.php(49): Adldap\\Connections\\Provider->setConfiguration(Array)\n#5 /var/www/html/vendor/adldap2/adldap2/src/Adldap.php(48): Adldap\\Connections\\Provider->__construct(Array, NULL, NULL)\n#6 /var/www/html/vendor/ad in /var/www/html/vendor/adldap2/adldap2/src/Configuration/DomainConfiguration.php on line 116

I found another user having a similar issue but after following through that I still have this error. 

I am able to bind as a user for the purposes of authenticating with the following:
[$config array is the same as above]
// Create a new Adldap Provider instance.
$provider = new \Adldap\Connections\Provider($config);
//$search = $provider->search();
$result = array();

if ($provider->auth()->attempt($username, $password, $bindAsUser = true)) {
    // Credentials were correct.
	$result['response']=1;
}
else
{
	$result['response']=0;
}
$json = json_encode($result);
echo $json;

**Comment by stevebauman** [comment]
Hi @rnrstar,

Are you able to confirm your Adldap2 version by viewing your `composer.lock` file in your project root?

It will show the version number there.

The error you're receiving is due to setting a configuration option incorrectly, but I need to verify which version you're running as there has been changes to the configuration object in each major version.

**Comment by rnrstar** [comment]
Hi Steve,

It's showing 8.0.3. 

"packages": [
        {
            "name": "adldap2/adldap2",
            "version": "v8.0.3",
            "source": {
                "type": "git",
                "url": "https://github.com/Adldap2/Adldap2.git",
                "reference": "42fbf5c9ba0049cc7da412b17d19d8730c753827"
            },

**Comment by rnrstar** [comment]
Looking at DomainConfiguration.php I find,

---start---
    protected $options = [
        // An array of LDAP hosts.
        'domain_controllers' => [],

        // The global LDAP operation timeout limit in seconds.
        'timeout' => 5,

        // The LDAP version to utilize.
        'version' => 3,

        // The port to use for connecting to your hosts.
        'port' => ConnectionInterface::PORT,

        // The base distinguished name of your domain.
        'base_dn' => '',

        // Whether or not to use SSL when connecting to your hosts.
        'use_ssl' => false,

        // Whether or not to use TLS when connecting to your hosts.
        'use_tls' => false,

        // Whether or not follow referrals is enabled when performing LDAP operations.
        'follow_referrals' => false,

        // The account prefix to use when authenticating users.
        'account_prefix' => null,

        // The account suffix to use when authenticating users.
        'account_suffix' => null,

        // The username to connect to your hosts with.
        'admin_username' => '',

        // The password that is utilized with the above user.
        'admin_password' => '',

        // The account prefix to use when authenticating your admin account above.
        'admin_account_prefix' => null,

        // The account prefix to use when authenticating your admin account above.
        'admin_account_suffix' => null,

        // Custom LDAP options that you'd like to utilize.
        'custom_options' => [],
    ];
-----end-----
I'm not seeing anything there that isn't in my config array or visa versa.

**Comment by rnrstar** [comment]
I've changed my config array to the following and now I don't get the option 0 error. 

$config = [
	'default'=> [
	// Mandatory Configuration Options
    'domain_controllers'    => ['fs-00-03'],
    'base_dn'               => 'DC=internal,DC=obfuscated,DC=com',
    'admin_username'        => 'internal\administrator',
    'admin_password'        => 'obfuscated',
    
    // Optional Configuration Options
    'account_prefix'        => '',
    'account_suffix'        => '',
    'admin_account_prefix'  => '',
    'admin_account_suffix'  => '',
    'port'                  => 389,
    'follow_referrals'      => false,
    'use_ssl'               => false,
    'use_tls'               => false,
    'timeout'               => 5,
    
    // Custom LDAP Options
    'custom_options'        => [
        // See: http://php.net/ldap_set_option
        LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_HARD
    ]
	]
];

**Comment by stevebauman** [comment]
Ohhh yes, this slipped past me looking at your code above.

If you're constructing a configuration array that you want to pass to the Adldap constructor, you need to supply the name of the provider (as you've discovered).

Otherwise, you'll need to simply construct an empty `Adldap` instance, and call the `addProvider` method:

```php
$ad = new Adldap();

$config = ['...'];

$ad->addProvider($config);
```
