### ISSUE TITLE
setThumbnail missing

### ISSUE THREAD

**Issue by minusmillionaer** [Adldap2/Adldap2#450]
- Adldap2 Version: 8.0.3
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:
I want to ask if function setThumbnail is planned? But i want to set ThumbnailPhotos from our PHP applicaiton for our users.

**Comment by stevebauman** [comment]
Hi @minusmillionaer, you can set this right now manually using:

```php
$user->thumbnailphoto = base64_encode($photo);

$user->save();
```

However, I'll implement this as a method and keep this issue open until then, thanks!
