### ISSUE TITLE
Invalid credentials with right pwd

### ISSUE THREAD

**Issue by daixiang0** [Adldap2/Adldap2#451]
- Adldap2 Version: 8.0
- LDAP Type: php70w-ldap-7.0.24-1.w7.x86_64
- PHP Version: 7.0.24

### Description:
I use admin account to connect ldap server and call `attempt` to auth user and pwd.
I am sure the user's pwd is right but it return `Invalid credentials` error

### Steps To Reproduce:

I am use CI, here is my test script:
```
require_once('../vendor/autoload.php'); 
		 $config = array(
				 	'account_suffix'        => '',
					'admin_account_suffix'  => '',
				        'domain_controllers'    => ['192.168.20.16'],
					'base_dn'               => 'ou=People,dc=test,dc=com',
					'admin_username'        => 'cn=manager,dc=test,dc=com',
					'admin_password'        => 'pwd'
				 );

		 try {
			 $ad = new \Adldap\Adldap();
			 $ad->addProvider($config);
			 $provider = $ad->connect();
			
			 $usr='cn=xiang,dc=test,dc=com';
			 $pwd='pwd';
			 $a=$provider->search()->users()->find('xiang');
			 echo $a; # no output
			 $bind=true;

			 if ($provider->auth()->attempt($usr, $pwd,$bind)) {
				 echo 'pass';
		 		 // Credentials were correct.
				 return 0;
		 	 } else {
				 echo 'fail';
				 // Credentials were incorrect.
				 return 1;
		 	 }
			  $root = $provider->search()->getRootDse();
			   echo $root->getRootDomainNamingContext();

		 } catch (\Adldap\Auth\UsernameRequiredException $e) {
			 echo $e;
			 // The user didn't supply a username.
			 return 2;
		 } catch (\Adldap\Auth\PasswordRequiredException $e) {
			 echo $e;
			 // The user didn't supply a password.
			 return 3;
		 } catch (\Adldap\Auth\BindException $e) {
			 echo $e;
		 }
```
It always return fail, and connect is right.
I add some output to debug:
```
Adldap\Auth\BindException: Invalid credentials in /var/www/html/application/vendor/adldap2/adldap2/src/Auth/Guard.php:79
Stack trace:
#0 /var/www/html/application/vendor/adldap2/adldap2/src/Auth/Guard.php(37): Adldap\Auth\Guard->bind('cn=xiang,dc...', 'pwd')
#1 /var/www/html/application/models/a.php(25): Adldap\Auth\Guard->attempt('cn=xiang,dc...', 'pwd.', true)
#2 {main}
```
I tried to change `base_dn` to `dc=test,dc=com`, tried not to set bindAsUser in attempt, all failed.

**Comment by jelenpivo** [comment]
Same problem

**Comment by stevebauman** [comment]
Hey guys, are you using OpenLDAP or active directory?

**Comment by jelenpivo** [comment]
AD.
its working fine with DN $app->ad->auth()->attempt('CN=USER,OU=test,OU=testing,DC=example,DC=ex,DC=com','PASS', $bindAsUser = true)
But not $app->ad->auth()->attempt('USER','PASS', $bindAsUser = true)

**Comment by daixiang0** [comment]
My host is centos 7 and i just use `yum install php70w-ldap` to get ldap extension.

**Comment by daixiang0** [comment]
Update：
user whole account like `uid=xiang,ou=people,dc=test,dc=com` can pass, but specify user as 'xiang' cannot.
I tried to add 'account_prefix' as 'uid=', but also failed since the username become 'uid=xiang', it do not use base_dn as a part of username.
The base_dn just use for search which i think it should also use as a part of attempt since a lot of app configs can set base_dn, 'xiang' as username, pwd, admin_username and admin_pwd those 5 parts to auth.

**Comment by jelenpivo** [comment]
Ubuntu 16.04
provider connection works 
<code>
'account_suffix'        => '',
'admin_account_suffix'  => '',
'domain_controllers'    => ['192.168.1.111'],
'base_dn'               => 'ou=test,dc=examle,dc=ex,dc=com',
'admin_username'        => 'user',
'admin_password'        => 'PASS',
</code>

**Comment by jelenpivo** [comment]
With setting 'account_suffix'        => ' @example.ex.com', works for me

**Comment by stevebauman** [comment]
> user whole account like uid=xiang,ou=people,dc=test,dc=com can pass, but specify user as 'xiang' cannot.
If add account_prefix as 'uid=' and account_suffix as ',ou=people,dc=test,dc=com',it can pass which lools ugly i think.

This is the purpose of the `account_suffix` and `account_prefix` options, so they stay out of your actual authentication code...

> The base_dn just use for search which i think it should also use as a part of attempt since a lot of app configs can set base_dn, 'xiang' as username, pwd, admin_username and admin_pwd those 5 parts to auth.

We can't use the `base_dn` apart of the authentication attempt. Organizations store users in different OU's and not just one. This would cause a lot of issues for active directory users.

**Comment by stevebauman** [comment]
> With setting 'account_suffix' => ' @example.ex.com', works for me

This is correct, since this is forming the users `userPrincipalName` for authentication.

**Comment by stevebauman** [comment]
@daixiang0 If you can suggest a better form of authentication I'm completely open to PR's.
