### ISSUE TITLE
ldap_modify_batch(): Batch Modify: Server is unwilling to perform in...

### ISSUE THREAD

**Issue by sourjya** [Adldap2/Adldap2#455]
- Adldap2 Version: 8.x
- LDAP Type: Active Directory 
- PHP Version: 7.1.4

### Description:
I'm attempting to enable users in AD using the following code:
```
    // Enable account
    $ac = new AccountControl();
    $ac->accountIsNormal();
    $adUser->setUserAccountControl( $ac );
    if( !$adUser->save() )
        throw new Exception( __( 'Unable to enable user "{0}" in Active Directory.', $username ) );
```
This throws an error: 

`2017-11-01 15:55:07 Warning: Warning (2): ldap_modify_batch(): Batch Modify: Server is unwilling to perform in [xxx\api\vendor\adldap2\adldap2\src\Connections\Ldap.php, line 302]`

If I inspect the $adUser object, it contains the correct user's data.

`	2017-11-01 15:55:07 Debug: {"objectclass":["top","person","organizationalPerson","user"],"0":"objectclass","cn":["Amitabh Singh Bachchan"],"1":"cn","sn":["Bachchan"],"2":"sn","title":["Student"],"3":"title","givenname":["Amitabh Singh"],"4":"givenname","distinguishedname":["CN=Amitabh Singh Bachchan,OU=Graduate,OU=Current,OU=Students,DC=xxx"],"5":"distinguishedname","instancetype":["4"],"6":"instancetype","whencreated":["20171101082658.0Z"],"7":"whencreated","whenchanged":["20171101082648.0Z"],"8":"whenchanged","displayname":["Amitabh Singh Bachchan"],"9":"displayname","usncreated":["46024767"],"10":"usncreated","usnchanged":["46024767"],"11":"usnchanged","company":["xxx.org"],"12":"company","name":["Amitabh Singh ...`

Prior to calling this block of code, I'm using ADLdap to do the following operations:

1. Create user in AD
2. Add to Group
3. Set password
4. Disable account

All 4 steps are going through without hiccup - but it's failing at this step when I try to enable the account.

Thanks,
sourjya

**Comment by stevebauman** [comment]
Hi @sourjya, `Server unwilling to perform` isn't an issue with Adldap, it's actually an issue with the server.

This is usually a connection issue, and it's likely that when you set the account to disabled and try to save it, it's saying you're not allowed to do so (likely due to not being secure).

Are you also using an SSL or TLS connection? This is required when setting or resetting passwords.

Can I also see the code where you're setting the password?

**Comment by sourjya** [comment]
Hi,
    Sorry I should have updated earlier. I'm using SSL. I spotted the issue. I'm using ADLDAP to create new accounts, that by default, require passwords to be changed upon first login and also are in the disabled state. If I attempt to enable such accounts (without changing password first) via ADLDAP, this error is being thrown. If I take an alternative approach i.e., change password first and then enable, no more error.

Thank you for your help.

- Sourjya

**Comment by stevebauman** [comment]
Ohh OK great, thanks so much for following up and letting me know, this is great for other users who may have the same issue.

Thanks again :).
