### ISSUE TITLE
auth() return false openLDAP with samaccountname for username

### ISSUE THREAD

**Issue by ikwijaya** [Adldap2/Adldap2#457]
- Adldap2 Version: #.#
- LDAP Type: OpenLDAP
- PHP Version: 7.0

### Description:
Sir @stevebauman, i need your help.. ;-)

I try to login to openldap, with samaccountname and password but always return false. 
`dd($provider->auth()->attempt($username,$password,true));`

but if try to login to AD, with samaccountname and password it return true. Maybe i wrong with my config or username i used? maybe use userprincipalnames or anything i dont know. And how to change it.

here my configuration:
`'LDAP_CONFIG' => [
        'domain_controllers'    => ['192.168.0.1'],
        'base_dn'               => 'DC=company,DC=corp,DC=local',
        'admin_username'        => 'admins',
        'admin_password'        => 'secret_password',
        'port'                  => 389,
        'follow_referrals'      => true, 
        'use_ssl'               => false,
        'use_tls'               => false,
        'timeout'               => 5,
        'custom_options'        => [
            LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_HARD,
            LDAP_OPT_REFERRALS          => 0,
            LDAP_OPT_PROTOCOL_VERSION   => 3,
            LDAP_OPT_DEBUG_LEVEL        => 7
        ],`

### Steps To Reproduce:

thanks, and cheers

ikwijaya

**Comment by ikwijaya** [comment]
close, 
sorry finally my wrong.

need use : account_suffix in config if use samaccountname for auth attempt.

thanks

**Comment by stevebauman** [comment]
No problem, thanks for following up @ikwijaya!
