### ISSUE TITLE
Get User Account name

### ISSUE THREAD

**Issue by jonesc11** [Adldap2/Adldap2#460]
- Adldap2 Version: 8.0
- LDAP Type: Active Directory
- PHP Version: 7.0.22

### Description:
What I'm trying to do is get all of the users from my AD server, and then run through them and connect them to a SQL database by their username (an example is that 'John Doe' would have a username of 'jdoe'). My main issue is that I can't figure out how to get 'jdoe' from the list of all users (that I got with '$users = $provider->search()->users()->get();'). When I print_r the individual user objects, I can see that the samaccountname is the value that I'm looking for, but I can't find any functions in the user model to let me pull from that.

I know it's probably a stupid question, but thanks for the help!

**Comment by stevebauman** [comment]
Hi @jonesc11,

When results are returned, they are returned in a `Collection`. Each item in the collection is a an Adldap `Model` instance.

To answer your question, you can do this is a couple ways:

### Iterating through each user:
```php
$users = $provider->search()->users()->get();

foreach ($users as $user) {
    $user->getAccountName();
}
```

### Retrieving an array of only usernames:
```php
$users = $provider->search()->users()->get();

$usernames = $users->map(function ($user)) {
    return $user->getAccountName();
});
```

If you need any further assistance, just leave another comment and I'll gladly help you out :).
