### ISSUE TITLE
Removing an address from proxyAddresses and saving does not work

### ISSUE THREAD

**Issue by KuenzelIT** [Adldap2/Adldap2#466]
- Adldap2 Version: 7.0.15
- LDAP Type: Active Directory
- PHP Version: 7.1.10

### Description:
Removing an address from proxyAddresses and saving does not work. As far as I see, the `getDirty()` function on the User Model thinks that the attribute did not change. There is no comparison of the array values.

Am I using it wrongly? Thanks!

### Steps To Reproduce:
Get a random user from the directory, remove an address from `getProxyAddresses()`, use `setProxyAddresses()` and `save()`.

**Comment by stevebauman** [comment]
Thanks @KuenzelIT! Looks like this was affected when a change was made on how dirty attributes are retrieved.

This will be fixed shortly.

**Comment by stevebauman** [comment]
Hi @KuenzelIT, a new release will be out shortly with this fix.

Thanks again!

**Comment by KuenzelIT** [comment]
Thanks for fixing this issue so quick!

**Comment by stevebauman** [comment]
No problem! Thanks for the report :smile:
