### ISSUE TITLE
setThumbnail using base64 encoding --> not working for our AD

### ISSUE THREAD

**Issue by KuenzelIT** [Adldap2/Adldap2#467]
- Adldap2 Version: 8.0.7
- LDAP Type: Active Directory
- PHP Version: 7.1.10

### Description:
My active directory does not save thumbnails photos as base64 encoded and I cannot find any reference that clearly states, that the photo has to be base64 encoded. Using our webmailer and choosing the photo there, it doesn't save the base64 encoded image either. If I remove the base64 encoding code from setThumbnail(), everything works like expected.

To make this clear: the base64 encoded string is being saved, but our Skype4Business and Webmailer cannot handle that format.

Do you have any reference for using base64 encoding? Or is there a config option maybe?

Thanks!

### Steps To Reproduce:
Use `setThumbnail()` method with an appropriate image file.

**Comment by KuenzelIT** [comment]
For testing purposes, I just removed the base64 encoding code from the User class.

The secondary argument sounds good.

**Comment by stevebauman** [comment]
Ok, I'm just curious what data you're inserting into the method? Is it raw image binary data? Or some other type of encoded image?

For example:

```php
$image = file_get_contents('image.jpg');

$user->setThumbnail($image);
```

**Comment by KuenzelIT** [comment]
Sorry, didnt' get your question there.

It's the image file that the user can upload, so it's just binary image data:

```php
$content = File::get($request->file('photo'));
$User->setThumbnail($content);
$User->save();
```

Which does exactly the same as your example.

**Comment by stevebauman** [comment]
No problem! Perfect, that's all the information I need.

Fixing now :smile:

**Comment by KuenzelIT** [comment]
Thank you for fixing this so quick again.

I don't get the newest version currently by requiring adldap2-laravel, since it points to version 8.0.7 without this fix. Do you have some kind of release cycle?

**Comment by stevebauman** [comment]
No problem!

I'm working on releasing `v4.0` of the Adldap2-Laravel package, which will include the latest release of `v8.0.*` of Adldap2. It's going to include a bunch of new features and fixes.

However right now you can set the attribute manually:

```php
$content = File::get($request->file('photo'));

$user->thumbnailphoto = $content;

$user->save();
```

**Comment by KuenzelIT** [comment]
I should have known that! :)

Thank you!
