### ISSUE TITLE
Error while setting 'userworkstations' attribute on User model

### ISSUE THREAD

**Issue by crux-capacitor** [Adldap2/Adldap2#468]
- Adldap2 Version: 7.0.15
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:
I'm attempting to set the 'userworkstations' attribute on the User model so that I can control the systems that a user can log onto. By manually setting this field in the domain, I found that it creates an array on the User model, like this:

"userworkstations" => array [
0 => "hostname1",
1 => "hostname2"
]

In my code, I have an associative array called $input, with an element called 'systems' with an array of hostnames, like this:
`$input = [
    'systems' = [
        'hostname1',
        'hostname2'
    ]
];`

After getting the User's LDAP model, I'm trying to set the 'userworkstations' attribute like this:

```
$ldap->userworkstations = null;
if($ldap->save()) #save 1
{
    $ldap->userworkstations = $input['systems'];
    if($ldap->save()) #save 2
    {
        dd($ldap);
    }
}
```
Save1 always works. Save2 works if $input['systems'] has only 1 element. If I have more than 1, I get the following error:

 "ErrorException in Ldap.php line 302:
 ldap_modify_batch(): Batch Modify: Type or value exists"

Help please!

**Comment by stevebauman** [comment]
Hi there,

Are there any duplicates in your hostnames array?

**Comment by crux-capacitor** [comment]
Hi Steve, no there aren't.

**Comment by crux-capacitor** [comment]
Steve,

I've tried a few other things.

createAttribute fails and says that the attribute already exists.

setAttribute('userworkstations', $input['systems']) throws the same error as in the original post.

Looping over the array of systems and doing $ldap->userworkstations[] = $system throws the "Indirect modification of overloaded property" error. 

Any ideas?

**Comment by stevebauman** [comment]
Hi @crux-capacitor, going to test this on my end tomorrow and will let you know of my findings.

**Comment by crux-capacitor** [comment]
Hi Steve. Just checking if you were able to test this out. Thanks.

**Comment by crux-capacitor** [comment]
Steve? Anyone?

**Comment by stevebauman** [comment]
Hi @crux-capacitor, testing this now, I receive the same exception if I have more than one workstation that I'm adding at once.

Looking into this, thanks!

**Comment by stevebauman** [comment]
Hey @crux-capacitor, got it.

The `userworkstations` attribute is only supposed to be single valued:

https://msdn.microsoft.com/en-us/library/ms680868(v=vs.85).aspx

You have to implode your workstations array into a comma separated list, and save it to the user:

```php
$ldap->userworkstations = null;

if($ldap->save())
{
    $workstations = implode(',', $input['systems']);
    
    $ldap->userworkstations = $workstations;
    
    if($ldap->save())
    {
        // Updated workstations.
    }
}
```

Just test and works great. I'm going to implement a method to set the workstations with an array that will do this for you. Then I'll close this issue.

**Comment by stevebauman** [comment]
Added: https://github.com/Adldap2/Adldap2/commit/a06cb570e285c58f225d4a0c179600b3fe075de7

**Comment by crux-capacitor** [comment]
Awesome! Thank you Steve. It works! 

One more thing I just found out while testing it is that if you are RDPing to one of the workstations that were set, the system you are RDPing from must also be in the list of allowed workstations.

**Comment by stevebauman** [comment]
No problem! Sorry for the wait on this 😅 

That's definitely good to know for the future, as I'm sure more people will be looking for this functionality.
