### ISSUE TITLE
Instead of hardcoded classes, is it possible to use classes from the schema?

### ISSUE THREAD

**Issue by tortuetorche** [Adldap2/Adldap2#471]
- Adldap2 Version: ad681914db847be437cc84b6b277305fedef4323
- LDAP Type: OpenLDAP
- PHP Version: 7.0

### Description:
Hi,

I use a custom OpenLDAP schema, where the `OpenLDAP::groupModel()` returns a `Adldap\Models\OrganizationalUnit` class.

But I can't get the groups (organizational units in reality) of my current user, because of this hardcoded class: https://github.com/Adldap2/Adldap2/blob/526cba85e3baca936b918abb7e7867c110d81ff6/src/Models/Concerns/HasMemberOf.php#L195

So, is it possible to replace this code:
```php
$group instanceof Group
```
By this one:
```php
is_a($group, $this->schema->groupModel())
```
Of course it could also be done for other classes than the `Group` one.

Cheers,
Tortue Torche

**Comment by stevebauman** [comment]
Hi @tortuetorche,

Why are you returning the `OrganizationalUnit` class from the `groupModel` method?

A group and organizational unit are completely different objects in LDAP.

**Comment by stevebauman** [comment]
Actually, even still I should implement your suggestion to allow developers to do as they please.

Will be fixed shortly :).

**Comment by tortuetorche** [comment]
Why not 😉? The LDAP schema at my job is structured like that, the user applications are OU entries... And I can't change the LDAP schema.

**Comment by stevebauman** [comment]
Yea sounds good :smile:, new release will be out shortly, thanks @tortuetorche!
