### ISSUE TITLE
getThumbnailEncoded() not working

### ISSUE THREAD

**Issue by cluwong** [Adldap2/Adldap2#473]
- Adldap2 Version: 8.0
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:

When trying to display user's thumbnail image using base 64 image encode, (in <img src=..... />) nothing is displayed. The function getThumbnailEncoded() always returns null on accounts where there are data in thumbnailphoto.
Previously used V6 and thumbnail was displaying, but stopped displaying once upgraded to V8.

On code reading getThumbnailEncoded(), the function tried to decode thumbnailphoto first - Why is it decoded first? Isn't the data for thumbnailphoto that needs to be encoded?

I tried to replicate and modify the function as standalone function for testing and the image is displayed:

```php
public static function getThumbnailEncoded($thumbnail)
    {
        if ($thumbnail) {
            // In case we don't have the file info extension enabled,
            // we'll set the jpeg mime type as default.
            $mime = 'image/jpeg';
            $image = base64_encode($thumbnail);
            if (function_exists('finfo_open')) {
                $finfo = finfo_open();
                $mime = finfo_buffer($finfo, $image, FILEINFO_MIME_TYPE);
                return "data:$mime;base64,$image";
            }
            return "data:$mime;base64,$image";
        }
    }
```

**Comment by stevebauman** [comment]
Hi @cluwong, you don't need to utilize the `getThumbnailEncoded()` method. If your thumbnails are already decoded, simply use the `getThumbnail()` method:

https://github.com/Adldap2/Adldap2/blob/master/src/Models/User.php#L787

As always, you can access all raw user attributes via: `$user->thumbnailphoto`.
