### ISSUE TITLE
Cannot set up traits to get the groups. bind_user_to_model does not exist

### ISSUE THREAD

**Issue by encrush** [Adldap2/Adldap2#475]
- Adldap2 Version: latest
- LDAP Type: FreeIpa 
- PHP Version: 7

### Description:
hello iam new to ldap, and i was asked to connect to an already set up ldap server with FreeIPA. The thing is that i managed to make the connection and get all the accounts synchronized to my user table from the ldap. But i cannot get the groups. There is no bind_user_to_model option in the config, i wonder how can i add it. And then i dont know how to use the traits to get the groups. Sorry if these are stupid questions or if i am reffering to the wrong thread. But it took me like 2 weeks now reading everything. Can you help me set up the traits to get the groups? What procedure do i need to follow to set things up?? thank you in advance!!

when i do that "$users = Adldap::search()->users()->get();" i get the users. But when i try to "$groups = $user->adldapUser->getGroups();" iam getting this error "Trying to get property of non-object". The point is that when i try to "$user->adldapUSer" iam getting null. Is that a set up problem or iam doing something obvious stupid thing?? again sorry that this issue might be newbie one but i want some guidence. Thank you!

now, when i try to getGroups i am gattng this error. "call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Connections\Provider' does not have a method 'getGroups'"

i edited this post because i am having these issues, and i believe they are all related.

**Comment by encrush** [comment]
i need to add something to the query above. when i do that "$users = Adldap::search()->users()->get();" i get the users. But when i try to "$groups = $user->adldapUser->getGroups();" iam getting this error "Trying to get property of non-object". The point is that when i try to "$user->adldapUSer" iam getting null. Is that a set up problem or iam doing something obvious stupid thing?? again sorry that this issue might be newbie one but i want some guidence. Thank you!

**Comment by stevebauman** [comment]
Hi @encrush,

Have you inserted the `HasLdapUser` trait onto your `app/User.php` model as shown in the model binding documentation?

https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#model-binding

The `bind_user_to_model` option was depreciated and removed in the new version of Adldap2-Laravel and was replaced by using a trait instead.

**Comment by stevebauman** [comment]
> Iam authenticating through laravels authenticator beacuse i imported all the users and passwords from the ldap with the artisan command you say in the documentation(is it mandatory to authenticte directly through ldap?).

The importer does not import password from your LDAP server, it sets a random 16 character password.

Passwords can only be synchronized while using the `adldap` auth driver and having the `sync` option in your configuration enabled.

You can retrieve the currently authenticated users LDAP details in the following scenario:

- You have properly set up the [Adldap2-Laravel Auth driver](https://github.com/Adldap2/Adldap2-Laravel/blob/master/docs/auth.md#installation)
- You have enabled the `adldap` auth driver in your `auth.php` (shown in the above setup guide)
- You are authenticating users normally using Laravel's `Auth::attempt()`
- You have inserted the `HasLdapUser` trait onto your `app/User.php` model

Once you have completed all of those steps, you can retrieve the currently authenticated users LDAP details via:

```php
$user = Auth::user();

$user->ldap->getGroups();
$user->ldap->getCommonName();
$user->ldap->getAccountName();

// etc...
```

**Comment by encrush** [comment]
as you say i have done all th steps. let me show you my model and controller to see what iam doing wrong because as you say i should get all the groups i need. 

User model:
<?php
namespace App;

use Adldap\Laravel\Traits\HasLdapUser;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, HasLdapUser;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

Controller:

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Adldap\AdldapInterface;
use Adldap\Laravel\Facades\Adldap;
use Illuminate\Support\Facades\Auth;
use Adldap\Models\Traits\HasMemberOf;


class DdController extends Controller
{

	protected $adldap;


	public function __construct(AdldapInterface $adldap)
    {
        $this->adldap = $adldap;
    }


    public function index()
    {
    	$user = Auth::user(); // when iam var_dump the user i am getting the authenticated user correctlly 

    //$users = $this->adldap->search()->users()->get(); //i am getting all the users correctlly

    //$groups = $user->adldap->getGroups(); // iam getting this error :"Call to a member function getGroups() on null"

    //var_dump($user);
   }
}

obviously iam missing something here, probably something to obvious...

**Comment by encrush** [comment]
let me show you my User model and my Controller iam using right now:

User model:
namespace App;


use Adldap\Laravel\Traits\HasLdapUser;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, HasLdapUser;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}



Controller
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Adldap\AdldapInterface;
use Adldap\Laravel\Facades\Adldap;
use Illuminate\Support\Facades\Auth;
use Adldap\Models\Traits\HasMemberOf;


class DdController extends Controller
{

	protected $adldap;


	public function __construct(AdldapInterface $adldap)
    {
        $this->adldap = $adldap;
    }


    public function index()
    {
    	$user = Auth::user();

    //$users = $this->adldap->search()->users()->get(); //iam getting all the users correctly

    $groups = $user->adldap->getGroups(); //iam getting here "Call to a member function getGroups() on null"

    var_dump($groups);
    }

}
 

What am i missing here?

**Comment by encrush** [comment]
ok update. i managed to get this work, but, the softdeletes trait it gives me an error now. I am getting that now "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.deleted_at' in 'where clause' (SQL: select * from `users` where `id` = 30 and `users`.`deleted_at` is null limit 1)".  When i exclude it from the User model i get results, but i need to understand how to use them. 

- Is this Softdeletes improtant?

**Comment by stevebauman** [comment]
Hey @encrush, this line is incorrect:

```php
// Incorrect.
$groups = $user->adldap->getGroups();

// Correct.
$groups = $user->ldap->getGroups();
```

Using SoftDeletes is up to you, it allows you to recover users you have deleted. But if you have inserted the SoftDeletes trait on your `app/User.php` model, you need to modify your `create_users_table` migration, as the SoftDeletes trait requires a new database column in your `users` table named `deleted_at`.

Going to close this as it seems you're all set, but if not just let me know and I will re-open, thanks!

**Comment by encrush** [comment]
Hello again! Your help so far was very important. Had to pause working on the project dude to some reasons but now we restarted it. I managed to get the groups but what i want to ask is: When i need to vefrify that a user is member of a group so as to create Access levels how i need to do it? 

i tried doing it this way.
 $group = $user->ldap->search()->groups()->findByDn('cn=admins,cn=groups,cn=accounts,dc=intersos,dc=local'); 

so what am i asking is how i will get an array of results with all the groups the authenticated user is in.

so how will i get the memberof property.

Iam asking because i need to understand. Can i import the HasMemeberOf trait? or am i confusing things?

**Comment by stevebauman** [comment]
Hi @encrush,

Don't use the `HasMemberOf` trait. It's used internally for Adldap2 models.

If you want **just** the distinguished names of groups in an array that the user is a member of, simply acess it like a property:

```php
$groups = $user->ldap->memberof;
```

The `getGroups()` method simply queries your LDAP server using the users `memberOf` attribute and **returns a collection of Group *models* that your user is a member of**.

For example:

```php
$groups = $user->ldap->memberof;

var_dump($groups);

// array ['cn=Group One,dc=acme,dc=org', 'cn=Group Two,dc=acme,dc=org'];

$groups = $user->ldap->getGroups();

var_dump($groups);

// Illuminate\Support\Collection(Group, Group)
```

**Comment by encrush** [comment]
@stevebauman  thank you for your help. Your answers helped me understand. I think you can close this thred. 👍

**Comment by stevebauman** [comment]
No problem @encrush. It's on the main page under model documentation:

https://github.com/Adldap2/Adldap2/blob/master/docs/models/user.md
