### ISSUE TITLE
ou model missing setDescription() method

### ISSUE THREAD

**Issue by MattBianco** [Adldap2/Adldap2#476]
- Adldap2 Version: 8.0
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:
ou lacks setDescription() method:
PHP Warning:  Uncaught Error: Call to undefined method Adldap\Models\OrganizationalUnit::setDescription() in php shell code:1

It works with group, but not with ou.

### Steps To Reproduce:
$ou=$provider->make()->ou();
if(empty($ou)) {
    return false;
}
$ou->setDn('OU=newOu,OU=parentOu,DC=blah,DC=local');
$ou->setDescription('Created '.date('Y-m-d H:i:s').'); // FAILS with undefined method.

**Comment by stevebauman** [comment]
Hi @MattBianco,

Thanks, going to resolve this now.
