### ISSUE TITLE
OpenLDAP objects

### ISSUE THREAD

**Issue by mryndin** [Adldap2/Adldap2#478]
- Adldap2 Version: #.#
- LDAP Type: OpenLDAP
- PHP Version: #.#

### Description:
OpenLDAP has different categories & classes. In case use OpenLDAP php can not fetch users(), groups() and etc... As result, I can`t select Adldap\Models\User

Can you add any flag to configuration for switch between using LDAP namespace or autodetect using LDAP server ?

### Steps To Reproduce:

// get all users
$userRecord = $provider->search()->users()->get();

            print_r($userRecord);

// get one user OpenLDAP specific (not Person, using People).
            $userRecord = $provider->search()->findByDn("uid={$username},ou=People,{$foundCompany->Domain}");

            print_r($userRecord);
            die();

**Comment by stevebauman** [comment]
Hi @mryndin, this is already implemented, and I'm surprised but I don't actually have documentation on this, so I will definitely create some.

Adldap2 uses a `Schema` object for different LDAP server types (in your case: OpenLDAP).

You will need to insert this schema when you create a new provider:

```php
use Adldap\Schemas\OpenLDAP;
use Adldap\Connections\Provider;

$config = ['...'];

// We pass in `null` into the second parameter
// so a default connection will be created.
$provider = new Provider($config, $connection = null, new OpenLDAP());

$users = $provider->search()->users()->get();
```

You will then be able to retrieve users / groups etc.

Let me know if you encounter any other issues!

**Comment by mryndin** [comment]
Ok, Thanks ! For continue this theme.

In OpenLDAP I select user,  he is member of two groups, but for

$userRecord = $provider->search()->users()->where('cn' ,'=', $username)->first();

$groups=$userRecord->getGroups();

print_r($groups);


I look result:

Illuminate\Support\Collection Object ( [items:protected] => Array ( ) )

Why ?!

**Comment by TwoHorus** [comment]
Same here.

**Comment by stuntguy3000** [comment]
https://github.com/Adldap2/Adldap2/issues/479

Same here also... @stevebauman
