### ISSUE TITLE
How to add custom attributes to the model

### ISSUE THREAD

**Issue by mehrdaad** [Adldap2/Adldap2#480]
- Adldap2 Version: 4.0.4
- LDAP Type: OpenLDAP
- PHP Version: 7.2

### Description:
My OpenLDAP has some attributes not implemented on Adldap\User Model.  
The question is simple: how to customize the user model so that other methods are added to it?  
also, all Adldap user related methods should return this User.

**Comment by stevebauman** [comment]
Hi @mehrdaad,

You'll need to create your own custom schema and a custom `User` model.

Please take a look at the documentation here:

https://github.com/Adldap2/Adldap2/blob/master/docs/models/model.md#extending

If you encounter any issues just comment back and I'll re-open this. Thanks!

**Comment by mehrdaad** [comment]
Totally solves my problem, thank you.

**Comment by mehrdaad** [comment]
Sorry, this is Laravel specific. 
 In a constructor class, I've set one dependency as ``SchemaInterface`` but Laravel gives an error:  
```
Target [Adldap\Schemas\SchemaInterface] is not instantiable while building [App\Repository\Provider\LdapUserProvider].
```
I do believe adlap should register a singleton in it's provider making a singleton like this:  
```
   $this->app->singleton(SchemaInterface::class, function ($app) {
           $className =  config('adldap.connections.default.schema');
            return new $className();
        });
```
shouldn't it?

**Comment by mvatansever** [comment]
Yes, you should be defined an implementation of interface to resolve it the Laravel IoC.
