### ISSUE TITLE
Add postOfficeBox getter to the user model

### ISSUE THREAD

**Issue by MrCrankHank** [Adldap2/Adldap2#482]
- Adldap2 Version: 8.0.10
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:
Hey guys,

could you add a getter for the "postOfficeBox" Active Directory attribute on the User Model?

If you would accept a pull request, i could also save you the work and add it myself.

Thanks.

**Comment by stevebauman** [comment]
Hi @MrCrankHank, no problem, it's been added.

Thanks! :)
