### ISSUE TITLE
Why is OpenLDAP renamed to OpenSchema 

### ISSUE THREAD

**Issue by mehrdaad** [Adldap2/Adldap2#483]
- Adldap2 Version: master
- LDAP type: OpenLDAP

Hey, after submitting my PR to this repo, there has been some refactorings,  
I see BaseLDAP is renamed to BaseSchma which makes sense but why is OpenLDAP renamed to OpenSchema?  
since this name is a known implementation of LDAP I see no reason in changing its name to sth else.  
It's like renaming ActiveDirectory class to ActiveSchema!

**Comment by pascalbaljet** [comment]
This is also a breaking change.

**Comment by stevebauman** [comment]
Sorry guys, I no idea how this happened, completely my fault.

Just pushed out a new release that fixes the class name.

**Comment by 36864** [comment]
I have an idea of how it happened. Replace All is a dangerous tool!

**Comment by stevebauman** [comment]
Lol such a rookie mistake by me, apologies again everyone. I face palm'ed hard when I saw this.

I'll definitely be vetting my releases much harder now.
