### ISSUE TITLE
Find : Internal error without logs

### ISSUE THREAD

**Issue by morreelsm** [Adldap2/Adldap2#484]
- Adldap2 Version: 8.0.10
- LDAP Type: Activedirectory
- PHP Version: 5.6.29

### Description:
Find function : Internal error without logs and error message
With php 7 no problem 

### Steps To Reproduce:

```php
      $provider = new \Adldap\Connections\Provider($this->ldapConfig);
        $username = $request->getParsedBody()['username'];
        $password = $request->getParsedBody()['password'];
        if (!empty($password) && $provider->auth()->attempt($username, $password)) {
            try {
                $user = $provider->search()->findOrFail('samaccountname',username );
                die($user->getAttribute('cn', 0)); //test user data
            } catch (\Adldap\Models\ModelNotFoundException $e) {
                die($e->getMessage());
            }
```

**Comment by stevebauman** [comment]
Hi @morreelsm, can you post the exact exception you're receiving?

**Comment by morreelsm** [comment]
no ModelNotFoundException has catch, no error displayed, no error in log file.

Another exception has possible ?

**Comment by stevebauman** [comment]
I don't think I'm understanding your issue.

What are you looking to achieve and what is happening?

Are you saying no exception is being thrown when the user is not found?

**Comment by stevebauman** [comment]
Also this usage is incorrect:

```php
$user = $provider->search()->findOrFail('samaccountname',username );
```

It should just be:

```php
$user = $provider->search()->findOrFail($username);
```

**Comment by morreelsm** [comment]
it does not work :
`
$user = $provider->search()->findOrFail($username);
`

After login/password check, I load the user data from the AD.
authentication is good so the user is good

This problem is only with php 5.6, not in 7

**Comment by stevebauman** [comment]
Okay, but do you receive an exception at all in PHP 5.6?

What is returned from the findOrFail call on 5.6?

I need more information to help you.

**Comment by morreelsm** [comment]
The function crash in findOrFail function without exception

```php
try {
                $u = $request->getParsedBody()['username'];
                $user = $provider->search()->findOrFail($u);
                die($user->getAttribute('cn', 0));
            } catch (\Adldap\Models\ModelNotFoundException $e) {
                die('ModelNotFoundException:' . $e->getMessage());
            } catch (\Exception $e) {
                die('Exception:' . $e->getMessage());
            } finally {
                die('Finaly');
            }
```

**Comment by stevebauman** [comment]
Okay, so from the code you posted, nothing happens? You just receive a blank screen?

How do you know it crashed?

**Comment by morreelsm** [comment]
Just return code 500 Internal Error

**Comment by stevebauman** [comment]
You'll need to check your **PHP 5.6 error logs** (not your application error logs) located in your PHP installation folder. They will contain the exception information.

Closing for now as this seems like an application issue, not an Adldap2 issue.

**Comment by morreelsm** [comment]
Ok!!  thanks but I said that I had nothing in the log (also PHP log and apache and screen and nowhere else).

You have test this code in a 5.6 env ?

My application use your code in php 7 env and it's ok, no probleme, he returns the good information but this same application in a php 5.6 env return nothing and nothing in logs and I have no information about the exception. 

I thought of a server problem, but I also have it on another server

**Comment by stevebauman** [comment]
Adldap2 is tested against PHP 5.5, 5.6, 7.0, 7.1 and 7.2:

https://travis-ci.org/Adldap2/Adldap2

You'll need to debug this as I have no information to work with on what's going on in your application.
