### ISSUE TITLE
Can't contact LDAP server with Ip Address

### ISSUE THREAD

**Issue by berkaygure** [Adldap2/Adldap2#486]
- Adldap2 Version: 7
- LDAP Type: Active Directory
- PHP Version: 7.2

### Description:
Hi, 
I try connect to ldap server with ip address but i get error like this: 
 [Adldap\Auth\BindException]  
 Can't contact LDAP server  

but when i changed getConnectionString method: (Ldap.php line 451)
`return "{$protocol}{$host}:{$port}`
to 
`return "{$protocol}{$host}`

and connect method in Ldap.php line 219

` return $this->connection = ldap_connect($connections);`
to
`return $this->connection = ldap_connect($connections, $port)`

it's works. 
What do you suggest?

**Comment by stevebauman** [comment]
Hi @berkaygure, what do you have your port set to in your configuration?

I believe this is likely the cause.

**Comment by berkaygure** [comment]
I use 636.

**Comment by stevebauman** [comment]
Use port `389` and try again.

**Comment by berkaygure** [comment]
This is not our port.

**Comment by stevebauman** [comment]
It has to be if removing the port from the connection string works, because `389` is the default LDAP port.

**Comment by stevebauman** [comment]
See: http://php.net/manual/en/function.ldap-connect.php

> **port** 
> The port to connect to. **Not used when using LDAP URIs**.

**Comment by berkaygure** [comment]
thanks
