### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by lledo3** [Adldap2/Adldap2#488]
Hello,

Wanted to know if there was work around for resetting a user password but still make sure the password follows any password policies that have been created in AD. Currently if a user wants to reset there password we bind an admin account to it which bypasses the password policies. I just want to know if there is way to check the password policies as well.

**Comment by stevebauman** [comment]
Hi @lledo3, policies shouldn't be bypassed even with an administrator account.

However, I would try binding as the user and give that a shot. For example:

> **Note** The third argument in the `attempt()` method.

```php
$username = 'jdoe';
$password = 'password123';
$newPassword = 'mynewpassword';

if ($provider->auth()->attempt($username, $password, $bindAsUser = true)) {
    // User is now bound to your LDAP server.
    // Try and perform a password change:
    
    $user = $provider->seach()->users()->find($username);

    if ($user->changePassword($password, $newPassword)) {
        // Password was changed.
    }
}
```

**Comment by lledo3** [comment]
Yes, but my issue is the user can reset there password to same password multiple times. I'm trying to prevent this. Some how my password policy is bypassed which doesn't catch this.

**Comment by lledo3** [comment]
Would there be an attribute that finds the password history in adldap? Then perform a check against that before changePassword().

**Comment by stevebauman** [comment]
Hi @lledo3,

> Some how my password policy is bypassed which doesn't catch this.

To be honest, it sounds like your password policy isn't configured correctly on your AD server.

> Would there be an attribute that finds the password history in adldap? Then perform a check against that before changePassword().

Unfortunately no. **No passwords or history** are visible in Active Directory, or in any LDAP distro to my knowledge.

You could prevent users from setting the same password by trying to authenticate them against your LDAP server with their **new password** and then rejecting them if it passes since it's the same.

This would really be your only option if you're not able to resolve the password policy issue on your LDAP server itself.

**Comment by chriseskow** [comment]
> To be honest, it sounds like your password policy isn't configured correctly on your AD server.

@stevebauman I work with @lledo3 and, as far as I know, our password policy is correct. Administrative password resets not enforcing the password history policy is [a "feature" of AD](https://serverfault.com/a/599458).

> You could prevent users from setting the same password by trying to authenticate them against your LDAP server with their new password and then rejecting them if it passes since it's the same.

I believe the problem with this is if the user's password has expired (which I think is the usual impetus to use the password reset feature in our PHP app), the authentication attempt will **always** fail - regardless of whether the new password was the same as the old one or not. So in that case we'd have no way of knowing if they're using the same password or not.

**Comment by stevebauman** [comment]
Hey @chriseskow,

> @stevebauman I work with @lledo3 and, as far as I know, our password policy is correct. Administrative password resets not enforcing the password history policy is a "feature" of AD.

I guess you pretty much answered you're own question there, I was actually unaware of this since I've never tried to change a password with the history policy applied... Thanks for educating me! 😄 

It seems there isn't really a way around this... The only thing you can really do is keep a password history in the local application.

**Comment by chriseskow** [comment]
In case anyone else ran into this issue, we found a way to force AD to enforce the password history policy by setting a server control option:

```php
    // Tell AD to enforce password history policy for password resets
    $provider->getConnection()->setOption(LDAP_OPT_SERVER_CONTROLS, [
        [
            'oid' => '1.2.840.113556.1.4.2239',
            'value' => sprintf('%c%c%c%c%c', 48, 3, 2, 1, 1),
        ],
    ]);
```

(Note that setting this via `custom_options` currently doesn't work due to #492)

See also: https://stackoverflow.com/a/26763748

**Comment by stevebauman** [comment]
Cool! Thanks for sharing @chriseskow.

I'll be sure to put this in the documentation after fixing #492.
