### ISSUE TITLE
Search() methods with last release

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#49]
Hi ! 

Just an information. With your new commit, there are some changes with search() methods ? I saw that you write some changes in class. Theses changes are definitive or you will upgrade your code to be compatible with the previous versions ?

Thanks

**Comment by stevebauman** [comment]
Hi, the changes are there to stay, but you won't have to change any of your code. It's mostly all backwards compatible (with the exception of the removal of `getQuery()` from the `Search` class. The search class implements the [`__call()` magic method](https://github.com/Adldap2/Adldap2/blob/master/src/Classes/Search.php#L84) which runs calls on the query builder instance if the method doesn't exist in the search class. So for example, even though the `whereHas()` method doesn't exist in the search class, it will be ran under the Query Builder:

```php
$ad->search()->whereHas('cn')->get();
```
