### ISSUE TITLE
'custom_options'

### ISSUE THREAD

**Issue by lledo3** [Adldap2/Adldap2#492]
I'm trying to use the LDAP_OPT_SERVER_CONTROL in the 'custom_options' in my $config array. From http://php.net/ldap_set_option the type is an array. I tried this way:

`'custom_options' => [
           LDAP_OPT_SERVER_CONTROLS => [
               [
                   'oid' => '1.2.840.113556.1.4.2239',
                   'value' => sprintf('%c%c%c%c%c', 48, 3, 2, 1, 1),
               ],
           ],
        ],
`
But it's not working. So then I tried this:

`'custom_options' => [
	LDAP_OPT_SERVER_CONTROLS => array(
		'oid' => '1.2.840.113556.1.4.2239',
		'value' => sprintf('%c%c%c%c%c', 48, 3, 2, 1, 1))
],`

Still not working correctly. Is there a certain syntax I'm missing when setting the 'custom_options'?

**Comment by lledo3** [comment]
I just tried this way:

_$ctrl1 = ['oid' => '1.2.840.113556.1.4.2239',
               'value' => sprintf('%c%c%c%c%c', 48, 3, 2, 1, 1)];_

and then added the $crtl1 along with ldap_set_option and set that to 'custom_option'


_$config = [
    'domain_controllers'    => ['corp-dc1.corp.acme.org', 'corp-dc2.corp.acme.org'],
    'base_dn'               => 'dc=corp,dc=acme,dc=org',
    'admin_username'        => 'admin',
    'admin_password'        => 'password',
    'account_prefix'        => 'ACME-',
    'account_suffix'        => '@acme.org',
    'admin_account_prefix'  => 'ACME-ADMIN-',
    'admin_account_suffix'  => '@acme.org',
    'port'                  => 389,
    'follow_referrals'      => false,
    'use_ssl'               => false,
    'use_tls'               => false,
    'timeout'               => 5,
    'custom_options' => [LDAP_OPT_SERVER_CONTROLS, array($ctrl1)],
];_

The setOption() is suppose to return ldap_set_option($this->getConnection, $option, $value) but I'm not sure why this isn't working. This will enforce AD password history.

**Comment by lledo3** [comment]
So here is a work around that works but I'm trying to have it work with using the 'custom_options' in the $config array like how I explained above:


```
function adLdapCon($username, $password)
{
    $config = [
        'domain_controllers' => ['corp-dc1.corp.acme.org', 'corp-dc2.corp.acme.org'],
        'base_dn' => 'dc=corp,dc=acme,dc=org',
        'admin_username' => '$username',
        'admin_password' => '$password',
        'account_prefix' => 'ACME-',
        'account_suffix' => '@acme.org',
        'admin_account_prefix' => 'ACME-ADMIN-',
        'admin_account_suffix' => '@acme.org',
        'port' => 389,
        'follow_referrals' => false,
        'use_ssl' => false,
        'use_tls' => false,
        'timeout' => 5,
    ];

    $ctrl1 = ['oid' => '1.2.840.113556.1.4.2239',
               'value' => sprintf('%c%c%c%c%c', 48, 3, 2, 1, 1), ];

    $provider = new Provider($config);

    if (!ldap_set_option($provider->getConnection()->getConnection(), LDAP_OPT_SERVER_CONTROLS, [$ctrl1])) {
        error_log('ERROR: Failed to set server controls');
    }

    $adldap = new Adldap();
    $adldap->addProvider($provider);

    return $adldap->connect();
}
```

**Comment by stevebauman** [comment]
Hi @lledo3,

Can you try modifying your `custom_options` array to the following:

From:

```php
'custom_options' => [LDAP_OPT_SERVER_CONTROLS, array($ctrl1)],
```

To:

```php
'custom_options' => [LDAP_OPT_SERVER_CONTROLS => [$ctrl1]],
```

The LDAP option needs to be the key for the value array.

**Comment by lledo3** [comment]
I tried that modification but that didn't work either:

```
function adLdapCon($username, $password)
{

    $ctrl1 = ['oid' => '1.2.840.113556.1.4.2239',
               'value' => sprintf('%c%c%c%c%c', 48, 3, 2, 1, 1)];

    $config = [
        'domain_controllers' => ['corp-dc1.corp.acme.org', 'corp-dc2.corp.acme.org'],
        'base_dn' => 'dc=corp,dc=acme,dc=org',
        'admin_username' => '$username',
        'admin_password' => '$password',
        'account_prefix' => 'ACME-',
        'account_suffix' => '@acme.org',
        'admin_account_prefix' => 'ACME-ADMIN-',
        'admin_account_suffix' => '@acme.org',
        'port' => 389,
        'follow_referrals' => false,
        'use_ssl' => false,
        'use_tls' => false,
        'timeout' => 5,
        'custom_options' => [LDAP_OPT_SERVER_CONTROLS => [$ctrl1]],
    ];

    $provider = new Provider($config);
    $adldap = new Adldap();
    $adldap->addProvider($provider);

    return $adldap->connect();
}
```

**Comment by chriseskow** [comment]
I think I figured out the problem: the options from `custom_options` are set before the connection is established, so `null` is passed into  `ldap_set_option()` instead of a resource. Maybe this doesn't matter for some options, but `LDAP_OPT_SERVER_CONTROLS` seems to need an established connection.

The problem is in `Provider::setConnection()`, which calls `$this->prepareConnection()` before it calls `$this->connection->connect(...)`. `prepareConnection()` is where the options are set. Those options should be set *after* `connect()`, not before.

**Comment by stevebauman** [comment]
Thanks @chriseskow!

Actually, this isn't very difficult to workaround, you can just call `getConnection()->setOptions()` after you've connected successfully to set other options:

```php
$provider->connect();

$options = ['...'];

$provider->getConnection()->setOptions($options);
```

I think this is preferable rather than bloating the Provider class to have its own `setOptions()` method, and also is very self explanatory when looking at this one line of code.
