### ISSUE TITLE
Working with groups and custom schema

### ISSUE THREAD

**Issue by Albvadi** [Adldap2/Adldap2#493]
- Adldap2 Version: 7.0.15
- LDAP Type: Sun ONE Directory Server
- PHP Version: 7.0.9

### Description:
Hi!
I´m working with a different approach of LDAP server, a Sun ONE Directory Server which differs in several things with OpenLDAP.

In this server, the group class it´s `posixgroup`, so, I created a new schema, extending OpenLDAP, with the following content:
```PHP
<?php

namespace App\Adldap2\Schemas;

use Adldap\Schemas\OpenLDAP;

class SunOneLDAP extends OpenLDAP
{
    /**
     * {@inheritdoc}
     */
    public function objectClassGroup()
    {
        return 'posixgroup';
    }
}
```

At this moment, all it´s working, so `Adldap::getProvider('ldap')->search()->groups()->get()` retrieve all groups correctly.
Now, I want retrieve all the members. I saw in the source method [here](https://github.com/Adldap2/Adldap2/blob/f375ed62d0cdff667685c8b56e470be6a43089bc/src/Models/Group.php#L21-L37) that it´s using `$this->schema->member()`, so in my custom schema, I added new method to overwrite member method:
```PHP
/**
 * {@inheritdoc}
 */
public function member()
{
    return 'memberuid';
}
```
but, the members function return empty object:
![image](https://user-images.githubusercontent.com/6285255/35732656-94e6c12a-081a-11e8-975d-ce996a573677.png)

Can you help me solve the problem?
I have tested a raw query (`(&(objectclass=posixGroup)(memberUid=user1.test))`) to retrieve users from a group in LDAPAdmin and working right:
![image](https://user-images.githubusercontent.com/6285255/35732874-7063eed0-081b-11e8-9a30-cd88340be18c.png)

Thank you!

**Comment by stevebauman** [comment]
Hi @Albvadi, we currently don't have support for SUN directory server, but would love to add it in.

The reason `getMembers()` returns an empty collection is because it's trying to locate users by their distinguished name, and not their `UID`, as that's what's given when using ActiveDirectory and OpenLDAP.

You'll need to do this manually at the moment:

```php
$members = [];

foreach ($group->memberuid as $uid) {
    $members[] = $provider->search()->users()->find($uid);
}
```

I'll see if I can make the method configurable with the schema for SUN directory server.

**Comment by stevebauman** [comment]
Thanks again for the report @Albvadi! Much appreciated.

Also, since you're working with Sun directory server, would you perhaps mind if you could post or put in a pull-request with your custom schema so it can be added into the base library for other devs? :smile:

**Comment by Albvadi** [comment]
No problem. I´ll try to test the actual `dev-master` today or tomorrow.
If all it´s working right, I´ll submit a PR with my custom schema.

Thanks as always for your awesome support!

**Comment by stevebauman** [comment]
Awesome, really appreciate it @Albvadi!

No problem at all!

**Comment by Albvadi** [comment]
Sorry, but isn´t working with `dev-master`.. :confused: 

- Adldap2 Version: dev-master
- LDAP Type: Sun ONE Directory Server
- PHP Version: 7.0.9

Custom Schema: `Adldap\Schemas\SunOneServer`
```php
<?php

namespace Adldap\Schemas;

use Adldap\Schemas\OpenLDAP;

class SunOneServer extends OpenLDAP
{
    /**
     * {@inheritdoc}
     */
    public function objectClassGroup()
    {
        return 'posixgroup';
    }

    /**
     * {@inheritdoc}
     */
    public function member()
    {
        return 'memberuid';
    }
}
```

Test Code:
```php
<?php
require_once('../vendor/autoload.php');

$ad = new \Adldap\Adldap();

$config = [  
  'domain_controllers'    => ['my-host'],
  'base_dn'               => 'my-ou',
  'username'        => 'my-admin-username',
  'password'        => 'my-admin-password',
];

$ad->addProvider($config);

try {
    $provider = $ad->connect();
    $provider->setSchema(new \Adldap\Schemas\SunOneServer());

    $group = $provider->search()->groups()->findByDn('cn=ADMINDESARR, ou=SES,o=intranet.rts');

    d($group->dn);
    d($group->memberuid);
    d($group->getMembers());
    d($group->members);

    foreach ($group->getMembers() as $member) {
        d($member);
    }
} catch (\Adldap\Auth\BindException $e) {
}
```

Result:
![image](https://user-images.githubusercontent.com/6285255/37651046-1c8aa9bc-2c37-11e8-838e-8bd552e243b2.png)

**Comment by stevebauman** [comment]
Hi @Albvadi, no problem! Appreciate you testing this for me.

Can you try try the following to see if you're actually able to locate these members by their 'uid'?

```php
$group = $provider->search()->groups()->findByDn('cn=ADMINDESARR, ou=SES,o=intranet.rts');

$memberUid = $group->memberuid[0];

$member = $provider->search()->findBy('uid', $memberUid);

d($member);
```

If nothing is returned, then there is a different attribute you'll need to use for the `memberIdentifier()`.

**Comment by Albvadi** [comment]
Member it´s returning correctly with the `uid` attribute...
I don´t if it´s good or bad.. :sweat_smile: 

![image](https://user-images.githubusercontent.com/6285255/37664253-35968772-2c5b-11e8-8db2-c02bcc077351.png)

**Comment by stevebauman** [comment]
Strange... That doesn't make any sense lol.

Can you verify you're on the `dev-master` branch by browsing the adldap vendor files and making sure the `getMembers()` method looks identical to this:

https://github.com/Adldap2/Adldap2/blob/b5fb04f3178b7b6eb89405accaac761501625011/src/Models/Group.php#L182-L219

**Comment by Albvadi** [comment]
Yes, exactly the same file.
I´m sure it´s `dev-master` because I went crazy when he told me that the `admin_username` option of the configuration didn´t exist.. :joy: 

Anyway, my vendor file copy/paste:

```php
    /**
     * Retrieves group members by the specified model attribute.
     *
     * @param $attribute
     *
     * @return array
     */
    protected function getMembersFromAttribute($attribute)
    {
        $members = [];

        $entries = $this->getAttribute($attribute) ?: [];

        $query = $this->query->newInstance();

        // Retrieving the member identifier to allow
        // compatibility with LDAP variants.
        $identifier = $this->schema->memberIdentifier();

        foreach ($entries as $entry) {
            // If our identifier is a distinguished name, then we need to
            // use an alternate query method, as we can't locate records
            // by distinguished names using an LDAP filter.
            if ($identifier == 'dn' || $identifier == 'distinguishedname') {
                $member = $query->findByDn($entry);
            } else {
                $member = $query->findBy($identifier, $entry);
            }

            // We'll double check that we've received a model from
            // our query before adding it into our results.
            if ($member instanceof Model) {
                $members[] = $member;
            }
        }

        return $members;
    }
```

**Comment by stevebauman** [comment]
Thanks @Albvadi! Can you see if anything is being returned by the queries during the foreach loop?

```php
foreach ($entries as $entry) {
    // If our identifier is a distinguished name, then we need to
    // use an alternate query method, as we can't locate records
    // by distinguished names using an LDAP filter.
    if ($identifier == 'dn' || $identifier == 'distinguishedname') {
        $member = $query->findByDn($entry);
    } else {
        $member = $query->findBy($identifier, $entry);

        d($member); // <-- DD here
    }

    // We'll double check that we've received a model from
    // our query before adding it into our results.
    if ($member instanceof Model) {
        $members[] = $member;
    }
}
````

**Comment by Albvadi** [comment]
WTF!? It´s null...

-  `d($identifier) ==> 'uid' //correct` 
- `d($entry) ==> 'test.user1' //correct`
- `d($member) ==> NULL` // O_O

If I change `$member = $query->findBy($identifier, $entry);` for `$member = $query->findBy('uid', 'test.user1');` it´s remains null, while in the example it´s return the member...

**Comment by stevebauman** [comment]
Strange! Can you see if your base DN is correct and everything on the query builder?:

```php
} else {
    d($query);

    $member = $query->findBy($identifier, $entry);
}
```

**Comment by Albvadi** [comment]
Seems correct...?? :confused: 
![image](https://user-images.githubusercontent.com/6285255/37667850-4e9b92e6-2c63-11e8-9b73-f881ffa26392.png)

**Comment by stevebauman** [comment]
Hmm the `dn` looks to be off. It seems like it's set to `cn=ADMINDESARR`, is this a user? Or an OU?

This is the base distinguished name of the search, so if the members of the group aren't located in this OU, then they won't be found.

**Comment by Albvadi** [comment]
Is the OU, the dn of the group. The users aren´t located inside the group OU, they are distributed across differents OUs, inside the base_dn Ou, that is `o=intratet.rts`

I thought the base DN for the queries was the base_dn option in the config...

**Comment by stevebauman** [comment]
> I thought the base DN for the queries was the base_dn option in the config...

It definitely is, can you validate your `base_dn` in your config?

https://github.com/Adldap2/Adldap2/blob/master/src/Connections/Provider.php#L206

**Comment by Albvadi** [comment]
The base_dn it´s definitely correct.

![image](https://user-images.githubusercontent.com/6285255/37668628-3f9affd2-2c65-11e8-9548-55b8f3e75fe3.png)

**Comment by stevebauman** [comment]
Hmmm, pushed a fix, but this won't do. Will need to refactor a little bit of the query builder to keep its own copy of the base DN while processing searches for other records.

Nice find @Albvadi! Really glad you've located this issue.

**Comment by Albvadi** [comment]
Tested your first approach of fix:

- `$group->getMembers()` now returns the first member of the group (before was null)
- `$group->members` returns null, same as before

![image](https://user-images.githubusercontent.com/6285255/37713565-9917e98c-2d17-11e8-9abf-5264adea8488.png)

**Comment by stevebauman** [comment]
Hi @Albvadi, just pushed a fix, this should resolve your issue. Let me know if you still encounter this!

For your issue mentioned above with `$group->members` returning null, that's your LDAP server not returning any values for the models `members` attribute.

Adldap2 fills each model with all attributes returned by your LDAP server, it doesn't filter anything out unless you specify it.

**Comment by Albvadi** [comment]
Thanks again. I´m very busy at this moment, but I´ll try to test as soon as possible..
If all works, I´ll create the PR to add the schema from SUN One LDAP Server.

Thanks so so much! :blush:
