### ISSUE TITLE
[v9.0] - Bump minimum PHP version to 7.0

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2#500]
Adldap2 v9.0 will require a minimum of PHP 7.0.

This will allow us to utilize new features in 7.0 throughout the package.

**Comment by 36864** [comment]
Might I suggest bumping to 7.1 instead? According to http://php.net/supported-versions.php 7.0 is now in security support only while 7.1 will be in active support through December.

**Comment by stevebauman** [comment]
Hey @36864, this definitely might be a better option. I just see a lot of developers **still** utilizing old PHP versions through issues created in this repository, and I'm not sure if this would be walling them out of using this package.

Though maybe I will just suggest using older versions of Adldap2 if they're using older PHP versions.

Going to think on this tonight, thanks for your input!

**Comment by wranger** [comment]
There is no support for 7.1 or higher in Debian 9 at the moment ...

**Comment by stevebauman** [comment]
I'll be keeping it to `7.0` for now since security support ends at in December of this year (still 8 months away).

At the halfway point (around June / July), I'll release another major version to bump the minimum to 7.1.

**Comment by stevebauman** [comment]
Completed. Keeping it at `7.0` for this release.
