### ISSUE TITLE
Base DN

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#503]
Hello,

Quickely, how can I set base DN before, for exemple a search() qurey ? I try multiple things but I don't find a correct documentation for that ? There is a function like 
```php
$ad->provider()->search()->setBaseDn() 
or
$ad->provider()->setBaseDn()
```
Thanks

**Comment by stevebauman** [comment]
Hi @ciadch, you can use the `in()` or `setDn()` method like you've shown above:

https://github.com/Adldap2/Adldap2/blob/master/docs/query-builder.md#base-dn

Your global base DN is set from your providers configuration (the `base_dn` option).

**Comment by ciadch** [comment]
Ok thanks for your return.
