### ISSUE TITLE
orWhere method dosen't work correctly

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#504]
Hello,

orWhere function doesn't work corretly, it returns an and (&) ldap param. 
```php
orWhere([['name', 'contains', 'test'],['displayname', 'contains', 'test']])
```
Returns
(&(name=*test*)(displayname=*test*))

Thanks

**Comment by MacBooc** [comment]
actually it works corretly while the param required is a string, not a multidimentional array. try this:

`search()->orWhere('name', 'contains', 'test')->orWhere('displayname', 'contains', 'test')`

**Comment by stevebauman** [comment]
Hi @ciadch,

This is a bug, thanks!

It currently works correctly with arrays and multiple calls (shown above by @MacBooc), but seems to have issues when providing nested array queries. I'll fix this :).

**Comment by stevebauman** [comment]
Fixed, will be in new release shortly. Thanks!

**Comment by ciadch** [comment]
Great ! Thank you !
