### ISSUE TITLE
How to execute wildcard search

### ISSUE THREAD

**Issue by christianmalek** [Adldap2/Adldap2#507]
Hi,

I really like Adldap2! It simplifies ldap queries so much. At the moment I need to find all groups which start with `foo` and end with `bar`. Normally I do this with an wildcard like `foo*bar`. How can I achieve this with your neat lib? If it's possible I would like to do this with the mentioned syntax.

**Comment by christianmalek** [comment]
I did it like this:

```js
        $filter = "(&(objectCategory=group)(cn=$groupCN))";

        $groups = $this->ad
            ->search()->groups()
            ->rawFilter($filter)
            ->select(["dn"])
            ->get()
            ->reduce(function ($groups, $group) {
                $groups[] = $group->distinguishedname[0];
                return $groups;
            }, []);

        return $groups;
```

Is there a more *Adldap2*-ish way?

**Comment by stevebauman** [comment]
Hey @christianmalek, I'm really glad you like Adldap2, thanks for using it!

Right now there isn't an option for performing **both** a *starts with* and *ends with* clause, however, you can do the following which should return the same results:

```php
$groups = $this->ad->search()
    ->whereStartsWith('cn', 'foo')
    ->whereEndsWith('cn', 'bar')
    ->get();
```

Does this answer your question? Also, here are all the query methods: 

https://github.com/Adldap2/Adldap2/blob/master/docs/query-builder.md#wheres

**Comment by christianmalek** [comment]
Ah, thanks! This makes sense. But I think I'll stick with the raw filter.

**Comment by stevebauman** [comment]
Ok no problem! Thanks for following up :)
