### ISSUE TITLE
Does not support nested groups 

### ISSUE THREAD

**Issue by splummer** [Adldap2/Adldap2#508]
- Adldap2 Version: 8.1.3
- LDAP Type: Active Directory
- PHP Version: 7.1.8

### Description:

When connecting to an AD server and trying to return the users in a group I get bad username password unless members are direct members of the group.

Perhaps this search filter will be helpful
memberOf:1.2.840.113556.1.4.1941 https://msdn.microsoft.com/en-us/library/aa746475(v=vs.85).aspx

**Comment by stevebauman** [comment]
Hi @splummer,

I'm not sure what you mean? Can you post your steps to reproduce and what exception you receive?

The search filter you've posted is already being used throughout Adldap2:

https://github.com/Adldap2/Adldap2/blob/master/src/Schemas/BaseSchema.php#L475-L481

https://github.com/Adldap2/Adldap2/blob/d9ccfa694a593723a50e12bf304682f22f0bd254/src/Query/Builder.php#L987-L997

**Comment by splummer** [comment]
Sorry I am using this as part of munkireport so I have no idea where it is outputting connection info and my PHP skills are SUPER rusty so I have no chance of hacking up the code they use. 

All I can tell is the behavior at this point. Group with direct members, lets me login. Group with no direct members and only groups as members (but I have membership in a sub group) it tells me invalid username/password.

Since it's not my direct use of this code and I really can't get much more info you can probably close this. I work with so many different packages that fail to honor nested groups from AD that I assumed. Sorry for the less than complete report. I can file a report with MunkiReport.

**Comment by stevebauman** [comment]
Just for clarification, to receive nested groups when calling `getGroups()`, you need to provide a second argument indicating you want recursive results:

```php
$user->getGroups($fields = ['*'], $recursive = true);
```

https://github.com/Adldap2/Adldap2/blob/master/src/Models/Concerns/HasMemberOf.php#L60-L75

**Comment by splummer** [comment]
Ohhh is that something that goes in the config array like $conf['auth']['auth_AD']['domain_controllers']?

**Comment by splummer** [comment]
Or something they probably need to modify in their code more likely, I will dig around a little bit.

**Comment by stevebauman** [comment]
> Ohhh is that something that goes in the config array like $conf['auth']['auth_AD']['domain_controllers']?

Nope, this is in the direct API of Adldap2 when they retrieve groups from users, or groups themselves.

> Or something they probably need to modify in their code more likely, I will dig around a little bit.

Unfortunately yes, they'll need to ask for recursive members.

If recursive results were default, then it could be a huge detriment to performance if developers only wanted the immediate groups on the user, rather than all nested groups.

**Comment by splummer** [comment]
You have been a huge help. Thanks so much.

**Comment by stevebauman** [comment]
No problem! Thanks for the quick responses :)

**Comment by stevebauman** [comment]
Also, not sure if this is the package you're referring to:

https://github.com/munkireport/munkireport-php

But they are using the original, outdated version adldap:

https://github.com/adldap/adLDAP

Shown here:

https://github.com/munkireport/munkireport-php#external-projects

**Comment by bochoven** [comment]
Just to be clear: Munkireport uses the latest release of Adldap2 os suggested in the `composer.json` file: https://github.com/munkireport/munkireport-php/blob/master/composer.json
