### ISSUE TITLE
[Discussion] Renaming Adldap2

### ISSUE THREAD

**Issue by stevebauman** [Adldap2/Adldap2#509]
I've been thinking about this for a while now and would love to have the community's thoughts and feedback on this.

Adldap2 was originally created as a fork from the original [adLDAP repository](https://github.com/adldap/adLDAP). I ran into issues with using the original repository as it had a major lack of support, and other bugs that prevented me from implementing it.

I wanted something as clean as possible as well as a nice fluid API. This is how Adldap2 was created. Due to me just *wanting to get something out there* as fast as possible, I simply named it Adldap2. Since Adldap2 has opened support for other LDAP server variants (OpenLDAP, FreeIPA, etc.), this name already feels out of place.

Adldap2 in its current version contains absolutely no similarities to the original repository, and the name (lets be honest) isn't the prettiest, or the easiest to identify, or remember.

I'm looking for an opinion from anyone who uses Adldap2, and if it would offer any benefit to rename the repository. A rename would offer a new namespace throughout the repository, but there would be no API changes.

There are more negatives than positives here, but renaming the repository could offer a new "brand" for Adldap2, and it could have its own identity that isn't attached to an old and out-dated repository.

Is it worth it? What are your thoughts? Thank you in advance for all opinions!

**Comment by stuntguy3000** [comment]
I fully agree, this project has expanded into much more than just Active Directory.

**Comment by wranger** [comment]
That's a good idea, maybe with the release of 9.0 and the force to use php 7.x. 8.x could be the last release of ADLdap2 and the 9.0 is then the "NewProjektName 1.0".

**Comment by stevebauman** [comment]
Thanks guys, any suggestions for a new repo name? :smile:

**Comment by wranger** [comment]
PHPLdapInterface PLI :D , I'll think about it

**Comment by stevebauman** [comment]
Lol sounds a little rigid, but not bad! I was thinking:

 "**_Dapper - Clean & Elegant LDAP Management_**"

Not set on this either though...

**Comment by Albvadi** [comment]
**"Dapper"** already exists... [StackExchange/Dapper](https://github.com/StackExchange/Dapper) :sweat_smile:

Anyway, I think it´s a good idea too. If this project has nothing to do with the original project, it's better to have nothing to do with the name neither.

As for the name, I can not think of any good, but I think the word (or concept) "LDAP" should appear in it.

**Comment by stevebauman** [comment]
@Albvadi damn! Lol.

Yea will have to use something else then, I definitely agree about the LDAP abbreviation being apart of the name.

Any other suggestions 😄

**Comment by wranger** [comment]
Hmmmmm, when I serach for "php ldap" on google, your framework is at top 3 on github at top 4.

**Comment by mvatansever** [comment]
I'm not so creative :) 
But the name sound is good:
ELDAPM => Easy LDAP Manager

**Comment by stevebauman** [comment]
@wranger Yeah that's definitely something I'm worried about, since it may be more worthwhile to keep the current name. Still on the fence to be honest.

I'd prefer something with a CamelCase name, would you all agree?

Love the suggestions!

**Comment by odvolk** [comment]
Well, how about FEADM - Flexible & Easy Active Directory Management?!

**Comment by mvatansever** [comment]
@odvolk this project more than Active Directory support various LDAP implementations like FreeIPA, OpenLDAP vs.

**Comment by JC5** [comment]
If you're up for doing some extra PR work and brand recognition, you could also go for something that isn't an abbreviation or clever play on the term LDAP. You could call it "Heimdal" or "Wodan" or whatever you want and think of some clever explanation  as to what the link is to your library.

**Comment by stevebauman** [comment]
@JC5, yeah I definitely want to go in that direction. I was thinking of Elm - like the tree (Elegant LDAP Management), also doubles as sort of a descriptor for a “directory tree”.

What are your thoughts?

**Comment by JC5** [comment]
I like it! You should combine it with a [fancy icon](https://www.flaticon.com/).

**Comment by stevebauman** [comment]
I’m still on the fence about this. I’ll have to go full rebrand - but I’d really hate to inconvenience everyone with the new namespaces. All stats will be lost as well, which could generate a big loss of trust.

The namespace would be `Elmseed\Elm` - so it would be a lot nice than “Adldap”, but I definitely want to get some more opinions on whether it’s worth it.

I’m also working on building an LDAP directory monitor service using Laravel. Would anyone find it useful if I open sourced it?

**Comment by mvatansever** [comment]
To be sincere, I think the Elmseed does not sound anything about LDAP :) 

The other topic is monitoring service, worth to try to open source it. But if the project can be a dependency so it would be nice than separated an application.

**Comment by Albvadi** [comment]
Hi!
IMHO, I think you should make the rebrand. It will be very hard for everyone:

- first for all of us, because it involves a code change in all the projects to accommodate the namespaces (Thanks God for Search / Replace).

- but more especially for you, for that loss of "identity", statistics and credibility that gives the use of a library with a version 1.0 (although behind carry 10 more versions with another name)...

However, if you don´t want to be tied or related to the original project, that rebrand is necessary and will be just as difficult now, that within a few years..

As for the name, Elm seems too short for me as a name, but I like the meaning as such "Elegant LDAP Management". (Super elegant I would say)...
And I agree with @JC5, you should have an image that, when viewed, relates directly to your package. I don´t know if an icon already made of Flaticon or an image designed with the project in mind, but I think you should have an image.

And finally, regarding your LDAP monitor project, I have been thinking about it for a long time, although it would be like a project outside of daily work and it has not been possible due to lack of time. In our organization, we have an active directory with 20k users, 15k computers and with daily and constant modifications. I have always thought that it was too big to monitor every change, that's why I find your project and focus on how to monitor it very interesting.

P.S: What does Elmseed mean? Is it https://www.elmseed.org/?

**Comment by stevebauman** [comment]
@mvatansever Thank you for your input! I was thinking of choosing "Elmseed" as the author name because "Elm" was taken on GitHub. Elm was going to be the actual name of the package (an abbreviation for Elegant LDAP Management), but I'm also not set on this name at all.

> The other topic is monitoring service, worth to try to open source it. But if the project can be a dependency so it would be nice than separated an application.

It would absolutely be a seperate application. The application would use Adldap2 to perform the monitoring.

@Albvadi Thanks for your input!

> IMHO, I think you should make the rebrand. It will be very hard for everyone:

Yea, I don't want to cause anyone too much work to change their code base, but Adldap2 is a very ugly name (to be honest lol) - so I'm on the fence still.

> However, if you don´t want to be tied or related to the original project, that rebrand is necessary and will be just as difficult now, that within a few years..

Exactly. The sooner the better!

> As for the name, Elm seems too short for me as a name, but I like the meaning as such "Elegant LDAP Management". (Super elegant I would say)...

You think so? I've been trying to think of some names for a while - I'm absolutely open to all suggestions 😅. I'm always sort of thinking of something "tree" related due to LDAP being a "directory tree". Thoughts?

> And I agree with @JC5, you should have an image that, when viewed, relates directly to your package. I don´t know if an icon already made of Flaticon or an image designed with the project in mind, but I think you should have an image.

I totally agree, I've actually been searching for a logo / image all weekend!

> In our organization, we have an active directory with 20k users, 15k computers and with daily and constant modifications. I have always thought that it was too big to monitor every change, that's why I find your project and focus on how to monitor it very interesting.

That's a lot of LDAP entries! We use an AD server with around 1k+ entries in total, so not really anywhere close to your usage. I'd have to build in such a way to run the directory scans in chunks so it would be possible to actually go through that many entries.

> P.S: What does Elmseed mean? Is it https://www.elmseed.org/?

I didn't know this website existed, I'm not sure what they do lol

**Comment by stevebauman** [comment]
What about LdapRecord? Since Adldap2 uses the ActiveRecord pattern, I thought it goes together well. Thoughts?

**Comment by mvatansever** [comment]
Yes, this name tells more about LDAP than the Elmseed 👍Additionally describes the technical background of this package. 

It's good from my perspective :)

**Comment by madmatt** [comment]
How about ElmDir? LdapRecord sounds a bit similar to Adldap (in that it's quite technical, rather than a 'nice' name).

In case you like it, I've registered the GitHub org ElmDir (https://github.com/elmdir) and will happily transfer it over to you and remove myself if you like it (there's a bit of name sniping on GitHub at the moment so thought it better to register the name before I proposed it). Otherwise I'll drop it in the future.

**Comment by stevebauman** [comment]
@mvatansever Thanks! And I actually registered the LdapRecord repo in case I wanted to go with it.

@madmatt ElmDir doesn't sound bad, though it doesn't really go well as an abbreviation, ex "Elegant LDAP Management Directory"? I'm open to everyones thoughts and opinions on it though.

> In case you like it, I've registered the GitHub org ElmDir (https://github.com/elmdir) and will happily transfer it over to you and remove myself if you like it (there's a bit of name sniping on GitHub at the moment so thought it better to register the name before I proposed it).

Thanks! I really appreciate it. I did this myself with LdapRecord - you just never know when someone wants to purposely mess with you on the internet and register names that are in discussion lol.

**Comment by ckieffer** [comment]
Sorry if I missed this in the discussion, but have you considered the following rebranding approach?

- Fork Adldap2 to the new branded name. Something based on "ELM" sounds great, IMHO.
- Prominently encourage new users here to use the rebranded fork.
- Encourage existing users to migrate to the fork ASAP over the next year or two. Commit to pushing work in the fork back to here for a while.

Seems like a fair distribution of the burden of rebranding between you and the user community while gradually transferring reputation and identity to the fork.

**Comment by madmatt** [comment]
Eventually once a name is settled on and the repo is renamed, just updating the composer name for the module should be enough. The original Packagist entry could be left in the abandoned state, with a reference to the new repository name. See https://getcomposer.org/doc/04-schema.md#abandoned

This will mean as users install the module via composer, they'll be alerted about it, and can manually upgrade to the new repo.

One other thing - if you rename the existing repo on GitHub, the old git URLs will redirect to the new location for a while (I think a few months), so if you want to mark the package as abandoned you'd need to remove it from Packagist, create a new repo with the abandoned codebase and update it there (this way the new repo will keep all the history etc)..

**Comment by aurelijusrozenas** [comment]
Maybe having "ldap" in package name would make it easier to find from search engines? From point of new ldap user, knowing nothing about available libraries, I would click on "LdapSomething" github link instead of "ELM". Just my 2 cents, the lib seems great so name is just cherry on top :)

**Comment by JC5** [comment]
Meh, if you describe it will everybody will find your package just fine.

**Comment by jspringe** [comment]
I'm also in favor of LDapper. Lends itself nicely to a logo of a fedora.

**Comment by JC5** [comment]
How about m’ldap? 😁

**Comment by stevebauman** [comment]
Hi everyone :smile:, I wanted to give an update about the status on this.

I've created another GitHub organization and another repository: [DirectoryTree/LdapRecord](https://github.com/DirectoryTree/LdapRecord)

I've decided on LdapRecord for a couple reasons:

- It has "LDAP" in the name so it's easily recognizable and searchable
- It relates directly to the ORM pattern in use (Active Record)

I've put a ton of work (and will continue to do so) into this new package. I have also created its own custom docs site - [ldaprecord.com](https://www.ldaprecord.com) with lots of documentation and usage. I'll be implementing global search on it soon so it's even easier to navigate.

I went with DirectoryTree as the organization name so I could start building LDAP applications under it. I thought DirectoryTree directly signifies what the organization is about (LDAP directories).

LdapRecord will be in beta in the coming weeks as I comb over all the documentation, code and tests. Once done, I'll be porting Adldap2-Laravel over to LdapRecord-Laravel, with a massively requested feature - multiple domain authentication.

For anyone interested, I have also began working on a brand new open source project you may find useful in the future: [DirectoryTree/Scout](https://github.com/DirectoryTree/Scout). Scout is an LDAP directory auditing and monitoring tool that automatically scans your directory and logs all changes to LDAP object attributes.

Some key features I want to flesh out with this:

- Automated notifications, such as:
  - Users being locked out
  - User accounts expiring or soon to be expiring
  - Group membership changes
  - Password changes
  - Account changes
  - And more.
- Generation of auditing reports, such as:
  - Showing all membership changes for certain users for certain dates or times
  - Showing all password resets done for certain dates or times
  - And more.
- Domain write-back, so you can modify LDAP objects from a web-interface
- Permissions and Groups so you can decide who can modify which LDAP objects without having them access the LDAP server directly
- And more.

This application is in it's *very* early stages, but the groundwork has been laid out for full synchronization.

Thanks for everyone's support, and I hope you try out LdapRecord at some point and let me know what you love - and hate!

**Comment by Albvadi** [comment]
Absolutely amazing job! :heart: 

I love all, the new name, the sponsor (LDAP for humans!) and all the rebrand.. it´s fantastic!
Fantastic work with documentation (surely a lot of search&replace AdLdap2 / LdapRecord) :laughing: 

And what to say about Scout! It´s a wonderful idea.
I think I´ll can´t monitor my organization, because it´s massively huge, but I´ll give it a try.

> * Domain write-back, so you can modify LDAP objects from a web-interface

I´m working in this exactly now, with your Adldap2-Laravel as base tool, so with more reason to try Scout... :heart_eyes:

Again, as always, thanks so much for all your selfless work to help us to be better developers.. :slightly_smiling_face:

**Comment by stevebauman** [comment]
Wow @Albvadi thanks so much for your kind words! :smile: That really means a lot to me, honestly. :heart:

I'm really excited to get things tested and released. Scout is something I've wanted to build for a long time as it's something that's always been a need for me in my current position, but to my knowledge there isn't anything free on the market that is up to date and easy to setup & use day to day.

**Comment by stevebauman** [comment]
Hi again everyone, it's been a while since my last update, but I'm now ready to close this issue out.

LdapRecord now has a full [v1.0.0 release](https://github.com/DirectoryTree/LdapRecord/releases) and a completely [rebuilt documentation site with search](ldaprecord.com) using Tailwind CSS and Jigsaw.

I'm putting the finishing touches on LdapRecord-Laravel - it finally supports multi-domain authentication out-of-the-box (along with some other niceties). I'm working on its documentation that will take me a couple days. Once that is complete, it will have it's own v1.0.0 version 🎉. 

Since LdapRecord is the successor to Adldap2, I'll be placing a notice on the Adldap2 front page of it's depreciation of further feature development. However, I will always continue to support it with bug fixes.

I really appreciate everyone's support over the years I've been building Adldap2. I don't expect everyone to migrate to LdapRecord until they are comfortable, but I hope you give it a shot at some point and let me know of your experience! :heart:
