### ISSUE TITLE
Queries are very slow since last updates

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#51]
Hi,

I don't know where you are in your releases and if the version 5.1 is not ready but since the two last updates, all my queries are really slow, 2 or 3 time slower than before. It's maybe a "normal" behaviour because you are now in development but keep it in mind :-)

Thank you

**Comment by stevebauman** [comment]
Just released `v5.1.1`. The slowness was caused by the models searching to see if they exist when `setRawAttributes()` was called. This was unnecessary and only needed when `save()/update()/ or create()` is called.

**Comment by ciadch** [comment]
That's great ! I just update my code now and it returns to normal speed ! Thanks for your reactivity

**Comment by stevebauman** [comment]
No problem at all

**Comment by ciadch** [comment]
Seems to occurs again with the last update !

Thanks

**Comment by ciadch** [comment]
Sorry it was me... works fine and quickly :-)

**Comment by stevebauman** [comment]
No problem :)
