### ISSUE TITLE
connect and close connection Adldap2

### ISSUE THREAD

**Issue by cuauhtemocSilva** [Adldap2/Adldap2#512]
Hello 

I have a doubt, into the configuration file adldap.php, when the 'auto_connect' => true, and into my controller I use a function like this:

 Adldap::search()->where('uid', '=', $variable)-get();

the connection and close to LDAP is by default? I mean, I don't have to worry about that? Because I don't know I have to close the connection after the function.

Thanks!!

**Comment by stevebauman** [comment]
Hi @cuauhtemocSilva, closing the connection is not necessary. This is done automatically in your connection provider when it's deconstructed:

https://github.com/Adldap2/Adldap2/blob/master/src/Connections/Provider.php#L62-L75
