### ISSUE TITLE
Can't setCommonName and setDn

### ISSUE THREAD

**Issue by brutax34** [Adldap2/Adldap2#515]
Hi all,
I'm using Adldap 8.1

I'm able to creat users on my active directory (using SSL), no problem about that.

Now, I want to update a user and I can't change the DN and the commonName. Here is my code : 
```
require_once __DIR__.'/vendor/autoload.php';
use Adldap\Adldap;
use Adldap\Utilities;
use Adldap\AdldapException;

$config= new \Adldap\Configuration\DomainConfiguration();

$ad = new \Adldap\Adldap();
$ad->addProvider($config);
$provider = $ad->connect();

$m=$ad->search()->users()->find('test01');
$m->setDisplayName('Raoul NUNUX');
$m->setFirstName('Raoul');
$m->setLastName('NUNUX');
$m->setCommonName('Raoul NUNUX');
$m->setDn('CN=Raoul NUNUX,OU=OU_4,OU=OU_3,OU=OU_2,OU=OU_1,DC=domain,DC=local');
$m->save();
```

If I add `$m->setCommonName('Raoul NUNUX');` I get this : 
> Warning: ldap_modify_batch(): Batch Modify: Operation not allowed on RDN in /var/www/html/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 309

If I add `$m->setDn('CN=Raoul NUNUX,OU=OU_4,OU=OU_3,OU=OU_2,OU=OU_1,DC=domain,DC=local');` I get this : 
>Warning: ldap_modify_batch(): Batch Modify: No such object in /var/www/html/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 309

What can I do please ?

Regards.

**Comment by stevebauman** [comment]
Hi @brutax34, you need to perform a `move` to change an objects distinguished name.

Here are the docs to perform this:

https://github.com/Adldap2/Adldap2/blob/master/docs/models/model.md#moving--renaming

**Comment by brutax34** [comment]
Many thanks @stevebauman, I'll try it on tomorrow.
