### ISSUE TITLE
Extendable maps in Query\Processor class

### ISSUE THREAD

**Issue by sooslaca** [Adldap2/Adldap2#518]
- Adldap2 Version: 8.1.3
- LDAP Type: OpenLDAP
- PHP Version: 7.2.2

### Description:
Extendable maps in Processor class

### Steps To Reproduce:
hi @stevebauman, first of all thanks for this handy extension, it's super helpful.

I would like to get a suggestion. I have custom LDAP objectClasses and trying to create similar like your adldap Models, where a search returns that specific Model instance if the objectClass matching a certain one. I figured out that mapping is hardcoded into Query\Processor::map()
How can I extend this mapping dynamically, Is there any way that you can suggest?

I tried monkey patching (patchwork2.org) but I would not like to run that in production code.
Also looked after composer overrides ("files") but that's still a hacky way.

Thanks for any advice in advance.

**Comment by stevebauman** [comment]
Hi @sooslaca, good question!

Just so I understand, you're looking to add an **additional** model in your search results for a different object classe? Not change or customize the current models & object classes (as this is already supported)?

**Comment by sooslaca** [comment]
Hi @stevebauman, that is correct. I read the manual ;) Both the Schema and the Model are already created. What I wish for is a way when I query the LDAP tree get a result with a custom (new, not existing) Model class instead of default Entry model class when no match in map() found.
As of today I solved by copying your whole Query\Process class to a file and forcing composer.json in the "files" section to superseeded the original one, but it's hacky.
I simply added another line into the return array or map():
`$this->schema->objectClassSooslacaExample()    => $this->schema->sooslacaExampleModel(),`

Low prio, but thinking it further it would be also nice if we can shorthand where queries like you have it in Query\Factory (users,printers,...) but as it returns a simple 'where' with filters, I can add the custom 'where' directly into the app.

**Comment by stevebauman** [comment]
Hey @sooslaca, this is definitely a valid use case and I definitely agree, this needs to be an option as well as much easier to implement.

Right now, you'll need to do the following:

- Create your own `Query\Builder` and extend from the current Adldap builder
- Create your own `Query\Processor` and extend from the current Adldap processor
- Override the `newProcessor()` method [here](https://github.com/Adldap2/Adldap2/blob/master/src/Query/Builder.php#L1508-L1516) and return your custom processor instance
- When opening a new search, set the query builder to your custom one:

```php
use Adldap\Schemas\OpenLDAP;
use App\Builders\MyQueryBuilder;

$factory = $provider->search();

$builder = new MyQueryBuilder($provider->getConnection(), null, new OpenLDAP());

$factory->setQuery($builder);

$users = $factory->users()->get();
```

This is definitely messy, so I'll need to make this easier and a viable option.

Will work on it, thanks @sooslaca :)

**Comment by sooslaca** [comment]
Awesome, thanks for the hints @stevebauman ! It helped me with some fixes ;)

Final code became (I created a custom class extending Provider)
```
    public function websites() {
        $factory = $this->search();
        $builder = (new Builder($this->getConnection(), $factory->newGrammar(), $this->schema))->in($this->configuration->get('base_dn'));
        $factory->setQuery($builder);
        return $factory->where([$this->schema->objectClass() => $this->schema->objectClassWebsites()]);
    }

```
