### ISSUE TITLE
Can't contact LDAP server after upgrade from 6.1 to 7.0

### ISSUE THREAD

**Issue by CYGREEN** [Adldap2/Adldap2#519]
- Adldap2 Version: 7.0
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:
I've been using 6.0 that's included in Adldap2-Laravel but when upgrading to the latest that includes 7.0 I can no longer connect to AD. I've done stand alone testing outside of Adlap2-Laravel with Adlap2 v5.2, v6.1, 7.0 and 8.0. I **can** connect with v5.2 and 6.1. I've used the v7 [ Quick Start Guide](https://github.com/Adldap2/Adldap2/blob/v7.0.0/docs/quick-start.md) only adding use_ssl and I get a BindException "Can't contact LDAP server" exception when attempting to connect. I'm at a loss on what I could be doing wrong. I've read through several other similar issues without any help (I can ping the DC and v5.2 and v6.1 work). 

Anything obvious I should be checking? I suspect it may be a config issue but I've followed the published guides.

**Comment by stevebauman** [comment]
Hi @CYGREEN,

The latest is Adldap2 `v8.0` and Adldap2-Laravel `v4.0`.

There were some changes made between those versions on how it handles the `account_prefix` and `account_suffix` configuration options, so that's something to look out for when upgrading.

You mentioned you've only added `use_ssl` to your configuration? Are you sure your server supports SSL connections?

**Comment by CYGREEN** [comment]
Thanks for the reply. 

I've tried Adldap2 v8.0 and Adldap2-Laravel v4.0 but it seems the anything after v6.1 seems to not work for me. 

As far as the admin credentials, I've verified it's using the correct username, password and account suffix via the exception and by dumping the username and password variables in the bind() function of Guard.php and by dumping the object in the bindAsAdministrator() function. 

For SSL, I've been using it with Adlap2-Laravel 2.0 without issues and it's required by the AD admins in my environment. TLS does not work in my environment. 

Any other things I should check? Any way to get more verbose logging or a way to get more info to troubleshoot?

**Comment by stevebauman** [comment]
Are you re-publishing the configuration files after changing to each release? There are large changes between config files for each major release, so you'll need to delete and reconfigure from scratch after upgrading or changing versions.

Lets just keep you at a version for troubleshooting, as there are major changes between all of those releases.

Stay on Adldap2-Laravael `v4.0` as it is current.

Once you've `composer update`'ed to `v4.0`, I would suggest re-configuring from scratch by deleting the `config/adldap.php` and `config/adldap_auth.php` files and re-publishing them.

I would then suggest dumping and dying (`dd()`) inside the `Guard.php` class to see why the bind is failing.

**Comment by CYGREEN** [comment]
Thanks Steve. I can get another brand new Laravel 5.6 instance going with Adldap2-Laravel v4.0 soon to troubleshoot with. I was doing most of my troubleshooting without Laravel but in the end this is where I'm using it. I posted here because I don't think my issue is Laravel specific.  

Thanks again for the help so far.

**Comment by stevebauman** [comment]
Hey @CYGREEN, no problem! We'll get you up and running.

Just let me know when you test with a new instance.

**Comment by CYGREEN** [comment]
Ok, so setup a new Laravel install with the latest Laravel (5.6) and Adldap2-Laravel (4.0). Unfortunately I'm still getting a “BindException: Can't contact LDAP server” I dumped the Guard class object and nothing looks obviously wrong with the config info. I added a second DC in the new version which is why there's two showing up. Any advice on what to check next?

```
Guard {#244 ▼
  #connection: Ldap {#234 ▼
    #connection: ldap link resource @9
    #bound: false
    #useSSL: true
    #useTLS: false
  }
  #configuration: DomainConfiguration {#243 ▼
    #options: array:15 [▼
      "domain_controllers" => array:2 [▼
        0 => "<redacted>"
        1 => "<redacted>"
      ]
      "timeout" => 5
      "version" => 3
      "port" => 389
      "base_dn" => "dc=<redacted>,dc=<redacted>"
      "use_ssl" => true
      "use_tls" => false
      "follow_referrals" => false
      "account_prefix" => ""
      "account_suffix" => "@<redacted>"
      "admin_username" => "<redacted>"
      "admin_password" => "<redacted>"
      "admin_account_prefix" => ""
      "admin_account_suffix" => "@<redacted>"
      "custom_options" => []
    ]
  }
}
```

From Adldap2-Laravel version 2.0 working:

```
Guard {#238 ▼
  #connection: Ldap {#234 ▼
    #useSSL: true
    #useTLS: false
    #connection: ldap link resource @8
    #bound: false
  }
  #configuration: Configuration {#237 ▼
    #baseDn: "dc=<redacted>,dc=<redacted>"
    #followReferrals: false
    #port: "389"
    #useSSL: true
    #useTLS: false
    #domainControllers: array:1 [▼
      0 => "<redacted>"
    ]
    #accountSuffix: "@<redacted>"
    #accountPrefix: ""
    -adminUsername: "<redacted>"
    -adminPassword: "<redacted>"
    -adminAccountSuffix: "@<redacted>"
  }
}
```

**Comment by stevebauman** [comment]
Hi @CYGREEN, are these apps running off of the same server and same PHP config?

**Comment by CYGREEN** [comment]
Yeah, they are virtual hosts on the same server and PHP config.  I suppose it's worth trying this on a different server, certainly could be the issue. I'll give that a try next.

**Comment by stevebauman** [comment]
Ok, are you using the same admin username and password on both configs?

Can you also change your port to `636`? This is likely the issue.

**Comment by stevebauman** [comment]
I believe there was an issue in an older Adldap version that even if you specified a port number, when SSL was enabled it forced port `636` no matter what was configured.

**Comment by CYGREEN** [comment]
Good New! Your suggestion of changing the port to 636 fixed the problem. I think I remember reading about the port automatically being chosen somewhere else so I didn't give that much thought. I figured it was a config issue. Thanks for the help and thanks for this package!

**Comment by stevebauman** [comment]
No problem! Glad you've resolved it :)

Thanks for the kind words!

**Comment by gbryant200** [comment]
in CYGREEN's 2 different configurations above, one port number is a string, the other is a number.

Which is correct?

**Comment by stevebauman** [comment]
Hi @gbryant200,

The port number must be an integer. Setting it otherwise will throw an exception.
