### ISSUE TITLE
Need of Doctrine ?

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#52]
I don't know if it's normal but since the 5.1 update (your last commit), I've this error : 
```
Fatal error: Class 'Doctrine\Common\Collections\ArrayCollection' not found 
```
We need to use Doctrine ? If yes could you please give us more informations or include in your code the correct package ?

Thanks

**Comment by stevebauman** [comment]
Do you use composer? Doctrine collections should have been installed automatically running `composer update`.

[Doctrine collections](https://github.com/doctrine/collections) are only installed, nothing else.

**Comment by ciadch** [comment]
No not yet. But I include it "manually" and it works correctly now !

**Comment by stevebauman** [comment]
Ok great. It's a small addition but provides some nice uses for developers when a collection is returned and not just an array.
