### ISSUE TITLE
I want to Access Multiple OU using single account.

### ISSUE THREAD

**Issue by krunaladaptit** [Adldap2/Adldap2#520]
- Adldap2 Version: 5.6
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:

Hello

I want to Access Multiple OU using a single account.

So can anyone have the idea about this?

**Comment by stevebauman** [comment]
Hi @krunaladaptit, I'm not sure what you're asking for here.

What is your current code and what are you looking to achieve?

You can access OU's performing the following:

```php
$ous = $provider->search()->ous()->get();
```

**Comment by krunaladaptit** [comment]
Hello @stevebauman ,

Well, Thanks for helping me

`$ous = $provider->search()->ous()->get();`

In This way, i am accessing the current OU from the AD.

I want to know how many OU available in the AD.

Do we have such method which will fetch all the OU from the AD?

**Comment by stevebauman** [comment]
Hi @krunaladaptit, as long as your `base_dn` set inside your configuration is the correct base distinguished name of your LDAP environment, then the code I've shown above will correctly return you all organizational units.

If you're looking for the count, then you can simply use the `count()` method:

```php
$count = $provider->search()->ous()->get()->count();
```

**Comment by krunaladaptit** [comment]
@stevebauman  Thank you so much

**Comment by stevebauman** [comment]
No problem @krunaladaptit! If you need help with anything else, give me a shout :)
