### ISSUE TITLE
LDAP over SSL between an IIS server and remote AD running on Windows Server 2012 R2

### ISSUE THREAD

**Issue by valentinstudent** [Adldap2/Adldap2#521]
- Adldap2 Version: last version
- LDAP Type: Active Directory
- PHP Version: 7.1.15

### Description: 

Hello,

I have an "A" machine for the Active Directory on Windows Server 2012 R2 and a "B" machine with an IIS web server on Windows Server 2012 R2 too. I'm having a huge problem setting a user's password because I can not set up SSL over LDAP.

Do you have a tutorial other than the one on GitHub (LDAP)? It's been 2 weeks since I stuck on this problem :'(

Here is my code for the connection:

![image](https://user-images.githubusercontent.com/36890233/37289794-d458d236-260a-11e8-820b-ce0ccd5bc7e4.png)

Thank you in advance !

**Comment by stevebauman** [comment]
Hi @valentinstudent,


Is SSL setup on your ActiveDirectory server?

If you receive a generic "Can't connect to LDAP server" exception, it's either your configuration, or your AD server.

**Comment by valentinstudent** [comment]
Hello @stevebauman,

I set up the role "Active Directory Certificate Services" on my AD server, yes, but at the level of errors, I have nothing more to display, only a blank page, however, when I used the first version ADLDAP I had the message you said! I followed your tutorial but nothing helps :/

**Comment by stevebauman** [comment]
Remove your `try / catch` block in your code and see what the exception says when you try to connect.

Have you tried any to connect to your AD server using SSL with any tools to see if it's actually configured properly at the server level?

**Comment by valentinstudent** [comment]
Here is the error that appears after removing the try / catch block :
![image](https://user-images.githubusercontent.com/36890233/37291281-9c489d0a-260e-11e8-8a76-97a70b445b21.png)

I tested the LDAPS connection with the tool "ldp.exe" and it returns all information, I read on the internet that if this information was displayed is that the connection is done correctly.
![image](https://user-images.githubusercontent.com/36890233/37291568-2f76b314-260f-11e8-9677-97f16f608922.png)

I also check the logs and when I try to set a password, event viewer turns me back error 48.
![image](https://user-images.githubusercontent.com/36890233/37291751-9c7fa308-260f-11e8-82fc-1918bbb0d833.png)

**Comment by stevebauman** [comment]
Hi @valentinstudent, according to this resource from Microsoft, error code 48 is:

> Received a valid certificate chain or partial chain, but the certificate was not accepted because the CA certificate could not be located or could not be matched with a known, trusted CA. This message is always fatal.

https://blogs.msdn.microsoft.com/kaushal/2012/10/05/ssltls-alert-protocol-the-alert-codes/

**Comment by valentinstudent** [comment]
Re, 
I have already looked at this error and I tested several tutorials from the internet but it seems that the stage of the certificate blocks me. So I'll still look at it :-/ Otherwise the code in my first post is enough to make an ldaps connection? Do not you have to enter a URL starting with "ldaps: //"?
Thank you for not closing this post too soon, I will probably need you again :)

**Comment by stevebauman** [comment]
The code you have is fine. You don't need to enter in `ldaps://` into your host names as this is done for you if you have `use_ssl` in your configuration enabled.

No problem! I'll close this for now, but please comment back if you get past this with your server and have an issue with this package.

**Comment by wranger** [comment]
Did you made an import of the AD-Server Certifikate and CA to your IIS?

Run mmc.exe Add SnapIn -> Certificate -> Computer and try an in and export.
----------
On Linux you have to enable the ability to use non public certificates by 
<code>
cat /etc/ldap/ldap.conf
#Setting this value
TLS_REQCERT allow
</code>
Maybe there is something similar to IIS ?

**Comment by valentinstudent** [comment]
Hello @wranger @stevebauman ,

I switched from IIS to Debian 9.
I followed the advice of @wranger and adding the line "TLS_REQCERT allow", the user is added in the AD but his password is not configured .. Namely I have an HTTPS connection but without having installed AD certificates on Apache.

Do you have any idea why the password was not configured using LDAPS?
![image](https://user-images.githubusercontent.com/36890233/37460233-ed027e80-284a-11e8-9333-47ef01abb126.png)
![image](https://user-images.githubusercontent.com/36890233/37460282-0bb78d98-284b-11e8-91c8-32db1ddd785e.png)

**Comment by wranger** [comment]
Stupid question: have you made a $user-save(); after setPassword()

**Comment by wranger** [comment]
Here is my complete routine:
<code>
$user = $this->pro_adint->make()->user($user_data);

$dn = $user->getDnBuilder();

$dn->addCn($cn_name);

$user->setDn($dn);

if(@$user->create())
{
$user->setUserAccountControl(512);

$user->setPassword($data["password"]);

if(@$user->save())
{
</code>
Sorry,the formatting sucks at the moment on github, don't know why.

**Comment by valentinstudent** [comment]
yes I save the user well as he registers well but without the password that I attribute to him :-/

Here is my code :
![image](https://user-images.githubusercontent.com/36890233/37462961-fad8f030-2853-11e8-865d-35067d000c1e.png)
![image](https://user-images.githubusercontent.com/36890233/37463012-30aca332-2854-11e8-808c-44c1473053a8.png)

**Comment by valentinstudent** [comment]
The password line is commented but when I tried, The line was uncommented :-)

**Comment by wranger** [comment]
Hmm I remember i ran into similar. 
1. Create the user
2. Set the password and the account control in a second step like in my code

**Comment by valentinstudent** [comment]
OMMMMG THANK YOU @wranger 
it's finally working! After 2 weeks of problem I can finally get there!

**Comment by wranger** [comment]
Perfect :)

**Comment by stevebauman** [comment]
Thanks @wranger! Really appreciate your help with this :smile:

Just so you don't feel crazy, I tweaked your posted code to fix the formatting.

To post PHP code you can type the following in GitHub (triple accent syntax):

```
    ```php
        <code goes here>
    ```
```

Really glad you were able to get this working @valentinstudent.

Since this issue is resolve I'll close it out, but if you encounter further issues just create one, thanks!
