### ISSUE TITLE
Wrong object class when creating users

### ISSUE THREAD

**Issue by superkozel** [Adldap2/Adldap2#523]
- Adldap2 Version: #.#
- LDAP Type: 
- PHP Version: #.#

### Description:
When creating users, user() method from schema is used, while there is special field in schema
userObjectClass(), that belongs here

file Models\Factory:97

```php 
    /**
     * Creates a new user instance.
     *
     * @param array $attributes
     *
     * @return User
     */
    public function user(array $attributes = [])
    {
        $model = $this->schema->userModel();

        return (new $model($attributes, $this->query))
            ->setAttribute($this->schema->objectClass(), [
                $this->schema->top(),
                $this->schema->person(),
                $this->schema->organizationalPerson(),
                $this->schema->objectClassUser(),
            ]);
    }
```

very easy fix

**Comment by stevebauman** [comment]
Hi @superkozel,

I'm not sure what you mean? Are you able to explain a bit further?

There is no method in the schema named `userObjectClass()`, however there is a `objectClassUser()` that is shown in the code you've posted.

**Comment by superkozel** [comment]
Thanks for the answer.
@stevebauman 
In my LDAP schema, class that belongs to "objectClass" variable for users is "inetorgperson", which differs from "users". When i create user through adldap2 build-in methods, i cant set this class without changing it manually with some tuning.

When i search users, i search "user", which is correctly set with users() method in schema.
But when i create user, i must set him another class(objectClass), "inetorgperson", instead of "user"

In both constructor of user object and query builder, Schema::users() is used. I guess, in User object constructor, Schema::objectClassUser() should be used. 

Schema::objectClassUser() is unused method, not used anywhere in the code of the library, so it must belong here.

**Comment by stevebauman** [comment]
Thanks for the response @superkozel.

If you could please fill out your version information above for logging and for my knowledge so I can assist you easier that would be great. This is described when creating an issue, and I need to enforce this at some point:

```
- Adldap2 Version: #.#
- LDAP Type: <!-- Active Directory / OpenLDAP / FreeIPA? -->
- PHP Version: #.#

<!-- ISSUES WITHOUT THE ABOVE INFORMATION WILL BE CLOSED! -->
```

Your LDAP shema differs for a reason and I'm not sure what type of LDAP server you have in your environment.

You're right about the `objectClassUser()` schema method. I'll add this into the `user()` factory method.

Thanks!

**Comment by superkozel** [comment]
@stevebauman 

> You're right about the objectClassUser() schema method. I'll add this into the user() factory method.

this totally solves my issue, thanks!

**Comment by stevebauman** [comment]
Added in `dev-master`, new version will be coming soon! Thanks again :smile:
