### ISSUE TITLE
Option admin_username does not exist

### ISSUE THREAD

**Issue by valentinstudent** [Adldap2/Adldap2#525]
- Adldap2 Version: last version
- LDAP Type: Active Directory
- PHP Version: 7.0.27

### Description:
ADLDAP2 running on Debian9.
Active Directory on Windows Server 2012 R2.
Hello @stevebauman,
Being stuck with IIS, I switched to Debian, but I can not add users to LDAP (389). Apache gives me the following error:
![image](https://user-images.githubusercontent.com/36890233/37411972-52aa9da0-27a4-11e8-8706-47c7defd4ca6.png)

Here is my code :
(config.php)
![image](https://user-images.githubusercontent.com/36890233/37412029-7675be72-27a4-11e8-8e39-fd07d81c0e46.png)

and (configNewUser.php) :
![image](https://user-images.githubusercontent.com/36890233/37412108-94b43d82-27a4-11e8-9c40-522837c0685f.png)
![image](https://user-images.githubusercontent.com/36890233/37412175-b5546de6-27a4-11e8-88d4-1656f7ae4328.png)
![image](https://user-images.githubusercontent.com/36890233/37412205-c30f8bdc-27a4-11e8-8cc4-3a4f8cc1bd59.png)

Could you please explain where is my error ? :-)

Thanks !

**Comment by valentinstudent** [comment]
The Debian should be in the domain maybe?

**Comment by stevebauman** [comment]
Hi @valentinstudent, are you using `dev-master`? I noticed the error message states that the `admin_username` configuration option does not exist. This was only changed in `dev-master`.

Please switch to `v8.0` branch, as `dev-master` contains breaking changes.

**Comment by stevebauman** [comment]
> The Debian should be in the domain maybe?

As long as your web server can contact your LDAP server, then you should be fine. You shouldn't need to add your web server to your domain for it to work properly.

**Comment by valentinstudent** [comment]
Thanks ! Should I follow "https://packagist.org/packages/adldap2/adldap2#v8.0.0" for download the V8.0?

**Comment by stevebauman** [comment]
No problem! You can use packagist to *identify* what new versions are available, but you will need to edit your `composer.json` file in your project and make sure you're targeting the right `v8.0` branch.

For example, make sure it looks like this:

```json
 "require": {
        "adldap2/adldap2": "8.0.*",
```

And **not**:

```json
 "require": {
        "adldap2/adldap2": "dev-master",
```

**Comment by stevebauman** [comment]
Then once you've corrected the version number, run the `composer update` command inside the root of your project to update your dependencies.

**Comment by valentinstudent** [comment]
Okay, I notice that I do not have the line:

"require": {
         "adldap2 / adldap2": "8.0. *",

in the composer.json file ....

to install ADLDAP2, I made a "git clone https://github.com/Adldap2/Adldap2.git"
Then: "cd Adldap2"
And finally "composer require adldap2 / adldap2 and dial returns this message:
![image](https://user-images.githubusercontent.com/36890233/37418645-fe17fb84-27b2-11e8-9f60-b08908deaada.png)

**Comment by stevebauman** [comment]
Please make sure only one `adldap2/adldap2` package exists inside the `require` array in your `composer.json` file.

**Comment by valentinstudent** [comment]
I have no adldap2/adldap2 package in my composer.json file..
![image](https://user-images.githubusercontent.com/36890233/37419028-d7bada00-27b3-11e8-95c4-99baceb887a2.png)
![image](https://user-images.githubusercontent.com/36890233/37419104-0a542b06-27b4-11e8-86c5-6240b3fbca6f.png)

**Comment by valentinstudent** [comment]
I just added the line "      "adldap2 / adldap2": "8.0. *",       "
![image](https://user-images.githubusercontent.com/36890233/37419650-3d3040f4-27b5-11e8-91ea-fac5a3c41970.png)
And then make a "composer update" et composer return this error :
![image](https://user-images.githubusercontent.com/36890233/37419682-4a3bf630-27b5-11e8-9504-6ac3ecb5ede5.png)

**Comment by stevebauman** [comment]
Great! Glad you're up and running. Thanks for the quick response and your kind words :smile:

**Comment by valentinstudent** [comment]
Thanks too for your quick response!
