### ISSUE TITLE
 Prevent user creation if passwords do not match ?

### ISSUE THREAD

**Issue by valentinstudent** [Adldap2/Adldap2#527]
- Adldap2 Version: 8.0
- LDAP Type: Active Directory
- PHP Version: 7.0.27

How does the code structure look to prevent the creation of a new user if the password and the password confirmation do not match?

I tried this:

```php
include "config.php";

$provider = $ad->connect();

$user = $provider->make()->user();

if($user->create()){
    // Account options here
}

if($Password != $ConfirmPassword){
    echo "not create";
} else {
    $user->setPassword($Password):
    $user->save();
    echo "user has been created";
}
```

but despite different tests, the user is always created.

Thank you in advance ! :)

**Comment by stevebauman** [comment]
Hi @valentinstudent, you're calling `create()` on the user, so you're always going to create the user regardless here?:

```php
if($user->create()){
    // Account options here
}
```

You will need to do your conditional logic before you call `create()` or `save()` on the user.

Ideally, you really only need to call `save()` on the model, as it knows whether it exists or not.

**Comment by valentinstudent** [comment]
Hello @stevebauman :-)

Thanks for reply, I think I understand that you explain ! I will test it as soon as possible :-)

Have a nice weekend !

**Comment by stevebauman** [comment]
No problem @valentinstudent!

Since I didn't provide an example in my previous response, here is one using your code:

```php
include "config.php";

$provider = $ad->connect();

// Always use triple equals for password comparisons
if($Password === $ConfirmPassword) {
    $user = $provider->make()->user();

    $user->setCommonName('John Doe');
    $user->setAccountName('jdoe');
    $user->setUserAccountControl(512);
    $user->setPassword('Password1');

    if ($user->save()) {
        // User was created!
    }
} else {
    // User not created.
}
```

Hope you have a nice weekend as well!

**Comment by valentinstudent** [comment]
Well it works fine ! Thank you @stevebauman  :100:
