### ISSUE TITLE
passwordExpired() does not return correct value

### ISSUE THREAD

**Issue by OllieB** [Adldap2/Adldap2#530]
- Adldap2 Version: 8.1.3
- LDAP Type: Active Directory
- PHP Version: 7.1.8

### Description:
passwordExpired() does not return true when a password expires of... natural causes.

The issue is the use of `getPasswordLastSet()`, which will still return the timestamp of when the password was last set, even after the password has expired.

The only way I have found to check for password expiry, is to see if the last set time + max password age has elapsed.

### Steps To Reproduce:
Allow a password to expire by allowing it to remain unchanged for longer than the max password age set on the domain.

**Comment by stevebauman** [comment]
Thanks for the report @OllieB! Fix will be coming shortly.

**Comment by stevebauman** [comment]
Fix has been taking longer than expected.

This is due to having to retrieve the domain root object to retrieve the max password age, but this is only required in ActiveDirectory, so looking for ways to have this configurable for other schemas.

**Comment by stevebauman** [comment]
Fixed in `v8.1.4`. Thanks for the report!
