### ISSUE TITLE
getSid does not return correct value.

### ISSUE THREAD

**Issue by gdesoto-lhs** [Adldap2/Adldap2#531]
- Adldap2 Version: 6.1.10
- LDAP Type: Active Directory
- PHP Version: 7.1
- Implementation: Adldap2-Laravel

### Description:
Trying to get the string version of a user's SID. The method to get the converted SID does not return the correct value.

### Steps To Reproduce:
```
$user = Adldap::search()->users()->whereCn('username')->first();
echo $user->objectsid[0]; // b"\x01\x05\0\0\0\0\0\x05\x15\0\0\0‗▓ÒÉ~\x08JóÛ&àù¶\x01\0\0"
echo $user->getObjectsid(); // b"\x01\x05\0\0\0\0\0\x05\x15\0\0\0‗▓ÒÉ~\x08JóÛ&àù¶\x01\0\0"
echo $user->getSid(); //  "S-1-5-21--1864125710--1572206466--1752881430-4013"
// The expected result should be: "S-1-5-21-2430841586-2722760830-2542085866-4013"
```

I tested the solution to convert SID to string found [here](https://stackoverflow.com/questions/39533560/php-ldap-get-user-sid), and that did return the expected value.

**Comment by stevebauman** [comment]
Hi @gdesoto-lhs, this was patched in later versions of Adldap2. Can you update to the latest v8?

https://github.com/Adldap2/Adldap2/blob/master/src/Utilities.php#L62-L74
