### ISSUE TITLE
I Can't change user password in Active Directory

### ISSUE THREAD

**Issue by DaliaPinto** [Adldap2/Adldap2#532]
- Adldap2 Version: 8.1.3
- LDAP Type: Active Directory
- PHP Version: 7.2
- Laravel Version: 5.6

### Description:

When I try to add a new user, I can create the user, but when I change the password, I get this error:

`Adldap \ Connections \ ConnectionException
You must be connected to your LDAP server with TLS or SSL to perform this operation`

I disabled "Password operations over LDAPS only" policy in the active directory server, and still get the same error.

Here is the function where the user is added:

```
    use Adldap\Laravel\Facades\Adldap;

    public function addUser(Request $request)
    {
        $full_name = $request->name.' '.$request->last_name.' '.$request->middle_name;

        $user = Adldap::make()->user([
            'givenname' => $request->name,
            'sn' => $request->last_name,
            'uid' => $request->username,
            'cn' => $full_name,
            'displayname' => $full_name,
            'name' => $full_name,
            'samaccountname' => $request->username,
            'userprincipalname' => $request->username.'@***.ads',
            'useraccountcontrol' => 66080,
            'pwdlastset' => -1
        ]);

        if($user->save()){
            $user->setPassword($request->password);
            $user->save();
            $message = 'User added';

        }
        return collect(['status' => 0, 'message' => $message]);
    }

```
This is my Adldap.php configuration file:

```
'connections' => [
        'default' => [
            'auto_connect' => env('ADLDAP_AUTO_CONNECT', true),
            'connection' => Adldap\Connections\Ldap::class,
            'schema' => Adldap\Schemas\ActiveDirectory::class,
            'connection_settings' => [
                'account_prefix' => env('ADLDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('ADLDAP_ACCOUNT_SUFFIX', ''),
                'domain_controllers' => explode(' ', env('ADLDAP_CONTROLLERS', 'v*********1')),
                'port' => env('ADLDAP_PORT', 389),
                'timeout' => env('ADLDAP_TIMEOUT', 5),
                'base_dn' => env('ADLDAP_BASEDN', 'dc=***,dc=***'),
                'admin_account_prefix' => env('ADLDAP_ADMIN_ACCOUNT_PREFIX', ''),
                'admin_account_suffix' => env('ADLDAP_ADMIN_ACCOUNT_SUFFIX', ''),
                'admin_username' => env('ADLDAP_ADMIN_USERNAME', '********'),
                'admin_password' => env('ADLDAP_ADMIN_PASSWORD', '********'),
                'follow_referrals' => false,
                'use_ssl' => env('ADLDAP_USE_SSL', false),
                'use_tls' => env('ADLDAP_USE_TLS', false),            ],

        ],
    ],
```

Why it doesn't work?
I hope you can help me

Ps: Sorry for my bad english -.-

**Comment by stevebauman** [comment]
Hi @DaliaPinto,

Unfortunately this is actually baked directly into the `setPassword()` and `changePassword()` user methods. It doesn't take into account that your server has that policy disabled.

You can see it here at `$this->validateSecureConnection()`:

https://github.com/Adldap2/Adldap2/blob/3f20fb3720dd291303d798edf01e38f8556e28b4/src/Models/User.php#L1086-L1097

However, it was done this way to make the Adldap2 more secure by enforcing SSL / TLS before these operations take place.

Otherwise, if you do send passwords without SSL / TLS, this traffic **can be sniffed** and your passwords **will be in plain text** when sent to the server (which is a massive security vulnerability).

Imagine resetting a password for a domain administrator account over plain text. Anyone sniffing that traffic now knows everything they need to access the account.

If you still want to do this, then you will need to mimic the underlying methods.

Here's what you'll need to do (using your posted code):

```php
if ($user->save()) {
    $mod = $this->newBatchModification(
        'unicodepwd',
        LDAP_MODIFY_BATCH_REPLACE,
        [\Adldap\Utilities::encodePassword($request->password)]
    );

    $user->addModification($mod);
    
    $user->save();
    
    $message = 'User added';
}
```

**Comment by DaliaPinto** [comment]
OMG Thank you for response so quickly.

I added the code lines that you told me, but I get this error.

`ErrorException (E_WARNING)
ldap_modify_batch(): Batch Modify: Server is unwilling to perform`

I've searched too much about this error, but nothing helps me.

**Comment by stevebauman** [comment]
No problem @DalioPinto!

This looks like the standard error being returned from your server when you try to change a users password without an SSL or TLS connection.

You could try rebooting the server or making sure you're connected to the host that has had the policy change.

**Comment by DaliaPinto** [comment]
I'll try tomorrow, when my partner back and check it, I hope it works. 

Thanks for your help <3

**Comment by DaliaPinto** [comment]
Hi @stevebauman.
The server was restarted, and I get the same error 

`ErrorException (E_WARNING) ldap_modify_batch(): Batch Modify: Server is unwilling to perform`

Then, we used Apache SSL connection (self signed certificate) from an Ubuntu Virtual Host to Active Directory Server. We made all these actions in our local network.

Why doesn't work yet? What's wrong?

**Comment by stevebauman** [comment]
Hi @DaliaPinto,

I'm not sure what the issue could be, you may need to look at the logs on your ActiveDirectory server and see why it's returning that response.

Unfortunately, there's nothing I can do on my end.

Your server is just saying "Sorry, I understand what you're trying to do, but I refuse to do it".

From what you mentioned above, are you saying you applied an SSL certificate to your ActiveDirectory server? If that's the case, you'll need to enable 'use_ssl' in your Adldap2 configuration to actually use SSL.

**Comment by DaliaPinto** [comment]
We changed the password with C# app, and it works as expected. 
We'll trying with Adldap2 yet, thanks for your help.

**Comment by DaliaPinto** [comment]
No, We applied SSL certificated (self signed certificate) in the Ubuntu Virtual Host.

Actually, we changed the password with C# app, and it works as expected.
We'll try with Adldap2 a few times, thanks for your help.

**Comment by stevebauman** [comment]
C# has the advantage of working with the Windows core API. It will allow you to bypass a lot of the security features ActiveDirectory sets.

For example, using Windows COM on PHP, you're able to actually bypass password requirements completely on your AD server. I created something a long time ago doing just that:

https://github.com/stevebauman/Corp/blob/master/src/Stevebauman/Corp/Services/UserComService.php#L47-L138

Let me know if you come to a resolution, thanks!

**Comment by DaliaPinto** [comment]
Ok, I'll try with that. 
thanks for your help.
