### ISSUE TITLE
setPasswordLastSet function missing

### ISSUE THREAD

**Issue by daniwb** [Adldap2/Adldap2#538]
- Adldap2 Version: 3.0
- LDAP Type: Active Directory
- PHP Version: 7.1.14

### Description:
In Active Directory we can set the Password to be changed at next Logon.
This is working with the Attribute pwdLastSet.
We can read the attribute via getPasswordLastSet(), but there is no setPasswordLastSet()

The Field cannot be set to any other value than 0 or -1 via LDAP.
With 0 the Password expires immediately, with -1 the Password doesn't expire at all.

According to the site http://ldapwiki.com/wiki/Pwd-Last-Set%20attribute it should be possible to set that attribute via LDAP

### Steps To Reproduce:
None. Feature Request

**Comment by daniwb** [comment]
duplicate of #357

**Comment by stevebauman** [comment]
Thanks @daniwb, I'll create a setter for this for convenience even though you can set it with the `setAttribute()` method.

**Comment by stevebauman** [comment]
Thanks @MacBooc! Appreciate the reminder.

@daniwb, this has been added to `v8.0`:

https://github.com/Adldap2/Adldap2/commit/255c339f1536b8e6ca86356ce78c1878e3cb1ac7

https://github.com/Adldap2/Adldap2/commit/85740a36638a89ac32b3e6c73a7f073573409c91

Judging by the version number you've given, I'm assuming it's your Adldap2-Laravel version which is using Adldap2 `v7.0`. You will need to use Adldap2-Laravel `v4.0` to use this new feature.
