### ISSUE TITLE
ADVICE: How to enable/disable an AD user?

### ISSUE THREAD

**Issue by Kerneltroll** [Adldap2/Adldap2#541]
- Adldap2 Version: v8.1.5
- LDAP Type: Active Directory
- PHP Version: 7.2.2

### Description: Evening all!

I'm hoping someone can help me, i'm trying to work out how to disable and enable a user account, i have tried codes like:

    $user = $ad->search()->find('test');
    $user->setUserAccountControl('512');
    var_dump($user->save()); // Return false
 
    if ($user) echo "User is disabled";
    else echo "Usj, something wrong happend";```

However it returns bool(true) but if i check AD the user is still enable! 

I'm struggling to find right documentation and using search is not helping too much!

Below i've listed my config.php that i made just to help y'all

    require '../vendor/autoload.php';
    use \Adldap\Adldap;
    include "../vendor/adldap2/adldap2/src/Adldap.php";
    $config = [
    'default' => [
    'domain_controllers' => ['tig.com'],
    'base_dn' => 'dc=tig,dc=com',
    'admin_username' => 'james@tig.com',
    'admin_password' => 'Something01',
    ]
    ];
    $ad = new \Adldap\Adldap($config);
    $provider = $ad->connect('default');

**Comment by MacBooc** [comment]
> $user = $ad->search()->find('test');
> $user->setUserAccountControl('512');
> var_dump($user->save()); // Return false

Actually 512 is to enable and 514 to disable an account. Also make sure that find('test') return an instance of User

**Comment by stevebauman** [comment]
Hi @Kerneltroll, @MacBooc is correct, try his suggested steps.

If you still encounter issues let us know and I will re-open this issue.

**Comment by Kerneltroll** [comment]
How do i find out if the user account is enabled?
 IF UserAccountControl === 512 user is enabled etc..?

**Comment by Kerneltroll** [comment]
1992 called, they told me to use the built in functions.. :D
