### ISSUE TITLE
Help needed to get config.php syntax right

### ISSUE THREAD

**Issue by jelockwood** [Adldap2/Adldap2#543]
- Adldap2 Version: 8.1.5
- LDAP Type: FreeIPA
- PHP Version: 7.0.28-0ubuntu0.16.04.1

### Description:
I am trying to get adldap2 working with an open-source project called MunkiReports-PHP. See - https://github.com/munkireport/munkireport-php

The MunkiReports project uses adldap2. There are two linked issues, firstly the syntax MunkiReports uses in its config.php is perhaps different to that used by others and secondly as I am using FreeIPA rather than Active Directory I presumably need to tell adldap2 this so it uses the correct FreeIPA schema. It is how to add this to the config.php I am struggling on as attempts I have made generate an error.

Here is a snippet from the MunkiReports config.php to illustrate how it configures using adldap2. The full config_default.php for MunkiReports-PHP is at https://github.com/munkireport/munkireport-php/blob/master/config_default.php

```
        |       4) Active Directory: fill the needed and include the lines in your config.php.
        |                e.g.
        |               $conf['auth']['auth_AD']['account_suffix'] = '@mydomain.local';
        |               $conf['auth']['auth_AD']['base_dn'] = 'DC=mydomain,DC=local'; //set to NULL to auto-detect
        |               $conf['auth']['auth_AD']['domain_controllers'] = array('dc01.mydomain.local'); //can be an array of servers
        |               $conf['auth']['auth_AD']['admin_username'] = NULL; //if needed to perform the search
        |               $conf['auth']['auth_AD']['admin_password'] = NULL; //if needed to perform the search
        |               $conf['auth']['auth_AD']['mr_allowed_users'] = array('macadmin','bossman');
        |               $conf['auth']['auth_AD']['mr_allowed_groups'] = array('AD Group 1','AD Group 2'); //case sensitive
```

I tried the following 

`                      $conf['auth']['auth_AD']['schemas'] = \Adldap\Schemas\FreeIPA::class;
`
and
`                      $conf['auth']['auth_AD']['schemas'] = \Adldap\Schemas\FreeIPA;
`
With these I get from MunkiReports an error like this

**Not authorized
Option schemas does not exist.**

I have spoken to the author of MunkiReports but I get the impression he has not himself had to use the Schema option.

I am not necessarily saying this is a bug in adldap2 but I am hoping that you might be able to shed some light on how to resolve this.

The previous version of MunkiReports 2.15.2 worked using its auth_ldap section and I believe this did not use adldap2. However even though the same auth_ldap section is supposedly supported by the new MunkiReports-PHP 3.1.1 it now gives an error when trying to use the former settings and the author is recommending switching to using his auth_AD section and hence adldap2. See https://github.com/munkireport/munkireport-php/issues/1006 
### Steps To Reproduce:
Install MunkiReports-PHP from https://github.com/munkireport/munkireport-php
Copy config_default.php to config.php
Edit config.php to use auth_AD rather than auth_ldap auth_AD would seem to correspond to using adldap2
Setup your web server to serve the munkireports project
Access the munkireports website
Try logging in using LDAP credentials

Note: The composer.json file for MunkiReports does include adldap2 and it does end up in the vendor/adldap2/adldap2 directory.

**Comment by stevebauman** [comment]
Hi @jelockwood,

The correct config option is called `schema` not `schemas`:

https://github.com/Adldap2/Adldap2/blob/master/src/Configuration/DomainConfiguration.php#L38

I'll have to look into how Munkireport is using Adldap2, but in the meantime give that a shot and let me know if it's resolved.

**Comment by jelockwood** [comment]
@stevebauman 
I changed it to -

`$conf['auth']['auth_AD']['schema'] = \Adldap\Schemas\FreeIPA::class;`

and it still fails, new error is as follows.

**Not authorized
Option schema does not exist.**

As you can see the error has noticed the change.

Thanks for your assistance.

**Comment by stevebauman** [comment]
Hi @jelockwood, are you absolutely 100% sure you're using the newest version of Adldap2?

`v7.0` does not include a configurable schema option, **only** `v8.0` does:

https://github.com/Adldap2/Adldap2/blob/v7.0/src/Configuration/DomainConfiguration.php

Can you open the `vendor` folder in your application and make sure that configuration option is actually there to be configured?

If it's not there, you're using an older version.

**Comment by jelockwood** [comment]
@stevebauman 
Thanks for the information about schema not actually being supported in 8.x I will pass on your information to the author of MunkiReports. As things stand your suggestion is not possible with the format of his config.php as far as I can see but he might be able to take your information and either adapt to it or provide me some other modification.

**Comment by jelockwood** [comment]
For what its worth, the author of MunkiReport-PHP updated his code. Since then he has also done a major version upgrade. The latest version 4.01 is working fine via ADLDAP2 to connect to FreeIPA. I am therefore closing this issue.

**Comment by stevebauman** [comment]
Thanks @jelockwood! Really appreciate you following up and closing this out.

**Comment by jelockwood** [comment]
As you may have seen in the process of finally finishing this off I found the same issue listed here https://github.com/Adldap2/Adldap2/pull/633

:)
