### ISSUE TITLE
Bind as User never running, bind as administrator running instead

### ISSUE THREAD

**Issue by Eliie58** [Adldap2/Adldap2#545]
- Adldap2 Version: 8.0.0
- LDAP Type: Active Directory
- PHP Version: 7.2.5

Description:

Hii, i am trying to integrate AD authentication into my application, i have followed the explanation provided, and when i try to login, i receive an invalid credentials error. When i tried to debug this, i noticed something weird, in the Guard.php, the function bind is being called with Admin username and password only.

Steps To Reproduce:

    protected function attemptLogin(Request $request) {
        $credentials = $request->only($this->username(), 'password');
        $username = $credentials[$this->username()];
        $password = $credentials['password'];
        $user_format = env('ADLDAP_USER_FORMAT', 'cn=%s,'.env('ADLDAP_BASEDN', ''));
        $userdn = sprintf($user_format, $username);
        
//This part is appearing in the logs        
Log::info('Trying' . $username . " " . $password);

        if(Adldap::auth()->attempt($username, $password, $bindAsUser = true)) {
//I am never reaching this part 
            $user = \App\User::where($this->username(), $username) -> first();
            if (!$user) {
                
                $user = new \App\User();
                $user->username = $username;
                $user->password = '';

                $sync_attrs = $this->retrieveSyncAttributes($username);
                foreach ($sync_attrs as $field => $value) {
                    $user->$field = $value !== null ? $value : '';
                }
            }
            $this->guard()->login($user, true);
            return true;
        }
        
        // the user doesn't exist in the LDAP server or the password is wrong
        // log error
        return false;
    }

In the Guard.php:

public function bind($username, $password, $prefix = null, $suffix = null)
    {
        // We'll allow binding with a null username and password
        // if they're empty. This will allow us to anonymously
        // bind to our servers if needed.

//When i check the logs, admin username and password appear, and not those used on login screen
        Log::info($username . " " . $password);

        $username = $username ?: null;
        $password = $password ?: null;

        if ($username) {
            $username = $this->applyPrefixAndSuffix($username, $prefix, $suffix);
        }

        Log::info($username);
        // We'll mute any exceptions / warnings here. All we need to know
        // is if binding failed and we'll throw our own exception.
        if (!@$this->connection->bind($username, $password)) {
            throw new BindException($this->connection->getLastError(), $this->connection->errNo());
        }
    }

**Comment by stevebauman** [comment]
Hi @Eliie58,

To comment on this line:

```php
if(Adldap::auth()->attempt($username, $password, $bindAsUser = true)) {
    //I am never reaching this part
    $user = \App\User::where($this->username(), $username) -> first();
```

You're not reaching this part due to your authentication attempt returning `false`.

As for your admin username appearing in the logs, that would be expected since automatic binding takes place if you have `auto_connect` set to true in your `config/adldap.php` file, though I'm surprised your not seeing your users usernames being passed...

Try calling a raw `bind()` and see if that is shown in your Laravel logs:

```php
if (Adldap::auth()->bind($username, $password)) {
```

If you don't see anything, there's something going on in your application.

**Comment by Eliie58** [comment]
I ended up writing my own authentication using the native php functions. Thanks for your reply.
