### ISSUE TITLE
Change expired password

### ISSUE THREAD

**Issue by zoriax** [Adldap2/Adldap2#552]
Hi @stevebauman,

Juste a simple question, how to allow password change if account it is expired ? What I need is to use "old password" and be sure this one is correct before allowing change. A suggestion ? 

I can get password "state" with passwordExpired() method but how can I "connect" or "bind" with an expired password (required to be sur that the user knows his password) 

Thanks for your help !

Cheers !

**Comment by ciadch** [comment]
I found this post : https://github.com/Adldap2/Adldap2/issues/391

Seems to be the solution :-) ! You agree ?
