### ISSUE TITLE
Swap out the users() filter on the Query/Factory class

### ISSUE THREAD

**Issue by borisuu** [Adldap2/Adldap2#555]
- Adldap2 Version: 4.0
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:
This is a general question. On my instance of LDAP I don't use a "objectCategory" field. Meaning the built in users() filter in the Query/Factory class will mess up my queries (In the source code it is often called as ```Adldap::search()->users()```. Is there an easy way to swap out the current filter being used on the query, or completely override the users() method from outside. I tried to bind to the Provider class and give back a custom Factory class, but that didn't work since the source uses exclusively concrete implementations.

### Steps To Reproduce:
Try finding a person without the objectCategory field.

Any help would be greatly appreciated.

P.S. Thanks for the great work so far!

### EDIT:
So one more detail about this. This is actually only relevant when I use the Auth Facade, then it goes into the ```UserResolver query()``` method and there the ```users()``` filter gets applied to all the queries.

**Comment by stevebauman** [comment]
Hi @borisuu,

You'll have to create your own `Provider` instance, as well as your own `Factory` class:

```php
// Provider
use Adldap\Connections\Provider;

class MyProvider extends Provider
{
    pubic function search()
    {
        return new MySearchFactory(
            $this->connection,
            $this->schema,
            $this->configuration->get('base_dn')
        );
    }
}
```

```php
// Factory
use Adldap\Query\Factory;

class MySearchFactory extends Factory
{
    public function users()
    {
        return $this->where('...');
    }
}
```

Then:

```php
use Adldap\Adldap;

$ad = new Adldap();

$config = ['...'];

$myProvider = new MyProvider($config);

$myProvider->connect();

$users = $myProvider->search()->users()->get();
```

You can also create your own `Schema` class to return a different value for the `objectCategory` method:

https://github.com/Adldap2/Adldap2/blob/v8.0/src/Query/Factory.php#L158

**Comment by stevebauman** [comment]
Also, thanks so much for your kind words :smile:

I'm glad you're enjoying Adldap2! If you encounter further issues just give me a shout and I'll re-open this.

**Comment by borisuu** [comment]
Hey thanks for the tip :) I'll make sure to implement it.
