### ISSUE TITLE
Get the objectSID ?

### ISSUE THREAD

**Issue by Beko67** [Adldap2/Adldap2#562]
- Adldap2 Version: #.#
- LDAP Type: Active Directory
- PHP Version: 7

Hello everyone,

Before using the Adldap2, I wanted to know if we can get the objectSID with it, it's very important for my application.

Thank you :)

**Comment by badgerfruit** [comment]
I'm pretty sure you can, there's a 'getObjectSid()' method but as I am new to this myself, I can't really give you any good examples, sorry!

**Comment by stevebauman** [comment]
Hi @Beko67,

You can absolutely retrieve any LDAP records ObjectSID.

Here's a full example:

```php
use Adldap\Adldap;

$config = [
    'default' => [
        'domain_controllers' => ['DC01.corp.acme.org'],
        'admin_username' => 'admin',
        'admin_password' => 'password',
        '...',
    ],
];

$ad = new Adldap($config);

$provider = $ad->connect();

$user = $provider->search()->find('jdoe');

$user->getObjectSid(); // Returns raw LDAP binary string
$user->getConvertedSid(); // Returns actual object SID (ex. 'S-1-5-21-1180699209-877415012-3182924384-1004')
```

**Comment by cemkoker** [comment]
Why are these functions 'hidden' and we must open an issue to 'discover' them ?

**Comment by stevebauman** [comment]
Hi @cemkoker,

These are not hidden, they are located in the documentation:

https://adldap2.github.io/Adldap2/#/models/model?id=attributes

![image](https://user-images.githubusercontent.com/6421846/61895949-e424c380-aee1-11e9-953c-43549746aba6.png)

**Comment by stevebauman** [comment]
@cemkoker Keep in mind you can also utilize the global search on the documentation website to quickly locate things you're looking for.
