### ISSUE TITLE
Trying to get user attributes, what am I doing wrong?

### ISSUE THREAD

**Issue by dmcconnell68** [Adldap2/Adldap2#564]
- Adldap2 Version: 8.0
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:
I'm trying to validate a users credentials, which works successfully.  I also need to get several user attributes like groups, email address, etc., which I can't get to work.  Please look at my code below and let me know the issue.  I get tons of data returned in the var_dump for $provider and $user, but nothing for $group.  I can see the users groups in the var_dump($user) output.

### Steps To Reproduce:
<pre><code>
require '../vendor/autoload.php';
$username = 'testuser';

$ad = new \Adldap\Adldap();
$config = [  
	  'domain_controllers'    => ['10.2.3.4'],
	  'base_dn'               => 'dc=corp,dc=tdomain,dc=com',
	  'account_suffix'        => '@corp.tdomain.com',
	  'port'                  => 389,
	];
$ad->addProvider($config);
$provider = $ad->connect();
var_dump($provider);
$provider->auth()->attempt($username, $password, $bindAsUser = true);
$user = $provider->search()->users()->where('samaccountname', '=', $username)->get();
var_dump($user);
$groups = $user->getGroups();
var_dump($groups);
</code></pre>

**Comment by stevebauman** [comment]
Hi @dmcconnell68,

The following line is returning a `Illuminate\Support\Collection` and not a `Adldap\Models\User` instance, so this won't work:

```php
$user = $provider->search()->users()->where('samaccountname', '=', $username)->get();

$user->getGroups(); // Won't work.
```

Instead, call the `first()` method at the end of a search query to indicate you want the first resulting model returned:

```php
$provider = $ad->connect();

$provider->auth()->attempt($username, $password, $bindAsUser = true);

$user = $provider->search()
        ->users()
        ->where('samaccountname', '=', $username)
        ->first(); // 'first' called here.

$groups = $user->getGroups();

var_dump($groups);
```

You can also use the `findBy()` method to indicate you want only the first resulting model:

```php
$user = $provider->search()->findBy('samaccountname', $username);
```

Give that a shot and let me know if you still encounter problems and I'll re-open :smile:
