### ISSUE TITLE
Docs needs updating re v9.0

### ISSUE THREAD

**Issue by orbsmiv** [Adldap2/Adldap2#567]
- Adldap2 Version: 9.0
- LDAP Type: Active Directory
- PHP Version: 7.2

### Description:

For example, docs/configuration.md doesn't reflect the version 9.0 options., e.g. `domain-controllers` being replaced by `hosts`.

**Comment by stevebauman** [comment]
Hi @orbsmiv,

This document was replaced by:

https://github.com/Adldap2/Adldap2/blob/master/docs/setup.md

This was my mistake, forgot to remove `docs/configuration.md`.

Removing now, thanks!
