### ISSUE TITLE
Paginator and sorting

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#57]
Hi ! 

It seems that Paginator continues not sorting elements correctly. In each array of page, it's ok but what could be really interesting is to have a sort in the entire array of results. With that, when you navigate in your differents pages, you keep the sort. Actually when I go to the last page of my results, I continue to have account with "A" letter, but it should be only with last letters of alphabet "Z".

Thanks

**Comment by stevebauman** [comment]
Hi, it's sorting correctly, however it's limited since the `ldap_sort()` method accepts search results, and using ldap pagination, you're limited to retrieving search results *per page*. Going to look for a way around this, thanks!

**Comment by stevebauman** [comment]
Fixed https://github.com/Adldap2/Adldap2/commit/5d857768956f84191bf50205c9ead76453cab189
