### ISSUE TITLE
[QUESTION] Creating custom scopes and returning custom models

### ISSUE THREAD

**Issue by danswiser** [Adldap2/Adldap2#570]
- Adldap2 Version: 9.0
- LDAP Type: OpenLDAP
- PHP Version: 7.2

### Description:
I've added to a custom search class that extends `Adldap\Query\Factory`. It seems the scope works perfectly fine but the result is an `Adldap\Models\Entry` class. How can also return a custom model class?

## Steps to reproduce
```
class SearchFactory extends Factory

  /**
   * Returns a query builder limited to departments.
   *
   * @return Builder
   */
  public function departments()
  {
      return $this->where([
          [$this->schema->objectClass(), Operator::$equals, $this->schema->objectClassDepartment()],
      ]);
  }
}
```

```
>>> $ad->search()->departments()->getUnescapedQuery()
=> "(objectClass=spDepartment)"
>>> $ad->search()->departments()->first()
PHP Warning:  ldap_search(): Partial search results returned: Sizelimit exceeded in /var/www/laravel/internal.domain/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 255
=> Adldap\Models\Entry {#2982
     +exists: true,
     +dateFormat: "Y-m-d H:i:s",
   }
```

**Comment by stevebauman** [comment]
Hi @danswiser,

You're almost there. You'll need to:

1. Create your own schema and extend the current `OpenLDAP` schema
2. Create your own `Department` model and extend from the `Adldap\Models\Entry` class
3. Override the `objectClassModelMap()` and add your new model to it
4. Use your new custom schema in your configuration array

```php
namespace App\LdapModels;

use Adldap\Models\Entry;

class Department extends Entry
{
    //
}
```

```php
namespace App\LdapSchemas;

use App\LdapModels\Department;
use Adldap\Schemas\OpenLDAP;

class MySchema extends OpenLDAP
{
    public function objectClassModelMap()
    {
        $map = parent::objectClassModelMap();

        $map[$this->objectClassDepartment()] = Department::class;

        return $map;
    }
}
```

```php
$config = [
    'hosts' => ['...'],
    'schema' => \App\LdapSchemas\MySchema::class,
    'username' => '...',
    'password' => '...',
    'base_dn' => '...',
];
```

https://github.com/Adldap2/Adldap2/blob/master/src/Schemas/Schema.php#L670-L681

Let me know if you still encounter issues and I'll re-open this ticket.

**Comment by yakatz** [comment]
@stevebauman Is there a similar procedure to create new objects with the custom Model? The documentation talks about calling `$provider->make()->objectName([attributes])`, but it seems like you need to override an awful lot to make it work.

**Comment by stevebauman** [comment]
Hi @yakatz, you just need to return a different model from your own custom Schema:

https://github.com/Adldap2/Adldap2/blob/fd31c24623cd2d92640b664bd7435382864d3bd6/src/Models/Factory.php#L81-L92

```php
use App\MyUserModel;
use Adldap\Schemas\Schema;

class MySchema extends Schema
{
    public function userModel()
    {
        return MyUserModel::class;
    }
}
```

**Comment by danswiser** [comment]
@stevebauman,

I'm back working on this again for a few hours. It doesn't seem to me like `objectClassModelMap()` is getting called. At least every result is being returned as an `Adldap\Models\Entry` model.

I set the Schema in the config and also extended the AdldapProvider to use my own search factory and override `search()->users()` and `search()->departments()`
```
$config = [
          'hosts'            => [env('LDAP_HOST')],
          'base_dn'          => env('LDAP_DN'),
          'username'         => env('LDAP_USER'),
          'password'         => env('LDAP_PASS'),

          // Optional Configuration Options
          'schema'           => Schema::class,
          'port'             => 389,
          'follow_referrals' => false,
          'use_ssl'          => false,
          'use_tls'          => false,
          'version'          => 3,
          'timeout'          => 30,

          // Custom LDAP Options
          'custom_options'        => [
            // See: http://php.net/ldap_set_option
          ]
$ldap = new Provider($config);
$ldap->connect();
```

```
namespace App\Services\LDAP;

use Adldap\Connections\Provider as AdldapProvider;
class Provider extends AdldapProvider
{
    public function search()
    {
        return new SearchFactory(
            $this->connection,
            $this->schema,
            $this->configuration->get('base_dn')
        );
    }
}
```

While trying to figure out why everything is being returned as `Adldap\Models\Entry`, I left only one option in the model map.
```
namespace App\Services\LDAP;

use App\Services\LDAP\User;
use Adldap\Schemas\OpenLDAP;
class Schema extends OpenLDAP
{
...
  /**
   * {@inheritdoc}
   */
  public function objectClassPerson()
  {
      return 'spPerson';
  }

...

  public function objectClassModelMap()
  {
    return [
        $this->objectClassPerson() => User::class,
    ];
  }
}
```

```
namespace App\Services\LDAP;

use Adldap\Models\Entry as Model;
class User extends Model
{
    public function getAnything()
    {
        return 'ANYTHING';
    }
}
```
Still get the `Entry` Model and nothing else.

```
>>> $ldap->search()->users()->getUnescapedQuery()
=> "(&(objectClass=spPerson)(employeeType=employee)(departmentnumber=*)(mail=*))"
>>> $user = $ldap->search()->users()->first()
PHP Warning:  ldap_search(): Partial search results returned: Sizelimit exceeded in /var/www/laravel/internal.domain/vendor/adldap2/adldap2/src/Connections/Ldap.php on line 255
=> Adldap\Models\Entry {#3185
     +exists: true,
     +dateFormat: "Y-m-d H:i:s",
   }
>>> $user->getAnything()
PHP Error:  Call to undefined method Adldap/Models/Entry::getAnything() in /var/www/laravel/quality.1and1.comeval()'d code on line 1
```

Where should I start from here?

**Comment by stevebauman** [comment]
Hi @danswiser,

Hmmm, strange...

This method here is where the instantiation happens for all models:

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Processor.php#L109-L139

Have you perhaps modified the `objectClass()` method on your extended schema?

https://github.com/Adldap2/Adldap2/blob/master/src/Query/Processor.php#L111

**Comment by danswiser** [comment]
@stevebauman,

I know it's been a long while since this came up. You're comment about the objectClass pointed me to the issue. The dev server used "objectClass" so I overrode the objectClass() method and the prod server used"objectclass".

**Comment by stevebauman** [comment]
Great, thanks for following up @danswiser! Appreciate it :smile:
