### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to Adldap\Models\Factory::__construct()

### ISSUE THREAD

**Issue by stedaniels** [Adldap2/Adldap2#571]
- Adldap2 Version: 9.0.0
- LDAP Type: Active Directory
- PHP Version: 7.1

### Description:
Fatal error</b>: Uncaught TypeError: Argument 1 passed to Adldap\Models\Factory::__construct() must be an instance of Adldap\Query\Builder, string given, called in vendor/adldap2/adldap2/src/Connections/Provider.php on line 194 and defined in vendor/adldap2/adldap2/src/Models/Factory.php:33

Attempting to create a user in AD.

### Steps To Reproduce:

	$config = [
		'hosts'    => $ad_domain_controllers,
		'base_dn'  => $ad_base_dn,
		'username' => $ad_username,
		'password' => $ad_password,

		'schema'           => \Adldap\Schemas\ActiveDirectory::class,
		'use_tls'          => true,
	];

	$ad->addProvider($config);

	try {
		$provider = $ad->connect();
	} catch (\Adldap\Auth\BindException $e) {
		error_log( var_export( $e, true ) );
		return false;
	}

	$user = $provider->make()->user( [ 'cn' => 'Daisy Duck' ] );

Produces:

Fatal error</b>: Uncaught TypeError: Argument 1 passed to Adldap\Models\Factory::__construct() must be an instance of Adldap\Query\Builder, string given, called in vendor/adldap2/adldap2/src/Connections/Provider.php on line 194 and defined in vendor/adldap2/adldap2/src/Models/Factory.php:33

$provider->make() calls getQuery:

    /**
     * {@inheritdoc}
     */
    public function make()
    {
        return new ModelFactory(
            $this->search()->getQuery()
        );
    }

It looks like getQuery was removed from Factory.php https://github.com/Adldap2/Adldap2/commit/3f9db94fc87bb36058b691ea0b1c03787190fc92#diff-c3807e36d2faab4d0f7e6d9ed38d8ede

Changing make() to use newQuery() seems to work.

    /**
     * {@inheritdoc}
     */
    public function make()
    {
        return new ModelFactory(
            $this->search()->newQuery()
        );
    }

But I have no idea if that is proper.  Restoring the getQuery function doesn't work because setQuery doesn't exist or get called, etc. etc.

**Comment by stevebauman** [comment]
Damn what a blunder on my part. I'll create some tests for this (though I had this covered), but I've patched it and putting out a release for `v9.0.1`.

Thanks a ton @stedaniels!

**Comment by stedaniels** [comment]
Thank you @stevebauman for adldap2 and the super fast turnaround!
