### ISSUE TITLE
The search is not returning any data

### ISSUE THREAD

**Issue by insinfo** [Adldap2/Adldap2#572]
- Adldap2 Version: 5.2
- LDAP Type: Active Directory
- PHP Version: 7.2.4

### Description:

The search is not returning any data
I can return the data with the "finder", but with "where get" brings nothing

**it works**
`$this->adldap->search()->newQueryBuilder()->find($value);`

**It does not work**

`$this->adldap->search()->newQueryBuilder()->where('cn', 'contains', 'Isaque Neves')->get();`

### Steps To Reproduce:

```
    $config = [           
            'domain_controllers' => [$this->domainControllerHost],//Domain Controllers
            'base_dn' => $this->baseDistinguishedName,//Base Distinguished Name
            'admin_username' => $this->domainAdminUsername,
            'admin_password' => $this->domainAdminPassword,
            'use_tls' => true      
        ];     
        $this->adldap = new Adldap($config);
       $this->adldap->search()->newQueryBuilder()->where('cn', 'contains', 'Isaque Neves')->get();
```

**Comment by insinfo** [comment]
@stevebauman
I'm sorry it was really my mistake, thank you for responding so quickly.

**Comment by stevebauman** [comment]
Hi @insinfo, no problem! I'll close this issue then?

If you still encounter issues, let me know and I will re-open this.
