### ISSUE TITLE
Can't contact LDAP server

### ISSUE THREAD

**Issue by vilify** [Adldap2/Adldap2#573]
- Adldap2 Version: master
- LDAP Type: Active Directory
- PHP Version: 7.2

Description: 

Inserting without password works with TSL = false.

use_tls => true, default port.
is enabled on the AD server.

( ! ) Fatal error: Uncaught Adldap\Auth\BindException: Can't contact LDAP server in C:\wamp64\www\vendor\adldap2\adldap2\src\Auth\Guard.php on line 78
--
1 | 0.0005 | 406248 | {main}( ) | ...\new.php:0
2 | 0.0035 | 597832 | Adldap\Adldap->connect( ) | ...\new.php:27
3 | 0.0035 | 597832 | Adldap\Connections\Provider->connect( ) | ...\Adldap.php:128
4 | 0.0037 | 598912 | Adldap\Auth\Guard->bindAsAdministrator( ) | ...\Provider.php:229
5 | 0.0038 | 598912 | Adldap\Auth\Guard->bind( ) | ...\Guard.php:89

**Comment by stevebauman** [comment]
Hi @vilify,

The Adldap2 exception message isn't lying to you, it can't make a connection to your LDAP server using TLS.

This is likely a certificate issue. You'll either need to:

- Retrieve a copy of your certificate from your LDAP server and configure your PHP application server to use it
- Bypass certificate verification

You should actually see errors on your ActiveDirectory server when your application attempts to make a connection with TLS enabled.

Here's a StackOverflow issue describing this process:

https://stackoverflow.com/questions/2689629/how-do-i-solve-ldap-start-tls-unable-to-start-tls-connect-error-in-php

If you still have issues after troubleshooting, let me know and I'll re-open this.

Thanks!
