### ISSUE TITLE
Error with paginate

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#574]
Hi @stevebauman ,

I encouter an error with serach and paginate. When I use

```php
$adldap->select([fields...]]->paginate(100, 1);
```
I recieve : 
```
Warning: ldap_escape() expects parameter 1 to be string, array given in \adldap2\adldap2\src\Utilities.php on line 42
```

Any idea ? I use the last release of Adldap

Thanks a log

**Comment by stevebauman** [comment]
Hi @ciadch,

What arguments are you passing to the select field? Only strings or an array or strings are allowed.

This is because the selected fields are escaped prior to the search being ran.

**Comment by ciadch** [comment]
Thanks four your return. I found the problem. It was effectively an error in my method. 

You can close :-) 

Thanks

**Comment by stevebauman** [comment]
Great thanks for the quick follow up!
