### ISSUE TITLE
DomainConfiguration

### ISSUE THREAD

**Issue by Jestre** [Adldap2/Adldap2#576]
- Adldap2 Version: 9.x (installed today)
- LDAP Type: Active Directory
- PHP Version: 7.2.7-0ubuntu0.18.04.2

### Description:

Following the docs, apparently fails to load the required features resulting in an error: 

    PHP Fatal error:  Uncaught Error: Class 'Aldldap\Configuration\DomainConfiguration' not found

Any Ideas?

### Steps To Reproduce:

$ mkdir test && cd test
$ composer require adldap2/adldap2  # creates composer.json, composer.lock and vendor/
$ vim test.php

`<?php

    require __DIR__ . '/vendor/autoload.php';

    // Setting options via first argument:
    $config = new \Aldldap\Configuration\DomainConfiguration([
        'hosts' => [
            '10.10.20.23',
            '10.5.13.15',
        ],
        'base_dn'   =>  'OU=Users,OU=Something,OU=Something Else,DC=Bobs,DC=co',
        'username'  =>  'authaccount',
        'password'  =>  'super s3kr3t',
        'account_suffix'    =>  '@bobs.co',
    ]);

    $ad = new Adldap();
    $ad->addProvider($config);
    $connectionName = 'test1';
    
    try {
        $provider = $ad->connect($connectionName);

        // Great, we're connected!
        echo 'Woohoo! That stuff worked!';
    } catch (\Adldap\Connections\BindException $e) {
        // Failed to connect.
        echo 'Nope, stuff broke';
    }
`
$ php test.php
PHP Fatal error:  Uncaught Error: Class 'Aldldap\Configuration\DomainConfiguration' not found in /home/bob/test/test.php:6
Stack trace:
#0 {main}
  thrown in /home/bob/test/test.php on line 6

**Comment by stevebauman** [comment]
You have a typo - unless I have that in the docs as well.

Aldldap\Configuration\DomainConfiguration

Should be

Adldap\Configuration\DomainConfiguration

**Comment by Jestre** [comment]
Oh jeez, hate I missed that.  But yes, that was copied directly from the docs.

Thank you for the response!

**Comment by Jestre** [comment]
That seems to have fixed it, although it appears the `$ad = new Adldap();` in the DomainConfig section should be `$ad = new \Adldap\Adldap();`

Thanks for the quick response!

**Comment by stevebauman** [comment]
Shoot! Lol okay I’ll fix that!

Thanks for letting me know! :smile: 

And no problem, if you encounter anything else just create and issue.
