### ISSUE TITLE
invalid credentials in bind after migrating to new version

### ISSUE THREAD

**Issue by MichalKrakow** [Adldap2/Adldap2#577]
- Adldap2 Version: 8.1.5
- LDAP Type: Active Directory
- PHP Version: 7.1.21

After migrating from php 5.6 to 7.1 and updating application on windows server 2012 we 
reused the config data as _prefixes, adldap_controllers, dldap_port, adldap_basedn, admin_username, admin_password,_ added prefixes to new _admin_account_prefixes_ configuration parameter.

Of course the data were inserted to new config templates in their respective places.

On the same server with the same credentials with old version of Adldap2 everything worked perfectly.
After migration i get **'invalid credentials'** from:
```
public function bind($username, $password, $prefix = null, $suffix = null)
{
        // We'll allow binding with a null username and password
        // if they're empty. This will allow us to anonymously
        // bind to our servers if needed.
        $username = $username ?: null;
        $password = $password ?: null;

        if ($username) {
            $username = $this->applyPrefixAndSuffix($username, $prefix, $suffix);
        }

        // We'll mute any exceptions / warnings here. All we need to know
        // is if binding failed and we'll throw our own exception.
        if (!@$this->connection->bind($username, $password)) {
            throw new BindException($this->connection->getLastError(), $this->connection->errNo());
        }
}
``` 
When i dd the username and password i get exacly the same values wchich work on the old server.

Is this could be some php ldap extension issue or there is something to change omited in docs?
How to pinpoint the issue?

Any help greatly appreciated.

**Comment by MichalKrakow** [comment]
so pinning it down:

```
$ldap_host = "ldap://corp.com";

$ldapconn = ldap_connect($ldap_host) or die("Could not connect to LDAP Server");

ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);
ldap_set_option($ldapconn, LDAP_OPT_REFERRALS, 0);


$ldappass = "xxx";
$username = 'xxx';

if ($ldapconn) {
	$ldapbind = username($ldapconn, $username, $ldappass);

	if ($ldapbind){
		echo "LDAP bind successful…";
	} else {
		echo "LDAP bind failed…";
	}
}
```
this **works** on php 5.6 - IIS windows server 2012 and **fails** on same server with php 7.1.21.
The bind function return 'invalid credentials'.
I've tried adding domain and doubleslash to it - with no results..

**Comment by MichalKrakow** [comment]
Ok this is getting wierder,

configuration is fine - i've managed to authenticate user, and then after few page refreshes i get 'invalid credentials'.

Anyone has idea what can cause this? How to track it to the source of the problem.

**Comment by wranger** [comment]
Could you switch between the PHP versions 7.0 /7.1 /7.2 and repeat your tests?

**Comment by MichalKrakow** [comment]
Yes, we have tested
5.6 - works
7.1 - invalid credentials
7.2 - invalid credentials. 

With 7.1 sometimes we got response from ldap server and it was working ok for few sessions and then it looks like server does not allow for user to bind anymore. We can’t access ldap server logs and debug messages only show ‘invalid credentials’. 

It must have something to do with the way sessions or connections are created/ destroyed in new version of php’s ldap controller.

**Comment by stevebauman** [comment]
This seems related to your server and not Adldap2. I've been using 5.6, 7.0, 7.1, 7.2 and 7.3 with Windows Server 2012 and Adldap2 and haven't had any issues.

Closing this, but if you encounter any Adldap2 related issues, please let me know, thanks!
