### ISSUE TITLE
Model setPassword error

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#58]
When I try to set a new password to my user, I have an error : 

```
Fatal error: Call to undefined method Adldap\Models\User::getAdldap() in Adldap\Models\User.php on line 583
```

Thanks

**Comment by stevebauman** [comment]
Fixed: https://github.com/Adldap2/Adldap2/commit/e6af03c2707d81ffb7c9b63c1d91cbfebc55756c

**Comment by ciadch** [comment]
Ok it seems to be working but I have an array as return in place of a boolean, can you correct that ?

Thanks

**Comment by stevebauman** [comment]
You may need to call `$user->changePassword()`, `setPassword()` is for creating new users with no password.

**Comment by ciadch** [comment]
Ok but is there a way to change current user password without knowing old password ? This functionality could be really, really useful
