### ISSUE TITLE
Warnings show after upgrade to 9.0.2

### ISSUE THREAD

**Issue by szaqal83** [Adldap2/Adldap2#581]
- Adldap2 Version: 9.0.2
- LDAP Type: Active Directory
- PHP Version: 7.2.9

Two warnings show after upgrade to version 9.0.2 (from 9.0.1):

```
Warning: Class 'Tightenco\Collect\Support\Debug\Dumper' not found in /var/www/html/test/ad/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18

Warning: Class 'Tightenco\Collect\Support\Debug\HtmlDumper' not found in /var/www/html/test/ad/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18
```

Steps To Reproduce:

upgrade to 9.0.2

**Comment by stevebauman** [comment]
Are you calling `dd()` anywhere in your application?

**Comment by szaqal83** [comment]
No

**Comment by stevebauman** [comment]
Do these warnings appear globally? Or do they show up when calling certain methods?

I need more information.

**Comment by szaqal83** [comment]
They appear right after requiring autoload.php

**Comment by szaqal83** [comment]
Something werid just happened I've hit composer update one more time and 1 package has been added (symfony/polyfill-php72), and 2 packages have been updated (symfony/var-dumper, tightenco/collect), warnings are gone now :)
