### ISSUE TITLE
Any mistakes in the documentation or did I do something wrong?

### ISSUE THREAD

**Issue by K-Hoffmann** [Adldap2/Adldap2#588]
Hi,

- Adldap2 Version: v9.1.0 (via composer)
- LDAP Type: OpenLDAP 2.4.45 (via apt-get)
- PHP Version: PHP 7.2.10 (via apt-get)
- OS: Ubuntu 18.04

I followed the documentation and created the following example:

```
<?php
require_once(__DIR__.'/vendor/autoload.php');

$connection = new \Adldap\Adldap();

$config = parse_ini_file('config.ini');
$options = [
  'hosts'    => ['127.0.0.1'],
  'base_dn'  => $config['base_dn'],
  'username' => $config['username'],
  'password' => $config['password'],
  'schema'   => Adldap\Schemas\OpenLDAP::class,
];

$connection->addProvider($options);
$provider = $connection->connect();

$search = $provider->search();

$result1 = $provider->search()->where('cn', '=', 'John Doe')->get();
$result2 = $search()->all();
$result3 = $search->find('John Doe');

echo $result1;
echo $result2;
echo $result3;
```

$result1 returns the expected result:

```
[{"cn":["John Doe"],"0":"cn","displayname":["John Doe"],"1":"displayname","mail":["john.doe@company.com"],"2":"mail","givenname":["John"],"3":"givenname","objectclass":["inetOrgPerson","top"],"4":"objectclass","sn":["Doe"],"5":"sn","dn":["cn=John Doe,ou=example.com,ou=users,dc=lane4,dc=digital"],"entryuuid":null,"objectsid":null}]N
```

$result2 surprises me because I would have expected all entries in the LDAP tree as result set.

```
PHP Fatal error:  Uncaught Error: Function name must be a string in /opt/user-manager/ldap_test.php:21
Stack trace:
#0 {main}
  thrown in /opt/user-manager/ldap_test.php on line 21
```

With `$result2 = $provider->search()->all();`:

```
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\Query\Processor' does not have a method 'all' in /opt/user-manager/vendor/adldap2/adldap2/src/Query/Builder.php on line 1430
```

Similarly, result3 does not return the expected result:

```
bool(false)
```

Can you give me a hint what i'm doing wrong? Help is appcreciated.

Thanks in advance.

**Comment by stevebauman** [comment]
Hi @K-Hoffmann,

For your second result, you're using incorrect syntax as you're calling the $search variable as a closure (function):

```php
$result2 = $search()->all();

// Should be:
$result2 = $search->get();
```

Also, there is a definitely a mistake in documentation, which is my fault. The `all()` method was removed from the search factory as it gave the wrong impression that all records would be returned, but this isn't the case as there's a hard limit of 1000 on the majority of LDAP distros.

For your third result, it wasn't able to locate any record named `John Doe` in your OpenLDAP server. Do you have someone with the common name (`CN`) of John Doe? I would try some other usernames and see if you're able to locate any.

Try the above and let me know how it goes!

**Comment by stevebauman** [comment]
Sorry I'm blind, I looked at your result set you posted and you do have a user named John Doe in your directory.

I don't believe OpenLDAP supports ambiguous naming resolution, so you'll likely have to locate users by a different attribute (their distinguished name or mail etc).

```php
$user = $provider->search()->findBy('mail', 'john.doe@company.com');
```

**Comment by stevebauman** [comment]
Actually though, this is a bug. The `find()` should be usable on other LDAP distro's, so I'm going to make the method compatible.

**Comment by K-Hoffmann** [comment]
Hi Steve,

thanks for your answers. 

First: `$result2 = $search->get()` now returns the expected result:

```
object(Tightenco\Collect\Support\Collection)#26 (1) {
  ["items":protected]=>
  array(6) {
    [0]=>
    object(Adldap\Models\Entry)#12 (8) {
      ["exists"]=>
      bool(true)
      ["query":protected]=>
      object(Adldap\Query\Builder)#13 (14) {
...
        string(2) "cn"
        ["displayname"]=>
        array(1) {
          [0]=>
          string(8) "John Doe"
        }
        [1]=>
        string(11) "displayname"
        ["mail"]=>
        array(1) {
          [0]=>
          string(20) "john.doe@company.com"
...
}
```

`$user = $provider->search()->findBy('mail', 'john.doe@company.com');`  returns an error:

```
PHP Recoverable fatal error:  Object of class Adldap\Models\User could not be converted to string in /opt/user-manager/ldap_test.php on line 41
```
The same is true for `$user = $provider->search()->findByDn('cn=John Doe,ou=example.com,ou=users,dc=lane4,dc=digital');`

Regards

Karsten

**Comment by stevebauman** [comment]
Hi @K-Hoffmann,

For your second issue, it sounds like you're `echo`'ing the returned user object, which would result in this error:

```php
$user = $provider->search()->findBy('mail', 'john.doe@company.com');

// You can't do this:
echo $user;

// You can however dump via:
var_dump($user);
```

**Comment by Albvadi** [comment]
Hi @stevebauman 
maybe it would be nice to add `$this->schema->userId()` in the custom anr equivalent query https://github.com/Adldap2/Adldap2/blob/5ba0e2793f7e56d79d54a63f522bc63e03c6441a/src/Query/Builder.php#L477-L511
This method it´s the method to return users in OpenLDAP through the username.

Thanks!!

**Comment by stevebauman** [comment]
Great suggestion @Albvadi! Adding this now. :)
