### ISSUE TITLE
Minor error in the DocBlocks

### ISSUE THREAD

**Issue by tontonsb** [Adldap2/Adldap2#589]
In the `Adldap\Query\Factory` the same description `Returns a query builder limited to exchange servers.` is provided for three methods: `containers()`, `contacts()` and `computers()`.

I am only a beginner in LDAP so I don't know what would be a proper description but I suspect that this description might only be appropriate for the `contacts()` method.

**Comment by stevebauman** [comment]
Thanks @tontonsb! Can't believe I didn't notice this 😅
