### ISSUE TITLE
Disable / enable account doesn't work

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#59]
Nothing appends when I try to disable or enable an account. Here is an exemple

```php 
$user = $this->search()->find('test');
$user->disable();
// I try this : 
$user->disable()->save(); // Returns false
```
Same behavious for some other methods, maybe in dev actually :-)

Thanks

**Comment by stevebauman** [comment]
I think you may have to use user account control to enable / disable users. I'll check this out.

**Comment by ciadch** [comment]
I try to use user account control yesterday but it seems that it doesn't work too :-(. My code was 
```php
$user-> = $this->users()->newInstance();
$user->setFirstName('John');
$user->setLastName('Doe');
$user->setUserAccountControl('512');
$user->setAccountName('johndoe');
$user->setPassword('12341234');
var_dump($user->save()); // Return false
```

Thanks

**Comment by stevebauman** [comment]
Try setting the user account control on a currently existing user instead of a new one. It could be a combination of things here. Let me know if that works!

**Comment by ciadch** [comment]
Ok it works with an active user ! But we need a method to active a new user account when we create it. It could be better than creating account then finding new account and enabling it.

Thanks

**Comment by stevebauman** [comment]
Removed `enable()` and `disable()` User model methods: https://github.com/Adldap2/Adldap2/commit/9421aad1a6859fe12c26b9b54151dfee0af437a0

This change will be found in `v5.2.0` coming shortly. Are you connected to your AD server via SSL? You'll need to be to be able to set a password and have the user account enabled upon creation.
