### ISSUE TITLE
Search not returning all attributes on users

### ISSUE THREAD

**Issue by kingkom001** [Adldap2/Adldap2#595]
Hi guys, It seems like the adldap search does not return attributes that has no values. I am working on a project and would like to also return fields with no values.. How can i do that

I used $userInfo = Adldap::search()->select($filters)->where('cn', '=', $user)->get();
I included these fields in the filters, but they are not being returned. Any assistance would be great!!
Thanks..

**Comment by stevebauman** [comment]
Hi @kingkom001,

This wouldn't be Adldap2 not returning empty values. The user records you're querying for must not contain the selected fields your looking for.

What are the selected fields you're querying for in the query you've posted?

**Comment by stevebauman** [comment]
Also, you've named the variable `$filters`, and I'm not sure what this variable contains, but you only insert the fields your looking to retrieve in the `select()` method, not LDAP filters.

**Comment by kingkom001** [comment]
Thanks for the quick response.
Anyways, $filters has the fields I am looking for i did the same query without any filters and it still wouldnt return these fields, I tested it with multiple users and in each case, it will not return any field who's value is null. I am looking for a total of 80 fields and in each case it returned between 40 and 50 fields depending on whether or not these fields have values. I am using laravel-Adldap...
I do  Adldap::search()->where('cn', '=', $user)->get();, the same thing happens. So i am asking if there is any parameters or extra function i need to add so that it would return both empty fields and non empty fields alike?

**Comment by kingkom001** [comment]
it is an  OpenLDAP Server, I have tried raw LDAP commands as well.

**Comment by stevebauman** [comment]
I would try raw LDAP commands to see what attributes are being returned by your LDAP query.

You can use the `raw()` method when creating a query to do this so it returns all raw data from your LDAP server.

Run the following:

```php
$rawUsers = Adldap::search()->->where('cn', '=', $user)->raw()->ge();
```

It's highly likely that your OpenLDAP server is just *not* returning `null` or empty attributes from an LDAP search.

For example, here's how LDAP results are processed:

https://github.com/Adldap2/Adldap2/blob/8fc0760b01f39f3bc932a6d215693b9d3a98ffa1/src/Query/Processor.php#L49-L78

When models are constructed with LDAP results using the `setRawAttributes()` method, only the `count` attributes are filtered out so they are not included in model attributes:

https://github.com/Adldap2/Adldap2/blob/8fc0760b01f39f3bc932a6d215693b9d3a98ffa1/src/Models/Concerns/HasAttributes.php#L220-L239

**Comment by kingkom001** [comment]
Thanks Steve.. Figured it out. Everything works just fine..

**Comment by stevebauman** [comment]
Great glad you resolved it! Do you know what the issues was in case some one else runs into this? Would be greatly appreciated!

**Comment by kingkom001** [comment]
There was really no issues. it does exactly what you said. I was converting a php5 code to laravel code. I just discovered they were pilling up a few more attributes from a different call into an array therefore creating an illusion of empty attributes getting retrieved from the LDAP call..
