### ISSUE TITLE
Error when trying to remove group from member

### ISSUE THREAD

**Issue by sythaera** [Adldap2/Adldap2#596]
- Adldap2 Version: Latest
- LDAP Type: Active Directory
- PHP Version: 7.0.30

I get error: Warning: ldap_modify_batch(): Batch Modify: Server is unwilling to perform when trying to remove one user with the following: `for ($i=0; $i < $count; $i++) { 

$group = $provider->search()->groups()->where("samaccountname","=",$array[$i])->first();
$members = $group->getMembers();
$members1 = json_encode($members);
$members2 = json_decode($members1, true);
$count1 = count($members2);

for ($e=0; $e < $count1; $e++) { 
$samname1 = implode(", ",$members2[$e]['samaccountname']);
	if($samname1 == $_POST['samid']){
		if($group->removeMember($samname1)){
			echo 'Removed from group'.$array[$i];
		}
	}
}

}

}`

I do not know why this is happening. I am using a Domain Admin account to do this,

**Comment by stevebauman** [comment]
Hi @sythaera,

You cannot pass a sAmAccountName into the `removeMember()` method. It must either be either a model instance or a users distinguishedName.

**Comment by sythaera** [comment]
That's awesome.
Thank you alot for the quick support.

**Comment by stevebauman** [comment]
No problem! Closing this for now but if you encounter any issues just comment back and I will re open :).
