### ISSUE TITLE
question on search results

### ISSUE THREAD

**Issue by heper** [Adldap2/Adldap2#598]
code below gets me a list of users. 
unfortunately it also returns 'security groups' that match the search pattern. what would be the easiest way to prevent that from happening? 

`$results = $search->where('cn', 'starts_with', htmlspecialchars($_POST['username']))->setDn($searchOU)->get();
`

sorry for the stupid question

**Comment by stevebauman** [comment]
Hi @heper,

If you create another issue in the future, please fill in the information requested in the issue template (such as PHP version, Adldap2 version etc.). I will be enforcing this in the coming days as a requirement for creating issues.

You can use [scopes](https://adldap2.github.io/Adldap2/#/searching?id=scopes) to do this, or you can simply add more `where()` conditionals to look specifically for user objects:

```php
$users = $search()
    ->users()
    ->where('cn', 'starts_with', htmlspecialchars($_POST['username']))
    ->setDn($searchOU)
    ->get();
```

Some more predefined scopes:

```php
// Retrieve all printers.
$results = $search->printers()->get();

// Retrieve all organizational units.
$results = $search->ous()->get();

// Retrieve all groups.
$results = $search->groups()->get();

// Retrieve all containers.
$results = $search->containers()->get();

// Retrieve all contacts.
$results = $search->contacts()->get();

// Retrieve all computers.
$results = $search->computers()->get();
```
