### ISSUE TITLE
[GROUPS] Cannot modify attribute

### ISSUE THREAD

**Issue by brutax34** [Adldap2/Adldap2#604]
- Adldap2 Version: 9.1
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:
Hi !

I have an issue while attempting to create a group : 

> ldap_add(): Add: Invalid syntax

It works with a custom attribute, but not with the pre-existing one.

In the example above, the last command fails. If I remove it, it works.

### Steps To Reproduce:
````
$new_grp=$provider->make()->group();
$new_grp->setCommonName($_POST['name']);
$new_grp->setDescription("Created by ".$_SESSION['displayname']);
$new_grp->setDn('CN='.$_POST['name'].',OU=GERES,'.$ou);
$new_grp->isMoodle = 'TRUE'; //OK
$new_grp->setAttribute('adminDescription',$_POST['description']); //not OK
````

I also tried : 
`
$new_grp->adminDescription = $_POST['description']);
`
It fails too.

Also tried without caps. It fails.

Any help ?

Thanks ! 👍

**Comment by stevebauman** [comment]
Hi @brutax34,

Are you sure its the `adminDescription` attribute that's causing this?

I've seen this error usually due to the DN of the entry not being set properly.

If you're sure it's the `adminDescription` attribute, can you try:

> **Note**: Notice the `subKey` attribute added here.

```php
$new_grp->setAttribute('adminDescription', $_POST['description'], $subKey = 0);
```

**Comment by brutax34** [comment]
Hi @stevebauman
Thanks for your answer.

Yes, I'm sure. If I remove that line, it works fine.

I'll try your advice on tomorrow, it's 8pm here :-)

Regards.

**Comment by brutax34** [comment]
Hi !
It didn't work but I finally found the solution. My **$_POST['description']** was an empty value, it now works fine on these ways : 
`$new_grp->adminDescription = $_POST['description'];`
AND
`$new_grp->setAttribute('adminDescription', $_POST['description']);`

I just add a default value to my var if $_POST['description'] is empty.

Regards.

**Comment by stevebauman** [comment]
Awesome thanks for following up @brutax34! Glad you've resolved it :)
