### ISSUE TITLE
[Question] Validation of Active Directory Distinguished Name

### ISSUE THREAD

**Issue by stuntguy3000** [Adldap2/Adldap2#605]
Hey 👋 

Just wondering - is it possible to validate if a provided DN is valid and exists?

Cheers

**Comment by stevebauman** [comment]
Hi @stuntguy3000,

You can try to finding a record in your LDAP server with a given DN by using the `findByDn()` method in the query builder:

```php
$dn = 'cn=John Doe,dc=acme,dc=org';

if ($record = $provider->search()->findByDn($dn)) {
    // Record exists!
}
```

If you're looking to see if a given DN exists, you can use PHP's raw `ldap_expode_dn()` which returns `false` if you pass it an invalid distinguished name:

```php
$dn = 'invalid';

if ($valid = ldap_explode_dn($dn, $withAttributes = false)) {
    // We won't reach this point, the above DN is invalid.
} else {
    // Invalid DN.
}
```

If you need any more help just give me a shout :smile:
