### ISSUE TITLE
Fatal error on $user->ingroup('group name')

### ISSUE THREAD

**Issue by jal617b** [Adldap2/Adldap2#61]
Hi. I am using this with CI 3 and so far I was able to authenticate users as well as retrieve user info. However, when I tried to use the *inGroup* function, I get the following error:

`Fatal error: Call to undefined method Adldap\Models\User::getAdldap() in C:\xampp\htdocs\dev\a\aaa\application\vendor\adldap2\adldap2\src\Models\Traits\HasMemberOfTrait.php on line 43`

I have tried the other suggestion on issue#36 but I got the same error.

**Comment by stevebauman** [comment]
Hi, please update to `v5.1.4`. This was just released and it solves these issues. If you still encounter problems, please don't hesitate to create another issue, thanks!
