### ISSUE TITLE
auth()->attempt() is generating php warning

### ISSUE THREAD

**Issue by longshadowdev** [Adldap2/Adldap2#613]
- Adldap2 Version: 9.1
- LDAP Type: Active Directory
- PHP Version: 7.2

### Description:
Attempts to run auth()->attempt($username, $password) are throwing the following warning:
ldap_bind(): Unable to bind to server: Invalid credentials

If you are using Adldap2 as a way to authenticate end users, it is expected that they will from time to time input the wrong password. Therefore I don't think a warning is appropriate. It just clogs up log files. I understand there's no easy answer because of the underlying ldap_bind call generating the error. However I don't think it would be best to suppress the warning with @ in this case.

**Comment by stevebauman** [comment]
Hi @longshadowdev,

This error (not warning) is thrown by PHP itself, not Adldap2. The error is suppressed so a custom exception can be generated from it. Have you changed your PHP's `error_reporting()`?

**Comment by stevebauman** [comment]
Actually, with PHP 7.0 being required now, we can use [Throwable](http://php.net/manual/en/class.throwable.php). I'm going to change this. Thanks!

**Comment by longshadowdev** [comment]
Thanks Steve, yes I have implemented my own handler using error_reporting.
