### ISSUE TITLE
changePassword() keep old password ?

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#615]
Hi @stevebauman,

I encounter a strange behaviour with changePassword() method. For me, it works perfetly but when my user changed his password, he can use the old one until a while (my opinion, this behaviour is based on AD DC replication).
But, how is it possible if I set only one host in the config ? 

Any idea ?

Thanks for your return.

**Comment by ciadch** [comment]
Another point I found is how can I user the current user credentials when change password is set inside AD account. Effectively, auth() returns false and getConnection()->getExtendedError() return the correct data of password need to be change. I think its not possible to do it with current user. I need to user another account witch have admin rights to change password. Do you confirm ?

**Comment by ciadch** [comment]
Hi @stevebauman,

Thanks for your complete response. It's exactely the behaviours I suspected. 

So I will investigate in my own infra to debug the replication. But to be sure, how can I discconect corretly my ldap connexion with ADldap ? I try multiple close() but I don't find the correct one

Thanks

**Comment by stevebauman** [comment]
No problem! If you'd like to disconnect early, you can call the `Provider::getConnection()->close()` method.

Though just for reference, when the `Provider` instance is no longer used, `__destruct()` will be called automatically and it will close the connection for you:

https://github.com/Adldap2/Adldap2/blob/e7376c1aaed0bcfb6e41558a816ffe1c9ff0b82a/src/Connections/Provider.php#L62-L75

Here's an example:

```php
$provider->getConnection()->close();
```

**Comment by ciadch** [comment]
Awesome ! Thanks a lot

**Comment by stevebauman** [comment]
No problem! :smile:
