### ISSUE TITLE
receive group members in an ordered list

### ISSUE THREAD

**Issue by eisbehr-** [Adldap2/Adldap2#616]
- Adldap2 Version: latest
- LDAP Type: ad
- PHP Version: 7x

### Description:
I would like to receive the members of a group ordered by a field. Lets say `samaccountname`. I saw that when i call `getMembers`, i will receive a `\Tightenco\Collect\Support\Collection` instance. There is a `sortBy` function on this collection too, but maybe i did it wrong, ot a sort isn't working as expected. Is there any way to do this?

### Steps To Reproduce:
```PHP
$group = $this->provider->search()->groups()->find('group_name');
$users = $group->getMembers()->sortBy('samaccountname');
```

**Comment by eisbehr-** [comment]
Okay, i found a solution by using an own callback. But i think there might be a shorter way to do this.

```PHP
$users = $group->getMembers()->sortBy(function($user) {
    return $user->getAccountName();
});
```

**Comment by stevebauman** [comment]
Hi @eisbehr-, this was brought up on the Adldap2-Laravel here - https://github.com/Adldap2/Adldap2-Laravel/issues/591.

I'll label this as a bug, as it's definitely an issue and I need to see how this can be resolved without breaking models all together.
