### ISSUE TITLE
Does connection use displayName attribute?

### ISSUE THREAD

**Issue by gurkin33** [Adldap2/Adldap2#617]
- Adldap2 Version: ^9.1
- LDAP Type: Active Directory
- PHP Version: 7.2

Hello Everyone,

I have to users inside of my AD:
- **user1** ( samaccountname = user1, displayname = user1 );
- **user2** ( samaccountname = user2, displayname = John ).

Configuration:

```
$config = new \Adldap\Configuration\DomainConfiguration([
// Mandatory Configuration Options
'hosts'            => ['1.1.1.1'],
'base_dn'          => 'dc=win2008,dc=g33',
'username'         => USERNAME,
'password'         => PASSWORD,
// Optional Configuration Options
'schema'           => ActiveDirectory::class,
'port'             => 389,
'version'          => 3,
'timeout'          => 5,
]);
```
```
$ad = new Adldap();

$ad->addProvider($config);

try {
   $provider = $ad->connect();
} catch (\Adldap\Auth\BindException $e) {
   $e->getMessage();
}
```
In case when I use **user1** connection is ok.
but when I use  **user2** connection error -> _Invalid credentials_

If I change display name of **user2** to _user2_ OR use **Jonh** (displayname instead of samaccountname), connection is ok.

I don't know how to change that, I didn't find the same issue. Could you help me please?

Best Regards, Aleksey

**Comment by gurkin33** [comment]
Sorry. If I use **user2@win2008.g33** it is works. 
The issue close.

Best Regards, Aleksey

**Comment by stevebauman** [comment]
Thanks for the fast update, and I appreciate you closing out the issue. :smile:

**Comment by sharonco-matrix** [comment]
I have exactly the same issue and using with prefix also doesn't work any suggestions?

**Comment by gurkin33** [comment]
Hello,

Can you share more info? Configuration? Example of your using?

Adldap2 works perfectly in my project.

**Comment by sharonco-matrix** [comment]
$ad = new Adldap\Adldap();
    $config = array(
        'account_suffix'        => 'account_suffix',
        'hosts'    => ['domain_controllers'],
        'base_dn'               => 'base_dn',
        'username'        => $user,
        'password'        => $pass,
    );
    $ad->addProvider($config);
    try {
        **### _$prov = $ad->connect();_**
        $valid = $prov->auth()->attempt($user, $pass,true);
    } catch (Exception $e) {
        error_log($e->getMessage());
    }
  return $valid;

  $prov = $ad->connect(); commande goest to bind as administrator  and then it tries to bind with $user and $pass, but it doesnt add the prefix so it gives an exception:
bindasadminitrator calls the function bind and uses the $config->get('user') and its the user xxxx 
I hope its clear now.
THanks !

**Comment by gurkin33** [comment]
Hello,

I hope my configuration will help you understand:

```
    $username = $user . '@'. 'mydomain.local';
    $config = [
    	// Mandatory Configuration Options
    	'hosts'            => ['domain_controllers'],
    	'base_dn'          => 'dc=mydomain,dc=local',
    	'username'         => $username,
    	'password'         => $password,
    	// Optional Configuration Options
    	'schema'           => ActiveDirectory::class,
    	'port'             => 389,
    	'version'          => 3,
    	'timeout'          => 5,
    ];
```
