### ISSUE TITLE
Find users in two different OUs

### ISSUE THREAD

**Issue by jagDanJu** [Adldap2/Adldap2#618]
- Adldap2 Version: 9.1.3
- LDAP Type: Active Directory
- PHP Version: 7.2.12

### Description:

Hey Guys,

how can i find all users in two different OUs?

### Steps To Reproduce:

ou=02,ou=04,ou=Gruppe,dc=company

or 

ou=User,ou=Extern,ou=Gruppe,dc=company

**Comment by stevebauman** [comment]
Hi @jagDanJu,

You will have to perform two separate queries and combine the resulting collections, as you can't set two separate base DN's in an LDAP search, nor search via their OU's distinguished names:

```php
$users = $provider->search()->users()->in('ou=02,ou=04,ou=Gruppe,dc=company')->get();

$combined = $users->merge(
    $provider->search()->users()->in('ou=User,ou=Extern,ou=Gruppe,dc=company')->get()
);
```
