### ISSUE TITLE
How to process the results?

### ISSUE THREAD

**Issue by igittigitt** [Adldap2/Adldap2#619]
I wonder how to process and use the results of a find operation? Could not find any example for it.
For example, i search a specific useraccount and want to retrieve it's phone, etc.
Would be great to have more infos of how to use this lib... besides of the exiting docs.

**Comment by stevebauman** [comment]
Hi @igittigitt,

Did you browse the model documentation on the doc site?

https://adldap2.github.io/Adldap2/#/models/model?id=attributes

It explains how to retrieve model attributes from search results.

For your question:

```php
$user = $provider->search()->users()->find('jdoe');

// Using the getter:
$user->getTelephoneNumber();

// Using the `getFirstAttribute()` method:
$user->getFirstAttribute('telephonenumber');

// Using dynamic property:
$user->telephonenumber[0];
```
