### ISSUE TITLE
Error when using inGroup function

### ISSUE THREAD

**Issue by jal617b** [Adldap2/Adldap2#62]
Good day. I have updated to v5.1.4 as you mentioned in issue #61 but I still got an error. This time it's on an undefined function *search*
`Call to undefined method Adldap\Query\Builder::search() in C:\xampp\htdocs\dev\a\aaa\application\vendor\adldap2\adldap2\src\Models\Traits\HasMemberOfTrait.php on line 45`

My usage is like this:
`$adldap = new \Adldap\Adldap($config);`
`$user = $adldap->users()->find($username );`
`$ingroup= $user->inGroup('ADgroupname');`
`var_dump($ingroup); `

**Comment by stevebauman** [comment]
Yup you're right. Just fixed, will have a new release shortly!
