### ISSUE TITLE
How to delete an OU

### ISSUE THREAD

**Issue by kiqerdgz** [Adldap2/Adldap2#620]
Laravel Version: 5.2
PHP Version: 7.1
LDAP Type: Active Directory

Description:
I need to delete an OU but I can't find how to do this, can you help me?

Steps To Reproduce:
Delete the OU

**Comment by stevebauman** [comment]
Hi @kiqerdgz,

You first locate the OU, then delete it:

```php
$ou = $provider->search()->findByDn('ou=Accounting,dc=acme,dc=org');

if ($ou) {
    $ou->delete();
}
```

**Comment by stevebauman** [comment]
I'm working on more tutorials for the basics like this by the way. Will take a couple days but check back and I should have some up.

Thanks!

**Comment by kiqerdgz** [comment]
Thank you Steve, it works!
