### ISSUE TITLE
Cannot use setAccountExpiry

### ISSUE THREAD

**Issue by sythaera2** [Adldap2/Adldap2#621]
- Adldap2 Version: latest
- LDAP Type: AD
- PHP Version: 7.x

So I am trying to set the users expire date with the function setAccountExpiry
But in the AD, it does not change even tho I get a 1 from the function. 

This is my code:

```php
$user = $provider->search()->whereEquals('samaccountname', $_POST['samid'])->firstOrFail();

$date = strtotime($_POST['date']);

if($user->setAccountExpiry($date)){
    echo 1;
}
```

**Comment by stevebauman** [comment]
Hi @sythaera2,

When using `setter` methods, you need to call `save()` afterwards:

```php
$user = $provider->search()->whereEquals('samaccountname', $_POST['samid'])->firstOrFail();

$date = strtotime($_POST['date']);

$user->setAccountExpiry($date)->save();
```

Let me know if you encounter issues and I'll re-open this. Thanks!

**Comment by sythaera2** [comment]
I tried that  but that leaves me with the following:
Warning: ldap_modify_batch(): Batch Modify: Invalid syntax in

**Comment by stevebauman** [comment]
Ohh yes that's right, you will need to convert the time to Windows time using `Adldap\Utilities`:

```php
use Adldap\Utilities;

$user = $provider->search()->whereEquals('samaccountname', $_POST['samid'])->firstOrFail();

$time = strtotime($_POST['date']);

$date = Utilities::convertUnixTimeToWindowsTime($time);

$user->setAccountExpiry($date)->save();
```

Can you give that a shot and let me know?

**Comment by sythaera2** [comment]
I still can't get it to work.
Do you have any ideas at all?

**Comment by stevebauman** [comment]
Hi @sythaera2,

Is the account your connecting with using Adldap2 a domain administrator?

**Comment by sythaera2** [comment]
@stevebauman 
Yes, everything else works just fine.
It's just this. Can it be that the result is: 
float(1.16444772E+17)?

**Comment by stevebauman** [comment]
Hmmm... It's possible. Are you using 32 or 64-bit PHP?

**Comment by sythaera2** [comment]
Hi again.
You can close this now.
Apparently I was running a 32-bit PHP. :) 
Thanks for your help.

**Comment by stevebauman** [comment]
Thansk @sythaera2! This is a bug in Adldap2, still looking to resolve. The workaround like you mentioned is to use 64-bit PHP.

Related: #497
