### ISSUE TITLE
auth() method return warning

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#622]
Hi @stevebauman,

Since last version (9.1.4), I recieve this error when I auth() my user : 
``` php
Warning: ldap_bind(): Unable to bind to server: Invalid credentials in adldap2\adldap2\src\Connections\Ldap.php on line 285
```

Thanks for your helps

**Comment by stevebauman** [comment]
Hi @ciadch,

Sorry about this, the I set the release of `v.9.1.4` to target the `master` branch instead of the `v9.0` branch which contains breaking changes. Please try updating again with `composer update` and let me know if you still have issues.

Thanks!
