### ISSUE TITLE
How to delete a Security Group

### ISSUE THREAD

**Issue by kiqerdgz** [Adldap2/Adldap2#623]
Laravel Version: 5.2
PHP Version: 7.1
LDAP Type: Active Directory

Description:
I need to delete an Security Group but I can't find how to do this, can you help me?

Steps To Reproduce:
I tried this:

$dn="OU=Seguridad,OU=Grupos,OU=Empresa,DC=dominio,DC=org";
$ou= \Adldap::search()->groups()->find($gp->name)->setDN($dn);
if ($ou){
  $ou->delete();
}

But I get the error "ldap_delete(): Delete: Operation not allowed on non-leaf", are groups with no members assigned.

**Comment by stevebauman** [comment]
Hi @kiqerdgz,

Your usage is somewhat incorrect, but I don't know if that's the direct cause of the LDAP error.

Try this:

```php
$dn="OU=Seguridad,OU=Grupos,OU=Empresa,DC=dominio,DC=org";

$ou = \Adldap::search()->findByDn($dn);

if ($ou) {
    $ou->delete();
}
```

Are there any sub-OU's inside the OU you're trying to delete? Usually this error indicates there are child OU's or entries that are contained in the OU you're deleting.

You have to delete all the sub-entries first to be able to delete the top level OU.

Basically, you have to chop all the leaves off before you can cut the branch off.

Let me know if you still encounter issues and I'll re-open this, thanks!
