### ISSUE TITLE
unable to authenticate with "simple" username

### ISSUE THREAD

**Issue by wouldsmina** [Adldap2/Adldap2#625]
- Adldap2 Version: 9.1
- LDAP Type:  OpenLDAP
- PHP Version: 7.0

Hello,
I used [this example](https://adldap2.github.io/Adldap2/#/setup?id=authenticating) to get an authentication. it didn't work with `$username = 'jdoe';` but working with `$username = 'uid=jdoe,ou=people,dc=domain,dc=tld';`

How can I do to get the same behavior as the example?

## Steps to reproduce : 
```PHP
//fail with jdoe user
$username = 'jdoe';
//Pass with jdoe@domain with AD or uid=jdoe,ou=people,dc=domain,dc=tld with OpenLDAP
//$username = 'uid=jdoe,ou=people,dc=domain,dc=tld'
$password = 'Password@1';

$ad = new Adldap\Adldap();
$config = ['...'];

$ad->addProvider($config);

try {
    $provider = $ad->connect();

    // Great, we're connected!
} catch (Adldap\Auth\BindException $e) {
    // Failed to connect.
}

try {
    if ($provider->auth()->attempt($username, $password)) {
        // Passed.
    } else {
        // Failed.
    }
} catch (Adldap\Auth\UsernameRequiredException $e) {
    // The user didn't supply a username.
} catch (Adldap\Auth\PasswordRequiredException $e) {
    // The user didn't supply a password.
}
```

**Comment by stevebauman** [comment]
Hi @wouldsmina,

Unfortunately, OpenLDAP only supports authentication using the users full distinguished name.

If the users you're going to be authenticating with are all contained in the same OU, you can set the [account prefix](https://adldap2.github.io/Adldap2/#/setup?id=account-prefix) and [account suffix](https://adldap2.github.io/Adldap2/#/setup?id=account-suffix) options in your config array so this doesn't need to be supplied to the users username every time:

```php
$ad = new Adldap\Adldap();
$config = [
    '...',

    'account_prefix' => 'uid=',
    'account_suffix' => ',ou=people,dc=domain,dc=tld',
];

$ad->addProvider($config);

try {
    $provider = $ad->connect();

    // Great, we're connected!
} catch (Adldap\Auth\BindException $e) {
    // Failed to connect.
}
```

If you're interested in having users simply pass LDAP authentication in your web app to log them into your application in some way, another approach you can take is to create an account in your OpenLDAP directory that will be used to connect to your server *first*, retrieve the user who is authenticating, and then use their full distinguished name to attempt a bind to your LDAP server successfully. This is actually how [Adldap2-Laravel](https://github.com/Adldap2/Adldap2-Laravel)'s auth driver works.

This will allow you to authenticate users in your OpenLDAP directory that aren't contained in the same OU.

Here's an example:

```php
//fail with jdoe user
$username = 'jdoe';
//Pass with jdoe@domain with AD or uid=jdoe,ou=people,dc=domain,dc=tld with OpenLDAP
//$username = 'uid=jdoe,ou=people,dc=domain,dc=tld'
$password = 'Password@1';

$ad = new Adldap\Adldap();
$config = [
    '...'
    'username' => 'uid=jdoe,ou=people,dc=domain,dc=tld',
    'password' => 'super-secret-password',
];

$ad->addProvider($config);

try {
    $provider = $ad->connect();

    // Great, we're connected, now let's try locating the user authenticating:

    $user = $provider->search()->users()->where('uid', $username)->firstOrFail();

    if ($provider->auth()->attempt($user->getDn(), $password)) {
        // User 
    }
} catch (Adldap\Auth\BindException $e) {
    // Failed to connect.
}
```

If you require more assistance, give me a shout and I'll re-open this. Thanks!

**Comment by Virtute90** [comment]
I finally found the solution to my problem! Thank you!

ps: I recommend adding in the documentation that if the server is OpenLDAP you have to pass the distinguished name.
