### ISSUE TITLE
Not importing all users when using $provider->search()->users()->get()

### ISSUE THREAD

**Issue by avinash403** [Adldap2/Adldap2#626]
- Adldap2 Version: 9.1
- LDAP Type: Active Directory
- PHP Version: 7.1.8

### Description:

I am importing all the users using `$provider->search()->users()->get()` but not all users appear in the result. Next, I have imported all records using `$provider->search()->get()` and filtered out records which are User instance. Now some records that appear here is not present in the users that were coming in the previous case.

### Steps To Reproduce:
Not sure if it happens in all Active Directories as I have tested in some and could not reproduce it there but the one that has 1000+ records got me this issue. 

Even a clue will be appreciated

**Comment by stevebauman** [comment]
Hi @avinash403,

If you have more than 1000 users in your AD instance, you'll need to call `paginate()` instead of `get()`, since AD typically has a search result limit of 1000.

Here's an example:

```php
$users = $provider->search()->users()->paginate()->getResults();
```

Let me know if you still encounter issues and I will re-open this. Thanks!
