### ISSUE TITLE
Authenticating to FreeIPA

### ISSUE THREAD

**Issue by JC5** [Adldap2/Adldap2#629]
- Adldap2 Version: 9.0 (through the Laravel package)
- LDAP Type: FreeIPA
- PHP Version: 7.2

### Description:
Firefly III supports LDAP using this package. I have a user who is having trouble configuring FreeIPA and Firefly III. Normally I wouldn't turn to you like this but I believe the issue is out of scope for me. Honestly, I am not entirely sure if this is caused by this package in particular or the Laravel adaptation.

### Steps To Reproduce:
The user in question (@mrshibe) has described his issue pretty well but unfortunately I am at a loss as to what the cause could be. 

For more information, please see https://github.com/firefly-iii/firefly-iii/issues/1933

I would appreciate any help you could give me.

**Comment by stevebauman** [comment]
Hi @JC5, I'd be glad to help! I'll comment on that issue and assist there, and close this out once resolved.

**Comment by stevebauman** [comment]
Closing due to being resolved.
