### ISSUE TITLE
setAttribute() and setRawAttributes() don't work correctly

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#63]
Hi,

I try to use setAttribute() (same for setRawAttributes()) method to change some of my attributes in my account but when I use this method, I always have return false. Here is my code : 
```php
$user = $this->users()->find('samaccount', array('pwdLastSet'));
$user->setAttribute('pwdLastSet', '0')->save(); // Returns false
```

It works if I use some of known attribute, like "title" :
```php
$user = $this->users()->find('samaccount', array('title'));
$user->setAttribute('title', 'New title')->save(); // Returns true
```

What I need is a method to "clear" an attribute, or to "unset" current value of an attribute, like pwdLastSet in my exemple

Thanks for your help !

**Comment by ciadch** [comment]
Sorry for that, it seems to work when I remove caps ?!?
```php
$user = $this->users()->find('samaccount', array('pwdlastset'));
$user->setAttribute('pwdlastset', '0')->save(); // Returns true
``` 
And my attribute is correctly setted in my directory.

**Comment by stevebauman** [comment]
To remove an attribute, or clear it, set it to `null`

```php
$user->setAttribute('title', null);

// Or

$user->title = null;
```

**Comment by ciadch** [comment]
Yeah and I saw that we can use : 
```php
$user->deleteAttribute('MyAttribute');
```

**Comment by stevebauman** [comment]
Yup that as well. Please re-open this issue if you still encounter any.
