### ISSUE TITLE
Adlap2 with codeigniter

### ISSUE THREAD

**Issue by klynicol** [Adldap2/Adldap2#631]
- Adldap2 Version: 9.1.4
- LDAP Type: Active Directory
- PHP Version: 7.2.12

### Description:
I installed Adlap2 into Codeigniter (version 3.1.9) running on Xampp from Windows 7, 64bit. After getting it up and running I noticed there is a bunch of Laravel functions from the Illuminate namepsace that it's trying to call. How would I go about getting around these for Codeigniter?

### Steps To Reproduce:

I dropped the Adlap2 src directory into the Codeigniter library, wrote a little autoload.php file to load the Classes and then called `$ad = new \Adldap\Adldap();` from my controller.

When I call `$provider->search()->find('myUsername');` it starts throwing errors starting with this one

`Message: Class 'Illuminate\Support\Arr' not found`

**Comment by stevebauman** [comment]
Hi @klynicol,

You need to install Adldap2 with composer. Drop in installations aren't supported.

Adldap2 uses Tightenco's [Collect](https://github.com/tightenco/collect) package to add drop-in support for only Laravel's collections and array helpers, and also be backwards compatible with Laravel installations so no code is duplicated.

https://github.com/Adldap2/Adldap2/blob/master/composer.json#L31

**Comment by klynicol** [comment]
Ahh! I had a feeling that might be the case! Thank you for the quick response, I will take a look at a composer install. :-)

**Comment by stevebauman** [comment]
No problem! If you encounter any issues let me know! :smile:
