### ISSUE TITLE
Using getComponents() from DistinguishedName.php

### ISSUE THREAD

**Issue by TipTopNick** [Adldap2/Adldap2#632]
- Adldap2 Version: 9.1.4
- LDAP Type: Active Directory
- PHP Version: 7.2.2

Is there currently a version/release of adldap2 that is using the getComponents() function in src/Models/Attributes/DistinguishedName.php?

I only see it in the master branch and somehow got to using it in my development environment.  I use _composer_ for package management and even though my composer.json files are identical I'm not able to update that file in production to use the getComponents() function. 

Any idea how I might've been able to get that newest DistinguishedName.php file pulled in my development environment but not able to pull it in production?

**Comment by stevebauman** [comment]
Hi @TipTopNick,

Unfortunately I'm not sure how that would have happened. Sounds like you may have required the `dev-master` version of Adldap2 and then modified the `composer.json` file to the proper version, but didn't run a `composer update`?

Version 10.0 of Adldap2 will be coming soon - with these new methods and features built in. Just finishing the documentation.

**Comment by stevebauman** [comment]
As a workaround right now, you could do:

```php
$components = [];

$base = Utilities::explodeDn($base, false);

// Remove the count key from the exploded distinguished name.
unset($base['count']);

foreach ($base as $key => $rdn) {
    // We'll break the RDN into pieces
    $pieces = explode('=', $rdn) ?: [];
  
    if (count($pieces) === 2) {
        $components[$pieces[0]] = $pieces[1];
    }
}
```
