### ISSUE TITLE
Check if member is a member

### ISSUE THREAD

**Issue by jtbratcher** [Adldap2/Adldap2#634]
- Adldap2 Version: 9.1.3
- LDAP Type: Active Directory
- PHP Version: 7.0

### Description:
I am attempting to loop through the members within a group and pull their information. However, the loop crashed when it encounters a subgroup and it attempts to run $member-getEmail(), by showing a undefined method call. Is there a way to test if a member is actually a member and not a group? I'd like to be able to check so that we can skip subgroups and avoid the error.

**Comment by stevebauman** [comment]
Hi @jtbratcher, you can just check the instance for a `Group` model instead of a `User` when looping through:

```php
$group = $provider->search()->groups()->find('Accounting');

foreach ($group->getMembers() as $member) {
    if ($member instanceof \Adldap\Models\Group) {
        // This member is a group.
    } else {
        // This member is not a group.
    }
}
```

**Comment by jtbratcher** [comment]
Perfect, thanks.

**Comment by stevebauman** [comment]
No problem! :smile:
