### ISSUE TITLE
Unable to connect with tls after upgrading to v10.0

### ISSUE THREAD

**Issue by B0bbyD0llar** [Adldap2/Adldap2#636]
- Adldap2 Version: 10.0.0
- LDAP Type: Active Directory
- PHP Version: 7.3.1

### Description:
After upgrade to Version 10.0.0 i cant connect via tls. There are no changes at any part of my configuration. AD Server is the same. PHP, Apache and so on are the same. Back to 9.1.4 all works like a charm.

`
errorCode protected => 52
errorMessage protected => "Server is unavailable" (21)
diagnosticMessage protected => "00000000: LdapErr: DSID-0C09102C, comment: Error initializing SSL/TLS, data 0, v2580" (84)`

### Steps To Reproduce:
Simply upgrading from a running 9.1.4 implementation to 10.0.0

**Comment by B0bbyD0llar** [comment]
Hi @stevebauman,

i connect succesfully to AD and authenticate afterwards successful an user with 9.1.4.

Unfortunately I do not have access to the AD server so I have no more logs.

**Comment by stevebauman** [comment]
Hi @B0bbyD0llar,

I'm not sure if I can assist, as this error points to an issue with the AD servers certificate:

https://social.technet.microsoft.com/Forums/en-US/28fd88b9-847f-4158-bf1a-fd7c12f38fa4/ldaperr-dsid0c090fb4?forum=winserverDS

**Comment by BBrunekreeft** [comment]
Had the same problem. Pull request #640 solved it for me!

**Comment by stevebauman** [comment]
Fixed in v10.0.3.

**Comment by eltharin** [comment]
I've a same problem.
Work in 10.0.1 but not in 10.0.3
Searching for why.

**Comment by eltharin** [comment]
OK,
problem was i declare 4 AD providers (2 PROD and 2 test) and if one test (i don't use in this script) does'nt work, all the script does'nt  work.
It's shame to connect to all providers. so it's I think.

**Comment by stevebauman** [comment]
Hi @eltharin, I'm not really understanding your issue exactly. If you're still encountering problems, please create a new issue on this repository, thanks!
