### ISSUE TITLE
[10.0] Unable to bind

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#637]
Hi @stevebauman !

Hope you're fine !

I encouter a strange behaviour since 10.0. When a user has password "need to change" checked, I recieve this error 
```
Warning: ldap_bind(): Unable to bind to server: Invalid credentials in \adldap2\adldap2\src\Connections\Ldap.php on line 296
```

If I roolback to 9.1.4 everything works fine. Any idea ? 

Thanks for your return

**Comment by stevebauman** [comment]
Hi @ciadch,

I know the issue, bind warnings are no longer muted in v10.0. What version of PHP are you on? I'm not able to reproduce in 7.2. 

Going to patch this now though since errors and notices can be muted for bindings. Thanks!

**Comment by ciadch** [comment]
Ok great ! Thanks a log. I use PHP 7.3, maybe it's why...

**Comment by stevebauman** [comment]
No problem! Thanks for letting me know :smile:

This could be the the defaults I have in my PHP config that is suppressing the warnings by default, but I think they should be suppressed regardless.

Let me know if you encounter anything else!
