### ISSUE TITLE
setGroups() and setMemberOf() don't work

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#64]
Hi !
I try to use setGroups() or setMemberOf() to modify groups in my users account. When I use on of these two methods, they always return false. Here is my exemple :
```php
$user = $this->users()->find('myuser');
$groups = array('CN=MYGROUP,OU=MYOU,DC=MYDC');
// Same is I use only group name : $groups = array('MYGROUP')
$user->setGroups($groups)->save(); // Return false
$user->setMemberOf($groups)->save(); // Return false
```

Is it the correct way to user these methods ?

Thanks for your help

**Comment by stevebauman** [comment]
Are you sure your DN's are correct for the groups you're trying to insert? The inserted groups **need** to be an array for already existing group DN's.

**Comment by ciadch** [comment]
Yeah I'm really sure that my groups exist. I try to create one "Domain Group" and one "Global group" and I but them in the same OU as my account but it doesn't work. 

I try to first create my account and then insert in in my group but same behaviour. 

Any suggestion ?

**Comment by ciadch** [comment]
I try to inverse by adding a member in the group with addMember() method. It works but it's not really what I want :-) ! Adding a user in an array of groups in "one shot" could be better !!!

**Comment by stevebauman** [comment]
Hmm I'll investigate this.

**Comment by ciadch** [comment]
Hi !

Any update for theses methods ? 

Thanks !!!!

**Comment by ChadSikorra** [comment]
The 'memberOf' attribute is actually a linked/calculated attribute in AD, so it is not possible to modify it directly. You have to actually modify the groups 'member' attribute. Perhaps the model could do something behind the scenes to add it to the correct groups 'members' attribute. Right now it looks like you'd have to use the groups model `addMember()` method.

**Comment by stevebauman** [comment]
Ah thanks @ChadSikorra! I'll implement this shortly.

**Comment by stevebauman** [comment]
Hmm. I'm actually not too sure about finding the groups in the `setMemberOf()` setter. This would sort of cause confusion since the developer wouldn't actually need to call the `save()` method since the modifications are being made on separate models.

I'm also not sure what a valuable return type would be in this situation? A bool indicating if the member has been added to all groups? An integer indicating how many groups the model was successfully added to? Or the model itself since every other setter returns the current model after being set for chaining setters? I think I'm going to remove these methods in `v5.2`, and add the method `addGroup()` or `addGroups()` which will perform this task with a clearer indication of what's going on.

**Comment by ciadch** [comment]
Ok thanks for these informations. Actually I use the methods addMember() and removeMember(), it works great. For exemple :
```php
          foreach($remote_groups as $group_dn => $group) {
               // Check if remote group is not in current user groups, then add it
               if(!in_array($group->getCommonName(), $current_groups_name)) {
                  // Add current user to group
                  if($group->addMember($current)) {
                     // New group for user
                     $logs['add'][$group->getCommonName()] = 'ok';
                  }
                  else {
                     // User already in group
                     $logs['add'][$group->getCommonName()] = 'ko';
                  }
               }
            }
```
And
```php
 foreach($current_groups as $group) {
               // Check if current group is not in remote user groups, then remove it
               if(!in_array($group->getCommonName(), $remote_groups_name)) {
                  if($group->removeMember($current)) {
                     $logs['remove'][$group->getCommonName()] = 'ok';
                  }
                  else {
                     $logs['remove'][$group->getCommonName()] = 'ko';
                  }
               }
            }
```

**Comment by stevebauman** [comment]
Added `addGroup()` and `removeGroup()` methods: https://github.com/Adldap2/Adldap2/commit/6e6326bcdde4facd0da15ebfbf05c2ff2f4a33df. Removed `setGroups()` and `setMemberOf()` methods.

**Comment by ciadch** [comment]
Works perfect ! Thanks for your job !

**Comment by stevebauman** [comment]
Great to hear! No problem!

**Comment by auth1299** [comment]
I don't see this documented https://adldap2.github.io/Adldap2/#/models/model

**Comment by stevebauman** [comment]
Apologies @auth1299 - I've been swamped lately with internal projects so my documentation updates have been lacking. Mind creating a PR?
