### ISSUE TITLE
Set True / False / Not set to an attribute

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#643]
Hi @stevebauman  

I hope you're fine !

Just à question, I'm looking for the way to add attribute with value TRUE/FALSE/<notset>. Actually I don't find the way to do that. 

I try
```php
$accout->setAttribute('msExchHideFromAddressLists', true)' --> dosen't works
$accout->setAttribute('msExchHideFromAddressLists', 1)' --> dosen't works
$accout->msExchHideFromAddressList = true --> dosen't works
$accout->msExchHideFromAddressList = true --> dosen't  works
```
Do I need to use setRawAttributes() ? 

Thanks for your help !

Cheers

**Comment by ciadch** [comment]
Sorry, I found the solution with : 

```php
$account->createAttribute('msExchHideFromAddressLists', 'TRUE');
```

:-)

**Comment by stevebauman** [comment]
Thanks for posting your solution @ciadch, much appreciated :smile:

I'll be sure to add this example in the documentation for reference.
