### ISSUE TITLE
Bind with specialchars

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#645]
Hi @stevebauman  !

How can I bind (with attempt method) a user with special chars in password, like '<1234<5678'  Actually it seems it dosent work

Many thanks

**Comment by stevebauman** [comment]
Hi @ciadch,

I'm not able to reproduce this. I created a user in my own environment with the username `<test><>` and the password '<1234<5678' I'm able to authenticate and bind without issue.

I'll need to know more to help, such as your LDAP server type, Adldap2 version, and code usage.

**Comment by ciadch** [comment]
Hello @stevebauman,

After some search, I foud that the problem was an encoding problem. I solved it with html_entity_decode function. 

Thanks for your help !

**Comment by stevebauman** [comment]
Thanks @ciadch! Just fixed this: 3456312

New release will be out shortly.
