### ISSUE TITLE
Sync is missing some users

### ISSUE THREAD

**Issue by jtbratcher** [Adldap2/Adldap2#646]
Adldap2 Version: 9.1.3
    LDAP Type: Active Directory
    PHP Version: 7.0

I have a client syncing with ActiveDirectory through our portal. They are pulling all users, so I'm calling the $provider->search()->users()->get() function. However, it is skipping over some users with no obvious reason. They have an email, first and last names, and all other usual info. They've checked the permissions of the users and everything appears correct. They've tried syncing the entire directory on another system (Barracuda I believe) and it is pulling those users. 

What would the actual query look like for the above function is sending to the AD? 

Any ideas of what to look for would be helpful.

**Comment by stevebauman** [comment]
Hi @jtbratcher,

You can retrieve the filter that will be executed from a query using the following:

```php
$filter = $provider->search()->users()->getQuery();

echo $filter; // Returns '(&(objectclass=user)(objectcategory=person)(!(objectclass=contact))';
```

The `users()` scope won't return ActiveDirectory `Contact`'s, is this possibly what you're missing from the results?

Let me know and I can definitely help you debug further!

**Comment by jtbratcher** [comment]
They say it is definitely a user

**Comment by jtbratcher** [comment]
I assume the function searches all sub groups and ous correct?

**Comment by stevebauman** [comment]
@jtbratcher What is their `base_dn` set to in their configuration?

If the `base_dn` from their configuration is not correct then only a subset of records will be returned that are children of that given `base_dn`.

For example, if I have `ou=Accounting,dc=acme,dc=org`, all search results performed within Adldap2 will only return records within the `Accounting` Organizational Unit.

**Comment by stevebauman** [comment]
> I assume the function searches all sub groups and ous correct?

That's correct, but their `base_dn` needs to be correct (as commented above) - otherwise they will only retrieve a subset of LDAP records.

**Comment by jtbratcher** [comment]
I believe it is correct. It is pulling other users from the same subgroup, just not this one user.

**Comment by stevebauman** [comment]
> I believe it is correct. It is pulling other users from the same subgroup, just not this one user.

Strange... How many `hosts` have they configured for their LDAP servers? If they have multiple, could it possibly be a replication issue between the two DC's?

**Comment by jtbratcher** [comment]
Just a single IP

**Comment by stevebauman** [comment]
Two more things:

- Are you able to post actual code usage? Or are they literally just calling what you mentioned `$provider->search()->users()`?
- Does the LDAP directory have more than 1000 users? They may be hitting the default 1000 record return limit from AD. In this case, they must call `$provider->search()->users()->paginate()->getResults();`

**Comment by jtbratcher** [comment]
That could be it. It looks like 1004 have been returned

**Comment by stevebauman** [comment]
> That could be it. It looks like 1004 have been returned

Okay, they will have to use the `paginate()` method:

```php
$users = $provider->search()->users()->paginate()->getResults();

foreach ($users as $user) {
    // ...
}
```

Let me know if that resolves the issue.

**Comment by jtbratcher** [comment]
Does that still return everything in the $users variables for me, or will I need to manually go through the pagination?

**Comment by stevebauman** [comment]
> Does that still return everything in the $users variables for me, or will I need to manually go through the pagination?

Calling `getResults()` from the `paginate()` method will return the entire result set of the whole query (over 1000).

All the `paginate()` method does is perform the LDAP pagination request and combine the entire result set into one object which you can then iterate over through pages, or retrieve the entire result via `getResults()`.

**Comment by jtbratcher** [comment]
That was it! Thanks for the help.

**Comment by stevebauman** [comment]
Awesome @jtbratcher! Really glad I could help :smile:. No problem at all.

Give me a shout if you have any other issues.

**Comment by jtbratcher** [comment]
one last question, 
so if I'm calling search()->users()->setDn($ou->getDn())->get() I should use search()->users()->setDn($ou->getDn())->paginate()->getResults() instead? Just want to make sure I get my syntax correct.

**Comment by stevebauman** [comment]
> one last question,

No worries!

Yup your code is correct, you would use:

```php
$users = $provider->search()->users()->setDn($ou->getDn())->paginate()->getResults();
```

Now you probably know this (but just making sure), calling the `setDn()` method on the search is overriding your default `base_dn` set in the configuration, so only records that are children of the `$ou` you've given will be returned.

**Comment by splashx** [comment]
@stevebauman is there a reason why in the first `search()` it only returns the page size, and not the actual total?
I'm debugging this issue [here](https://github.com/snipe/snipe-it/issues/7156) and I can't seem to find where the problem is :/

**Comment by splashx** [comment]
Extra info: I also changed the code to use `getResults()`, but it also only works if invoked twice. 😕

**Comment by stevebauman** [comment]
Hi @splashx,

It doesn’t appear that the project you mentioned uses Adldap2? It’s not located in its code or it’s composer.json file - so there isnt much I can assist with since I have no knowledge of its implementation.

**Comment by splashx** [comment]
@stevebauman 👋  I think you checked the wrong branch - as per the description of the issue, the version is 5 so you can find the reference to Adldap2 [here](https://github.com/snipe/snipe-it/blob/v5.0.0-beta-2/composer.json#L14).

**Comment by splashx** [comment]
Btw I've noticed the use of `paginate()` in the original code is probably wrong, I've changed it to:

```
    public function getAllLdapUsers(): array
    {
        $search = $this->ldap->search()->users()->in($this->getBaseDn());

        $filter = $this->getFilter();
        if (!is_null($filter)) {
            $search = $search->rawFilter($filter);
        }
        return $users = $search->select($this->getSelectedFields())
            ->paginate(self::PAGE_SIZE)->getResults();
    }
```

But it's behaving the same: if I perform a `count()` on the resulting array:
```
$ldapUsers = $this->ldap->getAllLdapUsers();
Log::info('count(): '.count($ldapUsers));
```
, it returns `100` (should be `600`).

I only get the desired result if I invoke it twice:
```
$ldapUsers = $this->ldap->getAllLdapUsers();
$ldapUsers = $this->ldap->getAllLdapUsers();
Log::info('count(): '.count($ldapUsers));
```
Prints `600`.

I'm totally 😕 on this one.

**Comment by stevebauman** [comment]
> I only get the desired result if I invoke it twice:

That's strange...

Try changing the following from:

```php
return $users = $search->select($this->getSelectedFields())
            ->paginate(self::PAGE_SIZE)->getResults();
```

To:

```php
return $users = $search->select($this->getSelectedFields())
            ->get()->toArray();
```

**Comment by splashx** [comment]
@stevebauman I'm unable to replicate it on OpenLDAP, only on `389-Directory/1.3.4.9` so I take this is a LDAP-implementation-specific issue 🤷‍♂

**Comment by stevebauman** [comment]
@splashx In that case it seems that the LDAP server isn't responding correctly to the first pagination request?

What is `self::PAGE_SIZE` equal to?

**Comment by splashx** [comment]
`self::PAGE_SIZE` is equal to `100`.
When analyzing the logs on the server side on 389-Directory for that double-call situation, I’ve noticed that it responds with:
`numEntries=100  ... pr_idx=0`
, for the first call.

The second call results in several lines of log (expected) like this:
`numEntries=100  ... pr_idx=1`

I couldn’t find in the 389 docs what `pr_idx` means though, but I assume it’s an indication for the client which the server is not building up correctly for some reason.

I’ll try with a newer version of 389 to see if that problem persists or not.

**Comment by splashx** [comment]
Testing on a newer version of 389Directory:

```
$ ldapsearch -H ldap://localhost:4389  -D "cn=Directory Manager" -w "$PASSWORD"  -b cn=config | grep nsslapd-versionstring
nsslapd-versionstring: 389-Directory/1.4.0.22
```

Now not only we can see the same behavior as the previous version, but we have a bit more info from the logs:

```
[14/Jun/2019:10:49:04.613383500 +0000] conn=32 op=3 SRCH base="ou=users,ou=accounts,dc=example,dc=org" scope=2 filter="(&(objectClass=inetOrgPerson)(objectClass=inetorgperson)(objectClass=person))" attrs="uid givenName sn mail employeeNumber  memberOf useraccountcontrol title telephoneNumber objectClass objectClass"
[14/Jun/2019:10:49:04.620456600 +0000] conn=32 op=3 RESULT err=0 tag=101 nentries=100 etime=0.0007274300 notes=P pr_idx=0 pr_cookie=0
[14/Jun/2019:10:49:10.716136900 +0000] conn=32 op=4 SRCH base="ou=users,ou=accounts,dc=example,dc=org" scope=2 filter="(&(objectClass=inetOrgPerson)(objectClass=inetorgperson)(objectClass=person))" attrs="uid givenName sn mail employeeNumber  memberOf useraccountcontrol title telephoneNumber objectClass objectClass"
[14/Jun/2019:10:49:10.725795300 +0000] conn=32 op=4 RESULT err=0 tag=101 nentries=100 etime=0.0009804400 notes=P pr_idx=1 pr_cookie=1
```

The first `SRCH` is linked to the first call; the second `SRCH` is the subsequent call(s).
Note that `pr_cookie` is set to `0` but later is changed to `1`. 

The end result is the same as in the previous versions of `389 Directory`: only _some_ users are found when `Paginator` is used.

I, unfortunately, have no time to dig deeper so we have concluded that using `adldap2` with `389 Directory` will result in inconsistent results when `Paginator` is used.

**Comment by stevebauman** [comment]
> Now not only we can see the same behavior as the previous version, but we have a bit more info from the logs:

Seems like you received this update: https://pagure.io/389-ds-base/c/ca50d1c

> I, unfortunately, have no time to dig deeper so we have concluded that using adldap2 with 389 Directory will result in inconsistent results when Paginator is used.

Adlpap2 is not doing anything unique in regards to LDAP pagination. Paginated results are retrieved and then placed into the `Paginator` object for easier iteration - that's it.

https://github.com/Adldap2/Adldap2/blob/c3b212c26d38e9136bf2fd72a1a6b597cfa5efe0/src/Query/Builder.php#L471-L508

This is an issue with 389 Directory Server - not Adldap2.

I would heavily suggest trying raw PHP `ldap_*` methods - as you would likely see the same result - which would guarantee you the cause of the issue (either 389 Directory or Adlap2).
