### ISSUE TITLE
Getting detailed error message

### ISSUE THREAD

**Issue by jtbratcher** [Adldap2/Adldap2#647]
Adldap2 Version: 9.1.3
LDAP Type: Active Directory
PHP Version: 7.0

I have a client trying to connect to ActiveDirectory but they are getting a "Can't Contact LDAP" error message. I've been trying to get the more detailed error message working but I'm having some trouble. Here is the code that makes the connection:

        $ad = new Adldap\Adldap();
        $ad->addProvider($config);
      
        try {
            // If a successful connection is made to your server, the provider will be returned.
            $provider = $ad->connect();
        } catch (Adldap\Auth\BindException $e) {
            echo json_encode(['error' => $e->getMessage()]);
        }
        //Detailed message stuff goes here

I've tried using $d = Adldap::getEventDispatcher(); and $d = Adldap\Adldap::getEventDispatcher(); but I keep getting error messages that it doesn't recognize the function. I'm probably calling something incorrectly.

**Comment by stevebauman** [comment]
Hi @jtbratcher,

Events and Logging were adding in [v10](https://github.com/Adldap2/Adldap2/releases/tag/v10.0.0), so using `Adldap::getEventDispatcher()` will return an exception.

Using v9, you can get more detail from the error messages by calling:

```php
$ad = new Adldap\Adldap();
$ad->addProvider($config);
  
try {
        // If a successful connection is made to your server, the provider will be returned.
        $provider = $ad->connect();
} catch (Adldap\Auth\BindException $e) {
        echo json_encode(['error' => $e->getMessage()]);

        $conn = $ad->getDefaultProvider()->getConnection();
        
        // Get detailed diagnostic error and the last reported LDAP error.
        $conn->getDetailedError();
        $conn->getLastError();
}

// Detailed message stuff goes here
```

On v10, this is included in the `BindException`, you can retrieve them from that:

```php
$ad = new Adldap\Adldap();
$ad->addProvider($config);
  
try {
        // If a successful connection is made to your server, the provider will be returned.
        $provider = $ad->connect();
} catch (Adldap\Auth\BindException $e) {
        echo json_encode(['error' => $e->getMessage()]);

        // Get the detailed diagnostic error.
        $e->getDetailedError();
}

// Detailed message stuff goes here
```

Let me know if you need more help and I'll re-open this.

**Comment by jtbratcher** [comment]
I upgraded to 10 and got it working (as in no errors now). But I'm not getting any content in the $e->getDetailedError() message. I've also tried the method on the Troubleshooting page with the listen method and getDiagnosticMessage(). 

Should "Can't contact LDAP server" be giving a more thorough answer? Our clients are asking for more, but it does seem rather self explanatory to me.

**Comment by stevebauman** [comment]
If there isn’t any message coming from the other exceptions, the server simply can’t  contact the LDAP server. It’s likely a network / firewall issue.

**Comment by jtbratcher** [comment]
I tried another connection that I know works to force a different error. I used an invalid password and I just got back an empty array with that error too, should that be the case?

**Comment by stevebauman** [comment]
@jtbratcher you should receive the following when retrieving the `DetailedError` using the `$e->getDetailedError()` method:

> **Note**: This is assuming you're using ActiveDirectory. I'm unsure what the detailed errors are for OpenLDAP.

```
DetailedError {#237 ▼
  #errorCode: 49
  #errorMessage: "Invalid credentials"
  #diagnosticMessage: "80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839"
}
```

**Comment by jtbratcher** [comment]
I'm definitely not getting that. I've upgraded to 10, is there some setting somewhere that needs to be turned on?

**Comment by stevebauman** [comment]
Can you post your full code with sensitive details omitted?

**Comment by jtbratcher** [comment]
It is essentially what you suggested to make it with one modification, I combined the two error lines into echo json_encode(['error' => $e->getMessage(), 'test' => $e->getDetailedError()]);

**Comment by jtbratcher** [comment]
The getMessage part returns fine, but the getDetailedError is blank

**Comment by stevebauman** [comment]
Doing a `json_encode()` on the `DetailedError` exception won't work because the `$detailedError` property is protected and cannot be converted to a string.

You will need to output the errors using the `DetailedError` methods:

```php
$detailedError = $e->getDetailedError();

json_encode([
    'error' => $e->getMessage(), 
    'diag' => $detailedError->getDiagnosticMessage(),
    'message' => $detailedError->getErrorMessage()
]);
```

**Comment by jtbratcher** [comment]
perfect, that was it
