### ISSUE TITLE
OpenLDAP: Invalid DN syntax due to ldap_escape

### ISSUE THREAD

**Issue by mstefan21** [Adldap2/Adldap2#649]
- Adldap2 Version: v10.0.4
- LDAP Type: OpenLDAP
- PHP Version: 7.0.33

### Description:
Invalid DN symtax due to ldap_escap

### Steps To Reproduce:
Login to OpenLDAP

### Solution in PR
https://github.com/Adldap2/Adldap2/pull/648

**Comment by stevebauman** [comment]
Fixed.
