### ISSUE TITLE
getGroups() and getMemberOf() don't work

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#65]
Same behavious for these two methods, they return full object despide of groups / memberof

**Comment by NullIsNot0** [comment]
Change function in src/Models/Traits/HasMemberOfTrait.php
Could somebody submit this to Github?
```
/**
 * Returns an array of groups the model is a member of.
 *
 * https://msdn.microsoft.com/en-us/library/ms677099(v=vs.85).aspx
 *
 * @return array
 */
public function getMemberOf()
{
    $memberof = $this->getAttribute(ActiveDirectory::MEMBER_OF);

    if (is_array($memberof)) {
        unset($memberof['count']);
    } else {
        $memberof = [];
    }

    return $memberof;
}
```

It will fix both getGroups() and getMemberOf() and return array fo groups like this:
```
0 => "CN=Group1,OU=Path,OU=To,OU=Groups,OU=Container,DC=domain,DC=com"
1 => "CN=Group2,OU=Path,OU=To,OU=Groups,OU=Container,DC=domain,DC=com"
2 => "CN=AlotherGroup,OU=Path,OU=To,OU=Groups,OU=Container,DC=domain,DC=com"
3 => "CN=GroupX,OU=Path,OU=To,OU=Groups,OU=Container,DC=domain,DC=com"
```

**Comment by stevebauman** [comment]
The `getMemberOf()` works as intended, it returns the full group object so you're able to run operations on it a receive more information about the group. I'm not sure of the issue here?

**Comment by NullIsNot0** [comment]
Thanks for explanation, but we definitely need a function to get an array of group names (plain text) with "nice" and "not nice" names as I explained above. It was in v4 and would be very nice to see it also in v5.
If I understand correctly, now when a user is a member of 150 groups then LDAP is queried 150 times to get groups as objects. If you just need a list of user's groups then this method is too heavy.

**Comment by stevebauman** [comment]
We don't need a `niceNames()` method in the utilities class. PHP already provides a function for exploding distinguished names (`ldap_explode_dn`) and this is already included as an alias in the utilities class (`Utilities::explodeDn()`). The first key in the array will always be the CN.
