### ISSUE TITLE
Problems creating an attribute

### ISSUE THREAD

**Issue by mafecito** [Adldap2/Adldap2#653]
- Adldap2 Version: 10.0.7
- LDAP Type: Active Directory
- PHP Version: 7.3.3

### Description:
I cant create a new attribute for the user, i got an exception on save. Except for that, all is working okey, i can log, and the attributes are syncing to the DB. I can update an existing attribute, but no create a new one.

Exception: ldap_modify_batch(): Batch Modify: No such attribute
The exception heppens here:

```php
/**
 * {@inheritdoc}
 */
public function modifyBatch($dn, array $values)
{
    return ldap_modify_batch($this->getConnection(), $dn, $values);
}

## Arguments passed to modifyBatch
ldap link resource @464
"CN=XXX,OU=Desarrollo,OU=Departamento de Sistemas,OU=Usuarios,OU=Organizacion XXX,DC=XXX,DC=XXX,DC=ar"
array:1 [▼
  0 => array:3 [▼
    "attrib" => "office"
    "modtype" => 1
    "values" => array:1 [▼
      0 => "Test"
    ]
  ]
]

```
Im using "adldap2/adldap2-laravel": "^6" too.

### Steps To Reproduce:

```php
$user = Auth::user();
$user->ldap->office = 'Test';
$user->ldap->save();

OR

$user = Adldap::search()->users()->where('mail', '=', 'xxx@xxx.xxx.ar')->firstOrFail();
$user->office = 'Test';
$user->save();
```
Thanks a lot, and sorry for my bad english.

**Comment by stevebauman** [comment]
Hi @mafecito,

The `office` attribute doesn't actually exist in ActiveDirectory. I think you're looking for `physicalDeliveryOfficeName` which is listed as `Office` in the ActiveDirectory user interface:

![SCQe5](https://user-images.githubusercontent.com/6421846/55598552-484c2d80-5721-11e9-8c57-3aaa6601339b.png)

You should be able to set that attribute.

Let me know if you encounter any issues!

**Comment by mafecito** [comment]
Oh, wait a minute, i thought that i can add whatever attribute i want, a custom one...

So, i must use the ones that AD had?

In the documentation says

> To create an attribute that does not exist on the model, you can set it like a regular property

https://adldap2.github.io/Adldap2/#/models/model?id=creating-attributes

**Comment by stevebauman** [comment]
> Oh, wait a minute, i thought that i can add whatever attribute i want, a custom one...
>
> So, i must use the ones that AD had?

Yes unfortunately. You can't add custom attributes to ActiveDirectory automatically. You would need to modify the root LDAP schema.

> In the documentation says

> **To create an attribute that does not exist on the model, you can set it like a regular property**

I guess my documentation is misleading. ActiveDirectory usually won't return you all `null` attributes from your directory, so to *create* an attribute that does not exist on the *model*, you can set it on the model even though the property doesn't exist and `save()` it.

I'll update this to more reflect my meaning 😅

**Comment by mafecito** [comment]
Cool, thanks a lot!
