### ISSUE TITLE
Check if user belong to a group

### ISSUE THREAD

**Issue by Vilican** [Adldap2/Adldap2#659]
- Adldap2 Version: 9.1.6 (latest in Composer)
- LDAP Type: AD
- PHP Version: 7.3

I am trying to get whether a user (known variable) belongs to a group (constant, but may be variable in future). I tried looking at the old issues on this topic, but I cannot seem to find the right method to call.

I have this code:

```
<?php

// config omitted

$ad = new \Adldap\Adldap();
$ad->addProvider($config, "AD");

try {

    $provider = $ad->connect("AD");

} catch (Exception $e) { ... }

if ($provider->auth()->attempt($_POST["user"], $_POST["pass"])) {

    $searchObject = $provider->search();

    try {

        $resultUser = $searchObject->findByOrFail('samaccountname', $_POST["user"]);

    } catch (Adldap\Models\ModelNotFoundException $e) { ... }

    // TODO: Authorization - is user in group?

    ...

}
```

**Comment by stevebauman** [comment]
Hi @Vilican,

You can use the `$user->inGroup($group)` method to determine whether a user belongs to a group.

Using this method, you can pass in either a distinguished name of the group, or an actual `Group` model that you retrieve from your directory:

```php
try {
    $resultUser = $searchObject->findByOrFail('samaccountname', $_POST["user"]);

    // Locating the group that the user needs to be apart of:
    $accounting = $searchObject->groups()->findOrFail('Accounting');

    if ($resultUser->inGroup($accounting)) {
        // The user is a member of the 'Accounting' group.
    }

    // --- //

    // Or using just the distinguished name:
    $accounting = 'cn=Accounting,ou=Groups,dc=corp,dc=acme,dc=org';

    if ($resultUser->inGroup($accounting)) {
        // The user is a member of the 'Accounting' group.
    }
} catch (Adldap\Models\ModelNotFoundException $e) {
    //
}
```

Let me know if you run into any issues and I can help you out further, thanks!

**Comment by Vilican** [comment]
Hi @stevebauman,
Thank you for your response. I tried that, but I am still getting this in my IDE:

![image](https://user-images.githubusercontent.com/11300407/56854560-e1ddb800-6938-11e9-8ea4-c5c47c5f7bbe.png)

In both scenarios (locating the group and the selection by DN) the result is always false.

**Comment by stevebauman** [comment]
> Thank you for your response. I tried that, but I am still getting this in my IDE:

That's fine - your IDE doesn't know the return type of the `find` methods because it may return different model instances (such as `User`, `Group`, `Computer` etc.).

> In both scenarios (locating the group and the selection by DN) the result is always false.

Are you sure your AD user is apart of the group you're locating? I would double check this by dumping the users `memberof` attribute and seeing if the groups DN is inside:

```php
$resultUser = $searchObject->findByOrFail('samaccountname', $_POST["user"]);

var_dump($resultUser->memberof);
```

**Comment by Vilican** [comment]
@stevebauman - I don't really know why, but the result is NULL.

**Comment by stevebauman** [comment]
Is the resulting object from the `findByOrFail()` method a `Adldap\Models\User` instance? Try dumping the entire users attributes and see if you're actually retrieving the right record:

```php
$resultUser = $searchObject->findByOrFail('samaccountname', $_POST["user"]);

var_dump($resultUser->getAttributes());
```

**Comment by Vilican** [comment]
@stevebauman - This is the result, with removed personal information:

```
array(40) {
  ["objectclass"]=>
  array(4) {
    [0]=>
    string(3) "top"
    [1]=>
    string(6) "person"
    [2]=>
    string(20) "organizationalPerson"
    [3]=>
    string(4) "user"
  }
  [0]=>
  string(11) "objectclass"
  ["cn"]=>
  array(1) {
    [0]=>
    string(12) "(REMOVED)"
  }
  [1]=>
  string(2) "cn"
  ["sn"]=>
  array(1) {
    [0]=>
    string(3) "(REMOVED)"
  }
  [2]=>
  string(2) "sn"
  ["givenname"]=>
  array(1) {
    [0]=>
    string(8) "(REMOVED)"
  }
  [3]=>
  string(9) "givenname"
  ["distinguishedname"]=>
  array(1) {
    [0]=>
    string(40) "(REMOVED)"
  }
  [4]=>
  string(17) "distinguishedname"
  ["displayname"]=>
  array(1) {
    [0]=>
    string(12) "(REMOVED)"
  }
  [5]=>
  string(11) "displayname"
  ["proxyaddresses"]=>
  array(1) {
    [0]=>
    string(19) "SMTP:(REMOVED)"
  }
  [6]=>
  string(14) "proxyaddresses"
  ["name"]=>
  array(1) {
    [0]=>
    string(12) "(REMOVED)"
  }
  [7]=>
  string(4) "name"
  ["objectguid"]=>
  array(1) {
    [0]=>
    string(16) "(REMOVED)"
  }
  [8]=>
  string(10) "objectguid"
  ["codepage"]=>
  array(1) {
    [0]=>
    string(1) "0"
  }
  [9]=>
  string(8) "codepage"
  ["countrycode"]=>
  array(1) {
    [0]=>
    string(1) "0"
  }
  [10]=>
  string(11) "countrycode"
  ["primarygroupid"]=>
  array(1) {
    [0]=>
    string(3) "513"
  }
  [11]=>
  string(14) "primarygroupid"
  ["objectsid"]=>
  array(1) {
    [0]=>
    string(28) "(REMOVED)"
  }
  [12]=>
  string(9) "objectsid"
  ["samaccountname"]=>
  array(1) {
    [0]=>
    string(6) "(REMOVED)"
  }
  [13]=>
  string(14) "samaccountname"
  ["samaccounttype"]=>
  array(1) {
    [0]=>
    string(9) "(REMOVED)"
  }
  [14]=>
  string(14) "samaccounttype"
  ["userprincipalname"]=>
  array(1) {
    [0]=>
    string(16) "(REMOVED)"
  }
  [15]=>
  string(17) "userprincipalname"
  ["objectcategory"]=>
  array(1) {
    [0]=>
    string(52) "CN=Person,CN=Schema,CN=Configuration,(REMOVED)"
  }
  [16]=>
  string(14) "objectcategory"
  ["msds-supportedencryptiontypes"]=>
  array(1) {
    [0]=>
    string(2) "24"
  }
  [17]=>
  string(29) "msds-supportedencryptiontypes"
  ["mail"]=>
  array(1) {
    [0]=>
    string(14) "(REMOVED)"
  }
  [18]=>
  string(4) "mail"
  ["mobile"]=>
  array(1) {
    [0]=>
    string(16) "(REMOVED)"
  }
  [19]=>
  string(6) "mobile"
}
```

Actually, I am member of plenty user groups:

![image](https://user-images.githubusercontent.com/11300407/56855004-d346cf00-693f-11e9-893d-44a2aba915b6.png)

**Comment by stevebauman** [comment]
Thanks for posting these details @Vilican.

Does the dumped user distinguished name match the one you're showing here in ActiveDirectory?

For some reason the `memberof` attribute isn't being returned by your server. Can you try selecting it and try again? Here's show you can select attributes:

```php
$resultUser = $searchObject->select('memberof')->findByOrFail('samaccountname', $_POST["user"]);

var_dump($resultUser->getAttributes());
```

Also, is the user account you're connecting to your domain with an administrator or a regular user account?

**Comment by Vilican** [comment]
@stevebauman - The DN matches with the one from my account, which I am using. That is OK.
The result from this query is this:

```
array(5) {
  ["objectclass"]=>
  array(4) {
    [0]=>
    string(3) "top"
    [1]=>
    string(6) "person"
    [2]=>
    string(20) "organizationalPerson"
    [3]=>
    string(4) "user"
  }
  [0]=>
  string(11) "objectclass"
  ["objectcategory"]=>
  array(1) {
    [0]=>
    string(52) "CN=Person,CN=Schema,CN=Configuration,(REMOVED)"
  }
  [1]=>
  string(14) "objectcategory"
  ["distinguishedname"]=>
  array(1) {
    [0]=>
    string(40) "(REMOVED)"
  }
}
```

The bind account and the user account are normal AD user accounts. They have no administrative permissions over anything for security reasons.

**Comment by stevebauman** [comment]
> The bind account and the user account are normal AD user accounts. They have no administrative permissions over anything for security reasons.

This is likely the issue. I believe the `memberof` attribute is hidden for security reasons from regular domain users. I would try binding as admin account once just to try.

See this issue on StackOverflow to apply the rights to read the `memberof` attribute with the user you're connecting with:

https://serverfault.com/questions/167371/what-permissions-are-required-for-enumerating-users-groups-in-active-directory

**Comment by Vilican** [comment]
@stevebauman - I tried to bind with an administrator account and it shows the groups. Thank you!

**Comment by stevebauman** [comment]
Ah perfect! Glad you were able to resolve it! No problem at all :smile:
