### ISSUE TITLE
Deleting a User: ErrorException  : ldap_delete(): Delete: Operation not allowed on non-leaf

### ISSUE THREAD

**Issue by ctyler69** [Adldap2/Adldap2#660]
- Adldap2 Version: ^6 
- LDAP Type: Active Directory
- PHP Version: 7.3

I have a laravel task that runs every night to go though my disabled users and deletes them after they have been in there after 14 days. It has worked flawlessly until I ran into an issue. When trying to delete two users I received the error:
ErrorException  : ldap_delete(): Delete: Operation not allowed on non-leaf

As it turns out these users have company phones and are attached to their AD accounts. The have a cn attribute called ExchangeActiveSyncDevices.

Inside ExchangeActiveSyncDevices are the devices - the cell phones. 
How can I programmatically check each user that is disabled for the devices and delete  them before deleting the user?

**Comment by stevebauman** [comment]
Hi @ctyler69,

Are you deleting the users from your ActiveDirectory or your local database?

**Comment by ctyler69** [comment]
Hi @stevebauman, 
I am deleting them from AD first (via $user->delete()), then if the delete is successful I am deleting them from the database.

**Comment by ctyler69** [comment]
Actual we are keeping the database records. They are being flagged in  the DB as being removed from AD.

**Comment by stevebauman** [comment]
Ok sounds good! I understand. You will need to delete the exchange devices prior to deleting their account.

Here's how you can do this:

```php
// Retrieve the user for deletion:
$user = Adldap::search()->find('sbauman');

// Create the DN for locating the users Exchange ActiveSync devices (using the DN builder):
$dn = (new \Adldap\Models\Attributes\DistinguishedName())->addCn('ExchangeActiveSyncDevices')->setBase($user->getDn())->get();

// Or create the DN manually:
$dn = 'cn=ExchangeActiveSyncDevices,' . $user->getDn();

// The DN should be similar to:
// "cn=ExchangeActiveSyncDevices,cn=Steve Bauman,dc=corp,dc=acme,dc=org"

// Retrieve all of the users Exchange ActiveSync Devices:
$devices = Adldap::search()->in($dn)->get();

// Go through each device and delete it:
foreach ($devices as $device) {
    $device->delete();
}

// Delete the user:
$user->delete();
```

Let me know if it works for you!

**Comment by ctyler69** [comment]
That looks great. I have not had a chance to test it yet but I will ASAP!

**Comment by ctyler69** [comment]
This is not working. Everything is returning what it should right up to 
$devices = Adldap::search()->in($dn)->get();
It returns an empty collection. 
$user = Adldap::search()->find(''hlong');
//This returned the correct dn for the user
$user->getDn()

So I continued on and tried this

$dn = (new \Adldap\Models\Attributes\DistinguishedName())->addCn('ExchangeActiveSyncDevices')->setBase($user->getDn())->get();

and this 
$dn = 'cn=ExchangeActiveSyncDevices,' . $user->getDn();
But neither returned and devices when used in:

$devices = Adldap::search()->in($dn)->get();
    dd($devices);

I even tried plugging in the DN manually:

$devices = Adldap::search()->in('CN=ExchangeActiveSyncDevices,CN=LastName\, FirstName,OU=Users-Disabled,DC=comlivserv,DC=com')->get();

Just no devices but no errors either. Is there another way to do it?

**Comment by stevebauman** [comment]
@ctyler69 Are you connecting to your domain with a domain administrator account? This may be a permission issue if you're using a standard user account to bind to your server with.

**Comment by ctyler69** [comment]
This is a domain administrator account. Very confusing. This should work.
I just tried:
Adldap::search()->in('OU=Users-Disabled,DC=comlivserv,DC=com')->get();
I am assuming that this would return everything in the Users-Disabled OU but this returns empty too.

**Comment by ctyler69** [comment]
@stevebauman I have this installed with Laravel. According to composer show adldap2 v10.0.1 is installed currently and Laravel 5.7

**Comment by stevebauman** [comment]
> I just tried: Adldap::search()->in('OU=Users-Disabled,DC=comlivserv,DC=com')->get();

Hmmm strange... So just to clarify, you are connecting to your AD server using a domain admin account?

I'm not really sure what the issue could be besides the spelling on the distinguished name perhaps being incorrect...

**Comment by barbuslex** [comment]
Hi, I have the same issue... :s
Anyone have found a solution ?

**Comment by barbuslex** [comment]
On PHP.net there are a way of solution : 

```
Useful function to delete dn entries recursively

bool myldap_delete ( resource ds, string dn, bool recursive)

Returns TRUE on success, FALSE on failure
recursive is by default FALSE (same behaviour as ldap_delete)

function myldap_delete($ds,$dn,$recursive=false){
    if($recursive == false){
        return(ldap_delete($ds,$dn));
    }else{
        //searching for sub entries
        $sr=ldap_list($ds,$dn,"ObjectClass=*",array(""));
        $info = ldap_get_entries($ds, $sr);
        for($i=0;$i<$info['count'];$i++){
            //deleting recursively sub entries
            $result=myldap_delete($ds,$info[$i]['dn'],$recursive);
            if(!$result){
                //return result code, if delete fails
                return($result);
            }
        }
        return(ldap_delete($ds,$dn));
    }
}
```

https://php.net/manual/fr/function.ldap-delete.php

**Comment by ctyler69** [comment]
@barbuslex, Thank you. I hope it could be translated. I would hate to set up a seperate process to delete users.

**Comment by barbuslex** [comment]
In Connections/Ldap.php maybe replace :+1: 
```php
public function delete($dn)
{
     return ldap_delete($this->getConnection(), $dn);
}
```
By : 
```php
public function delete($dn, $recursive = false)
{
     if($recursive == false) {
         return ldap_delete($this->getConnection(), $dn);
     }
     else {
         //searching for sub entries
        $sr=ldap_list($ds,$dn,"ObjectClass=*",array(""));
        $info = ldap_get_entries($ds, $sr);
        for($i=0;$i<$info['count'];$i++){
            //deleting recursively sub entries
            $result=$this->delete($info[$i]['dn'],$recursive);
            if(!$result){
                //return result code, if delete fails
                return($result);
            }
        }
        return ldap_delete($this->getConnection(), $dn);
     }
}
```

What do you think ?

**Comment by barbuslex** [comment]
Thanks @stevebauman ! Is it possible to create new release, like that my "composer update" update all my applications  ?

**Comment by ctyler69** [comment]
Thank you @stevebauman. Will this change be committed to the Adldap2-Laravel repo as well?

**Comment by stevebauman** [comment]
No problem @barbuslex and @ctyler69!

@barbuslex 
> Is it possible to create new release, like that my "composer update" update all my applications ? (i'm using version ^8.0)

I'll be creating a new release shortly - though it'll be on the `v10.0` branch. I can push the update to the `v9.0` branch, however `v8.0` is no longer receiving updates (unless you'd like to create a PR of course).

@ctyler69 
> Will this change be committed to the Adldap2-Laravel repo as well?

Yup absolutely, if you're using `v6.0` of Adldap2-Laravel you will receive the patch :smile:

**Comment by ctyler69** [comment]
@stevebauman - Works perfectly. Thank you very much for your efforts!

**Comment by stevebauman** [comment]
Awesome @ctyler69! Glad you're up and running! No problem at all :smile:
