### ISSUE TITLE
search()->users() do not return memberof 

### ISSUE THREAD

**Issue by nerdalertdk** [Adldap2/Adldap2#664]
- Adldap2 Version: 10.0
- LDAP Type: OpenLDAP
- PHP Version: 7.2.17

### Description:

`$provider->search()->users()` do not return `memberof`

This results in `$user->getGroups()` returns an empty collection

### Steps To Reproduce:

```
<?php

require __DIR__.'/vendor/autoload.php';

// Construct new Adldap instance.
$ad = new \Adldap\Adldap();

// Create a configuration array.
$config = [
  'hosts'    => ['ldap'],
  'base_dn'  => 'dc=domain,dc=tld',
  'username' => 'cn=admin,dc=domain,dc=tld',
  'password' => 'password',
  'schema'   => Adldap\Schemas\Openldap::class,
];

// Add a connection provider to Adldap.
$ad->addProvider($config);

try {
    $provider = $ad->connect();
 
    dump( $user1 = $provider->search()->users()->find('test') );
    dump( $user2 = $provider->search()->select(['*','memberof'])->where('uid', '=', 'test')->first() );

    dump( $user1->getGroups() );
    dump( $user2->getGroups() );
    
} catch (\Adldap\Auth\BindException $e) {

    var_dump($e->getMessage());
}

```

## dump( $user1 );
```
Array
(
    [cn] => Array
        (
            [0] => Test Testensen
        )

    [0] => cn
    [objectclass] => Array
        (
            [0] => inetOrgPerson
            [1] => top
        )

    [1] => objectclass
    [userpassword] => Array
        (
            [0] => {MD5}4QrcOUm6Wau+VuBX8g+IPg==
        )

    [2] => userpassword
    [sn] => Array
        (
            [0] => Testensen
        )

    [3] => sn
    [uid] => Array
        (
            [0] => test
        )

    [4] => uid
    [dn] => Array
        (
            [0] => uid=test,ou=People,dc=domain,dc=tld
        )

)
```

## dump( $user2 );
```

Array
(
    [cn] => Array
        (
            [0] => Test Testensen
        )

    [0] => cn
    [objectclass] => Array
        (
            [0] => inetOrgPerson
            [1] => top
        )

    [1] => objectclass
    [userpassword] => Array
        (
            [0] => {MD5}4QrcOUm6Wau+VuBX8g+IPg==
        )

    [2] => userpassword
    [sn] => Array
        (
            [0] => Testensen
        )

    [3] => sn
    [uid] => Array
        (
            [0] => test
        )

    [4] => uid
    [memberof] => Array
        (
            [0] => cn=testgruppen,ou=Groups,dc=domain,dc=tld
        )

    [5] => memberof
    [dn] => Array
        (
            [0] => uid=test,ou=People,dc=domain,dc=tld
        )

)
```

**Comment by stevebauman** [comment]
Hi @nerdalertdk,

This attribute being returned seems to be dependent on the OpenLDAP configuration. In ActiveDirectory, this attribute will be returned if the account your binding to the server with has access to read this property. I believe in OpenLDAP, there is a setting for allowing anonynmous access to the `memberof` property that will allow it to be returned by default - but I may be mistaken (I don't use OpenLDAP daily, so my experience is very limited). See the answer here:

https://stackoverflow.com/questions/37351840/ldapsearch-filter-memberof-group-returning-no-results

I don't think this is something we want to select by default for all users being returned in a global search - especially if a directory has thousands of users.

I also don't think this is a bug or issue necessarily. I think if the `memberof` property must be requested for in your search via a `select()` by your server to retrieve those values, then it should be visibly requested for by the developer and not in the background by Adldap2.

**Comment by nerdalertdk** [comment]
By default the MemberOf is hidden on
Openldap unless you ask for it. 

The problem is I can’t use the HasMember trait since users don’t have the MemberOf options.

**Comment by stevebauman** [comment]
> By default the MemberOf is hidden on Openldap unless you ask for it.

I understand for sure, though since this is expected usage for OpenLDAP, I'm don't think we should override the default behaviour and always request the `memberof` attribute regardless if the developer wants it or not. Simply asking for the `memberof` attribute via a `select()` seems appropriate here - and it's visible in your code along with being easily readable.

We would really only be able to apply this select when requesting users or groups via the `Search\Factory::users()` / `Search\Factory::groups()` / `Search\Factory::contacts()` scopes as they are the only records that can be members of groups - but this would lead to a problem if a developer requests other results via a regular query request (such as `Search\Factory::newQuery()->get()`) as we would have to apply the select *globally* for LDAP results that contain the `memberof` attribute to be returned.

I hope I'm making sense here - but I'm definitely up for discussion if you'd like to continue.

**Comment by nerdalertdk** [comment]
Well we might be moving to freeips, so don’t want to use a lot of time on it, Already spend a day debugging :)

But would still there to be an option to get MemberOf, maybe trough an opt-In setting

**Comment by stevebauman** [comment]
> Well we might be moving to freeips, so don’t want to use a lot of time on it, Already spend a day debugging :)

In that case you can leave the `$query->select(['*', 'memberof'])` in your code and it will work regardless of which type of LDAP server you're working with (whether it be AD, FreeIPA, OpenLDAP etc.).

> But would still there to be an option to get MemberOf, maybe trough an opt-In setting

Hmm this is definitely something to consider and could be a good feature. Maybe a config option for default selects?

```php
$config = new \Adldap\Configuration\DomainConfiguration();

$config->set('select', ['*', 'memberof']);
```

**Comment by nerdalertdk** [comment]
I removed my $query->select(['*', 'memberof']) code since it broke the Laravel package :)

Also removed it from here, but I think you might have gotten it in an mail

**Comment by stevebauman** [comment]
> I removed my $query->select(['*', 'memberof']) code since it broke the Laravel package :)

What do you mean? How did it break the Laravel package? Was an exception thrown or something weird happening?

**Comment by nerdalertdk** [comment]
Updated my last answer but yes some weird error, don’t have my laptop near me so can’t test right now

**Comment by stevebauman** [comment]
Oh this was patched in the Adldap2-Laravel repository on this commit here:

https://github.com/Adldap2/Adldap2-Laravel/commit/7cc16a8d4e8c8be55d3c533b4820b1073e6c0200

Also see issue here:

https://github.com/Adldap2/Adldap2-Laravel/issues/706

This attribute is selected by default using OpenLDAP during locating the user logging in for authentication since we sync the `entryUUID` attribute as the objectGUID in your `users` database table.

**Comment by nerdalertdk** [comment]
Ahh well basically need the same thing for MemberOf :)

**Comment by stevebauman** [comment]
Wait a second, I've patched this before...

I included a default scope for applying the requesting of the `memberof` scope in the `config/ldap_auth.php` file:

https://github.com/Adldap2/Adldap2-Laravel/blob/master/src/Scopes/MemberOfScope.php

I need to document this - so this is my fault 😅 . Apply the above scope in your `ldap_auth.php` config and this should resolve your issue:

```php
'scopes' => [
    \Adldap\Laravel\Scopes\MemberOfScope::class
],
```

https://github.com/Adldap2/Adldap2-Laravel/blob/a14d5040bfec62a2e57718d3565341333e4068f2/src/Config/auth.php#L92-L102

**Comment by stevebauman** [comment]
Re-opening this so I can remember to add this into the documentation 👍

**Comment by nerdalertdk** [comment]
But this would prevent users with no group to login right ?

Not that I think it’s going to be an problem for me,

**Comment by stevebauman** [comment]
No it just adds the `memberof` attribute to `select()` of the query that locates the user for logging in.

**Comment by heyFahad** [comment]
> I need to document this - so this is my fault 😅 . Apply the above scope in your `ldap_auth.php` config and this should resolve your issue:

Oh boy! It's been a year and there is still no reference to this scope in documentation. It took my whole day to solve this problem
