### ISSUE TITLE
php compatibility

### ISSUE THREAD

**Issue by LorenzoVET** [Adldap2/Adldap2#668]
Hi.

This is not exactly an issue but instead a request to have a simple information.

I would like to use this class in a my project.

But, checking in this page (https://adldap2.github.io/Adldap2/#/installation) I have read in the requirement section that this class support PHP 7.0 or greater.

Then, it is impossible to use it in a project that run with PHP 5.6 or greater.

Is it correct? Or can I still use this class in a project that run PHP 5.6 or greater?

Thanks.

**Comment by stevebauman** [comment]
Hi @LorenzoVET,

Unfortunately you will not be able to use Adldap2 v10 on PHP 5.6. You can however use v8.0 which has a requirement of PHP v5.5 or greater.

**Comment by LorenzoVET** [comment]
Hi  stevebauman.

Where I can download this version?
Do you have a link?

Thanks again.

**Comment by stevebauman** [comment]
Hey @LorenzoVET,

You will have to use composer to download - but specifying the version:

```json 
“adldap2/adldap2”: “8.0.*”
```

If you download Adldap2 manually, you would have to `require()` all of the project files, which would be pretty messy!

Have you used composer before?

**Comment by LorenzoVET** [comment]
Hi  stevebauman.

I have found the link from which download the version 8.

Cordially.

**Comment by stevebauman** [comment]
Great! Glad you located it.
