### ISSUE TITLE
User's getEmails() is supposed to retrieve array of LDAP's otherMailbox not mail

### ISSUE THREAD

**Issue by NullIsNot0** [Adldap2/Adldap2#67]
Now `getEmails()` is the same as `getEmail()`, but puts value in array. Change it to get `otherMailbox` values or introduce new function `getOtherMailbox()` and drop `getEmails()` so it does not confuse people.

**Comment by NullIsNot0** [comment]
I'm new to git. Can somebody submit this code?
Add one line to file src/Schemas/ActiveDirectory.php
`const OTHER_MAILBOX = "othermailbox";`
And this function to src/Models/User.php
```
/**
 * Returns an array of users other mailboxes
 *
 * @return array
 */
public function getOtherMailbox()
{
    $otherMailbox = $this->getAttribute(ActiveDirectory::OTHER_MAILBOX);

    if (is_array($otherMailbox)) {
        unset($otherMailbox['count']);
    }

    return $otherMailbox;
}

/**
 * Sets the users other mailboxes.
 *
 * @param array $otherMailbox
 * @return User
 */
public function setOtherMailbox($otherMailbox)
{
    return $this->setAttribute(ActiveDirectory::OTHER_MAILBOX, $otherMailbox);
}
```
I vote for removing getEmails() and setEmails().

**Comment by stevebauman** [comment]
`getEmails()` and `getEmail()` are intended methods. An active directory user can have more than one email, and they are inside the `mail` attribute. `getEmail()` returns the users **first** primary email. `getEmails()` returns **all** of the users email addresses, including their primary.

`othermailbox` is a completely separate attribute, however I'll definitely add these methods for the User model.

**Comment by stevebauman** [comment]
Also, just for a heads-up, you can already retrieve this attribute without a "getter". Just use:

```php
$user = $ad->users()->find('jdoe);

$user->othermailbox;
```
