### ISSUE TITLE
N+1 when results should already be available

### ISSUE THREAD

**Issue by jspringe** [Adldap2/Adldap2#671]
- Adldap2 Version: 10.0
- LDAP Type: Active Directory
- PHP Version: 7.2.18

### Description:
In short once you have a collection of groups from `$user->getGroups()` any time you try to iterate over that collection and reference a property you are making a new call to LDAP even though the `getGroups()` method returns a fully hydrated collection of `Group` models.

### Steps To Reproduce:
Once you have retrieved a user via:

    $user = $this->provider->search()
        ->where('samaccountname', '=', $sam_account_name)->get()->first();

and you want to get the associated groups `$groups = $user->getGroups();`
you are presented with a `Adldap\Query\Collection` that has one method that overrides Laravel's Collection class - `valueRetriever` which I think might be the culprit or somewhere along the chain.

If you were to call

    $groups->each(function (Group $group) {
        echo $group->getName();
    });

instead of just returning the hydrated information from the collection it instead makes a new call to LDAP and for every property you attempt to access in the group it makes a separate call, so it's actually something like n + 1 + referencedProperties.

**Comment by jspringe** [comment]
I'm closing this as I was getting a false positive from my test suite.. sorry.

**Comment by stevebauman** [comment]
Hi @jspringe,

I'm not sure if we can actually work around this when retrieving all groups from an LDAP record. LDAP prevents us from executing one search for retrieving all of their memberships in one call (unless you're only looking for the DN of each group). Each group that the record is apart of must be queried for independently to retrieve it's attributes.

If you're looking to simply retrieve the DN's of each group that the record is apart of, you can call `$record->memberof`.

> instead of just returning the hydrated information from the collection it instead makes a new call to LDAP and for every property you attempt to access in the group it makes a separate call

I don't believe this is true. When you call `getGroups()` it returns a collection of group models that the record is apart of. When retrieving the groups attributes - there is no LDAP call. These attributes are already existing inside the model.

**Comment by stevebauman** [comment]
Convenient timing! Thanks for the update @jspringe!

**Comment by jspringe** [comment]
The love hate with TDD when you're `dump()`ing and `dd()`ing to make sure you're on the right path. I'm ashamed to admit it but I've never noticed the delay in the `dump` function before and it made me think it was making a new call until I `array_map`ed over a simple array of values and it did the same thing.

**Comment by stevebauman** [comment]
Ah I've definitely done similar, lol no worries!

This issue actually reminded me of a missing feature I was going to add - query logging - https://github.com/Adldap2/Adldap2/commit/0b55e8e2298e86d47acad136ce23956c652dd0ef.

I just added it now, so you'll be able to see what queries are being executed and how long they take.

Will have a new release out today, thanks! :smile:

**Comment by jspringe** [comment]
Awesome! I implemented a simple logger to look for those queries and only saw `Binding` and `Bound`. This will be wonderful for testing.

It would allow me to write tests to assure _I'm_ not causing any n+1s.
