### ISSUE TITLE
Minor things from cloning master

### ISSUE THREAD

**Issue by jspringe** [Adldap2/Adldap2#673]
- Adldap2 Version: master
- LDAP Type: any
- PHP Version: 7.2.18

### Description:
I just cloned the master branch to contribute a few things that have been bothering me, but ran into a couple issues:

1. ~~There is no composer.lock nor is there an entry in .gitignore.~~
> I forgot that you don't include your composer.lock in libraries/packages.. dummy, but my feeling is it should be in the .gitignore vs a global .gitignore.

2. Related to the above - there isn't an entry for .idea (PHPStorm) - I also noticed that Laravel recently removed this. Is there something I missed? Are people using global .gitignores as the standard?
> Yes. You should use a global .gitignore

3. Running the test suite produces 3 failures in the UserTest class. All related to a `float` being used instead of an `integer`.

> The last issue is related to me using 32bit PHP (due to work limitations) in my dev environment. I feel like this should be handled in some way. Worth a look. This actually looks very tricky.. it actually might be easier for me to just move to 64bit.

4. Are you adhering to PSR-2 in this project?

### Steps To Reproduce:
Run the test suite on master.

**Comment by jspringe** [comment]
The last issue is probably related to me using 32bit PHP (due to work limitations) in my dev environment. I feel like this should be handled in some way. Worth a look.

**Comment by jspringe** [comment]
And for point one - I forgot that you don't include your composer.lock in libraries/packages..

**Comment by jspringe** [comment]
Closing this because it's not important enough to keep open.

**Comment by stevebauman** [comment]
Hi @jspringe,

> Running the test suite produces 3 failures in the UserTest class. All related to a float being used instead of an integer.

This is definitely an issue, though I haven't had time to figure out a workaround for the integer based operations using 32-bit PHP.

> Are you adhering to PSR-2 in this project?

I am to the best of my ability, though it may be violated in some files - I'll be implementing Style-CI soon to ensure I adhere to this spec.

**Comment by jspringe** [comment]
I've never messed around too much with style files. Is this something you could include/provide so I can get my IDE to complain before your StyleCI does?

**Comment by jspringe** [comment]
Also, I'm confused. You organized an array by lengths (which I did alphabetically on a whim) but your `use` statements are out of control. I actually changed them in every file I touched to be shortest to longest, but we had merge conflicts between the time I did that and the time I presented my PR so I reverted everything and added all of my changes back in on a fresh clone (which is why I missed the most important feature - passing proxied calls to the builder with arguments).

**Comment by stevebauman** [comment]
@jspringe - This is StyleCI's doing. I'm going to be tweaking it's configuration to revert namespaces back to shortest to longest. These changes are only in the `master` branch. I consider everything in `master` to be dirty until I create a release.
