### ISSUE TITLE
Set password for current user

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#68]
Hi ! 

As I say a few days age, it could be really useful to have a method to reset user account without knowing current password (especially for domain admins). This method perviously exists in ADLDAP 4.4.

Thanks

**Comment by stevebauman** [comment]
I'll change this in the `setPassword()` method, however you might be able to perform this right now by using:

```php
$password = '12345';

$user = $ad->users()->find('jdoe');

$user->unicodepwd = \Adldap\Classes\Utilities::encodePassword($password);

$user->save();
```

**Comment by stevebauman** [comment]
Fixed https://github.com/Adldap2/Adldap2/commit/804c55cbb86e5e16cbe8089bfe1bc99734ec1b13

**Comment by ciadch** [comment]
Thanks for the job, but sorry it always returns false :-(. I'm authenticated with an admin user and I use SSL
