### ISSUE TITLE
Add contact in OU and a group DL

### ISSUE THREAD

**Issue by vikramsra** [Adldap2/Adldap2#683]
- Adldap2 Version: #6.0.6#
- LDAP Type: < Active Directory-->
- PHP Version: #7.0#

### Description:
We are trying to create contact in a OU and add the same in DL

### Steps To Reproduce:

$contact = $provider->make()->contact([
    'cn' => 'Suzy Doe',
   'ou' = > 'OUName'
]);

It works without the OU

**Comment by stevebauman** [comment]
Hi @vikramsra,

To create an LDAP record inside of an OU, the record needs to be saved as a leaf of the OU you are trying to save it in.

You do this by setting the records distinguished name that you are trying to create as the OU's distinguished name and then adding a common name (CN) to it.

You can do this easily by first locating the OU you want to save the contact in.

Here's an example:

```php
// Locate the OU we want to save the contact inside:
$ou = $provider->search()->findByDn('ou=Contacts,dc=acme,dc=local,dc=org');

$contactCn = 'Suzy Doe';

// Create a new distinguished name from the OU's distinguished
// name and add our contacts common name to it:
$contactDn = $ou->getDnBuilder()->addCn($contactCn);

// Create the contact:
$contact = $provider->make()->contact([
    'cn' => $contactCn,
    'dn' => $contactDn,
]);
```

This should work for you.

Let me know if you have further issues and I'll re-open this. Thanks!
