### ISSUE TITLE
Checking group membership

### ISSUE THREAD

**Issue by cschwehm** [Adldap2/Adldap2#689]
- Adldap2 Version: #.# 10.0.11
- LDAP Type:  Active Directory
- PHP Version: #.# 7.3.6

### Description:

I'm trying to get a list of group memberships using the getGroups function but I get the following error:

[Tue Jun 18 15:52:35.626264 2019] [php7:error] [pid 10715] [client 96.125.118.208:59383] PHP Fatal error:  Uncaught BadMethodCallException: Method Adldap\\Query\\Collection::getGroups does not exist. in /web-secure_a/sso/vendor/tightenco/collect/src/Collect/Support/Traits/Macroable.php:102\nStack trace:\n#0 /web-secure_a/sso/tools/login/login.php(86): Tightenco\\Collect\\Support\\Collection->__call('getGroups', Array)\n#1 {main}\n  thrown in /web-secure_a/sso/vendor/tightenco/collect/src/Collect/Support/Traits/Macroable.php on line 102, referer: https://sso.eng.lsu.edu/

I am able to search the users using:
 $user = $provider->search()->users()->where('sAMAccountName','=',$pawsIdshort)->get();

and that info looks good.  

Am I missing a needed use command?  I tried to add:

use Adldap\Models\Concerns\HasMemberOf 

but that didn't do it.

Thanks so much for your help.

**Comment by stevebauman** [comment]
Hi @cschwehm,

You're almost there! You have to call `first()` instead of `get()`:

```php
$user = $provider->search()->users()->where('sAMAccountName','=',$pawsIdshort)->first();

$groups = $user->getGroups();
```

Calling the `get()` method will **always** return a collection (a glorified array) and not just one record.
