### ISSUE TITLE
ldap_modify_batch is not available on some PHP versions

### ISSUE THREAD

**Issue by samhsuqld** [Adldap2/Adldap2#69]
According to [https://secure.php.net/manual/en/function.ldap-modify-batch.php](the docs), ldap_modify_batch is only available on PHP 5.4.26+, PHP 5.5.10+ and PHP 5.6.0+. On versions older than those, attempting to update a model results in a fatal error.

I was able to use a workaround in my case, but this should at least be documentated.

**Comment by stevebauman** [comment]
Agreed, I'll document this now and close this issue when it's complete.
