### ISSUE TITLE
getGroups() recursive on large directory

### ISSUE THREAD

**Issue by zoriax** [Adldap2/Adldap2#691]
Hi @stevebauman 

I Hope you're fine ! I need you help today because I face a bug and I need your opinion.

We use now Active Directory 2019 and there is a bug with the native nested memberof query 
```
memberOf:1.2.840.113556.1.4.1941:=
```
Sometimes this query doesn't work. It's known by MS but not yet corrected. 

I need a way to find if a user is member of a group, recursively. The problem is that I have a lot of groups and nested groups. So, if I use on my user object :
```php
$user->getGroups(['dn'], true) 
```
It takes approximately 10 seconds to finish (normal, I have 700 groups retrieved). But, it's not usable in an application. 

Do you have any idea how to improve or speed up this function. Is it useful to paginate it ?

By advance, thanks for your help

Cheers

**Comment by stevebauman** [comment]
Hi @zoriax,

> It takes approximately 10 seconds to finish (normal, I have 700 groups retrieved). But, it's not usable in an application.

That's definitely a lot of groups to query!

> Do you have any idea how to improve or speed up this function. Is it useful to paginate it ?

You can only paginate members of an individual group, not groups of an individual user.

For example:

```php
$group = $provider->search()->groups()->select('*', 'member;0-50')->find('Accounting');

// `getMembers()` will automatically paginate the requested
// range of requested members from the above query.
$members = $group->getMembers();
```

This cannot be done in the reverse.

The only real solution I can suggest is caching the results. You could cache the entire result set and perform a background job that runs and refreshes this cache without requesting it on demand. 

Unfortunately there isn't really a workaround if there's an issue with using ActiveDirectory's native nested membership filter (to my knowledge).

**Comment by zoriax** [comment]
Hi @stevebauman,

Thank you very much for your answer. I'll investigate theses possible solutions. 

Have a nice day
