### ISSUE TITLE
Doesn't use SSL port correctly

### ISSUE THREAD

**Issue by gjm** [Adldap2/Adldap2#694]
- Adldap2 Version: 10.0.11
- LDAP Type: OpenLDAP
- PHP Version: 7.3

### Description:
When I try to add a configuration for an OpenLDAP server that uses SSL it uses the default 389 port instead of 636. 

### Steps To Reproduce:
Add a provider config using SSL with LDAP debugging active:
```php
$ad = new Adldap\Adldap();

$ad->addProvider([
    'hosts' => ['example.com'], 
    'use_ssl' => true, 
    'custom_options' => [
        LDAP_OPT_DEBUG_LEVEL => 7,
    ],
]);
```

With this config it tries to connect to port 389 instead of 636:
```
ldap_create
ldap_url_parse_ext(ldaps://example.com:389)
...
```

**Comment by stevebauman** [comment]
Hi gjm, you need to use the `port` configuration option and set it to 636.

**Comment by gjm** [comment]
That has been my "workaround". I only created the issue because, according to the docs, you should only have to specify the port if it is non standard.

**Comment by stevebauman** [comment]
> you should only have to specify the port if it is non standard.

Port 389 is the standard LDAP port. If you require a different port then you must specify it. I'm not sure how that could be classified as a "workaround"?

**Comment by gjm** [comment]
In https://adldap2.github.io/Adldap2/#/setup?id=options:

*The default ports are already used for non SSL and SSL connections (389 and 636).

Only insert a port if your LDAP server uses a unique port.*

That's why I assumed no port entry was required.

**Comment by stevebauman** [comment]
Sorry @gjm! This is my mistake. I appreciate you letting me know.

I've just patched this. A new release will be out shortly.

**Comment by gjm** [comment]
@stevebauman glad I could contribute! Thanks.
