### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by means2014** [Adldap2/Adldap2#697]
- Adldap2 Version: 3.0.4
- LDAP Type: Active Directory 
- PHP Version: 7.3.5

### Description:
I'm not really a web developer, and I'm completely green when it comes to PHP.  So, I apologize if this is just something that is over my head.  I am having trouble with the base_dn configuration.
Our Active Directory users are in a tree like this:
CN={username},OU=Users,OU={location},DC=WCS,DC=local

Using the base_dn=OU=Users,OU={location},DC=WCS,DC=local works with no issue, but then only users in this location can log in.  I've tried to make this base_dn=DC=WCS,DC=local which does not allow any user to log in.  

### Steps To Reproduce:

This is my ldap.php file:
```

<?php
return [
    'logging' => env('LDAP_LOGGING', true),
    'connections' => [
        'default' => [
            'auto_connect' => env('LDAP_AUTO_CONNECT', true),
            'connection' => Adldap\Connections\Ldap::class,
            'settings' => [
                'schema' => Adldap\Schemas\ActiveDirectory::class,
                'account_prefix' => env('LDAP_ACCOUNT_PREFIX', ''),
                'account_suffix' => env('LDAP_ACCOUNT_SUFFIX', ''),
                'hosts' => explode(' ', env('LDAP_HOSTS', )),
                'port' => env('LDAP_PORT', 389),
                'timeout' => env('LDAP_TIMEOUT', 30),
                'base_dn' => env('LDAP_BASE_DN', 'OU=Users,OU=BOE,DC=WCS,DC=local'),
                'username' => env('NewsSiteUN', ''),
                'password' => env('NewsSitePW',''),
                'follow_referrals' => true,
                'use_ssl' => env('LDAP_USE_SSL', false),
                'use_tls' => env('LDAP_USE_TLS', false),
            ],
        ],
    ],
];
```

**Comment by stevebauman** [comment]
Hi @means2014,

I'll definitely help you get up and running!

Looking at your configuration, your base DN should definitely be `DC=WCS,DC=local`.

Try changing it back to the above, then disable `follow_referrals` (set it to `false`), then try logging in.

If that doesn't work, give me a shout back and we can continue debugging :smile:

**Comment by stevebauman** [comment]
Also, since you have `logging` enabled, after attempting to login, check your `storage/logs` directory and see what is output in the file.

**Comment by means2014** [comment]
🤣 Thanks for the help, changing that option took care of it.

**Comment by stevebauman** [comment]
Awesome, no problem at all! Glad you were able to resolve it.
