### ISSUE TITLE
How do I add a user to a group

### ISSUE THREAD

**Issue by auth1299** [Adldap2/Adldap2#698]
- Adldap2 Version: Latest build (Where would I find the version #?)
- LDAP Type: 
- PHP Version: 7.1

### Description:
How do I add a user to a group. I see addMember() from 2015 but it does not appear correct for the current version. I can't find documentation on how to add a user to a AD group. 

Documentation that I'm looking at:
https://adldap2.github.io/Adldap2/#/models/model

### Steps To Reproduce:
I don't know.

**Comment by stevebauman** [comment]
Hi @auth1299,

You can find this by looking at your `composer.lock` file in the root of your projects directory.

For example:

```
"packages": [
    {
        "name": "adldap2/adldap2",
        "version": "v10.0.11",
```

Here are the docs for adding / removing members from groups:

https://adldap2.github.io/Adldap2/#/models/group?id=adding-multiple-group-members

Basically:

```php
$group = $provider->search()->groups()->find('Accounting');

$user = $provider->search()->users()->find('John Doe');

if ($group->addMember($user)) {
    // Successfully added.
}

if ($group->removeMember($user)) {
    // Successfully removed.
}

$users = $provider->search()->users()->get()->toArray();

if ($group->setMembers($users)) {
    // Successfully updated all members.
}
```

**Comment by auth1299** [comment]
I have version "version": "v10.0.11",

In this screen shot you can see my php storm IDE is showing that the function you mention does not exist 

![ldap_function](https://user-images.githubusercontent.com/7773605/61544893-4ed28c80-aa14-11e9-910b-01e3654a4fb5.png)

**Comment by stevebauman** [comment]
That's because PHPStorm doesn't know what type of model will be returned from the search.

You can resolve this by either checking it's type, or by including an `@var` doc above it:

```php
$group = $provider->search()->groups()->find('Support_G_DL_Citrite_AWS_BasicUsers');

if ($group instanceof \Adldap\Models\Group) {
    $group->addMember($user);
}
```

**Or**:

```php
/** @var \Adldap\Models\Group */
$group = $provider->search()->groups()->find('Support_G_DL_Citrite_AWS_BasicUsers');

$group->addMember($user);
```

**Comment by auth1299** [comment]
I get the following error when using this code:

$group = $provider->search()->groups()->find('Support_G_DL_Citrite_AWS_BasicUsers'); 
$user = $provider->search()->users()->find('joe bob');
        if($group->addMember($user)) {
           echo 'success';
        } else {
            echo 'failed';
        }

[13-Aug-2019 13:43:54 America/New_York] PHP Warning:  ldap_modify_batch(): Batch Modify: Insufficient access in C:\inetpub\wwwroot\SF-to-AD\cron-job\Adldap2\vendor\adldap2\adldap2\src\Connections\Ldap.php on line 362

**Comment by auth1299** [comment]
Looks like there is two was yo modify in PHP
https://secure.php.net/manual/en/function.ldap-modify.php
and
https://www.php.net/manual/en/function.ldap-modify-batch.php

**Comment by stevebauman** [comment]
@auth1299 

_Insufficient access_ means the account you are binding to your LDAP server with does not have permission to add the user to the group.
