### ISSUE TITLE
Updating multi-value attribute

### ISSUE THREAD

**Issue by Maarten90** [Adldap2/Adldap2#699]
- Adldap2 Version: 10.0
- LDAP Type: Active Directory
- PHP Version: 7.2.19

### Description:

I cant seem to get a multi-value DN attribute to add multiple DN's. Only the last DN gets added

### Steps To Reproduce:

I have this code:

```
        $count=0;
        foreach ($rights as $username) {
        $user->updateAttribute('MyCustomAttr', $username, $count);
        $count++;
        }
       $update = $user->update();
if ($update) {
.....
```

Why are the other DNs not getting added. DN's are added to an html select element, which is posted as an array ($rights). 

Please let me know how to resolve this. Thanks in advance.

**Comment by stevebauman** [comment]
Hi @Maarten90,

In your above code sample you're actually overwriting your attribute on every `foreach`.

You need to pass the entire array into the `updateAttribute()` method:

```php
$user->updateAttribute('MyCustomAttr', $rights);
```

Also, the `updateAttribute()` method updates the attribute immediately on your LDAP server - so calling `update()` is unnecessary.

If you'd like to use `update()`, you must use `setAttribute()` instead:

```php
$user->setAttribute('MyCustomAttr', $rights);

$user->update();
```

Hope this helps! Let me know if you run into any issues.

**Comment by Maarten90** [comment]
@stevebauman Thank you so much for this. It has resolved my issue.
