### ISSUE TITLE
Can't seem to move user to other OU

### ISSUE THREAD

**Issue by Maarten90** [Adldap2/Adldap2#701]
- Adldap2 Version: 10.0
- LDAP Type: Active Directory
- PHP Version: 7.2.19

### Description:
Hi everyone,

I seem to have an issue when trying to move a user to another OU

### Steps To Reproduce:
I currently have this code:

```
$userd = $provider->search()->whereEquals('cn', $username)->firstOrFail();
$username = "MyUser";
$newParentDn = 'OU=Users_deleted,DC=domain,DC=tld';
 $user->move("CN=".$userd->getCommonName(),$newParentDn,false);
```

I have also tried to set false to true in the move() command, but that doesnt seem to do anything either. I'm also not sure what this option does. Can anyone please tell me what I should do to make this work? I have read https://github.com/Adldap2/Adldap2/issues/72 , but it did not seem to work for me.  Thanks in advance.

**Comment by stevebauman** [comment]
Hi @Maarten90,

You are using the `move()` method incorrectly:

https://adldap2.github.io/Adldap2/#/models/model?id=moving-renaming

```php
$newParentDn = 'OU=Users_deleted,DC=domain,DC=tld';

if ($user->move($newParentDn)) {
    // User was successfully moved into the new OU.
}
```

**Comment by stevebauman** [comment]
Hi @Maarten90,

You are using the `move()` method incorrectly:

https://adldap2.github.io/Adldap2/#/models/model?id=moving-renaming

```php
$newParentDn = 'OU=Users_deleted,DC=domain,DC=tld';

if ($user->move($newParentDn)) {
    // User was successfully moved into the new OU.
}
```
