### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by cemkoker** [Adldap2/Adldap2#702]
- Adldap2 Version: 10.0.11
- LDAP Type: ADLDS
- PHP Version: 7.2

### Description:

Always get 'No such object'; why ?

### Steps To Reproduce:

      $user = $provider->make()->user();
            $user->setCommonName("Cem Koker");
            $dn = $user->getDnBuilder();
            $dn->addCn($user->getCommonName());
            $dn->addOu("XYZ");
            $user->setDn($dn);
            if ($user->save()) {
                echo "User saved";
            } else {
                $error = $provider->getConnection()->getLastError();
                print $error;
            }

**Comment by stevebauman** [comment]
What is your `base_dn` set to in your configuration? Usually you will get this error when the distinguished name you've assigned to your user is incorrect.

**Comment by cemkoker** [comment]
base_dn is set :   'base_dn'  => 'OU=USERS,DC=domain,DC=org',
So the full path is OU=XYZ,OU=USERS,DC=dmain,DC=org

**Comment by cemkoker** [comment]
Ok so turns out you can't set OU in the base_dn ... adding it afterwards works. Clearly a bug and nothing to help about finding out.

**Comment by stevebauman** [comment]
Does your `XYZ` organizational unit exist? Your LDAP server is returning that response because it cannot create an entry with the distinguished name you've set.

If you think you've found a bug, then please tell me how I can replicate it.
