### ISSUE TITLE
Can't create user ?

### ISSUE THREAD

**Issue by cemkoker** [Adldap2/Adldap2#703]
- Adldap2 Version: 10.0.11
- LDAP Type: ADLDS
- PHP Version: 7.2

### Description:

Always get 'No such object'; why ?

### Steps To Reproduce:

      $user = $provider->make()->user();
            $user->setCommonName("John Doe");
            $dn = $user->getDnBuilder();
            $dn->addCn($user->getCommonName());
            $dn->addOu("XYZ");
            $user->setDn($dn);
            if ($user->save()) {
                echo "User saved";
            } else {
                $error = $provider->getConnection()->getLastError();
                print $error;
            }

**Comment by stevebauman** [comment]
Duplicate.
