### ISSUE TITLE
Searching For MemberOf Groups inside specific OU

### ISSUE THREAD

**Issue by Maarten90** [Adldap2/Adldap2#704]
Adldap2 Version: 10.0
    LDAP Type: Active Directory
    PHP Version: 7.2.19

### Description:

I have a user and would like to get all of the groups its a member of that reside in a certain OU. I haven't been able to find anything describing this in the docs. I tried using in() , but that did not seem to give the desired result

### Steps To Reproduce:
```
$user = "username";
    $userd = $provider->search()->select('memberof')->whereEquals('cn', $user)->firstOrFail();
    $groups = $userd->getGroups($fields = ['*'], $recursive = false)->in("OU=DL,OU=CNT,ou=BRD,dc=DOMAIN,dc=TLD");
```

Thanks in advance!

**Comment by stevebauman** [comment]
Hi @Maarten90,

Good question! You can do this in a couple ways.

Firstly, you can simply use a raw filter for `member` if you **do not** want nested groups being returned:

```php
$name = 'John Doe';

$user = $provider->search()->whereEquals('cn', $name)->firstOrFail();

$dn = ldap_escape($user->getDn(), '', LDAP_ESCAPE_DN);

$groups = $provider->search()
        ->groups()
        ->in('OU=DL,OU=CNT,ou=BRD,dc=DOMAIN,dc=TLD')
        ->rawFilter("(member=$dn)")
        ->get();
```

Or if **you do** want nested groups included, you can use ActiveDirectory's recursive `member` search filter:

```php
$name = 'John Doe';

$user = $provider->search()->whereEquals('cn', $name)->firstOrFail();

$dn = ldap_escape($user->getDn(), '', LDAP_ESCAPE_DN);

$groups = $provider->search()
        ->groups()
        ->in('OU=DL,OU=CNT,ou=BRD,dc=DOMAIN,dc=TLD')
        ->rawFilter("(member:1.2.840.113556.1.4.1941:=$dn)")
        ->get();
```

You can also use the `getGroups()` method and filter the resulting collection:

> **Note**: The `getGroups()` method will include the users primary group as well as any groups the primary group is apart of. These groups **will not be** included in the first or second example since AD will not return them from those queries (they must be queried for independently).

```php
$name = "John Doe";

$user = $provider->search()->select('memberof')->whereEquals('cn', $name)->firstOrFail();

$ou = 'OU=DL,OU=CNT,ou=BRD,dc=DOMAIN,dc=TLD';

$groups = $user->getGroups($fields = ['*'], $recursive = false)->filter(function ($group) use ($ou) {
    // Here we are simply checking if the group DN contains the OU's DN we want.
    return strpos($group->getDn(), $ou) !== false;
});
```

Hope this helps! Let me know if you run into any issues.

**Comment by Maarten90** [comment]
Hi @stevebauman ,

Thanks, this works like a charm. Have a great day!
