### ISSUE TITLE
inGroup() not working, blank output, no documentation.

### ISSUE THREAD

**Issue by bradjtrammell** [Adldap2/Adldap2#719]
- Adldap2 Version: 4.0.4
- LDAP Type: Active Directory
- PHP Version: 7.2

### Description:
For the life of me I can not seem to use the function that is labelled either here or in the documentation to see if a user if the member of a group.

The function I see everywhere doesn't bring up anything, no error, no result, nothing in var_dump, which leads me to believe it's a dead function or I'm just not doing it right. When I did a little digging I found out that that documentation available on SourceForge is outdated, and since the User() function was renamed to Users(), all the code there is basically unusable because its out of date.

Here I found an issue that was closed but basically says the same thing, but there's no example code, or resolution to how it was fixed. How can I successfully check to see if a user is a member of ONE particular group without grabbing all of the groups and filtering it down by the one I need to check. 

What I'm trying to do is make menu items available in an SSO portal only to those users who are members of a particular group, or set of particular groups.

### Steps To Reproduce:
```
<?php
include("adLDAP.php");
$adldap = new adLDAP();
$check = $adldap->users()->inGroup("username", "GroupName");

if ($check) {
     echo "User in group";
} else {
     echo "User not in group";
}
?>
```

**Comment by stevebauman** [comment]
Hi @bradjtrammell,

You’re using a **massively** outdated version of “adLDAP” that wasn’t created or maintained by me. I’d heavily suggest upgrading your version to the latest v10, or use [LdapRecord](https://ldaprecord.com).

The usage is described on both packages home pages.

Also, from your posted code it looks like you’re not passing any configuration to actually connect to your server, along with other issues - but I don’t support adLDAP v4 and below.

**Comment by bradjtrammell** [comment]
That would explain a lot. Thank you I will update and adjust my source code to use the new libraries you've provided. Thanks!
