### ISSUE TITLE
Move an account

### ISSUE THREAD

**Issue by ciadch** [Adldap2/Adldap2#72]
Hi !

Just a question, how can I move a user (or another LDAP account) from an OU to another one ? I try to use setDn() but it doesn't work.

Thanks

**Comment by stevebauman** [comment]
I believe we actually need to use the `ldap_rename` method for this, but I haven't built this into Adldap models yet. Will work on this.

**Comment by stevebauman** [comment]
Added ability to move models: https://github.com/Adldap2/Adldap2/commit/4c7b6c632f4c70e45b2f52386630e870ee65cee6

This will still need to be documented, however it'll be in the new release shortly. Closing for now.

**Comment by ciadch** [comment]
Thank you for the method ! Question : how can I use it ? What do you mean by RDN ? Is it the CommonName of my account, a part of it ? 

Thanks for your reply

**Comment by stevebauman** [comment]
Hi @ciadch, an RDN stands for **relative distinguished name**. This means that you only need to insert a portion of the current models DN. Here's an example:

```php
$user = $ad->users()->find('jdoe');

$newRdn= 'cn=John Doe';
$newParentDn = 'ou=New,dc=corp,dc=acme,dc=org';

$user->move($newRdn, $newParentDn);
```

This performs an `ldap_rename()` on the current model.

If you don't want to worry about building an RDN string from a model you already have, then you can always use the DN builder:

```php
$user = $ad->users()->find('jdoe');

// This would return the same line as above, but automatically
// instead of having to build the string yourself
$rdn= $user->getDnBuilder()->assembleCns();

$newParentDn = 'ou=New,dc=corp,dc=acme,dc=org';

$user->move($rdn, $newParentDn);
```

**Comment by ciadch** [comment]
Awesome, it's exactly what I want ! 

Thanks a lot, it works perfectly

**Comment by stevebauman** [comment]
Glad to hear! No problem at all.
