### ISSUE TITLE
unable to perform query whereEquals

### ISSUE THREAD

**Issue by kichetof** [Adldap2/Adldap2#73]
Hi Steve,

Great improvement on query builder ! So nice :)

I encounter a bug when I want to find a user:

Doesn't work:
```
$result = $adldap->search() // tried with $adldap->users()->search()
        ->where("samaccountname", "=", $username) // tried with whereEquals("samaccountname", $username)
        ->get();
```

Works:

```
$results = $adldap->users()->search()
        ->orWhere("cn", "contains", $person)
        ->orWhere("samaccountname", "contains", $person)
        ->sortBy('sn')
        ->get();
```

My first code worked before I updated the code.
Do you have an idea?
Many thanks!

**Comment by stevebauman** [comment]
Have you tried using the find method?

`$ad->search->users()->find($username);`

**Comment by kichetof** [comment]
That doesn't work: `Uncaught SyntaxError: Unexpected end of input`

`$result = $adldap->search()->find($username);` seem to works but my test failed because I'm looking for exact samaccountname.

I don't know why it doesn't work anymore ?

**Comment by stevebauman** [comment]
That syntax error has nothing to do with Adldap. There's something not closed right in your code.

**Comment by kichetof** [comment]
`$ad->search->users()->find($username);` => `PHP Notice:  Undefined property: Adldap\\Adldap::$search`

`$ad->search()->users()->find($username);` => `PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Adldap\\Query\\Builder' does not have a method 'users' in vendor/adldap2/adldap2/src/Classes/Search.php on line 89 PHP Fatal error:  Call to a member function find() on null`

Sorry for my poor log before :)

**Comment by stevebauman** [comment]
No problem at all, but you're calling it wrong, it should be `$ad->users()->search()`, not `$ad->search()->users();`

**Comment by stevebauman** [comment]
Ahh shoot sorry about that! I wrote it wrong above, that's completely my fault. Edited.

**Comment by kichetof** [comment]
Okay like that it "works":

My target : __duponj__
If il look for d, du, dup, dupo, dupon or duponj it doesn't work but if I look for duponj2 that works ?!

My final code looks if a specific samaccountname already exists

**Comment by stevebauman** [comment]
That's strange, can you share your code please?

**Comment by kichetof** [comment]
```php
use Adldap\Adldap;

try {
    $option = array('account_suffix'        => ACCOUNT_SUFFIX,
                    'base_dn'               => BASE_DN,
                    'domain_controllers'    => unserialize(DOMAIN_CONTROLLERS),
                    'admin_username'        => ADMIN_USERNAME,
                    'admin_password'        => ADMIN_PASSWORD,
                   );
    $adldap = new adLDAP($option);
}
catch (adLDAPException $e) {
    echo $e;
    exit();
}

$adldap->getConnection()->showErrors();
$username = isset($_POST['username']) ? strtolower($_POST['username']) : "";

$regexUser = "/^[a-z0-9]+$/";

if(preg_match($regexUser ,$username)){
    /*$result = $adldap->search()
        ->where("samaccountname", "=", $username)
        ->get();
*/ // works before update
    $result = $adldap->users()->search()->find($username);
    print !$result ? json_encode(array("success" => true)) : json_encode(array("success" => false));
}
```

It's an ajax function and I need to have __true__, that seem the samaccount does'nt exist :)

**Comment by stevebauman** [comment]
Replace:

    $result = $adldap->users()->search()->find($username);

With:

    $result = $adldap->users()->find($username);

**Comment by kichetof** [comment]
Yeaaaaaah !!! :)
You rocks guy !! :)

Thanks a lot!!

**Comment by stevebauman** [comment]
No problem at all, please don't hesitate to create more issues if you need anymore help!
