### ISSUE TITLE
Server unwilling to perform ?

### ISSUE THREAD

**Issue by C9Kaiser** [Adldap2/Adldap2#737]
- Adldap2 Version: 10.2.1
- LDAP Type: Active Directory
- PHP Version: 7.2.18

Description:

When i  try to create a user, everything is fine. Howerer, when i try to create one and put either "memberOf" or "passwordUser" attribute, server is unwilling to perform.

TLS set to true and enable on both client and server.
Everything else than TLS is set as default on Adldap.
If i set $user->setUserAccountControl  to 544 User is create and activate but password isnt set.
If i set $user->setUserAccountControl to 512 Server is unwilling to perform

Steps To Reproduce:

Revelant code : 
`<?php
$ad = new \Adldap\Adldap();

$config = [
//Mandatory Configuration Options
'domain_controllers'    => ['XXX.XXX.XX.XXX'],
'base_dn'               => 'dc=dom,dc=com',
'admin_username'        => 'admin@dom.com',
'admin_password'        => 'adminpassword'
];

$ad->addProvider($config);
$provider = $ad->connect();

try {
  $provider = $ad->connect();

  $user = $provider->make()->user([
    'givenname'         => $firstname,
    'sn'                => $name,
    'cn'                => $name." ".$firstname,
    'userPrincipalName' => $login."@dom.com",
    'sAMAccountName'    => $login,
    'mail'              => $mail,
    'userpassword'      => 'Test2019+',
    'Memberof'          => 'cn='.$login.',ou=Service 1,dc=dom,dc=com',
  ]);

  //$user->userPassword="Test2019+"; I also tried this to set pw but doesnt work
  //$user->isActive(); I tried this to set it as active but doesnt work

  //$dn = $user->getDnBuilder()->addOu("Service 1"); Tried this but User isnt add to OU "Service 1"

              

  $user->setUserAccountControl('512'); 

  if ($user->create()) {
      echo "<br>You did it !";
  } else {
      echo "<br>Failed !";
  }
  // Great, we're connected!
            
  } catch (Adldap\Auth\BindException $e) {
      Echo "<br><br>Connection failled !";
      echo $e->getMessage();
  } 
          
}`

**Comment by stevebauman** [comment]
Hi @C9Kaiser,

The attribute you are using (`userpassword`) does not exist in ActiveDirectory. You must use the `unicodePwd` attribute. It must also be encoded.

There is a convenience method for this - using the `setPassword()` method on your new `User` model:

```php
$user = $provider->make()->user(['...']);

$user->setPassword('Super-Secret');
```

The reason why setting the users `userAccountControl` to `512` is failing is due to the user not yet having a password.

Also, when you set the `memberof` attribute, it must contain the distinguished names of a pre-existing (already created) Groups. I may be wrong - but it appears you are dynamically assigning a distinguished name of a Group that does not exist.

I hope this helps!

**Comment by C9Kaiser** [comment]
Ty for your answer.

I tried to use both : 
$user->setPassword('Test2019+'); //No error, but password isnt set somehow. Setting the users userAccountControl to 512 still return "Server is unwilling to perform"

$user->unicodepwd = \Adldap\Utilities::encodePassword('Test2019+'); //Server is unwilling to perform

If i try to set same password (Test2019+) from AD, its working just fine. I don't get why he doesnt want to set it from PHP.
TLS is enable for sure, if i set TLS to false, $user->setPassword('Super-Secret'); return "error, TLS or SSL must be enable"

**Comment by stevebauman** [comment]
Hi @C9Kaiser,

Can you first try creating the user with it's password set, and then enabling them via `userAccountControl`?

```php
$user = $provider->make()->user([
'givenname' => $firstname
'sn' => $name
'cn' => $firstnameName,
'displayName' => $firstnameName,
'initials' => $init,
'userPrincipalName' => $login."@nls.local",
'sAMAccountName' => $login,
'mail' => $mail,
'distinguishedName' => 'cn='.$firstnameName.',ou='.$OU.',dc=nls,dc=local',
]);

$user->setPassword('Test2019+');

// Create the user.
$user->save();

// Enable the user and save.
$user->setUserAccountControl(512)->save();
```

**Comment by C9Kaiser** [comment]
Getting same error.
Howerer, error happen only on seconds save() and user is still created.

If i try to put UserAccountControl to 512 from AD, i'm getting an error saying that password isnt long/complex enough. If i then change password from AD to put it on "Test2019+", i can set  UserAccountControl to 512 from AD without problem.

So its seems like even if user is created and first save() doesnt return any error, password still isnt set to Test2019+
