### ISSUE TITLE
Laravel error in using LDAP

### ISSUE THREAD

**Issue by jakelowie** [Adldap2/Adldap2#739]
- Adldap2 Version: ^6.0 for adldap2/adldap2-laravel
- LDAP Type:  Active Directory 
- PHP Version: PHP 7.3.12

ErrorException
Use of undefined constant LDAP_OPT_PROTOCOL_VERSION - assumed 'LDAP_OPT_PROTOCOL_VERSION' (this will throw an Error in a future version of PHP)

### Description:
Laravel throws this error when in using LDAP 
I have enabled my extension in php.ini but still it throws the same error
Is there anyway that this can be fixed ? I just carefully followed the tutorial that was provided on how to install ldap in laravel but it still is throwing the same error .

Please help .

**Comment by mvatansever** [comment]
Did you see ldap extension is enabled while execute this codes in first line of public/index.php:
`phpinfo();die;`

**Comment by jakelowie** [comment]
> Did you see ldap extension is enabled while execute this codes in first line of public/index.php ? :
> `phpinfo();die;`
Yes , i actually have a print screen of it .
![image](https://user-images.githubusercontent.com/46545502/71160590-d30a9380-2282-11ea-97a7-aa81354d89aa.png)

**Comment by jakelowie** [comment]
> Did you see ldap extension is enabled while execute this codes in first line of public/index.php ? :
> `phpinfo();die;`



Hi , i just found out that LDAP is not enabled in my project , now may i ask on how to enable LDAP in my laravel project ? Thanks

**Comment by mvatansever** [comment]
> > Did you see ldap extension is enabled while execute this codes in first line of public/index.php ? :
> > `phpinfo();die;`
> 
> Hi , i just found out that LDAP is not enabled in my project , now may i ask on how to enable LDAP in my laravel project ? Thanks

Ah okey It's looks like I expected. It depend on your server OS and it's version? You can see in [here](https://stackoverflow.com/questions/39786114/how-to-enable-ldap-with-php-7-0-in-ubuntu-server) for Ubuntu Server with PHP 7.0.

**Comment by stevebauman** [comment]
> Hi , i just found out that LDAP is not enabled in my project , now may i ask on how to enable LDAP in my laravel project ? Thanks

Hi @jakelowie, you must edit your `php.ini` file and enable the `ldap` extension:

```
;;;;;;;;;;;;;;;;;;;;;;
; Dynamic Extensions ;
;;;;;;;;;;;;;;;;;;;;;;

; If you wish to have an extension loaded automatically, use the following
; syntax:
;
;   extension=modulename
;
; For example:
;
;   extension=mysqli
;
; When the extension library to load is not located in the default extension
; directory, You may specify an absolute path to the library file:
;
;   extension=/path/to/extension/mysqli.so
;
; Note : The syntax used in previous PHP versions ('extension=<ext>.so' and
; 'extension='php_<ext>.dll') is supported for legacy reasons and may be
; deprecated in a future PHP major version. So, when it is possible, please
; move to the new ('extension=<ext>) syntax.
;
; Notes for Windows environments :
;
; - Many DLL files are located in the extensions/ (PHP 4) or ext/ (PHP 5+)
;   extension folders as well as the separate PECL DLL download (PHP 5+).
;   Be sure to appropriately set the extension_dir directive.
;

extension=ldap
```

This PHP.ini file must be located inside the directory of the PHP installation that your web server utilizes, otherwise you will still receive this exception.

**Comment by jakelowie** [comment]
> > Hi , i just found out that LDAP is not enabled in my project , now may i ask on how to enable LDAP in my laravel project ? Thanks
> 
> Hi @jakelowie, you must edit your `php.ini` file and enable the `ldap` extension:
> 
> ```
> ;;;;;;;;;;;;;;;;;;;;;;
> ; Dynamic Extensions ;
> ;;;;;;;;;;;;;;;;;;;;;;
> 
> ; If you wish to have an extension loaded automatically, use the following
> ; syntax:
> ;
> ;   extension=modulename
> ;
> ; For example:
> ;
> ;   extension=mysqli
> ;
> ; When the extension library to load is not located in the default extension
> ; directory, You may specify an absolute path to the library file:
> ;
> ;   extension=/path/to/extension/mysqli.so
> ;
> ; Note : The syntax used in previous PHP versions ('extension=<ext>.so' and
> ; 'extension='php_<ext>.dll') is supported for legacy reasons and may be
> ; deprecated in a future PHP major version. So, when it is possible, please
> ; move to the new ('extension=<ext>) syntax.
> ;
> ; Notes for Windows environments :
> ;
> ; - Many DLL files are located in the extensions/ (PHP 4) or ext/ (PHP 5+)
> ;   extension folders as well as the separate PECL DLL download (PHP 5+).
> ;   Be sure to appropriately set the extension_dir directive.
> ;
> 
> extension=ldap
> ```
> 
> This PHP.ini file must be located inside the directory of the PHP installation that your web server utilizes, otherwise you will still receive this exception.



Good day, for my part what I did is to enable the extension on my Apache , inside httpd.conf after that I restarted my apache server and then my computer . And it now working , the next thing Im figuring out is retrieving the data and to configure the connection .
