### ISSUE TITLE
Some attributes are not showing in OpenLDAP

### ISSUE THREAD

**Issue by Haziqasyraff** [Adldap2/Adldap2#747]
- Adldap2 Version: 10.1
- LDAP Type: OpenLDAP
- PHP Version: 7.2

### Description:
Some attributes retrieved from LDAP are not shown. The attributes can only be retrieved by using `select('attributename')` operator. This is hard since I have to select all "hidden" attribute name and list them out one by one instead of just use `getAttributes()`.

### Steps To Reproduce:
The following code returns some attributes with values:

`
Adldap::search()->where('uid', 'haziq')->firstOrFail()->getAttributes();
`

Attributes like 'pwdupdatetime' and 'modifiersname' are not shown in the returned values. However, if I wrote like:

`
Adldap::search()->select('pwdupdatetime')->where('uid', 'haziq')->firstOrFail()->pwdupdatetime;
`

The above code will return only 'pwdupdatetime' which means the attribute exist but does not show when using `getAttributes()`

**Comment by stevebauman** [comment]
Hi @Haziqasyraff,

You will need to select all attributes using the asterisk and also include your virtual attribute:

```php
Adldap::search()->select(['*', 'pwdupdatetime'])->where('uid', 'haziq')->firstOrFail()->pwdupdatetime;
```

Let me know if you run into issues and I'll re-open this.

**Comment by Haziqasyraff** [comment]
This is working, but may I know why the `getAttributes()` does not retrieve all of the attributes and instead only some?

**Comment by stevebauman** [comment]
My guess is that it's a virtual attribute and must be requested for manually from your LDAP server.

I'm assuming you're using Red Had Directory Server? Unfortunately I haven't had any experience with that LDAP directory type, so I'm unsure if there's any way around it. This may be something that is configurable on the server itself if you have admin access to it.

Sorry I can't assist you more in this, but I hope this helps in some way.

**Comment by Albvadi** [comment]
@stevebauman Maybe, you can make select columns configurable... :man_shrugging: 
https://github.com/Adldap2/Adldap2/blob/f5ef3aee2de057055672a6241aaf670ba9029a3c/src/Query/Builder.php#L19-L24

In Laravel across config files and here same as other configurable properties, with a array to push to `['*']`...

I have the same situation in other scenarios, I need attributes not retrieved by default and I need my own `$columns` array in all my app.

**Comment by stevebauman** [comment]
You could do this now by extending the current query `Builder` instance and using it instead of the current one.

Adding this would be a feature request though, which I've closed down due to [LdapRecord](https://ldaprecord.com) - a rebuild of Adldap2.

With LdapRecord, you can add a [model scope](https://ldaprecord.com/docs/models/#creating-global-scope) and then add the select columns on a given model which will request them for every search request:

```php
<?php

namespace App\Ldap\Scopes;

use LdapRecord\Models\Scope;
use LdapRecord\Models\Model;
use LdapRecord\Query\Model\Builder;

class UserAttributeScope implements Scope
{
    public function apply(Builder $builder, Model $model)
    {
        $builder->addSelect('pwdupdatetime');
    }
}
```

Then, adding it to your `User` model:

```php
<?php

namespace App\Ldap;

use LdapRecord\Models\Model;
use App\Ldap\Scopes\UserAttributeScope;

class User extends Model
{
    public static $objectClasses = [ 'top', 'person', 'organizationalperson', 'user'];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new UserAttributeScope);
    }
}
