### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Illuminate\Support\Arr' not found in /app/public/vendor/adldap2/adldap2/src/Events/Dispatcher.php:147

### ISSUE THREAD

**Issue by cor1-11** [Adldap2/Adldap2#748]
- Adldap2 Version: 10.2.2
- LDAP Type: Active Directory
- PHP Version: 7.3

### Description:
getting a Laravel error on a non-Laravel install?'

full error:

Fatal error: Uncaught Error: Class 'Illuminate\Support\Arr' not found in /app/public/vendor/adldap2/adldap2/src/Events/Dispatcher.php:147 Stack trace: #0 /app/public/vendor/adldap2/adldap2/src/Events/Dispatcher.php(105): Adldap\Events\Dispatcher->parseEventAndPayload('Adldap\\Auth\\Eve...', Array) #1 /app/public/vendor/adldap2/adldap2/src/Events/Dispatcher.php(93): Adldap\Events\Dispatcher->dispatch(Object(Adldap\Auth\Events\Binding), Array, false) #2 /app/public/vendor/adldap2/adldap2/src/Auth/Guard.php(241): Adldap\Events\Dispatcher->fire(Object(Adldap\Auth\Events\Binding)) #3 /app/public/vendor/adldap2/adldap2/src/Auth/Guard.php(96): Adldap\Auth\Guard->fireBindingEvent(NULL, NULL) #4 /app/public/lib/ldap.php(33): Adldap\Auth\Guard->bind() #5 /app/public/models/ptUser.class.php(164): getLDAPConn('*****', '*****') #6 /app/public/index.php(63): ptUser->loginUser() #7 {main} thrown in /app/public/vendor/adldap2/adldap2/src/Events/Dispatcher.php on line 147

### Steps To Reproduce:
Setup Anonymously Binding
Authenticate with user bind

**Comment by stevebauman** [comment]
Hi there,

Did you install Adldap2 via composer?

**Comment by cor1-11** [comment]
No my initial attempt was by downloading. I have now installed by composer.
