### ISSUE TITLE
How use CURLOPT_SSL_VERIFYPEER?

### ISSUE THREAD

**Issue by Vasiliy-Makogon** [Adldap2/Adldap2#758]
- Adldap2 Version: 10.1
- LDAP Type: Active Directory
- PHP Version: 7.2

Hi. I use AdLdap/AdLdap-Larevel for connection to AD. Current error - "Can't contact LDAP server, error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (unable to get local issuer certificate)" my system admin say so need set the option `CURLOPT_SSL_VERIFYPEER` in `false` value, but is not work:

`
            'custom_options' => [
                CURLOPT_SSL_VERIFYPEER => false
            ],
`

1. Why is not work?
2. And how to use this const in ldap.php config file?

**Comment by stevebauman** [comment]
Hi @Vasiliy-Makogon,

I would recommend checking out the docs here on connecting to your LDAP server via TLS or SSL:

https://ldaprecord.com/docs/configuration/#ssl-amp-tls

It’s from the newer LdapRecord package, but it’s docs can be applied to Adldap2 in this area.

I’ve never seen the constant you’re setting used for LDAP configuration and it has never been required for Adldap2 — so for that reason I am closing this out.

I hope the above docs helps, thanks!

**Comment by stevebauman** [comment]
Check the comments here:

https://www.php.net/manual/en/function.curl-setopt.php

There appears to be many referencing that constant with resolution to this issue.
