### ISSUE TITLE
Add an option to disable autologin

### ISSUE THREAD

**Issue by Xento** [Adldap2/Adldap2#76]
When you don't specify an admin user in the config and you create an instance of the class it tries to authenticate with null username and password.
Maybe this works when anonymous binding is allowed but when you don't have this enabled and you want to authenticate somewere else in you code you always create an failed logon attempt.
I think an option 'autoAuthenticate' or something like this would be nice as configoption.

**Comment by stevebauman** [comment]
Hey @Xento, this is already an option called 'autoConnect':https://github.com/Adldap2/Adldap2/blob/master/docs/GETTING-STARTED.md
