### ISSUE TITLE
ldap_control_paged_result deprecated

### ISSUE THREAD

**Issue by kkatpcc** [Adldap2/Adldap2#760]
- Adldap2 Version: 10.2.3
- LDAP Type: Any/All
- PHP Version: 7.4

### Description:
This was fixed in https://github.com/DirectoryTree/LdapRecord/issues/59, but should also be backported here as a preemptive bug fix.
> As per https://www.php.net/manual/en/migration74.deprecated.php:
> ldap_control_paged_result_response() and ldap_control_paged_result() are deprecated. Pagination controls can be sent along with ldap_search() instead.

**Comment by stevebauman** [comment]
Thanks @kkatpcc, mind writing a PR?

**Comment by kkatpcc** [comment]
@stevebauman sure, I should be able come up with something this week.

**Comment by kkatpcc** [comment]
Pagination was backported from LdapRecord. Closing this as resolved.
