### ISSUE TITLE
Potential false positive test cases due to missing Mockery::close()

### ISSUE THREAD

**Issue by kkatpcc** [Adldap2/Adldap2#761]
- Adldap2 Version: 10.2.3
- LDAP Type: Any/All
- PHP Version: Any/All

### Description:
While working on tests related to a PR for https://github.com/Adldap2/Adldap2/issues/760, I came across a situation where I know the test I was working on should have failed, but it unexpectedly passed.

Upon investigation, I found the [official Mockery PHPUnit integration documentation](http://docs.mockery.io/en/latest/reference/phpunit_integration.html) which indicates that `Mockery::close()` needs to be called to verify expectations. I changed `TestCase::tearDown` accordingly, and the test I was working on finally failed as expected, but I also found that quite a few existing tests now have errors.

### Steps To Reproduce:
Run phpunit, and observe the result: 
> Tests: 399, Assertions: 726, Failures: 2

Add `Mockery::close()` to the end of `Adldap\Tests\TestCase::tearDown`, run phpunit, and observe the new result: 
> Tests: 399, Assertions: 726, **Errors: 22**, Failures: 2

**Comment by stevebauman** [comment]
Thanks @kkatpcc! Fixed.
