### ISSUE TITLE
QUESTION: ldaps VS start-TLS for ldap

### ISSUE THREAD

**Issue by auth1299** [Adldap2/Adldap2#766]
- Adldap2 Version: Latest version
- LDAP Type: 
- PHP Version: 7.x

### Description: There is a difference between ldaps and start-TLS for ldap.  Start-TLS uses port 389, while ldaps uses port 636.  ldaps has been deprecated in favor of start-TLS for ldap.  Both encrypted (start-TLS ldap)  and unencrypted ldap (ldap) run on port 389 concurrently. 

reference: https://www.php.net/manual/en/function.ldap-start-tls.php

**Does ADLDAP2 support start-TLS?**

**Comment by stevebauman** [comment]
Hi @auth1299,

Yes, TLS is supported. You simply enable it via the configuration flag `use_tls`:

```php
$ad = new \Adldap\Adldap();

// Create a configuration array.
$config = [
  // ...
  'username' => 'admin@corp.acme.org',
  'password' => 'password',
  'use_tls' => true, // <-- Use TLS flag
];

// Add a connection provider to Adldap.
$ad->addProvider($config);
```

**Comment by auth1299** [comment]
Are there other requirements and dependencies to enable TLS? I have PHP installed on a windows 2016 server. Based on the second entry on this url: https://www.php.net/manual/en/function.ldap-start-tls.php

1) Download the Certificate X.509 (PEM format) from a web browser, I used Firefox. I put the name webcert.crt
2) Create the folder c:\openldap\sysconf
3) Copy the file webcert.crt to c:\openldap\sysconf
4) With notepad you must create the file c:\openldap\sysconf\ldap.conf file. The file contents:
TLS_REQCERT never
TLS_CACERT c:\openldap\sysconf\webcert.crt
5) The code:

This entry is 10 years old.

**Comment by auth1299** [comment]
Would you know if enabling TLS also satisfies LDAP Channel Binding and LDAP Signing? 

I have to satisfy this requirement: 
https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV190023

**Comment by stevebauman** [comment]
This will be insecure:

> With notepad you must create the file c:\openldap\sysconf\ldap.conf file. The file contents:
> TLS_REQCERT never
> TLS_CACERT c:\openldap\sysconf\webcert.crt

If you are providing a certificate for PHP LDAP connections to utilize, you must remove the `TLS_REQCERT never` line, as this will negate the usage of the certificate you have placed in the configuration. You should use `TLS_REQCERT hard` instead.

I have some documentation written about this here in the new LdapRecord framework:

https://ldaprecord.com/docs/configuration/#ssl-amp-tls

Your `ldap.conf` file should look similar to:

```
TLS_CACERT C:\OpenLDAP\sysconf\ca.pem
TLS_REQCERT hard
```

To my knowledge, this is the most secure way you can connect to your LDAP servers in PHP.

**Comment by stevebauman** [comment]
> Would you know if enabling TLS also satisfies LDAP Channel Binding and LDAP Signing?

I do not, unfortunately. Looking at the docs it does mention:

> The security of Active Directory domain controllers can be significantly improved by configuring the server to reject Simple Authentication and Security Layer (SASL) LDAP binds that do not request signing (integrity verification) or to reject LDAP simple binds that are performed on a clear text **(non-SSL/TLS-encrypted) connection.**

TLS is an encrypted protocol, so I honestly think you're okay here. I do not believe there is any other way you can further secure the connection. I would however not use SSL, as it is now deprecated.

Hope this helps!

**Comment by auth1299** [comment]
Thank you Steve

**Comment by stevebauman** [comment]
Glad to help @auth1299! :smile:

**Comment by wranger** [comment]
Hi there,

when you enable/or use SSL, its not the protocol itselfs you use, its the ssl mechanism and that defines to start an encrypted connection on a special port.

I use also ssl, but the library choose TLS1.3 to secure the connection. 

(I saw this while debugging some connection issus.)

@Steve: Thanks a lot for your work :)!

Regards
Carsten

**Comment by auth1299** [comment]
Hi Steve, 

I've been working on this non-stop trying to get TLS to work.

I have no issues when I set TLS to false. Your solution works and returns data with a query. When I turn on TLS to true. It fails.

Fatal error: Uncaught Exception: Can't contact LDAP server in

All the researching I've been doing seems to point that with php version 7.1.0 on windows servers, it no longer uses that static file C:\OpenLDAP\sysconf\ldap.conf

https://www.php.net/manual/en/function.ldap-set-option.php

I even put my own function together with ldap-start-tls with the same fail.  command (ldap_set_option($ldaps_connection, LDAP_OPT_DEBUG_LEVEL, 7); //debugging errors) provides me with no more data than the error I had. 

It would greatly help if I was able to enable some sort of debug so I can see where the issue is failing. I have not been able to get any kind of debugging working.  I went to your page: https://adldap2.github.io/Adldap2/#/troubleshooting and copied and pasted your listener but gave me nothing. 

Any ideas? 
[php_function.txt](https://github.com/Adldap2/Adldap2/files/4635691/php_function.txt)
![php_ldap](https://user-images.githubusercontent.com/7773605/82073431-3f10ec80-96a7-11ea-8aa3-93d7289fd57f.PNG)
![ldap](https://user-images.githubusercontent.com/7773605/82073435-3f10ec80-96a7-11ea-9519-f670357b9199.PNG)

**Comment by stevebauman** [comment]
Hi @auth1299, I have a couple questions:

- Are you sure you have TLS enabled on your Active Directory server?
- If you use `TLS_REQCERT never` instead of `TLS_REQCERT hard`, are you able to connect?

**Comment by auth1299** [comment]
Hi Steve, 

same issue with never

**Comment by auth1299** [comment]
After more test, I tried again with never and now it is working. It's not ideal that I have it to never. I think that tells me my ca cert is not right even though I open it and there are no errors.

**Comment by stevebauman** [comment]
> I think that tells me my ca cert is not right even though I open it and there are no errors.

Unfortunately you'll have to troubleshoot this on your own with your AD server. Maybe check your servers logs and see why connections are being rejected with that certificate?
