### ISSUE TITLE
Option hosts does not exist

### ISSUE THREAD

**Issue by elmys** [Adldap2/Adldap2#767]
'ldapConnect' => [
            'hosts' => ['ip1', 'ip2'],
            'base_dn'  => 'dc=on,dc=site,dc=ru',
            'username' => 'login@site.ru',
            'password' => '**************',
            'port' => 389,
            //'use_tls' => true,
    ],

Error had after component init. What i did wrong?
Or need to use domain_controllers instead hosts as in #448 ?

composer.json:  "adldap2/adldap2": "*" 
in lock: "version": "v7.0.15",

**Comment by stevebauman** [comment]
Hi @elmys,

Can you post your entire code sample? I need to know how you're adding this configuration array into Adldap.

**Comment by elmys** [comment]
$ad = new Adldap(Yii::$app->params['ldapConnect']);
or also tried $ad->addProvider(Yii::$app->params['ldapConnect']);

**Comment by stevebauman** [comment]
Ok, if you're using v7.0, you will need to use `domain_controllers`. I would however heavily recommend using v10, or moving to [LdapRecord](https://github.com/DirectoryTree/LdapRecord).

**Comment by elmys** [comment]
> using v10

of what software?

**Comment by stevebauman** [comment]
Let me know if you still encounter issues and I will re-open. Thanks!

**Comment by stevebauman** [comment]
> of what software?

Adldap2. Update your `composr.json` to use v10:

```json
"require": {
    "adldap2/adldap2": "^10.0"
}
```
