### ISSUE TITLE
Adlap2 - update “Batch Modify: Insufficient access”

### ISSUE THREAD

**Issue by vbaseghyanupwork** [Adldap2/Adldap2#769]
Adldap2 Version: Master
LDAP Type: ActiveDirectory
PHP Version: 7.3

I have successfully connected to active directory, and I can do create new user operation like

```
$user = Adldap::make()->user([
    'cn' => 'Vlad Test7',
    'samaccountname' => 'vlad_test7',
    'Company' => 'Company Name',
    'givenname' => 'Vlad',
]);

$user->objectclass = [
    'top',
    'person',
    'inetOrgPerson',
];

$user->save();
```

This will work. But after if I will try to set another attribute like department, doing it as below

```
$user->setAttribute('Department', 'Information Systems');
$user->save();
```
I will get this error message

> ErrorException : ldap_modify_batch(): Batch Modify: Insufficient access at PATH_TO_PROJECT_ROOT\vendor\adldap2\adldap2\src\Connections\Ldap.php:386

I asked system admin about provided accounts permissions, and he told me that I have full access within OU for test user, that they have been created for me.

I suppose, that possibly can be something wrong with my config files, I have there as admin told me.

Here how config file (ldap.php) looks like

```
'hosts' => explode(' ', env('LDAP_HOSTS', 'corp-dc1.corp.acme.org corp-dc2.corp.acme.org')),
'port' => env('LDAP_PORT', 389),
'timeout' => env('LDAP_TIMEOUT', 5),
'base_dn' => env('LDAP_BASE_DN', 'dc=corp,dc=acme,dc=org'),
'username' => env('LDAP_USERNAME', 'username'),
'password' => env('LDAP_PASSWORD', 'secret'),
```
Based on my search result, possibly error message on update can be related with dn (distinguished name), as I have something like that as base_dn

`base_dn=OU=TEST USER,OU=xxxxxx1,OU=xxxxxx2,OU=xxxxxx3,OU=xxxxxx3,DC=domain,DC=local`
and when I'm creating a user, for new created user I'm getting new generated dn which is like below

`dn=CN=Vlad Test7,OU=TEST USER,OU=xxxxxx1,OU=xxxxxx2,OU=xxxxxx3,OU=xxxxxx3,DC=domain,DC=local`
not sure, is this correct or not? Thinking also about possibility, that I can perform operations using provided distinguished names, but if to add something to it, permission is denied.

Any suggestions or thoughts about this issue? Thanks

**Comment by stevebauman** [comment]
Hi @vbaseghyanupwork,

Everything seems proper for user creation, and the generated distinguished name appears to be correct as well.

This is almost certainly a permission issue with the user account you have configured in your `ldap.php`. It seems it likely has create permissions, but does not have modify. You could ask your IT department to temporarily give you a higher permission / role level (such as domain administrator) for a moment to run your script and test modification of the user you create.

If they are unwilling to do that, they must verify that the account your binding with has modify permissions on all accounts inside of the organizational unit you have access to. Your LDAP server is telling you the truth with an "Insufficient Access" error.

Hope this helps!

**Comment by vbaseghyanupwork** [comment]
Hi @stevebauman ,

Thanks for confirmation, I supposed that I was doing everything right here, basically there is nothing special in my code, so it should work if user, that I'm using has proper permissions. 

I've also tried with tool (softerra LDAP administrator) the same exact thing, and user creation was successful, but I wasn't able to edit anything or create new parameter and got exact same error message, so this is 100% user permission issue.

Thanks again!
