### ISSUE TITLE
Upgrade to Laravel 7

### ISSUE THREAD

**Issue by justageek** [Adldap2/Adldap2#772]
- Adldap2 Version: 6.0
- LDAP Type: Active Directory
- PHP Version: 7.3

### Description:
Upgrade to Laravel 7.  Do we need to do any work on the adldap2 package to upgrade to Laravel 7

### Steps To Reproduce:
Just a question.

**Comment by stevebauman** [comment]
Hi @justageek,

No, it is fully compatible with Laravel 7. 👍
