### ISSUE TITLE
Not able to ldap bind as user

### ISSUE THREAD

**Issue by AnilGillAlipuria** [Adldap2/Adldap2#777]
- jotaelesalinas-laravel-adminless-ldap-auth: 0.5.1
- LDAP Type:  Active Directory
- PHP Version: 7.2.5

### Description:
Hi, I am trying to integrate LDAP authentication into my application and it's done with openldap. But  I want authentication with Active Directory, which requires user credentials to bind and authenticate. And ADMINLESS-LDAP-AUTH needs the configuration of ADMIN credentials to bind ldap. It's also done successfully, but with hard coding of user credentials  in place of ADMIN username and password in config>ldap.php . How can I bind adldap with user credential dynamically. In my case AD users  have permission to bind and read attributes in ldap. #545 

Steps To Reproduce:
**config > ldap.php**
    ```
    'username' => env('LDAP_USERNAME', 'user@username'),
    'password' => env('LDAP_PASSWORD', 'user@password'),
```

@stevebauman

**Comment by stevebauman** [comment]
Hi @AnilGillAlipuria,

Adldap2-Laravel does not support this, and the mentioned project is not associated with this one. 

You will have to create an issue on their repository to ask for their assistance, as I have not been involved in its creation or maintenance.

Thanks!
