### ISSUE TITLE
when "deprecatedPaginationCallback" fetches users and loses connection generates huge log files

### ISSUE THREAD

**Issue by santstor** [Adldap2/Adldap2#779]
- Adldap2 Version: 10.3.1
- LDAP Type: -
- PHP Version: 7.2.18

### Steps To Reproduce:

1.  configure OU with X users
2.  use the following line of code: $adLdap->search()->users()->paginate(Y)->getResults();  where _Y < X_
3.  set a breakpoint inside "deprecatedPaginationCallback" before updating $cookie
4.  in the second run, before fetching the next page, turn off conection to ldap server.

Result:
while never ends, and generates infinites errors. 

### Fix?:
![image](https://user-images.githubusercontent.com/46936713/108371740-d11cc700-71dc-11eb-82aa-cc4bbb74bc19.png)

**Comment by stevebauman** [comment]
Great catch @santstor! I'll patch this shortly and make a new release. Once released, I'll send you an update here so you're aware 👍 .

**Comment by stevebauman** [comment]
Hi @santstor,

I've completed patching this. A new release has just been created ([v10.3.2](https://github.com/Adldap2/Adldap2/releases/tag/v10.3.2)). Thanks!

**Comment by santstor** [comment]
Thank you @stevebauman !!
