### ISSUE TITLE
Iterating over records

### ISSUE THREAD

**Issue by rudischenck** [Adldap2/Adldap2#782]
- Adldap2 Version: 10.0.4
- LDAP Type: 
- PHP Version: 7.2.31

### Description:
The library gets all models at once OR the server limit if pagination isn't used. For large ADs this is crashing our application due to memory limits when paginating. We have to use pagination because we need all records for our customers, hence we need a way to not return all results and only view one page at a time if possible. I have searched the docs and can't find a way to paginate results with limit/offset or likewise. How to deal with large data sets while using this library?

**Comment by rudischenck** [comment]
> Hi @rudischenck,
> 
> PHP's LDAP extension is not capable of handling storing the cookie needed to fetch individual pages of LDAP objects due to it initiating a brand new LDAP connection upon each application request. Databases can handle this differently, since they have the ability to execute offsets or slices of data. Without a concurrent connection to an LDAP server, this is not possible (PHP is stateless, after all).
> 
> There's a couple of immediate ways to get around this:
> 
> 1. Limit the attributes you're requesting in your pagination request
> 2. Paginate your requests by letter/number (i.e. `whereStartsWith('a')`)
> 3. Allow navigating the LDAP tree in your interface (i.e. displaying a collapsable folder like structure allowing navigation into OU's)

Thank you, this is quite helpful. And respond so quickly! Now that we can rule out pagination, you have given us some ideas on how to proceed.

**Comment by stevebauman** [comment]
Happy to help @rudischenck! 😄  Going to close this out, but if you need any further assistance give me a shout.
