### ISSUE TITLE
Adldap\\Query\\Builder->parse() faild in php8

### ISSUE THREAD

**Issue by sdfjenny** [Adldap2/Adldap2#787]
- Adldap2 Version: 10.3.2
- LDAP Type: 
- PHP Version: 8

### Description:
Adldap\\Query\\Builder->parse():

`$entries = $this->connection->getEntries($resource) ?: [];`

failed in php8, if there is no query result.

It will solve the problem if we check the $resource first. 

`if ($resource === false) { $entries = []; } else { $entries = $this->connection->getEntries($resource); }`

Otherwise the "ldap_get_entries" get a 'false' as second parameter which should be data type resource. This is ok in php7 but not in php8, because php8 will check the data type.

### Steps To Reproduce:
in PHP8 laravel 6.0 adldap2/adldap2-laravel 6.1.5 try to call 

`public function findByDnOrFail($dn, $columns = [])`

, and try to type in some unreasonable id, then get 

ldap_get_entries(): Argument #2 ($result) must be of type resource, bool given

**Comment by FJReber** [comment]
This issue should be fixed by https://github.com/Adldap2/Adldap2/pull/789.

@sdfjenny: Thank you very much for your efforts!

**Comment by stevebauman** [comment]
I've released [v10.3.3](https://github.com/Adldap2/Adldap2/releases/tag/v10.3.3) with this fix included. Thanks! 👍

**Comment by causefx** [comment]
I will update and push
