### ISSUE TITLE
Fatal error: Class 'Adldap\Connections\Configuration' not found in /var/www/base/Adldap/Adldap.php on line 44

### ISSUE THREAD

**Issue by Rexima** [Adldap2/Adldap2#79]
I have an problem to initialize adldap.

Here is the error code:
Fatal error: Class 'Adldap\Connections\Configuration' not found in /var/www/base/Adldap/Adldap.php on line 44

And here is my code:
include dirname(__FILE__).'/Adldap/Adldap.php';
use Adldap\Adldap;

$config = [
    'account_suffix' => '@test.int',
    'domain_controllers' => [''],
    'port' => 389,
    'base_dn' => '',
    'admin_username' => '',
    'admin_password' => '',
    'follow_referrals' => true,
    'use_ssl' => false,
    'use_tls' => false,
    'use_sso' => false,
];

$adLDAP = new Adldap($config);

**Comment by stevebauman** [comment]
You need to include the Configuration class as well. Why not use composer if I may ask?

**Comment by Rexima** [comment]
Sorry, i installed it with composer, it works not, but i cant get all users now.

Message on the site:
bool(false)

Code:
if (!file_exists(__DIR__.'/../vendor/autoload.php')) {
    echo 'Before using this demo, please run <code>composer dump-autoload</code>';
    exit(1);
}
require_once __DIR__.'/../vendor/autoload.php';
use Adldap\Adldap;
use Adldap\Exceptions\AdldapException;

// Set up all options.
$options = [
    'account_suffix'	 => '@test.int',
    'base_dn' 		 	 => '',
    'domain_controllers' => [''],
    'admin_username' 	 => '',
    'admin_password' 	 => '',
    'real_primarygroup'  => '',
    'use_ssl'            => false,
    'use_tls'            => false,
    'recursive_groups'   => true,
    'ad_port'            => '389',
    'sso'                => '',
];

// Try to bind.
$adldap = false;
$exception = false;
try {
	$adldap = new Adldap($options);
} catch (adLDAPException $e) {
	$exception = $e;
}

echo("<pre>\n");
$users = $adldap->users()->all();
var_dump($users);

**Comment by stevebauman** [comment]
Did you fill in the configuration or are they just blank for security reasons? Just want to make sure

**Comment by Rexima** [comment]
For security reasons ^^
I just test the connection with an authentication, and i can authenticate my ad user, but i can't get all users, or just use
<pre>
$user = $ad->users()->find("drumstein");
var_dump($user);
</pre>
To get any information about my ad user... Why?

**Comment by stevebauman** [comment]
Hmm try `$results = $ad->search()->all();` and see if you're able to retrieve anything. You may need to set your `base_dn` as well.

**Comment by Rexima** [comment]
I can login with my AD user, so the connection to my AD seems to be working.
But i can't retrieve any information, and your code doesnt work for me, too...

**Comment by stevebauman** [comment]
Did you try setting your `base_dn` in your configuration? That may be incorrect and would be the reason you won't retrieve any search results.

**Comment by Rexima** [comment]
Okay base_dn was wrong, thank you very much.

But i saw that in my installation (did with composer, like in the readme) in Classes\User.php, that there is no find function.

Should i just download the latest master and just upload it to my composer installation?

**Comment by stevebauman** [comment]
Ok great, glad to hear you've got it resolved!

Also, there is a find method in `Classes\Users`: https://github.com/Adldap2/Adldap2/blob/master/src/Classes/Users.php#L20.
