### ISSUE TITLE
Upgdate php from 7.4 to 8.1 - empty search results 

### ISSUE THREAD

**Issue by Hajtowy** [Adldap2/Adldap2#797]
- Adldap2 Version: v10.3.3
- LDAP Type: Active Directory
- PHP Version: 8.1
- Laravel v8.74

### Description:
After my upgrade from php 7.4 to 8.1 I got empty string when I want find some user. I didn't get any errors. I connect to my AD successfully. Do I need to add some extra extension for php or docker file?

### Steps To Reproduce:
```
$config = [
	'hosts'    => ['my-host.com'],
	'port'     => '1234',
	'schema'   => ActiveDirectory::class,
	'base_dn'  => 'dns',
	'username' => 'usernames',
	'password' => 'password,
];

/**
@var Adldap\Adldap $this->adldap
*/
$this->adldap->addProvider($config);
$this->providerConnection = $this->adldap->connect();

// Here I want to find my user
$this->providerConnection
	->search()
	->where('CN', '=', $username)
	->get();

$user = $this->providerConnection
	->search()
	->find($username);
	
dd($user) // ''

**Comment by stevebauman** [comment]
Hi @Hajtowy,

I just created a new release that includes PHP 8.1 support (the hard work was done by @villfa 🎉 ), can you run `composer update` and give it another shot?

**Comment by Hajtowy** [comment]
Hi @stevebauman,

Everything works fine! Thanks.
