### ISSUE TITLE
Laravel 9 Make:Auth Not available.

### ISSUE THREAD

**Issue by softtailwind** [Adldap2/Adldap2#815]
- Adldap2 Version: 10.4.3
- LDAP Type: MS Active Directory
- PHP Version: 8.1.12
- Laravel Version: 9.41.0
- Operating System: Windows Server 2019
- Operating System Build: 17763.3650
- Hypervisor:  Hyper-V

### Description:
Following the process found in the article below, Make:Auth is not an available command.

[https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction](url)

### Steps To Reproduce:
I followed the steps right out of the link provided above with a fresh OS build. To reproduce this:

- Install Windows Server 2019
  - Add two drives (One  for the OS, One for the App)
- Add IIS with CGI
- Install PHP from the website (Do not use the web platform)
- Install Nodejs 
- Install Composer
- Install Laravel as a global installer
- on the app drive Run Laravel new App
- CD to new directory app
- run composer require adldap2/adldap2-laravel -W

From there you can follow the rest of the directions out of the link I provided above

**Comment by stevebauman** [comment]
Hi @softtailwind,

Adldap2-Laravel is no longer supported. I would suggest using its replacement, [LdapRecord](https://ldaprecord.com).
