### ISSUE TITLE
Find user of specific OU

### ISSUE THREAD

**Issue by fourteenmeister** [Adldap2/Adldap2#82]
This code not worked - return false.
```php
$ldap->search()
   ->where('OU', '=', 'All_Users')
   ->where('sn', '=', $lastName)
   ->first();
```
How do I find the user in the definition "Organizational Unit"?

**Comment by ciadch** [comment]
Hi,

You can do that with setDn() in serach() methods : 
```php
// Complete OU DN
$ou = 'OU=MyOU,DC=MyDc';
// Get by lastname
$ldap->users()->search()->where('sn', '=', $lastName)->setDn($ou)->first();
// Or get all in you OU
$ldap->users()->search()->setDn($ou)->all();
```
Have a look in API here : http://adldap2.github.io/api/Adldap/Models/User.html

You can also use the setBaseDn() from configuration to set the default base DN for all your search requests. API here : http://adldap2.github.io/api/Adldap/Connections/Configuration.html

Hop it helps you

**Comment by fourteenmeister** [comment]
```php
$ou = 'OU=All_Users';
$ldap->users()->search()->where('sn', '=', $lastName)->setDn($ou)->first();
```
not work for me(

**Comment by ciadch** [comment]
I think you need to add the DC in your OU name. Look in your OU attributes to find the entire DN.

**Comment by fourteenmeister** [comment]
> I think you need to add the DC in your OU name. Look in your OU attributes to find the entire DN.
Already tried - no result.

**Comment by ciadch** [comment]
Are you correctly authentified ? With method authenticate() ?

**Comment by fourteenmeister** [comment]
```php
$ldap->users()->search()->where('sn', '=', $lastName)->first();
```
Find perfect, but does not consider definition "Organizational Unit".

**Comment by ciadch** [comment]
I'm glad it works ! Today it's not possible to find "by OU", but in a few release maybe :-) !

**Comment by stevebauman** [comment]
You can't target OU's inside a LDAP query filter. You need to set the DN by the OU's dn, and then retrieve users by that. For example:

```php
$ou = $ad->ous()->where('name', '=', 'All_Users')->first();

$users = $ad->users()->search()->setDn($ou->getDn())->get();
```

**Comment by fourteenmeister** [comment]
Thank you for reporting. I'll look forward to.

**Comment by fourteenmeister** [comment]
> // Find the OU first
$ou = $ad->ous()->where('name', '=', 'All_Users')->first();

if($ou) {
    // Retrieve users by the OU's DN
    $users = $ad->users()->search()->setDn($ou->getDn())->get();
} else {
    // OU Couldn't be found!
}

Wow. Work perfect (but $ad->ous()->where('name', '=', 'All_Users')->first() not right - $ldap->ous()->find('All_Users') right). Thanks for help!

**Comment by stevebauman** [comment]
Great to hear! No problem.
