### ISSUE TITLE
Create a Laravel auth package

### ISSUE THREAD

**Issue by samwilson** [Adldap2/Adldap2#9]
(This issue stems from discussion at #3.)

It would be great to have a `Adldap2/Laravel` package that unifies some or all of the following and their myriad of forks...

* https://github.com/ccovey/ldap-auth
* https://github.com/dsdevbe/ldap-connector
* https://github.com/atorscho/laravel-ldap-42
* https://github.com/stevebauman/Corp

So, which fork to go with? @strebl yours is pretty up to date isn't it? @stevebauman could Corp be extended to include auth stuff (or am I reading it wrong, and it does already!)? :)

**Comment by stevebauman** [comment]
Sorry for the long response Sam, yes Corp includes AD authentication. It's used by calling `Corp::auth($username, $password)`. Corp should be automatically be compatible with new the `5.0.0` of Aldap, so once it's been released, Corp will be updated to follow suit. It's also fully compatible with both Laravel 4 and 5.

I agree though, offering a one stop shop doc unifying the packages that incorporate Adldap would be great.

**Comment by wunc** [comment]
[dsdevbe/ldap-connector](https://github.com/dsdevbe/ldap-connector) is no longer maintained, which is a shame because it was the most popular L5-compatible package according to Packalyst. I really liked the way it just replaced the Laravel Auth driver to work. I've forked it ([utdallasresearch/ldap-connector](https://github.com/utdallasresearch/ldap-connector)) to fit my own needs, and was just about to submit it to Packagist when I saw that we now have adLDAP2. I will probably update it to support adLDAP2 instead of my forked adLDAP and then submit, but I'm a bit reluctant to take on being the unifier of all things Laravel 5 ldap.

**Comment by stevebauman** [comment]
I can add the ability to replace the Laravel Auth driver with Corp (using Adldap in the background), but this will definitely be in the works *after* v5.0 releases (which should be in the next week or so hopefully). I'm all up for options though!

**Comment by samwilson** [comment]
I've been trying to look through all the different permutations of LDAP Laravel stuff, and it's doing my head in. :-) Everyone seems to have slightly different ideas about what they're trying to integrate Adldap into: sometimes it's just to authenticate, sometimes to also pull user data, or other times to sort out authorisation as well. What's the scope of Laravel Auth? I think I want it to be just *authentication*!

Or am I on the wrong track?

Here's a rough idea: https://github.com/samwilson/adldap-laravel

**Comment by wunc** [comment]
I think those are good thoughts. Probably the main two that most people need via LDAP are authentication and search/retrieve. If I was installing a "Laravel LDAP" package I would expect it to have at least those. Maybe the first part via an auth driver and the second as a helper? I'm still new to Laravel, so I'm not sure of the appropriate way to implement it.

Looking back, I probably put too much logic into my provider implementation that could/should have been handled in another way, but I was kind of a Laravel noob at the time; I will correct that in time ;)

**Comment by samwilson** [comment]
Gosh, I'm certainly still learning the Laravel way too! So am likely to get things quite out of order. :)

But yes, I think there's the basic authentication, and then there's authorisation (which is usually about querying group membership, or other LDAP attributes), and then general LDAP searching. I feel like the latter two circumstances are better handled by using Adldap directly in one's application. Laravel Auth by default handles authentication, registration, and logging out. It doesn't have any `isMemberOf` or `hasRole` or anything... I reckon that means that Auth drivers shouldn't provide that stuff. A helper sounds like a great idea; do you mean `adldap()` as a shortcut to the Adldap object?

I'm currently working on three Laravel projects, all with AD authentication: one just authenticates, and doesn't have a User model or store anything about the user, or really care about anything other than that they were allowed to log in. The second has a user model, but it's very basic because authorisation is handled by other bits of the system (e.g. access control is determined by workflow statuses and things, rather than any attributes of the user). The third is much more 'enterprisy' and needs AD authorisation things like "so-and-so is a member of the HR department in Toowoomba".

I reckon the simpler the better....

**Comment by strebl** [comment]
I like the way how ccovey's package handles it. It automatically binds the ldap model and all additional attributes to your user model.
This is very handy if you need additional data like the email address or something like that in your database.
After that you can use Auth::user()->email or whatever.

Only authentication without a model binding and the Laravel authentication implementation Laravel package isn't worthy for me.

**Comment by KerchumA222** [comment]
I have a forked version of CCovey's ldap-auth. It has support for L5.1 and some new features like persisting certain ldap information to the model (database) so it can be searched without using needing to contact LDAP. https://github.com/KerchumA222/ldap-auth
3.1-dev is for L5.1

Just throwing it out there as an option for people

**Comment by stevebauman** [comment]
I've actually created a repository for this: https://github.com/Adldap2/Adldap2-laravel

I'll be pushing some code there soon.

Also, @samwilson, by the looks of your profile you're really experienced with Kohana? Would you be interested in creating a Adldap-kohana package?

**Comment by strebl** [comment]
My ccovey fork got some attention too.

**Comment by stevebauman** [comment]
Yea that's true... Feel free to start pushing into the adldap2-laravel repo if you'd like! A new beta tag has been created for adldap2, no further API changes are going to take place until a next major version so we can start building with it.

**Comment by samwilson** [comment]
For Kohana, I could transfer `samwilson/kohana_kadldap` to `Adldap2/Adldap2-Kohana` perhaps?

And yeah `samwilson/laravel-adldap2` works for authentication, but not authorisation, (also doesn't require a database). So, more limited than @strebl's module. I use it because it makes it possible to swap between auth drivers without any issue.

**Comment by stevebauman** [comment]
@samwilson Definitely, are you able to transfer that to kohana by chance? 

Also, Adldap2-Laravel is up and running, though doesn't contain the Auth implementation yet.

**Comment by samwilson** [comment]
Done: https://github.com/Adldap2/Adldap2-Kohana (I deleted the older placeholder repo). It'll need to have its Composer name updated I reckon?

**Comment by samwilson** [comment]
(And I'm updating the kohana module now, to fix various bits.)

**Comment by stevebauman** [comment]
Great thanks! And yea it will. Just name it `adldap2\adldap2-kohana`, and I'll add it to packagist.

**Comment by samwilson** [comment]
Okay, changed, and a new version tagged.

**Comment by stevebauman** [comment]
Great! Thanks

**Comment by samwilson** [comment]
Could you add `adldap2\adldap2-kohana` to Packagist @stevebauman ?

**Comment by stevebauman** [comment]
Shoot didn't know it wasn't added! Will be added shortly, thanks for bringing this up.

**Comment by samwilson** [comment]
Thanks! :)

**Comment by stevebauman** [comment]
Fixed!

**Comment by samwilson** [comment]
Thanks Steve. Yep, works brill. I wonder if it'll ever get more downloads than my two projects....
