### ISSUE TITLE
Autocompletition in eclipse

### ISSUE THREAD

**Issue by Xento** [Adldap2/Adldap2#91]
I'm using Zend Studio for programming.
Normaly you get hints, when you are doing something like this $ad->
When you use adldap2 you only get sometimes hints.
I think this is because you dynamically catch the methods.
Is there a possbility to get Zend Studio or Eclipse to notice that and give you the correct available Methods?

**Comment by stevebauman** [comment]
Unfortunately the only time you won't receive auto completion is when calling the search class and building a query. However you can always call `$ad->search()->getQueryBuilder()` to resolve this.

I personally use PHPStorm with development, and the type-hints I receive definitely suffice with development, and unfortunately from my experience you can't add type-hints for classes which involve the `_call()` magic method.

**Comment by Xento** [comment]
For example I use this code: 
$results = $ad->search()->select('dn')->where("sAMAccountType","=","805306368")->where('objectClass', '=', 'person')->where("userAccountControl:1.2.840.113556.1.4.803:", "!","2")->paginate(100, 0);

I don't have autocompletition for $results.
For $ad I get autocompletition.
Maybe a wrong setting in Zend Studio?

**Comment by stevebauman** [comment]
You won't receive autocompletion results since you're calling `$ad->search()`. All methods you've called after that are called on the searches query builder object. If you want auto-completion, you'll have to use `getQueryBuilder()` after the search call:

```php
$ad->search()->getQueryBuilder()->where("sAMAccountType","=","805306368")->where('objectClass', '=', 'person')->where("userAccountControl:1.2.840.113556.1.4.803:", "!","2")->paginate(100, 0);
```
